namespace StageLib
{
	public enum STAGE_SYNC_OBJ_MODE
	{
		STAGE_SYNC_OBJ_PLAYER = 0,
		STAGE_SYNC_OBJ_USETIME = 1,
		STAGE_SYNC_OBJ_MEMBERINFO = 2,
		STAGE_SYNC_OBJ_SEASONDATA = 3,
		STAGE_SYNC_OBJ_PAUSE = 4,
		STAGE_SYNC_OBJ_ENEMY_DATA = 5,
		STAGE_SYNC_OBJ_GAMESAVEDATA = 6
	}
}
