namespace StageLib
{
	public enum STAGE_EVENT
	{
		NONE = 0,
		STAGE_VOICE_ON = 1,
		STAGE_ENEMYEVENT_STOP = 2,
		STAGE_PLAYER_REBORN = 3,
		STAGE_SYNC_COUNTDOWN = 4,
		STAGE_SYNC_SCORE = 5,
		STAGE_SYNC_RECONNECTEVENT = 6,
		STAGE_SYNC_OBJ = 7,
		STAGE_SYNC_PVPUI = 8,
		STAGE_PLAYER_CHANGECHARACTER = 9,
		STAGE_SYNC_BATTLETIMER = 10,
		STAGE_SET_RECONNECT = 11,
		STAGE_SYNC_FLAG_SCORE = 12,
		STAGE_SYNC_STAGEFALL = 13,
		STAGE_SYNC_PVPENDDATA = 14,
		STAGE_SYNC_WAITSTAGECTRL = 15,
		STAGE_SYNC_PLAYERGIVEUP = 16,
		STAGE_SYNC_PLAYERSPAWN = 17,
		STAGE_SYNC_PLAYEROUTGAME = 18,
		STAGE_SYNC_DMGERROR_ENDGAME = 19,
		STAGE_SYNC_BATTLEEND_RQ = 20,
		STAGE_START_SUMMON_ENEMY = 21,
		STAGE_ADD_COUNTDOWN = 22,
		STAGE_SYNC_MAX = 23
	}
}
