namespace StageLib
{
	public enum StageObjType
	{
		PREFAB_OBJ = 0,
		START_OBJ = 1,
		END_OBJ = 2,
		ENEMY_OBJ = 3,
		CAMERA_OBJ = 4,
		LIGHT_OBJ = 5,
		BG_OBJ = 6,
		LOCK_RANGE_OBJ = 7,
		ENEMYEP_OBJ = 8,
		DEADAREA_OBJ = 9,
		MAPEVENT_OBJ = 10,
		BLOCKWALL_OBJ = 11,
		STAGECTRL_OBJ = 12,
		STAGECOLLISION_OBJ = 13,
		STAGEONEWORK_OBJ = 14,
		STAGEREBORN_OBJ = 15,
		RIDEABLE_OBJ = 16,
		PATROLPATH_OBJ = 17,
		DATAPOING_OBJ = 18,
		MIX_OBJ = 99
	}
}
