namespace StageLib
{
	public enum STAGE_STATUS
	{
		NONE = 0,
		STAGE_BUFF = 1,
		STAGE_SHOT_BULLET = 2,
		STAGE_SOB_ADDMEASURE = 3,
		STAGE_SOB_ADDPET = 4,
		STAGE_DEL_BUFF = 5,
		STAGE_DEL_MARKED_BUFF = 6,
		STAGE_ADD_GAMESAVEDATA = 7,
		STAGE_CHECK_OUTDEAD = 8,
		STAGE_RESET_OUTDEAD = 9,
		STAGE_PLAYSOUND = 10,
		STAGE_PLAYFX = 11,
		STAGE_UPDATE_PASSIVESKILL = 12
	}
}
