namespace StageLib
{
	public enum STAGE_QUEST_TYPE
	{
		QUEST_NONE = 0,
		QUEST_KILLENEMY_CALLEVENT = 1,
		QUEST_EVENTID_COUNT = 2,
		QUEST_CHECK_BUFF = 3,
		QUEST_CHECK_OBJALIVE = 4,
		QUEST_CAMPAIGN_SCORE = 5,
		QUEST_MKILLENEMY_CALLEVENT = 6
	}
}
