public static class BattleSEi
{
	public const int iCRI_BATTLESE_CUENUM = 150;

	public const int iCRI_BATTLESE_BT_READY01 = 1;

	public const int iCRI_BATTLESE_BT_WARNING01 = 2;

	public const int iCRI_BATTLESE_BT_KIME01 = 3;

	public const int iCRI_BATTLESE_BT_BOSS13 = 193;

	public const int iCRI_BATTLESE_BT_DIE01 = 6;

	public const int iCRI_BATTLESE_BT_REVIVE01 = 7;

	public const int iCRI_BATTLESE_BT_GETITEM01 = 11;

	public const int iCRI_BATTLESE_BT_GETITEM02 = 12;

	public const int iCRI_BATTLESE_BT_GETITEM03 = 13;

	public const int iCRI_BATTLESE_BT_SPSKILL01 = 120;

	public const int iCRI_BATTLESE_BT_SPSKILL02 = 121;

	public const int iCRI_BATTLESE_BT_RIDEARMOR00 = 20;

	public const int iCRI_BATTLESE_BT_RIDEARMOR01 = 21;

	public const int iCRI_BATTLESE_BT_RIDEARMOR02 = 22;

	public const int iCRI_BATTLESE_BT_RIDEARMOR03 = 23;

	public const int iCRI_BATTLESE_BT_RIDEARMOR04 = 24;

	public const int iCRI_BATTLESE_BT_RIDEARMOR05 = 25;

	public const int iCRI_BATTLESE_BT_RIDEARMOR06 = 26;

	public const int iCRI_BATTLESE_BT_RIDEARMOR08 = 28;

	public const int iCRI_BATTLESE_BT_MBOSS_DOOR_UNLOCK = 31;

	public const int iCRI_BATTLESE_BT_MBOSS_DOOR_OPEN = 32;

	public const int iCRI_BATTLESE_BT_MBOSS_DOOR_CLOSE = 33;

	public const int iCRI_BATTLESE_BT_BOSS_DOOR_UNLOCK = 34;

	public const int iCRI_BATTLESE_BT_BOSS_DOOR_OPEN = 35;

	public const int iCRI_BATTLESE_BT_BOSS_DOOR_CLOSE = 36;

	public const int iCRI_BATTLESE_BT_BOSSHP01_STOP = 42;

	public const int iCRI_BATTLESE_BT_BOSSHP01_LP = 41;

	public const int iCRI_BATTLESE_BT_BOSS01 = 44;

	public const int iCRI_BATTLESE_BT_BOSS02 = 45;

	public const int iCRI_BATTLESE_BT_HP01 = 204;

	public const int iCRI_BATTLESE_BT_NUMB_LP = 217;

	public const int iCRI_BATTLESE_BT_NUMB_STOP = 218;

	public const int iCRI_BATTLESE_BT_BURN_LP = 211;

	public const int iCRI_BATTLESE_BT_BURN_STOP = 212;

	public const int iCRI_BATTLESE_BT_COLD_LP = 213;

	public const int iCRI_BATTLESE_BT_COLD_STOP = 214;

	public const int iCRI_BATTLESE_BT_ICE01 = 210;

	public const int iCRI_BATTLESE_BT_PMDOWN01 = 206;

	public const int iCRI_BATTLESE_BT_PMUP01 = 205;

	public const int iCRI_BATTLESE_BT_ROCK01 = 209;

	public const int iCRI_BATTLESE_BT_SHIELD01 = 207;

	public const int iCRI_BATTLESE_BT_SHIELD02 = 208;

	public const int iCRI_BATTLESE_BT_POISON_LP = 215;

	public const int iCRI_BATTLESE_BT_POISON_STOP = 216;

	public const int iCRI_BATTLESE_BT_DARK_LP = 219;

	public const int iCRI_BATTLESE_BT_WALL01 = 87;

	public const int iCRI_BATTLESE_BT_TRAM01_STOP = 81;

	public const int iCRI_BATTLESE_BT_BONUS_GET = 43;

	public const int iCRI_BATTLESE_BT_WALL02 = 89;

	public const int iCRI_BATTLESE_BT_TRAM01_LP = 80;

	public const int iCRI_BATTLESE_BT_PRESS02 = 72;

	public const int iCRI_BATTLESE_BT_PRESS01 = 71;

	public const int iCRI_BATTLESE_BT_PRESS03_LP = 73;

	public const int iCRI_BATTLESE_BT_PRESS03_STOP = 74;

	public const int iCRI_BATTLESE_BT_TORNADO01 = 83;

	public const int iCRI_BATTLESE_BT_TORNADO02_LP = 84;

	public const int iCRI_BATTLESE_BT_TORNADO02_STOP = 85;

	public const int iCRI_BATTLESE_BT_WATER01 = 18;

	public const int iCRI_BATTLESE_BT_ELEVATOR01_LP = 77;

	public const int iCRI_BATTLESE_BT_ELEVATOR01_STOP = 78;

	public const int iCRI_BATTLESE_BT_WALL03_LP = 91;

	public const int iCRI_BATTLESE_BT_WALL03_STOP = 92;

	public const int iCRI_BATTLESE_BT_TRAIN01_LP = 100;

	public const int iCRI_BATTLESE_BT_TRAIN01_STOP = 101;

	public const int iCRI_BATTLESE_BT_TRAIN02 = 102;

	public const int iCRI_BATTLESE_BT_BOSS03 = 39;

	public const int iCRI_BATTLESE_BT_BOSS04 = 40;

	public const int iCRI_BATTLESE_BT_WALL_SLIDE_LP = 14;

	public const int iCRI_BATTLESE_BT_WALL_SLIDE_STOP = 15;

	public const int iCRI_BATTLESE_BT_PVP01_LP = 110;

	public const int iCRI_BATTLESE_BT_PVP01_STOP = 111;

	public const int iCRI_BATTLESE_BT_DARK_STOP = 220;

	public const int iCRI_BATTLESE_BT_PVP02 = 112;

	public const int iCRI_BATTLESE_BT_BOSSOFF = 203;

	public const int iCRI_BATTLESE_BT_BOSSON = 202;

	public const int iCRI_BATTLESE_BT_BLOCK_RAKKA = 46;

	public const int iCRI_BATTLESE_BT_CHANGE01 = 9;

	public const int iCRI_BATTLESE_BT_HEAVY_RAKKA = 47;

	public const int iCRI_BATTLESE_BT_ICE_RAKKA = 67;

	public const int iCRI_BATTLESE_BT_SLIDE01_LP = 37;

	public const int iCRI_BATTLESE_BT_SLIDE01_STOP = 38;

	public const int iCRI_BATTLESE_BT_SILINDA_LP = 97;

	public const int iCRI_BATTLESE_BT_SILINDA_STOP = 98;

	public const int iCRI_BATTLESE_BT_FOOTHOLD_LP = 94;

	public const int iCRI_BATTLESE_BT_FOOTHOLD_STOP1 = 95;

	public const int iCRI_BATTLESE_BT_FOOTHOLD_STOP2 = 96;

	public const int iCRI_BATTLESE_BT_SPSKILL03 = 122;

	public const int iCRI_BATTLESE_BT_SPSKILL05_1 = 125;

	public const int iCRI_BATTLESE_BT_SPSKILL04_1 = 123;

	public const int iCRI_BATTLESE_BT_SPSKILL04_2 = 124;

	public const int iCRI_BATTLESE_BT_SPSKILL05_2_LP = 126;

	public const int iCRI_BATTLESE_BT_SPSKILL05_2_STOP = 127;

	public const int iCRI_BATTLESE_BT_SPSKILL06_1 = 128;

	public const int iCRI_BATTLESE_BT_SPSKILL06_2 = 129;

	public const int iCRI_BATTLESE_BT_SPSKILL09 = 134;

	public const int iCRI_BATTLESE_BT_SPSKILL10 = 135;

	public const int iCRI_BATTLESE_BT_SCAN = 5;

	public const int iCRI_BATTLESE_BT_SCAN02 = 19;

	public const int iCRI_BATTLESE_BT_TIMER = 4;

	public const int iCRI_BATTLESE_BT_HP02 = 201;

	public const int iCRI_BATTLESE_BT_CAUTION = 8;

	public const int iCRI_BATTLESE_BT_X_CHARGE_LP = 113;

	public const int iCRI_BATTLESE_BT_X_CHARGEMAX = 119;

	public const int iCRI_BATTLESE_BT_X1_CHARGE_LP = 116;

	public const int iCRI_BATTLESE_BT_XU_CHARGE_LP = 114;

	public const int iCRI_BATTLESE_BT_X2_CHARGE_LP = 115;

	public const int iCRI_BATTLESE_BT_X2_CHARGE02_STOP = 137;

	public const int iCRI_BATTLESE_BT_X2_CHARGE02_LP = 136;

	public const int iCRI_BATTLESE_BT_TIMER02 = 10;

	public const int iCRI_BATTLESE_BT_RIDEARMOR07 = 27;

	public const int iCRI_BATTLESE_BT_X_CHARGE_STOP = 130;

	public const int iCRI_BATTLESE_BT_X1_CHARGE_STOP = 131;

	public const int iCRI_BATTLESE_BT_XU_CHARGE_STOP = 132;

	public const int iCRI_BATTLESE_BT_XF_CHARGE_STOP = 118;

	public const int iCRI_BATTLESE_BT_X2_CHARGE_STOP = 133;

	public const int iCRI_BATTLESE_BT_FIRE01_STOP = 69;

	public const int iCRI_BATTLESE_BT_FIRE01_LP = 68;

	public const int iCRI_BATTLESE_BT_ICEBLOCK01 = 86;

	public const int iCRI_BATTLESE_BT_BAR = 70;

	public const int iCRI_BATTLESE_BT_WARP_OP = 75;

	public const int iCRI_BATTLESE_BT_WARP01 = 76;

	public const int iCRI_BATTLESE_BT_RESTRICT_LP = 221;

	public const int iCRI_BATTLESE_BT_RESTRICT_STOP = 222;

	public const int iCRI_BATTLESE_BT_PANIC_STOP = 224;

	public const int iCRI_BATTLESE_BT_XF_CHARGE_LP = 117;

	public const int iCRI_BATTLESE_BT_BUTTON = 82;

	public const int iCRI_BATTLESE_BT_RIDEARMOR09 = 29;

	public const int iCRI_BATTLESE_BT_DENKIKAN_LP = 103;

	public const int iCRI_BATTLESE_BT_DENKIKAN_STOP = 104;

	public const int iCRI_BATTLESE_BT_SLIDE02_LP = 16;

	public const int iCRI_BATTLESE_BT_SLIDE02_STOP = 17;

	public const int iCRI_BATTLESE_BT_HEAVY_CLASH = 79;

	public const int iCRI_BATTLESE_BT_SECURITY_OPEN = 93;

	public const int iCRI_BATTLESE_BT_BOSS05 = 30;

	public const int iCRI_BATTLESE_BT_WALL04 = 90;

	public const int iCRI_BATTLESE_BT_PANIC_LP = 223;

	public const int iCRI_BATTLESE_BT_BOSS06 = 200;

	public const int iCRI_BATTLESE_BT_BOSS11 = 195;

	public const int iCRI_BATTLESE_BT_BOSS12 = 194;

	public const int iCRI_BATTLESE_BT_BOMB01_LP = 105;

	public const int iCRI_BATTLESE_BT_BOMB01_STOP = 106;

	public const int iCRI_BATTLESE_BT_BOMB02_PUSH = 107;

	public const int iCRI_BATTLESE_BT_BOMB02_COUNT = 108;

	public const int iCRI_BATTLESE_BT_BOMB02_ZERO = 109;

	public const int iCRI_BATTLESE_BT_BOSS07 = 199;

	public const int iCRI_BATTLESE_BT_BOSS08 = 198;

	public const int iCRI_BATTLESE_BT_BOSS09 = 197;

	public const int iCRI_BATTLESE_BT_BOSS10 = 196;

	public const int iCRI_BATTLESE_BT_BOSS14 = 192;

	public const int iCRI_BATTLESE_BT_BOSS15 = 191;

	public const BattleSE CRI_BATTLESE_CUENUM = BattleSE.CRI_BATTLESE_CUENUM;

	public const BattleSE CRI_BATTLESE_BT_READY01 = BattleSE.CRI_BATTLESE_BT_READY01;

	public const BattleSE CRI_BATTLESE_BT_WARNING01 = BattleSE.CRI_BATTLESE_BT_WARNING01;

	public const BattleSE CRI_BATTLESE_BT_KIME01 = BattleSE.CRI_BATTLESE_BT_KIME01;

	public const BattleSE CRI_BATTLESE_BT_BOSS13 = BattleSE.CRI_BATTLESE_BT_BOSS13;

	public const BattleSE CRI_BATTLESE_BT_DIE01 = BattleSE.CRI_BATTLESE_BT_DIE01;

	public const BattleSE CRI_BATTLESE_BT_REVIVE01 = BattleSE.CRI_BATTLESE_BT_REVIVE01;

	public const BattleSE CRI_BATTLESE_BT_GETITEM01 = BattleSE.CRI_BATTLESE_BT_GETITEM01;

	public const BattleSE CRI_BATTLESE_BT_GETITEM02 = BattleSE.CRI_BATTLESE_BT_GETITEM02;

	public const BattleSE CRI_BATTLESE_BT_GETITEM03 = BattleSE.CRI_BATTLESE_BT_GETITEM03;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL01 = BattleSE.CRI_BATTLESE_BT_SPSKILL01;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL02 = BattleSE.CRI_BATTLESE_BT_SPSKILL02;

	public const BattleSE CRI_BATTLESE_BT_RIDEARMOR00 = BattleSE.CRI_BATTLESE_BT_RIDEARMOR00;

	public const BattleSE CRI_BATTLESE_BT_RIDEARMOR01 = BattleSE.CRI_BATTLESE_BT_RIDEARMOR01;

	public const BattleSE CRI_BATTLESE_BT_RIDEARMOR02 = BattleSE.CRI_BATTLESE_BT_RIDEARMOR02;

	public const BattleSE CRI_BATTLESE_BT_RIDEARMOR03 = BattleSE.CRI_BATTLESE_BT_RIDEARMOR03;

	public const BattleSE CRI_BATTLESE_BT_RIDEARMOR04 = BattleSE.CRI_BATTLESE_BT_RIDEARMOR04;

	public const BattleSE CRI_BATTLESE_BT_RIDEARMOR05 = BattleSE.CRI_BATTLESE_BT_RIDEARMOR05;

	public const BattleSE CRI_BATTLESE_BT_RIDEARMOR06 = BattleSE.CRI_BATTLESE_BT_RIDEARMOR06;

	public const BattleSE CRI_BATTLESE_BT_RIDEARMOR08 = BattleSE.CRI_BATTLESE_BT_RIDEARMOR08;

	public const BattleSE CRI_BATTLESE_BT_MBOSS_DOOR_UNLOCK = BattleSE.CRI_BATTLESE_BT_MBOSS_DOOR_UNLOCK;

	public const BattleSE CRI_BATTLESE_BT_MBOSS_DOOR_OPEN = BattleSE.CRI_BATTLESE_BT_MBOSS_DOOR_OPEN;

	public const BattleSE CRI_BATTLESE_BT_MBOSS_DOOR_CLOSE = BattleSE.CRI_BATTLESE_BT_MBOSS_DOOR_CLOSE;

	public const BattleSE CRI_BATTLESE_BT_BOSS_DOOR_UNLOCK = BattleSE.CRI_BATTLESE_BT_BOSS_DOOR_UNLOCK;

	public const BattleSE CRI_BATTLESE_BT_BOSS_DOOR_OPEN = BattleSE.CRI_BATTLESE_BT_BOSS_DOOR_OPEN;

	public const BattleSE CRI_BATTLESE_BT_BOSS_DOOR_CLOSE = BattleSE.CRI_BATTLESE_BT_BOSS_DOOR_CLOSE;

	public const BattleSE CRI_BATTLESE_BT_BOSSHP01_STOP = BattleSE.CRI_BATTLESE_BT_BOSSHP01_STOP;

	public const BattleSE CRI_BATTLESE_BT_BOSSHP01_LP = BattleSE.CRI_BATTLESE_BT_BOSSHP01_LP;

	public const BattleSE CRI_BATTLESE_BT_BOSS01 = BattleSE.CRI_BATTLESE_BT_BOSS01;

	public const BattleSE CRI_BATTLESE_BT_BOSS02 = BattleSE.CRI_BATTLESE_BT_BOSS02;

	public const BattleSE CRI_BATTLESE_BT_HP01 = BattleSE.CRI_BATTLESE_BT_HP01;

	public const BattleSE CRI_BATTLESE_BT_NUMB_LP = BattleSE.CRI_BATTLESE_BT_NUMB_LP;

	public const BattleSE CRI_BATTLESE_BT_NUMB_STOP = BattleSE.CRI_BATTLESE_BT_NUMB_STOP;

	public const BattleSE CRI_BATTLESE_BT_BURN_LP = BattleSE.CRI_BATTLESE_BT_BURN_LP;

	public const BattleSE CRI_BATTLESE_BT_BURN_STOP = BattleSE.CRI_BATTLESE_BT_BURN_STOP;

	public const BattleSE CRI_BATTLESE_BT_COLD_LP = BattleSE.CRI_BATTLESE_BT_COLD_LP;

	public const BattleSE CRI_BATTLESE_BT_COLD_STOP = BattleSE.CRI_BATTLESE_BT_COLD_STOP;

	public const BattleSE CRI_BATTLESE_BT_ICE01 = BattleSE.CRI_BATTLESE_BT_ICE01;

	public const BattleSE CRI_BATTLESE_BT_PMDOWN01 = BattleSE.CRI_BATTLESE_BT_PMDOWN01;

	public const BattleSE CRI_BATTLESE_BT_PMUP01 = BattleSE.CRI_BATTLESE_BT_PMUP01;

	public const BattleSE CRI_BATTLESE_BT_ROCK01 = BattleSE.CRI_BATTLESE_BT_ROCK01;

	public const BattleSE CRI_BATTLESE_BT_SHIELD01 = BattleSE.CRI_BATTLESE_BT_SHIELD01;

	public const BattleSE CRI_BATTLESE_BT_SHIELD02 = BattleSE.CRI_BATTLESE_BT_SHIELD02;

	public const BattleSE CRI_BATTLESE_BT_POISON_LP = BattleSE.CRI_BATTLESE_BT_POISON_LP;

	public const BattleSE CRI_BATTLESE_BT_POISON_STOP = BattleSE.CRI_BATTLESE_BT_POISON_STOP;

	public const BattleSE CRI_BATTLESE_BT_DARK_LP = BattleSE.CRI_BATTLESE_BT_DARK_LP;

	public const BattleSE CRI_BATTLESE_BT_WALL01 = BattleSE.CRI_BATTLESE_BT_WALL01;

	public const BattleSE CRI_BATTLESE_BT_TRAM01_STOP = BattleSE.CRI_BATTLESE_BT_TRAM01_STOP;

	public const BattleSE CRI_BATTLESE_BT_BONUS_GET = BattleSE.CRI_BATTLESE_BT_BONUS_GET;

	public const BattleSE CRI_BATTLESE_BT_WALL02 = BattleSE.CRI_BATTLESE_BT_WALL02;

	public const BattleSE CRI_BATTLESE_BT_TRAM01_LP = BattleSE.CRI_BATTLESE_BT_TRAM01_LP;

	public const BattleSE CRI_BATTLESE_BT_PRESS02 = BattleSE.CRI_BATTLESE_BT_PRESS02;

	public const BattleSE CRI_BATTLESE_BT_PRESS01 = BattleSE.CRI_BATTLESE_BT_PRESS01;

	public const BattleSE CRI_BATTLESE_BT_PRESS03_LP = BattleSE.CRI_BATTLESE_BT_PRESS03_LP;

	public const BattleSE CRI_BATTLESE_BT_PRESS03_STOP = BattleSE.CRI_BATTLESE_BT_PRESS03_STOP;

	public const BattleSE CRI_BATTLESE_BT_TORNADO01 = BattleSE.CRI_BATTLESE_BT_TORNADO01;

	public const BattleSE CRI_BATTLESE_BT_TORNADO02_LP = BattleSE.CRI_BATTLESE_BT_TORNADO02_LP;

	public const BattleSE CRI_BATTLESE_BT_TORNADO02_STOP = BattleSE.CRI_BATTLESE_BT_TORNADO02_STOP;

	public const BattleSE CRI_BATTLESE_BT_WATER01 = BattleSE.CRI_BATTLESE_BT_WATER01;

	public const BattleSE CRI_BATTLESE_BT_ELEVATOR01_LP = BattleSE.CRI_BATTLESE_BT_ELEVATOR01_LP;

	public const BattleSE CRI_BATTLESE_BT_ELEVATOR01_STOP = BattleSE.CRI_BATTLESE_BT_ELEVATOR01_STOP;

	public const BattleSE CRI_BATTLESE_BT_WALL03_LP = BattleSE.CRI_BATTLESE_BT_WALL03_LP;

	public const BattleSE CRI_BATTLESE_BT_WALL03_STOP = BattleSE.CRI_BATTLESE_BT_WALL03_STOP;

	public const BattleSE CRI_BATTLESE_BT_TRAIN01_LP = BattleSE.CRI_BATTLESE_BT_TRAIN01_LP;

	public const BattleSE CRI_BATTLESE_BT_TRAIN01_STOP = BattleSE.CRI_BATTLESE_BT_TRAIN01_STOP;

	public const BattleSE CRI_BATTLESE_BT_TRAIN02 = BattleSE.CRI_BATTLESE_BT_TRAIN02;

	public const BattleSE CRI_BATTLESE_BT_BOSS03 = BattleSE.CRI_BATTLESE_BT_BOSS03;

	public const BattleSE CRI_BATTLESE_BT_BOSS04 = BattleSE.CRI_BATTLESE_BT_BOSS04;

	public const BattleSE CRI_BATTLESE_BT_WALL_SLIDE_LP = BattleSE.CRI_BATTLESE_BT_WALL_SLIDE_LP;

	public const BattleSE CRI_BATTLESE_BT_WALL_SLIDE_STOP = BattleSE.CRI_BATTLESE_BT_WALL_SLIDE_STOP;

	public const BattleSE CRI_BATTLESE_BT_PVP01_LP = BattleSE.CRI_BATTLESE_BT_PVP01_LP;

	public const BattleSE CRI_BATTLESE_BT_PVP01_STOP = BattleSE.CRI_BATTLESE_BT_PVP01_STOP;

	public const BattleSE CRI_BATTLESE_BT_DARK_STOP = BattleSE.CRI_BATTLESE_BT_DARK_STOP;

	public const BattleSE CRI_BATTLESE_BT_PVP02 = BattleSE.CRI_BATTLESE_BT_PVP02;

	public const BattleSE CRI_BATTLESE_BT_BOSSOFF = BattleSE.CRI_BATTLESE_BT_BOSSOFF;

	public const BattleSE CRI_BATTLESE_BT_BOSSON = BattleSE.CRI_BATTLESE_BT_BOSSON;

	public const BattleSE CRI_BATTLESE_BT_BLOCK_RAKKA = BattleSE.CRI_BATTLESE_BT_BLOCK_RAKKA;

	public const BattleSE CRI_BATTLESE_BT_CHANGE01 = BattleSE.CRI_BATTLESE_BT_CHANGE01;

	public const BattleSE CRI_BATTLESE_BT_HEAVY_RAKKA = BattleSE.CRI_BATTLESE_BT_HEAVY_RAKKA;

	public const BattleSE CRI_BATTLESE_BT_ICE_RAKKA = BattleSE.CRI_BATTLESE_BT_ICE_RAKKA;

	public const BattleSE CRI_BATTLESE_BT_SLIDE01_LP = BattleSE.CRI_BATTLESE_BT_SLIDE01_LP;

	public const BattleSE CRI_BATTLESE_BT_SLIDE01_STOP = BattleSE.CRI_BATTLESE_BT_SLIDE01_STOP;

	public const BattleSE CRI_BATTLESE_BT_SILINDA_LP = BattleSE.CRI_BATTLESE_BT_SILINDA_LP;

	public const BattleSE CRI_BATTLESE_BT_SILINDA_STOP = BattleSE.CRI_BATTLESE_BT_SILINDA_STOP;

	public const BattleSE CRI_BATTLESE_BT_FOOTHOLD_LP = BattleSE.CRI_BATTLESE_BT_FOOTHOLD_LP;

	public const BattleSE CRI_BATTLESE_BT_FOOTHOLD_STOP1 = BattleSE.CRI_BATTLESE_BT_FOOTHOLD_STOP1;

	public const BattleSE CRI_BATTLESE_BT_FOOTHOLD_STOP2 = BattleSE.CRI_BATTLESE_BT_FOOTHOLD_STOP2;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL03 = BattleSE.CRI_BATTLESE_BT_SPSKILL03;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL05_1 = BattleSE.CRI_BATTLESE_BT_SPSKILL05_1;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL04_1 = BattleSE.CRI_BATTLESE_BT_SPSKILL04_1;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL04_2 = BattleSE.CRI_BATTLESE_BT_SPSKILL04_2;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL05_2_LP = BattleSE.CRI_BATTLESE_BT_SPSKILL05_2_LP;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL05_2_STOP = BattleSE.CRI_BATTLESE_BT_SPSKILL05_2_STOP;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL06_1 = BattleSE.CRI_BATTLESE_BT_SPSKILL06_1;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL06_2 = BattleSE.CRI_BATTLESE_BT_SPSKILL06_2;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL09 = BattleSE.CRI_BATTLESE_BT_SPSKILL09;

	public const BattleSE CRI_BATTLESE_BT_SPSKILL10 = BattleSE.CRI_BATTLESE_BT_SPSKILL10;

	public const BattleSE CRI_BATTLESE_BT_SCAN = BattleSE.CRI_BATTLESE_BT_SCAN;

	public const BattleSE CRI_BATTLESE_BT_SCAN02 = BattleSE.CRI_BATTLESE_BT_SCAN02;

	public const BattleSE CRI_BATTLESE_BT_TIMER = BattleSE.CRI_BATTLESE_BT_TIMER;

	public const BattleSE CRI_BATTLESE_BT_HP02 = BattleSE.CRI_BATTLESE_BT_HP02;

	public const BattleSE CRI_BATTLESE_BT_CAUTION = BattleSE.CRI_BATTLESE_BT_CAUTION;

	public const BattleSE CRI_BATTLESE_BT_X_CHARGE_LP = BattleSE.CRI_BATTLESE_BT_X_CHARGE_LP;

	public const BattleSE CRI_BATTLESE_BT_X_CHARGEMAX = BattleSE.CRI_BATTLESE_BT_X_CHARGEMAX;

	public const BattleSE CRI_BATTLESE_BT_X1_CHARGE_LP = BattleSE.CRI_BATTLESE_BT_X1_CHARGE_LP;

	public const BattleSE CRI_BATTLESE_BT_XU_CHARGE_LP = BattleSE.CRI_BATTLESE_BT_XU_CHARGE_LP;

	public const BattleSE CRI_BATTLESE_BT_X2_CHARGE_LP = BattleSE.CRI_BATTLESE_BT_X2_CHARGE_LP;

	public const BattleSE CRI_BATTLESE_BT_X2_CHARGE02_STOP = BattleSE.CRI_BATTLESE_BT_X2_CHARGE02_STOP;

	public const BattleSE CRI_BATTLESE_BT_X2_CHARGE02_LP = BattleSE.CRI_BATTLESE_BT_X2_CHARGE02_LP;

	public const BattleSE CRI_BATTLESE_BT_TIMER02 = BattleSE.CRI_BATTLESE_BT_TIMER02;

	public const BattleSE CRI_BATTLESE_BT_RIDEARMOR07 = BattleSE.CRI_BATTLESE_BT_RIDEARMOR07;

	public const BattleSE CRI_BATTLESE_BT_X_CHARGE_STOP = BattleSE.CRI_BATTLESE_BT_X_CHARGE_STOP;

	public const BattleSE CRI_BATTLESE_BT_X1_CHARGE_STOP = BattleSE.CRI_BATTLESE_BT_X1_CHARGE_STOP;

	public const BattleSE CRI_BATTLESE_BT_XU_CHARGE_STOP = BattleSE.CRI_BATTLESE_BT_XU_CHARGE_STOP;

	public const BattleSE CRI_BATTLESE_BT_XF_CHARGE_STOP = BattleSE.CRI_BATTLESE_BT_XF_CHARGE_STOP;

	public const BattleSE CRI_BATTLESE_BT_X2_CHARGE_STOP = BattleSE.CRI_BATTLESE_BT_X2_CHARGE_STOP;

	public const BattleSE CRI_BATTLESE_BT_FIRE01_STOP = BattleSE.CRI_BATTLESE_BT_FIRE01_STOP;

	public const BattleSE CRI_BATTLESE_BT_FIRE01_LP = BattleSE.CRI_BATTLESE_BT_FIRE01_LP;

	public const BattleSE CRI_BATTLESE_BT_ICEBLOCK01 = BattleSE.CRI_BATTLESE_BT_ICEBLOCK01;

	public const BattleSE CRI_BATTLESE_BT_BAR = BattleSE.CRI_BATTLESE_BT_BAR;

	public const BattleSE CRI_BATTLESE_BT_WARP_OP = BattleSE.CRI_BATTLESE_BT_WARP_OP;

	public const BattleSE CRI_BATTLESE_BT_WARP01 = BattleSE.CRI_BATTLESE_BT_WARP01;

	public const BattleSE CRI_BATTLESE_BT_RESTRICT_LP = BattleSE.CRI_BATTLESE_BT_RESTRICT_LP;

	public const BattleSE CRI_BATTLESE_BT_RESTRICT_STOP = BattleSE.CRI_BATTLESE_BT_RESTRICT_STOP;

	public const BattleSE CRI_BATTLESE_BT_PANIC_STOP = BattleSE.CRI_BATTLESE_BT_PANIC_STOP;

	public const BattleSE CRI_BATTLESE_BT_XF_CHARGE_LP = BattleSE.CRI_BATTLESE_BT_XF_CHARGE_LP;

	public const BattleSE CRI_BATTLESE_BT_BUTTON = BattleSE.CRI_BATTLESE_BT_BUTTON;

	public const BattleSE CRI_BATTLESE_BT_RIDEARMOR09 = BattleSE.CRI_BATTLESE_BT_RIDEARMOR09;

	public const BattleSE CRI_BATTLESE_BT_DENKIKAN_LP = BattleSE.CRI_BATTLESE_BT_DENKIKAN_LP;

	public const BattleSE CRI_BATTLESE_BT_DENKIKAN_STOP = BattleSE.CRI_BATTLESE_BT_DENKIKAN_STOP;

	public const BattleSE CRI_BATTLESE_BT_SLIDE02_LP = BattleSE.CRI_BATTLESE_BT_SLIDE02_LP;

	public const BattleSE CRI_BATTLESE_BT_SLIDE02_STOP = BattleSE.CRI_BATTLESE_BT_SLIDE02_STOP;

	public const BattleSE CRI_BATTLESE_BT_HEAVY_CLASH = BattleSE.CRI_BATTLESE_BT_HEAVY_CLASH;

	public const BattleSE CRI_BATTLESE_BT_SECURITY_OPEN = BattleSE.CRI_BATTLESE_BT_SECURITY_OPEN;

	public const BattleSE CRI_BATTLESE_BT_BOSS05 = BattleSE.CRI_BATTLESE_BT_BOSS05;

	public const BattleSE CRI_BATTLESE_BT_WALL04 = BattleSE.CRI_BATTLESE_BT_WALL04;

	public const BattleSE CRI_BATTLESE_BT_PANIC_LP = BattleSE.CRI_BATTLESE_BT_PANIC_LP;

	public const BattleSE CRI_BATTLESE_BT_BOSS06 = BattleSE.CRI_BATTLESE_BT_BOSS06;

	public const BattleSE CRI_BATTLESE_BT_BOSS11 = BattleSE.CRI_BATTLESE_BT_BOSS11;

	public const BattleSE CRI_BATTLESE_BT_BOSS12 = BattleSE.CRI_BATTLESE_BT_BOSS12;

	public const BattleSE CRI_BATTLESE_BT_BOMB01_LP = BattleSE.CRI_BATTLESE_BT_BOMB01_LP;

	public const BattleSE CRI_BATTLESE_BT_BOMB01_STOP = BattleSE.CRI_BATTLESE_BT_BOMB01_STOP;

	public const BattleSE CRI_BATTLESE_BT_BOMB02_PUSH = BattleSE.CRI_BATTLESE_BT_BOMB02_PUSH;

	public const BattleSE CRI_BATTLESE_BT_BOMB02_COUNT = BattleSE.CRI_BATTLESE_BT_BOMB02_COUNT;

	public const BattleSE CRI_BATTLESE_BT_BOMB02_ZERO = BattleSE.CRI_BATTLESE_BT_BOMB02_ZERO;

	public const BattleSE CRI_BATTLESE_BT_BOSS07 = BattleSE.CRI_BATTLESE_BT_BOSS07;

	public const BattleSE CRI_BATTLESE_BT_BOSS08 = BattleSE.CRI_BATTLESE_BT_BOSS08;

	public const BattleSE CRI_BATTLESE_BT_BOSS09 = BattleSE.CRI_BATTLESE_BT_BOSS09;

	public const BattleSE CRI_BATTLESE_BT_BOSS10 = BattleSE.CRI_BATTLESE_BT_BOSS10;

	public const BattleSE CRI_BATTLESE_BT_BOSS14 = BattleSE.CRI_BATTLESE_BT_BOSS14;

	public const BattleSE CRI_BATTLESE_BT_BOSS15 = BattleSE.CRI_BATTLESE_BT_BOSS15;
}
