public static class CharaSE_VIA2i
{
	public const int iCRI_CHARASE_VIA2_CUENUM = 10;

	public const int iCRI_CHARASE_VIA2_VI2_JUMP = 1;

	public const int iCRI_CHARASE_VIA2_VI2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_VIA2_VI2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_VIA2_VI2_DASH = 4;

	public const int iCRI_CHARASE_VIA2_VI2_DASHEND = 5;

	public const int iCRI_CHARASE_VIA2_VI2_KABEPETA = 6;

	public const int iCRI_CHARASE_VIA2_VI2_KABEKERI = 7;

	public const int iCRI_CHARASE_VIA2_VI2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_VIA2_VI2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_VIA2_VI2_FOOT = 10;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_CUENUM = CharaSE_VIA2.CRI_CHARASE_VIA2_CUENUM;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_VI2_JUMP = CharaSE_VIA2.CRI_CHARASE_VIA2_VI2_JUMP;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_VI2_JUMP_HIGH = CharaSE_VIA2.CRI_CHARASE_VIA2_VI2_JUMP_HIGH;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_VI2_CHAKUCHI = CharaSE_VIA2.CRI_CHARASE_VIA2_VI2_CHAKUCHI;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_VI2_DASH = CharaSE_VIA2.CRI_CHARASE_VIA2_VI2_DASH;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_VI2_DASHEND = CharaSE_VIA2.CRI_CHARASE_VIA2_VI2_DASHEND;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_VI2_KABEPETA = CharaSE_VIA2.CRI_CHARASE_VIA2_VI2_KABEPETA;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_VI2_KABEKERI = CharaSE_VIA2.CRI_CHARASE_VIA2_VI2_KABEKERI;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_VI2_TELEPORT_IN = CharaSE_VIA2.CRI_CHARASE_VIA2_VI2_TELEPORT_IN;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_VI2_TELEPORT_OUT = CharaSE_VIA2.CRI_CHARASE_VIA2_VI2_TELEPORT_OUT;

	public const CharaSE_VIA2 CRI_CHARASE_VIA2_VI2_FOOT = CharaSE_VIA2.CRI_CHARASE_VIA2_CUENUM;
}
