public static class CharaSE_DRAGOONi
{
	public const int iCRI_CHARASE_DRAGOON_CUENUM = 10;

	public const int iCRI_CHARASE_DRAGOON_DG_JUMP = 1;

	public const int iCRI_CHARASE_DRAGOON_DG_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_DRAGOON_DG_CHAKUCHI = 3;

	public const int iCRI_CHARASE_DRAGOON_DG_DASH = 4;

	public const int iCRI_CHARASE_DRAGOON_DG_DASHEND = 5;

	public const int iCRI_CHARASE_DRAGOON_DG_KABEPETA = 6;

	public const int iCRI_CHARASE_DRAGOON_DG_KABEKERI = 7;

	public const int iCRI_CHARASE_DRAGOON_DG_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_DRAGOON_DG_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_DRAGOON_DG_FOOT = 10;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_CUENUM = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_CUENUM;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_DG_JUMP = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_DG_JUMP;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_DG_JUMP_HIGH = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_DG_JUMP_HIGH;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_DG_CHAKUCHI = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_DG_CHAKUCHI;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_DG_DASH = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_DG_DASH;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_DG_DASHEND = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_DG_DASHEND;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_DG_KABEPETA = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_DG_KABEPETA;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_DG_KABEKERI = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_DG_KABEKERI;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_DG_TELEPORT_IN = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_DG_TELEPORT_IN;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_DG_TELEPORT_OUT = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_DG_TELEPORT_OUT;

	public const CharaSE_DRAGOON CRI_CHARASE_DRAGOON_DG_FOOT = CharaSE_DRAGOON.CRI_CHARASE_DRAGOON_CUENUM;
}
