public static class CharaSE_TRON2i
{
	public const int iCRI_CHARASE_TRON2_CUENUM = 10;

	public const int iCRI_CHARASE_TRON2_TR2_JUMP = 1;

	public const int iCRI_CHARASE_TRON2_TR2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_TRON2_TR2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_TRON2_TR2_DASH = 4;

	public const int iCRI_CHARASE_TRON2_TR2_DASHEND = 5;

	public const int iCRI_CHARASE_TRON2_TR2_KABEPETA = 6;

	public const int iCRI_CHARASE_TRON2_TR2_KABEKERI = 7;

	public const int iCRI_CHARASE_TRON2_TR2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_TRON2_TR2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_TRON2_TR2_FOOT = 10;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_CUENUM = CharaSE_TRON2.CRI_CHARASE_TRON2_CUENUM;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_TR2_JUMP = CharaSE_TRON2.CRI_CHARASE_TRON2_TR2_JUMP;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_TR2_JUMP_HIGH = CharaSE_TRON2.CRI_CHARASE_TRON2_TR2_JUMP_HIGH;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_TR2_CHAKUCHI = CharaSE_TRON2.CRI_CHARASE_TRON2_TR2_CHAKUCHI;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_TR2_DASH = CharaSE_TRON2.CRI_CHARASE_TRON2_TR2_DASH;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_TR2_DASHEND = CharaSE_TRON2.CRI_CHARASE_TRON2_TR2_DASHEND;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_TR2_KABEPETA = CharaSE_TRON2.CRI_CHARASE_TRON2_TR2_KABEPETA;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_TR2_KABEKERI = CharaSE_TRON2.CRI_CHARASE_TRON2_TR2_KABEKERI;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_TR2_TELEPORT_IN = CharaSE_TRON2.CRI_CHARASE_TRON2_TR2_TELEPORT_IN;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_TR2_TELEPORT_OUT = CharaSE_TRON2.CRI_CHARASE_TRON2_TR2_TELEPORT_OUT;

	public const CharaSE_TRON2 CRI_CHARASE_TRON2_TR2_FOOT = CharaSE_TRON2.CRI_CHARASE_TRON2_CUENUM;
}
