public enum CharaSE_X
{
	NONE = 0,
	CRI_CHARASE_X_CUENUM = 10,
	CRI_CHARASE_X_X_JUMP = 1,
	CRI_CHARASE_X_X_JUMP_HIGH = 2,
	CRI_CHARASE_X_X_CHAKUCHI = 3,
	CRI_CHARASE_X_X_DASH = 4,
	CRI_CHARASE_X_X_DASHEND = 5,
	CRI_CHARASE_X_X_KABEPETA = 6,
	CRI_CHARASE_X_X_KABEKERI = 7,
	CRI_CHARASE_X_X_TELEPORT_IN = 8,
	CRI_CHARASE_X_X_TELEPORT_OUT = 9,
	CRI_CHARASE_X_X_FOOT = 10
}
