public enum CharaSE_BLUES
{
	NONE = 0,
	CRI_CHARASE_BLUES_CUENUM = 10,
	CRI_CHARASE_BLUES_BL_JUMP = 1,
	CRI_CHARASE_BLUES_BL_JUMP_HIGH = 2,
	CRI_CHARASE_BLUES_BL_CHAKUCHI = 3,
	CRI_CHARASE_BLUES_BL_DASH = 4,
	CRI_CHARASE_BLUES_BL_DASHEND = 5,
	CRI_CHARASE_BLUES_BL_KABEPETA = 6,
	CRI_CHARASE_BLUES_BL_KABEKERI = 7,
	CRI_CHARASE_BLUES_BL_TELEPORT_IN = 8,
	CRI_CHARASE_BLUES_BL_TELEPORT_OUT = 9,
	CRI_CHARASE_BLUES_BL_FOOT = 10
}
