public enum CharaSE_BlackZERO
{
	NONE = 0,
	CRI_CHARASE_BLACKZERO_CUENUM = 10,
	CRI_CHARASE_BLACKZERO_ZU_JUMP = 1,
	CRI_CHARASE_BLACKZERO_ZU_JUMP_HIGH = 2,
	CRI_CHARASE_BLACKZERO_ZU_CHAKUCHI = 3,
	CRI_CHARASE_BLACKZERO_ZU_DASH = 4,
	CRI_CHARASE_BLACKZERO_ZU_DASHEND = 5,
	CRI_CHARASE_BLACKZERO_ZU_KABEPETA = 6,
	CRI_CHARASE_BLACKZERO_ZU_KABEKERI = 7,
	CRI_CHARASE_BLACKZERO_ZU_TELEPORT_IN = 8,
	CRI_CHARASE_BLACKZERO_ZU_TELEPORT_OUT = 9,
	CRI_CHARASE_BLACKZERO_ZU_FOOT = 10
}
