public static class CharaSE_ICOi
{
	public const int iCRI_CHARASE_ICO_CUENUM = 10;

	public const int iCRI_CHARASE_ICO_IC_JUMP = 1;

	public const int iCRI_CHARASE_ICO_IC_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ICO_IC_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ICO_IC_DASH = 4;

	public const int iCRI_CHARASE_ICO_IC_DASHEND = 5;

	public const int iCRI_CHARASE_ICO_IC_KABEPETA = 6;

	public const int iCRI_CHARASE_ICO_IC_KABEKERI = 7;

	public const int iCRI_CHARASE_ICO_IC_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ICO_IC_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ICO_IC_FOOT = 10;

	public const CharaSE_ICO CRI_CHARASE_ICO_CUENUM = CharaSE_ICO.CRI_CHARASE_ICO_CUENUM;

	public const CharaSE_ICO CRI_CHARASE_ICO_IC_JUMP = CharaSE_ICO.CRI_CHARASE_ICO_IC_JUMP;

	public const CharaSE_ICO CRI_CHARASE_ICO_IC_JUMP_HIGH = CharaSE_ICO.CRI_CHARASE_ICO_IC_JUMP_HIGH;

	public const CharaSE_ICO CRI_CHARASE_ICO_IC_CHAKUCHI = CharaSE_ICO.CRI_CHARASE_ICO_IC_CHAKUCHI;

	public const CharaSE_ICO CRI_CHARASE_ICO_IC_DASH = CharaSE_ICO.CRI_CHARASE_ICO_IC_DASH;

	public const CharaSE_ICO CRI_CHARASE_ICO_IC_DASHEND = CharaSE_ICO.CRI_CHARASE_ICO_IC_DASHEND;

	public const CharaSE_ICO CRI_CHARASE_ICO_IC_KABEPETA = CharaSE_ICO.CRI_CHARASE_ICO_IC_KABEPETA;

	public const CharaSE_ICO CRI_CHARASE_ICO_IC_KABEKERI = CharaSE_ICO.CRI_CHARASE_ICO_IC_KABEKERI;

	public const CharaSE_ICO CRI_CHARASE_ICO_IC_TELEPORT_IN = CharaSE_ICO.CRI_CHARASE_ICO_IC_TELEPORT_IN;

	public const CharaSE_ICO CRI_CHARASE_ICO_IC_TELEPORT_OUT = CharaSE_ICO.CRI_CHARASE_ICO_IC_TELEPORT_OUT;

	public const CharaSE_ICO CRI_CHARASE_ICO_IC_FOOT = CharaSE_ICO.CRI_CHARASE_ICO_CUENUM;
}
