public static class CharaSE_XMHi
{
	public const int iCRI_CHARASE_XMH_CUENUM = 10;

	public const int iCRI_CHARASE_XMH_XM_JUMP = 1;

	public const int iCRI_CHARASE_XMH_XM_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_XMH_XM_CHAKUCHI = 3;

	public const int iCRI_CHARASE_XMH_XM_DASH = 4;

	public const int iCRI_CHARASE_XMH_XM_DASHEND = 5;

	public const int iCRI_CHARASE_XMH_XM_KABEPETA = 6;

	public const int iCRI_CHARASE_XMH_XM_KABEKERI = 7;

	public const int iCRI_CHARASE_XMH_XM_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_XMH_XM_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_XMH_XM_FOOT = 10;

	public const CharaSE_XMH CRI_CHARASE_XMH_CUENUM = CharaSE_XMH.CRI_CHARASE_XMH_CUENUM;

	public const CharaSE_XMH CRI_CHARASE_XMH_XM_JUMP = CharaSE_XMH.CRI_CHARASE_XMH_XM_JUMP;

	public const CharaSE_XMH CRI_CHARASE_XMH_XM_JUMP_HIGH = CharaSE_XMH.CRI_CHARASE_XMH_XM_JUMP_HIGH;

	public const CharaSE_XMH CRI_CHARASE_XMH_XM_CHAKUCHI = CharaSE_XMH.CRI_CHARASE_XMH_XM_CHAKUCHI;

	public const CharaSE_XMH CRI_CHARASE_XMH_XM_DASH = CharaSE_XMH.CRI_CHARASE_XMH_XM_DASH;

	public const CharaSE_XMH CRI_CHARASE_XMH_XM_DASHEND = CharaSE_XMH.CRI_CHARASE_XMH_XM_DASHEND;

	public const CharaSE_XMH CRI_CHARASE_XMH_XM_KABEPETA = CharaSE_XMH.CRI_CHARASE_XMH_XM_KABEPETA;

	public const CharaSE_XMH CRI_CHARASE_XMH_XM_KABEKERI = CharaSE_XMH.CRI_CHARASE_XMH_XM_KABEKERI;

	public const CharaSE_XMH CRI_CHARASE_XMH_XM_TELEPORT_IN = CharaSE_XMH.CRI_CHARASE_XMH_XM_TELEPORT_IN;

	public const CharaSE_XMH CRI_CHARASE_XMH_XM_TELEPORT_OUT = CharaSE_XMH.CRI_CHARASE_XMH_XM_TELEPORT_OUT;

	public const CharaSE_XMH CRI_CHARASE_XMH_XM_FOOT = CharaSE_XMH.CRI_CHARASE_XMH_CUENUM;
}
