public static class CharaSE_FORTEi
{
	public const int iCRI_CHARASE_FORTE_CUENUM = 10;

	public const int iCRI_CHARASE_FORTE_FO_JUMP = 1;

	public const int iCRI_CHARASE_FORTE_FO_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_FORTE_FO_CHAKUCHI = 3;

	public const int iCRI_CHARASE_FORTE_FO_DASH = 4;

	public const int iCRI_CHARASE_FORTE_FO_DASHEND = 5;

	public const int iCRI_CHARASE_FORTE_FO_KABEPETA = 6;

	public const int iCRI_CHARASE_FORTE_FO_KABEKERI = 7;

	public const int iCRI_CHARASE_FORTE_FO_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_FORTE_FO_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_FORTE_FO_FOOT = 10;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_CUENUM = CharaSE_FORTE.CRI_CHARASE_FORTE_CUENUM;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_FO_JUMP = CharaSE_FORTE.CRI_CHARASE_FORTE_FO_JUMP;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_FO_JUMP_HIGH = CharaSE_FORTE.CRI_CHARASE_FORTE_FO_JUMP_HIGH;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_FO_CHAKUCHI = CharaSE_FORTE.CRI_CHARASE_FORTE_FO_CHAKUCHI;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_FO_DASH = CharaSE_FORTE.CRI_CHARASE_FORTE_FO_DASH;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_FO_DASHEND = CharaSE_FORTE.CRI_CHARASE_FORTE_FO_DASHEND;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_FO_KABEPETA = CharaSE_FORTE.CRI_CHARASE_FORTE_FO_KABEPETA;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_FO_KABEKERI = CharaSE_FORTE.CRI_CHARASE_FORTE_FO_KABEKERI;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_FO_TELEPORT_IN = CharaSE_FORTE.CRI_CHARASE_FORTE_FO_TELEPORT_IN;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_FO_TELEPORT_OUT = CharaSE_FORTE.CRI_CHARASE_FORTE_FO_TELEPORT_OUT;

	public const CharaSE_FORTE CRI_CHARASE_FORTE_FO_FOOT = CharaSE_FORTE.CRI_CHARASE_FORTE_CUENUM;
}
