public enum CharaSE_HARPNOTE
{
	NONE = 0,
	CRI_CHARASE_HARPNOTE_CUENUM = 10,
	CRI_CHARASE_HARPNOTE_HN_JUMP = 1,
	CRI_CHARASE_HARPNOTE_HN_JUMP_HIGH = 2,
	CRI_CHARASE_HARPNOTE_HN_CHAKUCHI = 3,
	CRI_CHARASE_HARPNOTE_HN_DASH = 4,
	CRI_CHARASE_HARPNOTE_HN_DASHEND = 5,
	CRI_CHARASE_HARPNOTE_HN_KABEPETA = 6,
	CRI_CHARASE_HARPNOTE_HN_KABEKERI = 7,
	CRI_CHARASE_HARPNOTE_HN_TELEPORT_IN = 8,
	CRI_CHARASE_HARPNOTE_HN_TELEPORT_OUT = 9,
	CRI_CHARASE_HARPNOTE_HN_FOOT = 10
}
