public enum CharaSE_KOBUN
{
	NONE = 0,
	CRI_CHARASE_KOBUN_CUENUM = 10,
	CRI_CHARASE_KOBUN_KB_JUMP = 1,
	CRI_CHARASE_KOBUN_KB_JUMP_HIGH = 2,
	CRI_CHARASE_KOBUN_KB_CHAKUCHI = 3,
	CRI_CHARASE_KOBUN_KB_DASH = 4,
	CRI_CHARASE_KOBUN_KB_DASHEND = 5,
	CRI_CHARASE_KOBUN_KB_KABEPETA = 6,
	CRI_CHARASE_KOBUN_KB_KABEKERI = 7,
	CRI_CHARASE_KOBUN_KB_TELEPORT_IN = 8,
	CRI_CHARASE_KOBUN_KB_TELEPORT_OUT = 9,
	CRI_CHARASE_KOBUN_KB_FOOT = 10
}
