public static class CharaSE_MASSIMOi
{
	public const int iCRI_CHARASE_MASSIMO_CUENUM = 10;

	public const int iCRI_CHARASE_MASSIMO_MS_JUMP = 1;

	public const int iCRI_CHARASE_MASSIMO_MS_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_MASSIMO_MS_CHAKUCHI = 3;

	public const int iCRI_CHARASE_MASSIMO_MS_DASH = 4;

	public const int iCRI_CHARASE_MASSIMO_MS_DASHEND = 5;

	public const int iCRI_CHARASE_MASSIMO_MS_KABEPETA = 6;

	public const int iCRI_CHARASE_MASSIMO_MS_KABEKERI = 7;

	public const int iCRI_CHARASE_MASSIMO_MS_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_MASSIMO_MS_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_MASSIMO_MS_FOOT = 10;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_CUENUM = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_CUENUM;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_MS_JUMP = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_MS_JUMP;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_MS_JUMP_HIGH = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_MS_JUMP_HIGH;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_MS_CHAKUCHI = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_MS_CHAKUCHI;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_MS_DASH = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_MS_DASH;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_MS_DASHEND = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_MS_DASHEND;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_MS_KABEPETA = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_MS_KABEPETA;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_MS_KABEKERI = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_MS_KABEKERI;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_MS_TELEPORT_IN = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_MS_TELEPORT_IN;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_MS_TELEPORT_OUT = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_MS_TELEPORT_OUT;

	public const CharaSE_MASSIMO CRI_CHARASE_MASSIMO_MS_FOOT = CharaSE_MASSIMO.CRI_CHARASE_MASSIMO_CUENUM;
}
