public static class CharaSE_ROLLi
{
	public const int iCRI_CHARASE_ROLL_CUENUM = 10;

	public const int iCRI_CHARASE_ROLL_RL_JUMP = 1;

	public const int iCRI_CHARASE_ROLL_RL_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ROLL_RL_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ROLL_RL_DASH = 4;

	public const int iCRI_CHARASE_ROLL_RL_DASHEND = 5;

	public const int iCRI_CHARASE_ROLL_RL_KABEPETA = 6;

	public const int iCRI_CHARASE_ROLL_RL_KABEKERI = 7;

	public const int iCRI_CHARASE_ROLL_RL_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ROLL_RL_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ROLL_RL_FOOT = 10;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_CUENUM = CharaSE_ROLL.CRI_CHARASE_ROLL_CUENUM;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_RL_JUMP = CharaSE_ROLL.CRI_CHARASE_ROLL_RL_JUMP;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_RL_JUMP_HIGH = CharaSE_ROLL.CRI_CHARASE_ROLL_RL_JUMP_HIGH;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_RL_CHAKUCHI = CharaSE_ROLL.CRI_CHARASE_ROLL_RL_CHAKUCHI;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_RL_DASH = CharaSE_ROLL.CRI_CHARASE_ROLL_RL_DASH;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_RL_DASHEND = CharaSE_ROLL.CRI_CHARASE_ROLL_RL_DASHEND;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_RL_KABEPETA = CharaSE_ROLL.CRI_CHARASE_ROLL_RL_KABEPETA;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_RL_KABEKERI = CharaSE_ROLL.CRI_CHARASE_ROLL_RL_KABEKERI;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_RL_TELEPORT_IN = CharaSE_ROLL.CRI_CHARASE_ROLL_RL_TELEPORT_IN;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_RL_TELEPORT_OUT = CharaSE_ROLL.CRI_CHARASE_ROLL_RL_TELEPORT_OUT;

	public const CharaSE_ROLL CRI_CHARASE_ROLL_RL_FOOT = CharaSE_ROLL.CRI_CHARASE_ROLL_CUENUM;
}
