public enum CharaSE_GOUKI
{
	NONE = 0,
	CRI_CHARASE_GOUKI_CUENUM = 10,
	CRI_CHARASE_GOUKI_GO_JUMP = 1,
	CRI_CHARASE_GOUKI_GO_JUMP_HIGH = 2,
	CRI_CHARASE_GOUKI_GO_CHAKUCHI = 3,
	CRI_CHARASE_GOUKI_GO_DASH = 4,
	CRI_CHARASE_GOUKI_GO_DASHEND = 5,
	CRI_CHARASE_GOUKI_GO_KABEPETA = 6,
	CRI_CHARASE_GOUKI_GO_KABEKERI = 7,
	CRI_CHARASE_GOUKI_GO_TELEPORT_IN = 8,
	CRI_CHARASE_GOUKI_GO_TELEPORT_OUT = 9,
	CRI_CHARASE_GOUKI_GO_FOOT = 10
}
