public static class CharaSE_RMEXEi
{
	public const int iCRI_CHARASE_RMEXE_CUENUM = 10;

	public const int iCRI_CHARASE_RMEXE_RE_JUMP = 1;

	public const int iCRI_CHARASE_RMEXE_RE_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_RMEXE_RE_CHAKUCHI = 3;

	public const int iCRI_CHARASE_RMEXE_RE_DASH = 4;

	public const int iCRI_CHARASE_RMEXE_RE_DASHEND = 5;

	public const int iCRI_CHARASE_RMEXE_RE_KABEPETA = 6;

	public const int iCRI_CHARASE_RMEXE_RE_KABEKERI = 7;

	public const int iCRI_CHARASE_RMEXE_RE_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_RMEXE_RE_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_RMEXE_RE_FOOT = 10;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_CUENUM = CharaSE_RMEXE.CRI_CHARASE_RMEXE_CUENUM;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_RE_JUMP = CharaSE_RMEXE.CRI_CHARASE_RMEXE_RE_JUMP;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_RE_JUMP_HIGH = CharaSE_RMEXE.CRI_CHARASE_RMEXE_RE_JUMP_HIGH;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_RE_CHAKUCHI = CharaSE_RMEXE.CRI_CHARASE_RMEXE_RE_CHAKUCHI;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_RE_DASH = CharaSE_RMEXE.CRI_CHARASE_RMEXE_RE_DASH;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_RE_DASHEND = CharaSE_RMEXE.CRI_CHARASE_RMEXE_RE_DASHEND;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_RE_KABEPETA = CharaSE_RMEXE.CRI_CHARASE_RMEXE_RE_KABEPETA;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_RE_KABEKERI = CharaSE_RMEXE.CRI_CHARASE_RMEXE_RE_KABEKERI;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_RE_TELEPORT_IN = CharaSE_RMEXE.CRI_CHARASE_RMEXE_RE_TELEPORT_IN;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_RE_TELEPORT_OUT = CharaSE_RMEXE.CRI_CHARASE_RMEXE_RE_TELEPORT_OUT;

	public const CharaSE_RMEXE CRI_CHARASE_RMEXE_RE_FOOT = CharaSE_RMEXE.CRI_CHARASE_RMEXE_CUENUM;
}
