public static class CharaSE_ALIAi
{
	public const int iCRI_CHARASE_ALIA_CUENUM = 10;

	public const int iCRI_CHARASE_ALIA_AA_JUMP = 1;

	public const int iCRI_CHARASE_ALIA_AA_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ALIA_AA_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ALIA_AA_DASH = 4;

	public const int iCRI_CHARASE_ALIA_AA_DASHEND = 5;

	public const int iCRI_CHARASE_ALIA_AA_KABEPETA = 6;

	public const int iCRI_CHARASE_ALIA_AA_KABEKERI = 7;

	public const int iCRI_CHARASE_ALIA_AA_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ALIA_AA_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ALIA_AA_FOOT = 10;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_CUENUM = CharaSE_ALIA.CRI_CHARASE_ALIA_CUENUM;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_AA_JUMP = CharaSE_ALIA.CRI_CHARASE_ALIA_AA_JUMP;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_AA_JUMP_HIGH = CharaSE_ALIA.CRI_CHARASE_ALIA_AA_JUMP_HIGH;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_AA_CHAKUCHI = CharaSE_ALIA.CRI_CHARASE_ALIA_AA_CHAKUCHI;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_AA_DASH = CharaSE_ALIA.CRI_CHARASE_ALIA_AA_DASH;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_AA_DASHEND = CharaSE_ALIA.CRI_CHARASE_ALIA_AA_DASHEND;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_AA_KABEPETA = CharaSE_ALIA.CRI_CHARASE_ALIA_AA_KABEPETA;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_AA_KABEKERI = CharaSE_ALIA.CRI_CHARASE_ALIA_AA_KABEKERI;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_AA_TELEPORT_IN = CharaSE_ALIA.CRI_CHARASE_ALIA_AA_TELEPORT_IN;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_AA_TELEPORT_OUT = CharaSE_ALIA.CRI_CHARASE_ALIA_AA_TELEPORT_OUT;

	public const CharaSE_ALIA CRI_CHARASE_ALIA_AA_FOOT = CharaSE_ALIA.CRI_CHARASE_ALIA_CUENUM;
}
