public enum CharaSE_CIEL2
{
	NONE = 0,
	CRI_CHARASE_CIEL2_CUENUM = 10,
	CRI_CHARASE_CIEL2_CL2_JUMP = 1,
	CRI_CHARASE_CIEL2_CL2_JUMP_HIGH = 2,
	CRI_CHARASE_CIEL2_CL2_CHAKUCHI = 3,
	CRI_CHARASE_CIEL2_CL2_DASH = 4,
	CRI_CHARASE_CIEL2_CL2_DASHEND = 5,
	CRI_CHARASE_CIEL2_CL2_KABEPETA = 6,
	CRI_CHARASE_CIEL2_CL2_KABEKERI = 7,
	CRI_CHARASE_CIEL2_CL2_TELEPORT_IN = 8,
	CRI_CHARASE_CIEL2_CL2_TELEPORT_OUT = 9,
	CRI_CHARASE_CIEL2_CL2_FOOT = 10
}
