public static class CharaSE_ERATOi
{
	public const int iCRI_CHARASE_ERATO_CUENUM = 10;

	public const int iCRI_CHARASE_ERATO_ER_JUMP = 1;

	public const int iCRI_CHARASE_ERATO_ER_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ERATO_ER_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ERATO_ER_DASH = 4;

	public const int iCRI_CHARASE_ERATO_ER_DASHEND = 5;

	public const int iCRI_CHARASE_ERATO_ER_KABEPETA = 6;

	public const int iCRI_CHARASE_ERATO_ER_KABEKERI = 7;

	public const int iCRI_CHARASE_ERATO_ER_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ERATO_ER_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ERATO_ER_FOOT = 10;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_CUENUM = CharaSE_ERATO.CRI_CHARASE_ERATO_CUENUM;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_ER_JUMP = CharaSE_ERATO.CRI_CHARASE_ERATO_ER_JUMP;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_ER_JUMP_HIGH = CharaSE_ERATO.CRI_CHARASE_ERATO_ER_JUMP_HIGH;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_ER_CHAKUCHI = CharaSE_ERATO.CRI_CHARASE_ERATO_ER_CHAKUCHI;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_ER_DASH = CharaSE_ERATO.CRI_CHARASE_ERATO_ER_DASH;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_ER_DASHEND = CharaSE_ERATO.CRI_CHARASE_ERATO_ER_DASHEND;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_ER_KABEPETA = CharaSE_ERATO.CRI_CHARASE_ERATO_ER_KABEPETA;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_ER_KABEKERI = CharaSE_ERATO.CRI_CHARASE_ERATO_ER_KABEKERI;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_ER_TELEPORT_IN = CharaSE_ERATO.CRI_CHARASE_ERATO_ER_TELEPORT_IN;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_ER_TELEPORT_OUT = CharaSE_ERATO.CRI_CHARASE_ERATO_ER_TELEPORT_OUT;

	public const CharaSE_ERATO CRI_CHARASE_ERATO_ER_FOOT = CharaSE_ERATO.CRI_CHARASE_ERATO_CUENUM;
}
