public enum CharaSE_FERHAM
{
	NONE = 0,
	CRI_CHARASE_FERHAM_CUENUM = 10,
	CRI_CHARASE_FERHAM_FM_JUMP = 1,
	CRI_CHARASE_FERHAM_FM_JUMP_HIGH = 2,
	CRI_CHARASE_FERHAM_FM_CHAKUCHI = 3,
	CRI_CHARASE_FERHAM_FM_DASH = 4,
	CRI_CHARASE_FERHAM_FM_DASHEND = 5,
	CRI_CHARASE_FERHAM_FM_KABEPETA = 6,
	CRI_CHARASE_FERHAM_FM_KABEKERI = 7,
	CRI_CHARASE_FERHAM_FM_TELEPORT_IN = 8,
	CRI_CHARASE_FERHAM_FM_TELEPORT_OUT = 9,
	CRI_CHARASE_FERHAM_FM_FOOT = 10
}
