public static class CharaSE_HARPNOTEi
{
	public const int iCRI_CHARASE_HARPNOTE_CUENUM = 10;

	public const int iCRI_CHARASE_HARPNOTE_HN_JUMP = 1;

	public const int iCRI_CHARASE_HARPNOTE_HN_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_HARPNOTE_HN_CHAKUCHI = 3;

	public const int iCRI_CHARASE_HARPNOTE_HN_DASH = 4;

	public const int iCRI_CHARASE_HARPNOTE_HN_DASHEND = 5;

	public const int iCRI_CHARASE_HARPNOTE_HN_KABEPETA = 6;

	public const int iCRI_CHARASE_HARPNOTE_HN_KABEKERI = 7;

	public const int iCRI_CHARASE_HARPNOTE_HN_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_HARPNOTE_HN_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_HARPNOTE_HN_FOOT = 10;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_CUENUM = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_CUENUM;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_HN_JUMP = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_HN_JUMP;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_HN_JUMP_HIGH = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_HN_JUMP_HIGH;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_HN_CHAKUCHI = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_HN_CHAKUCHI;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_HN_DASH = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_HN_DASH;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_HN_DASHEND = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_HN_DASHEND;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_HN_KABEPETA = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_HN_KABEPETA;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_HN_KABEKERI = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_HN_KABEKERI;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_HN_TELEPORT_IN = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_HN_TELEPORT_IN;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_HN_TELEPORT_OUT = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_HN_TELEPORT_OUT;

	public const CharaSE_HARPNOTE CRI_CHARASE_HARPNOTE_HN_FOOT = CharaSE_HARPNOTE.CRI_CHARASE_HARPNOTE_CUENUM;
}
