public enum CharaSE_AwakenZero
{
	NONE = 0,
	CRI_CHARASE_AWAKENZERO_CUENUM = 10,
	CRI_CHARASE_AWAKENZERO_ZA_JUMP = 1,
	CRI_CHARASE_AWAKENZERO_ZA_JUMP_HIGH = 2,
	CRI_CHARASE_AWAKENZERO_ZA_CHAKUCHI = 3,
	CRI_CHARASE_AWAKENZERO_ZA_DASH = 4,
	CRI_CHARASE_AWAKENZERO_ZA_DASHEND = 5,
	CRI_CHARASE_AWAKENZERO_ZA_KABEPETA = 6,
	CRI_CHARASE_AWAKENZERO_ZA_KABEKERI = 7,
	CRI_CHARASE_AWAKENZERO_ZA_TELEPORT_IN = 8,
	CRI_CHARASE_AWAKENZERO_ZA_TELEPORT_OUT = 9,
	CRI_CHARASE_AWAKENZERO_ZA_FOOT = 10
}
