public enum CharaSE_IRIS3
{
	NONE = 0,
	CRI_CHARASE_IRIS3_CUENUM = 10,
	CRI_CHARASE_IRIS3_IR3_JUMP = 1,
	CRI_CHARASE_IRIS3_IR3_JUMP_HIGH = 2,
	CRI_CHARASE_IRIS3_IR3_CHAKUCHI = 3,
	CRI_CHARASE_IRIS3_IR3_DASH = 4,
	CRI_CHARASE_IRIS3_IR3_DASHEND = 5,
	CRI_CHARASE_IRIS3_IR3_KABEPETA = 6,
	CRI_CHARASE_IRIS3_IR3_KABEKERI = 7,
	CRI_CHARASE_IRIS3_IR3_TELEPORT_IN = 8,
	CRI_CHARASE_IRIS3_IR3_TELEPORT_OUT = 9,
	CRI_CHARASE_IRIS3_IR3_FOOT = 10
}
