public enum CharaSE_ROCKMAN
{
	NONE = 0,
	CRI_CHARASE_ROCKMAN_CUENUM = 10,
	CRI_CHARASE_ROCKMAN_RM_JUMP = 1,
	CRI_CHARASE_ROCKMAN_RM_JUMP_HIGH = 2,
	CRI_CHARASE_ROCKMAN_RM_CHAKUCHI = 3,
	CRI_CHARASE_ROCKMAN_RM_DASH = 4,
	CRI_CHARASE_ROCKMAN_RM_DASHEND = 5,
	CRI_CHARASE_ROCKMAN_RM_KABEPETA = 6,
	CRI_CHARASE_ROCKMAN_RM_KABEKERI = 7,
	CRI_CHARASE_ROCKMAN_RM_TELEPORT_IN = 8,
	CRI_CHARASE_ROCKMAN_RM_TELEPORT_OUT = 9,
	CRI_CHARASE_ROCKMAN_RM_FOOT = 10
}
