public static class CharaSE_PANDORAi
{
	public const int iCRI_CHARASE_PANDORA_CUENUM = 10;

	public const int iCRI_CHARASE_PANDORA_PD_JUMP = 1;

	public const int iCRI_CHARASE_PANDORA_PD_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_PANDORA_PD_CHAKUCHI = 3;

	public const int iCRI_CHARASE_PANDORA_PD_DASH = 4;

	public const int iCRI_CHARASE_PANDORA_PD_DASHEND = 5;

	public const int iCRI_CHARASE_PANDORA_PD_KABEPETA = 6;

	public const int iCRI_CHARASE_PANDORA_PD_KABEKERI = 7;

	public const int iCRI_CHARASE_PANDORA_PD_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_PANDORA_PD_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_PANDORA_PD_FOOT = 10;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_CUENUM = CharaSE_PANDORA.CRI_CHARASE_PANDORA_CUENUM;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_PD_JUMP = CharaSE_PANDORA.CRI_CHARASE_PANDORA_PD_JUMP;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_PD_JUMP_HIGH = CharaSE_PANDORA.CRI_CHARASE_PANDORA_PD_JUMP_HIGH;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_PD_CHAKUCHI = CharaSE_PANDORA.CRI_CHARASE_PANDORA_PD_CHAKUCHI;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_PD_DASH = CharaSE_PANDORA.CRI_CHARASE_PANDORA_PD_DASH;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_PD_DASHEND = CharaSE_PANDORA.CRI_CHARASE_PANDORA_PD_DASHEND;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_PD_KABEPETA = CharaSE_PANDORA.CRI_CHARASE_PANDORA_PD_KABEPETA;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_PD_KABEKERI = CharaSE_PANDORA.CRI_CHARASE_PANDORA_PD_KABEKERI;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_PD_TELEPORT_IN = CharaSE_PANDORA.CRI_CHARASE_PANDORA_PD_TELEPORT_IN;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_PD_TELEPORT_OUT = CharaSE_PANDORA.CRI_CHARASE_PANDORA_PD_TELEPORT_OUT;

	public const CharaSE_PANDORA CRI_CHARASE_PANDORA_PD_FOOT = CharaSE_PANDORA.CRI_CHARASE_PANDORA_CUENUM;
}
