public static class CharaSE_ZERODivei
{
	public const int iCRI_CHARASE_ZERODIVE_CUENUM = 10;

	public const int iCRI_CHARASE_ZERODIVE_ZD_JUMP = 1;

	public const int iCRI_CHARASE_ZERODIVE_ZD_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ZERODIVE_ZD_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ZERODIVE_ZD_DASH = 4;

	public const int iCRI_CHARASE_ZERODIVE_ZD_DASHEND = 5;

	public const int iCRI_CHARASE_ZERODIVE_ZD_KABEPETA = 6;

	public const int iCRI_CHARASE_ZERODIVE_ZD_KABEKERI = 7;

	public const int iCRI_CHARASE_ZERODIVE_ZD_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ZERODIVE_ZD_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ZERODIVE_ZD_FOOT = 10;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_CUENUM = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_CUENUM;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_ZD_JUMP = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_ZD_JUMP;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_ZD_JUMP_HIGH = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_ZD_JUMP_HIGH;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_ZD_CHAKUCHI = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_ZD_CHAKUCHI;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_ZD_DASH = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_ZD_DASH;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_ZD_DASHEND = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_ZD_DASHEND;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_ZD_KABEPETA = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_ZD_KABEPETA;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_ZD_KABEKERI = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_ZD_KABEKERI;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_ZD_TELEPORT_IN = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_ZD_TELEPORT_IN;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_ZD_TELEPORT_OUT = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_ZD_TELEPORT_OUT;

	public const CharaSE_ZERODive CRI_CHARASE_ZERODIVE_ZD_FOOT = CharaSE_ZERODive.CRI_CHARASE_ZERODIVE_CUENUM;
}
