public enum CharaSE_GATE
{
	NONE = 0,
	CRI_CHARASE_GATE_CUENUM = 10,
	CRI_CHARASE_GATE_GT_JUMP = 1,
	CRI_CHARASE_GATE_GT_JUMP_HIGH = 2,
	CRI_CHARASE_GATE_GT_CHAKUCHI = 3,
	CRI_CHARASE_GATE_GT_DASH = 4,
	CRI_CHARASE_GATE_GT_DASHEND = 5,
	CRI_CHARASE_GATE_GT_KABEPETA = 6,
	CRI_CHARASE_GATE_GT_KABEKERI = 7,
	CRI_CHARASE_GATE_GT_TELEPORT_IN = 8,
	CRI_CHARASE_GATE_GT_TELEPORT_OUT = 9,
	CRI_CHARASE_GATE_GT_FOOT = 10
}
