public static class CharaSE_CIEL3i
{
	public const int iCRI_CHARASE_CIEL3_CUENUM = 10;

	public const int iCRI_CHARASE_CIEL3_CL3_JUMP = 1;

	public const int iCRI_CHARASE_CIEL3_CL3_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_CIEL3_CL3_CHAKUCHI = 3;

	public const int iCRI_CHARASE_CIEL3_CL3_DASH = 4;

	public const int iCRI_CHARASE_CIEL3_CL3_DASHEND = 5;

	public const int iCRI_CHARASE_CIEL3_CL3_KABEPETA = 6;

	public const int iCRI_CHARASE_CIEL3_CL3_KABEKERI = 7;

	public const int iCRI_CHARASE_CIEL3_CL3_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_CIEL3_CL3_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_CIEL3_CL3_FOOT = 10;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CUENUM = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CUENUM;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CL3_JUMP = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CL3_JUMP;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CL3_JUMP_HIGH = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CL3_JUMP_HIGH;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CL3_CHAKUCHI = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CL3_CHAKUCHI;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CL3_DASH = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CL3_DASH;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CL3_DASHEND = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CL3_DASHEND;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CL3_KABEPETA = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CL3_KABEPETA;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CL3_KABEKERI = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CL3_KABEKERI;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CL3_TELEPORT_IN = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CL3_TELEPORT_IN;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CL3_TELEPORT_OUT = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CL3_TELEPORT_OUT;

	public const CharaSE_CIEL3 CRI_CHARASE_CIEL3_CL3_FOOT = CharaSE_CIEL3.CRI_CHARASE_CIEL3_CUENUM;
}
