public static class CharaSE_LAYERi
{
	public const int iCRI_CHARASE_LAYER_CUENUM = 10;

	public const int iCRI_CHARASE_LAYER_LY_JUMP = 1;

	public const int iCRI_CHARASE_LAYER_LY_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_LAYER_LY_CHAKUCHI = 3;

	public const int iCRI_CHARASE_LAYER_LY_DASH = 4;

	public const int iCRI_CHARASE_LAYER_LY_DASHEND = 5;

	public const int iCRI_CHARASE_LAYER_LY_KABEPETA = 6;

	public const int iCRI_CHARASE_LAYER_LY_KABEKERI = 7;

	public const int iCRI_CHARASE_LAYER_LY_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_LAYER_LY_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_LAYER_LY_FOOT = 10;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_CUENUM = CharaSE_LAYER.CRI_CHARASE_LAYER_CUENUM;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_LY_JUMP = CharaSE_LAYER.CRI_CHARASE_LAYER_LY_JUMP;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_LY_JUMP_HIGH = CharaSE_LAYER.CRI_CHARASE_LAYER_LY_JUMP_HIGH;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_LY_CHAKUCHI = CharaSE_LAYER.CRI_CHARASE_LAYER_LY_CHAKUCHI;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_LY_DASH = CharaSE_LAYER.CRI_CHARASE_LAYER_LY_DASH;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_LY_DASHEND = CharaSE_LAYER.CRI_CHARASE_LAYER_LY_DASHEND;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_LY_KABEPETA = CharaSE_LAYER.CRI_CHARASE_LAYER_LY_KABEPETA;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_LY_KABEKERI = CharaSE_LAYER.CRI_CHARASE_LAYER_LY_KABEKERI;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_LY_TELEPORT_IN = CharaSE_LAYER.CRI_CHARASE_LAYER_LY_TELEPORT_IN;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_LY_TELEPORT_OUT = CharaSE_LAYER.CRI_CHARASE_LAYER_LY_TELEPORT_OUT;

	public const CharaSE_LAYER CRI_CHARASE_LAYER_LY_FOOT = CharaSE_LAYER.CRI_CHARASE_LAYER_CUENUM;
}
