public enum CharaSE_ZERO
{
	NONE = 0,
	CRI_CHARASE_ZERO_CUENUM = 10,
	CRI_CHARASE_ZERO_Z_JUMP = 1,
	CRI_CHARASE_ZERO_Z_JUMP_HIGH = 2,
	CRI_CHARASE_ZERO_Z_CHAKUCHI = 3,
	CRI_CHARASE_ZERO_Z_DASH = 4,
	CRI_CHARASE_ZERO_Z_DASHEND = 5,
	CRI_CHARASE_ZERO_Z_KABEPETA = 6,
	CRI_CHARASE_ZERO_Z_KABEKERI = 7,
	CRI_CHARASE_ZERO_Z_TELEPORT_IN = 8,
	CRI_CHARASE_ZERO_Z_TELEPORT_OUT = 9,
	CRI_CHARASE_ZERO_Z_FOOT = 10
}
