public static class CharaSE_RMZeroi
{
	public const int iCRI_CHARASE_RMZERO_CUENUM = 10;

	public const int iCRI_CHARASE_RMZERO_ZZ_JUMP = 1;

	public const int iCRI_CHARASE_RMZERO_ZZ_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_RMZERO_ZZ_CHAKUCHI = 3;

	public const int iCRI_CHARASE_RMZERO_ZZ_DASH = 4;

	public const int iCRI_CHARASE_RMZERO_ZZ_DASHEND = 5;

	public const int iCRI_CHARASE_RMZERO_ZZ_KABEPETA = 6;

	public const int iCRI_CHARASE_RMZERO_ZZ_KABEKERI = 7;

	public const int iCRI_CHARASE_RMZERO_ZZ_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_RMZERO_ZZ_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_RMZERO_ZZ_FOOT = 10;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_CUENUM = CharaSE_RMZero.CRI_CHARASE_RMZERO_CUENUM;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_ZZ_JUMP = CharaSE_RMZero.CRI_CHARASE_RMZERO_ZZ_JUMP;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_ZZ_JUMP_HIGH = CharaSE_RMZero.CRI_CHARASE_RMZERO_ZZ_JUMP_HIGH;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_ZZ_CHAKUCHI = CharaSE_RMZero.CRI_CHARASE_RMZERO_ZZ_CHAKUCHI;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_ZZ_DASH = CharaSE_RMZero.CRI_CHARASE_RMZERO_ZZ_DASH;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_ZZ_DASHEND = CharaSE_RMZero.CRI_CHARASE_RMZERO_ZZ_DASHEND;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_ZZ_KABEPETA = CharaSE_RMZero.CRI_CHARASE_RMZERO_ZZ_KABEPETA;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_ZZ_KABEKERI = CharaSE_RMZero.CRI_CHARASE_RMZERO_ZZ_KABEKERI;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_ZZ_TELEPORT_IN = CharaSE_RMZero.CRI_CHARASE_RMZERO_ZZ_TELEPORT_IN;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_ZZ_TELEPORT_OUT = CharaSE_RMZero.CRI_CHARASE_RMZERO_ZZ_TELEPORT_OUT;

	public const CharaSE_RMZero CRI_CHARASE_RMZERO_ZZ_FOOT = CharaSE_RMZero.CRI_CHARASE_RMZERO_CUENUM;
}
