public enum CharaSE_DRRIGHT
{
	NONE = 0,
	CRI_CHARASE_DRRIGHT_CUENUM = 10,
	CRI_CHARASE_DRRIGHT_DR_JUMP = 1,
	CRI_CHARASE_DRRIGHT_DR_JUMP_HIGH = 2,
	CRI_CHARASE_DRRIGHT_DR_CHAKUCHI = 3,
	CRI_CHARASE_DRRIGHT_DR_DASH = 4,
	CRI_CHARASE_DRRIGHT_DR_DASHEND = 5,
	CRI_CHARASE_DRRIGHT_DR_KABEPETA = 6,
	CRI_CHARASE_DRRIGHT_DR_KABEKERI = 7,
	CRI_CHARASE_DRRIGHT_DR_TELEPORT_IN = 8,
	CRI_CHARASE_DRRIGHT_DR_TELEPORT_OUT = 9,
	CRI_CHARASE_DRRIGHT_DR_FOOT = 10
}
