public enum CharaSE_CHUNLI
{
	NONE = 0,
	CRI_CHARASE_CHUNLI_CUENUM = 10,
	CRI_CHARASE_CHUNLI_CH_JUMP = 1,
	CRI_CHARASE_CHUNLI_CH_JUMP_HIGH = 2,
	CRI_CHARASE_CHUNLI_CH_CHAKUCHI = 3,
	CRI_CHARASE_CHUNLI_CH_DASH = 4,
	CRI_CHARASE_CHUNLI_CH_DASHEND = 5,
	CRI_CHARASE_CHUNLI_CH_KABEPETA = 6,
	CRI_CHARASE_CHUNLI_CH_KABEKERI = 7,
	CRI_CHARASE_CHUNLI_CH_TELEPORT_IN = 8,
	CRI_CHARASE_CHUNLI_CH_TELEPORT_OUT = 9,
	CRI_CHARASE_CHUNLI_CH_FOOT = 10
}
