public enum CharaSE_ZERODMC
{
	NONE = 0,
	CRI_CHARASE_ZERODMC_CUENUM = 10,
	CRI_CHARASE_ZERODMC_ZC_JUMP = 1,
	CRI_CHARASE_ZERODMC_ZC_JUMP_HIGH = 2,
	CRI_CHARASE_ZERODMC_ZC_CHAKUCHI = 3,
	CRI_CHARASE_ZERODMC_ZC_DASH = 4,
	CRI_CHARASE_ZERODMC_ZC_DASHEND = 5,
	CRI_CHARASE_ZERODMC_ZC_KABEPETA = 6,
	CRI_CHARASE_ZERODMC_ZC_KABEKERI = 7,
	CRI_CHARASE_ZERODMC_ZC_TELEPORT_IN = 8,
	CRI_CHARASE_ZERODMC_ZC_TELEPORT_OUT = 9,
	CRI_CHARASE_ZERODMC_ZC_FOOT = 10
}
