public static class CharaSE_IRIS2i
{
	public const int iCRI_CHARASE_IRIS2_CUENUM = 10;

	public const int iCRI_CHARASE_IRIS2_IR2_JUMP = 1;

	public const int iCRI_CHARASE_IRIS2_IR2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_IRIS2_IR2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_IRIS2_IR2_DASH = 4;

	public const int iCRI_CHARASE_IRIS2_IR2_DASHEND = 5;

	public const int iCRI_CHARASE_IRIS2_IR2_KABEPETA = 6;

	public const int iCRI_CHARASE_IRIS2_IR2_KABEKERI = 7;

	public const int iCRI_CHARASE_IRIS2_IR2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_IRIS2_IR2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_IRIS2_IR2_FOOT = 10;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_CUENUM = CharaSE_IRIS2.CRI_CHARASE_IRIS2_CUENUM;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_IR2_JUMP = CharaSE_IRIS2.CRI_CHARASE_IRIS2_IR2_JUMP;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_IR2_JUMP_HIGH = CharaSE_IRIS2.CRI_CHARASE_IRIS2_IR2_JUMP_HIGH;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_IR2_CHAKUCHI = CharaSE_IRIS2.CRI_CHARASE_IRIS2_IR2_CHAKUCHI;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_IR2_DASH = CharaSE_IRIS2.CRI_CHARASE_IRIS2_IR2_DASH;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_IR2_DASHEND = CharaSE_IRIS2.CRI_CHARASE_IRIS2_IR2_DASHEND;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_IR2_KABEPETA = CharaSE_IRIS2.CRI_CHARASE_IRIS2_IR2_KABEPETA;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_IR2_KABEKERI = CharaSE_IRIS2.CRI_CHARASE_IRIS2_IR2_KABEKERI;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_IR2_TELEPORT_IN = CharaSE_IRIS2.CRI_CHARASE_IRIS2_IR2_TELEPORT_IN;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_IR2_TELEPORT_OUT = CharaSE_IRIS2.CRI_CHARASE_IRIS2_IR2_TELEPORT_OUT;

	public const CharaSE_IRIS2 CRI_CHARASE_IRIS2_IR2_FOOT = CharaSE_IRIS2.CRI_CHARASE_IRIS2_CUENUM;
}
