public enum CharaSE_DYNAMO
{
	NONE = 0,
	CRI_CHARASE_DYNAMO_CUENUM = 10,
	CRI_CHARASE_DYNAMO_DY_JUMP = 1,
	CRI_CHARASE_DYNAMO_DY_JUMP_HIGH = 2,
	CRI_CHARASE_DYNAMO_DY_CHAKUCHI = 3,
	CRI_CHARASE_DYNAMO_DY_DASH = 4,
	CRI_CHARASE_DYNAMO_DY_DASHEND = 5,
	CRI_CHARASE_DYNAMO_DY_KABEPETA = 6,
	CRI_CHARASE_DYNAMO_DY_KABEKERI = 7,
	CRI_CHARASE_DYNAMO_DY_TELEPORT_IN = 8,
	CRI_CHARASE_DYNAMO_DY_TELEPORT_OUT = 9,
	CRI_CHARASE_DYNAMO_DY_FOOT = 10
}
