public static class CharaSE_MARINOi
{
	public const int iCRI_CHARASE_MARINO_CUENUM = 10;

	public const int iCRI_CHARASE_MARINO_MR_JUMP = 1;

	public const int iCRI_CHARASE_MARINO_MR_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_MARINO_MR_CHAKUCHI = 3;

	public const int iCRI_CHARASE_MARINO_MR_DASH = 4;

	public const int iCRI_CHARASE_MARINO_MR_DASHEND = 5;

	public const int iCRI_CHARASE_MARINO_MR_KABEPETA = 6;

	public const int iCRI_CHARASE_MARINO_MR_KABEKERI = 7;

	public const int iCRI_CHARASE_MARINO_MR_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_MARINO_MR_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_MARINO_MR_FOOT = 10;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_CUENUM = CharaSE_MARINO.CRI_CHARASE_MARINO_CUENUM;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_MR_JUMP = CharaSE_MARINO.CRI_CHARASE_MARINO_MR_JUMP;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_MR_JUMP_HIGH = CharaSE_MARINO.CRI_CHARASE_MARINO_MR_JUMP_HIGH;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_MR_CHAKUCHI = CharaSE_MARINO.CRI_CHARASE_MARINO_MR_CHAKUCHI;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_MR_DASH = CharaSE_MARINO.CRI_CHARASE_MARINO_MR_DASH;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_MR_DASHEND = CharaSE_MARINO.CRI_CHARASE_MARINO_MR_DASHEND;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_MR_KABEPETA = CharaSE_MARINO.CRI_CHARASE_MARINO_MR_KABEPETA;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_MR_KABEKERI = CharaSE_MARINO.CRI_CHARASE_MARINO_MR_KABEKERI;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_MR_TELEPORT_IN = CharaSE_MARINO.CRI_CHARASE_MARINO_MR_TELEPORT_IN;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_MR_TELEPORT_OUT = CharaSE_MARINO.CRI_CHARASE_MARINO_MR_TELEPORT_OUT;

	public const CharaSE_MARINO CRI_CHARASE_MARINO_MR_FOOT = CharaSE_MARINO.CRI_CHARASE_MARINO_CUENUM;
}
