public enum CharaSE_XMH
{
	NONE = 0,
	CRI_CHARASE_XMH_CUENUM = 10,
	CRI_CHARASE_XMH_XM_JUMP = 1,
	CRI_CHARASE_XMH_XM_JUMP_HIGH = 2,
	CRI_CHARASE_XMH_XM_CHAKUCHI = 3,
	CRI_CHARASE_XMH_XM_DASH = 4,
	CRI_CHARASE_XMH_XM_DASHEND = 5,
	CRI_CHARASE_XMH_XM_KABEPETA = 6,
	CRI_CHARASE_XMH_XM_KABEKERI = 7,
	CRI_CHARASE_XMH_XM_TELEPORT_IN = 8,
	CRI_CHARASE_XMH_XM_TELEPORT_OUT = 9,
	CRI_CHARASE_XMH_XM_FOOT = 10
}
