public static class CharaSE_X1stArmori
{
	public const int iCRI_CHARASE_X1STARMOR_CUENUM = 10;

	public const int iCRI_CHARASE_X1STARMOR_X1_JUMP = 1;

	public const int iCRI_CHARASE_X1STARMOR_X1_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_X1STARMOR_X1_CHAKUCHI = 3;

	public const int iCRI_CHARASE_X1STARMOR_X1_DASH = 4;

	public const int iCRI_CHARASE_X1STARMOR_X1_DASHEND = 5;

	public const int iCRI_CHARASE_X1STARMOR_X1_KABEPETA = 6;

	public const int iCRI_CHARASE_X1STARMOR_X1_KABEKERI = 7;

	public const int iCRI_CHARASE_X1STARMOR_X1_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_X1STARMOR_X1_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_X1STARMOR_X1_FOOT = 10;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_CUENUM = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_CUENUM;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_X1_JUMP = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_X1_JUMP;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_X1_JUMP_HIGH = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_X1_JUMP_HIGH;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_X1_CHAKUCHI = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_X1_CHAKUCHI;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_X1_DASH = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_X1_DASH;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_X1_DASHEND = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_X1_DASHEND;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_X1_KABEPETA = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_X1_KABEPETA;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_X1_KABEKERI = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_X1_KABEKERI;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_X1_TELEPORT_IN = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_X1_TELEPORT_IN;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_X1_TELEPORT_OUT = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_X1_TELEPORT_OUT;

	public const CharaSE_X1stArmor CRI_CHARASE_X1STARMOR_X1_FOOT = CharaSE_X1stArmor.CRI_CHARASE_X1STARMOR_CUENUM;
}
