public enum CharaSE_CINNAMON
{
	NONE = 0,
	CRI_CHARASE_CINNAMON_CUENUM = 10,
	CRI_CHARASE_CINNAMON_SM_JUMP = 1,
	CRI_CHARASE_CINNAMON_SM_JUMP_HIGH = 2,
	CRI_CHARASE_CINNAMON_SM_CHAKUCHI = 3,
	CRI_CHARASE_CINNAMON_SM_DASH = 4,
	CRI_CHARASE_CINNAMON_SM_DASHEND = 5,
	CRI_CHARASE_CINNAMON_SM_KABEPETA = 6,
	CRI_CHARASE_CINNAMON_SM_KABEKERI = 7,
	CRI_CHARASE_CINNAMON_SM_TELEPORT_IN = 8,
	CRI_CHARASE_CINNAMON_SM_TELEPORT_OUT = 9,
	CRI_CHARASE_CINNAMON_SM_FOOT = 10
}
