public static class CharaSE_KARNELi
{
	public const int iCRI_CHARASE_KARNEL_CUENUM = 10;

	public const int iCRI_CHARASE_KARNEL_KN_JUMP = 1;

	public const int iCRI_CHARASE_KARNEL_KN_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_KARNEL_KN_CHAKUCHI = 3;

	public const int iCRI_CHARASE_KARNEL_KN_DASH = 4;

	public const int iCRI_CHARASE_KARNEL_KN_DASHEND = 5;

	public const int iCRI_CHARASE_KARNEL_KN_KABEPETA = 6;

	public const int iCRI_CHARASE_KARNEL_KN_KABEKERI = 7;

	public const int iCRI_CHARASE_KARNEL_KN_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_KARNEL_KN_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_KARNEL_KN_FOOT = 10;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_CUENUM = CharaSE_KARNEL.CRI_CHARASE_KARNEL_CUENUM;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_KN_JUMP = CharaSE_KARNEL.CRI_CHARASE_KARNEL_KN_JUMP;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_KN_JUMP_HIGH = CharaSE_KARNEL.CRI_CHARASE_KARNEL_KN_JUMP_HIGH;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_KN_CHAKUCHI = CharaSE_KARNEL.CRI_CHARASE_KARNEL_KN_CHAKUCHI;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_KN_DASH = CharaSE_KARNEL.CRI_CHARASE_KARNEL_KN_DASH;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_KN_DASHEND = CharaSE_KARNEL.CRI_CHARASE_KARNEL_KN_DASHEND;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_KN_KABEPETA = CharaSE_KARNEL.CRI_CHARASE_KARNEL_KN_KABEPETA;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_KN_KABEKERI = CharaSE_KARNEL.CRI_CHARASE_KARNEL_KN_KABEKERI;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_KN_TELEPORT_IN = CharaSE_KARNEL.CRI_CHARASE_KARNEL_KN_TELEPORT_IN;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_KN_TELEPORT_OUT = CharaSE_KARNEL.CRI_CHARASE_KARNEL_KN_TELEPORT_OUT;

	public const CharaSE_KARNEL CRI_CHARASE_KARNEL_KN_FOOT = CharaSE_KARNEL.CRI_CHARASE_KARNEL_CUENUM;
}
