public static class CharaSE_GOUKIi
{
	public const int iCRI_CHARASE_GOUKI_CUENUM = 10;

	public const int iCRI_CHARASE_GOUKI_GO_JUMP = 1;

	public const int iCRI_CHARASE_GOUKI_GO_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_GOUKI_GO_CHAKUCHI = 3;

	public const int iCRI_CHARASE_GOUKI_GO_DASH = 4;

	public const int iCRI_CHARASE_GOUKI_GO_DASHEND = 5;

	public const int iCRI_CHARASE_GOUKI_GO_KABEPETA = 6;

	public const int iCRI_CHARASE_GOUKI_GO_KABEKERI = 7;

	public const int iCRI_CHARASE_GOUKI_GO_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_GOUKI_GO_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_GOUKI_GO_FOOT = 10;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_CUENUM = CharaSE_GOUKI.CRI_CHARASE_GOUKI_CUENUM;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_GO_JUMP = CharaSE_GOUKI.CRI_CHARASE_GOUKI_GO_JUMP;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_GO_JUMP_HIGH = CharaSE_GOUKI.CRI_CHARASE_GOUKI_GO_JUMP_HIGH;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_GO_CHAKUCHI = CharaSE_GOUKI.CRI_CHARASE_GOUKI_GO_CHAKUCHI;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_GO_DASH = CharaSE_GOUKI.CRI_CHARASE_GOUKI_GO_DASH;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_GO_DASHEND = CharaSE_GOUKI.CRI_CHARASE_GOUKI_GO_DASHEND;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_GO_KABEPETA = CharaSE_GOUKI.CRI_CHARASE_GOUKI_GO_KABEPETA;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_GO_KABEKERI = CharaSE_GOUKI.CRI_CHARASE_GOUKI_GO_KABEKERI;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_GO_TELEPORT_IN = CharaSE_GOUKI.CRI_CHARASE_GOUKI_GO_TELEPORT_IN;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_GO_TELEPORT_OUT = CharaSE_GOUKI.CRI_CHARASE_GOUKI_GO_TELEPORT_OUT;

	public const CharaSE_GOUKI CRI_CHARASE_GOUKI_GO_FOOT = CharaSE_GOUKI.CRI_CHARASE_GOUKI_CUENUM;
}
