public enum CharaSE_SIGMA
{
	NONE = 0,
	CRI_CHARASE_SIGMA_CUENUM = 10,
	CRI_CHARASE_SIGMA_SG_JUMP = 1,
	CRI_CHARASE_SIGMA_SG_JUMP_HIGH = 2,
	CRI_CHARASE_SIGMA_SG_CHAKUCHI = 3,
	CRI_CHARASE_SIGMA_SG_DASH = 4,
	CRI_CHARASE_SIGMA_SG_DASHEND = 5,
	CRI_CHARASE_SIGMA_SG_KABEPETA = 6,
	CRI_CHARASE_SIGMA_SG_KABEKERI = 7,
	CRI_CHARASE_SIGMA_SG_TELEPORT_IN = 8,
	CRI_CHARASE_SIGMA_SG_TELEPORT_OUT = 9,
	CRI_CHARASE_SIGMA_SG_FOOT = 10
}
