public enum CharaSE_LAYER
{
	NONE = 0,
	CRI_CHARASE_LAYER_CUENUM = 10,
	CRI_CHARASE_LAYER_LY_JUMP = 1,
	CRI_CHARASE_LAYER_LY_JUMP_HIGH = 2,
	CRI_CHARASE_LAYER_LY_CHAKUCHI = 3,
	CRI_CHARASE_LAYER_LY_DASH = 4,
	CRI_CHARASE_LAYER_LY_DASHEND = 5,
	CRI_CHARASE_LAYER_LY_KABEPETA = 6,
	CRI_CHARASE_LAYER_LY_KABEKERI = 7,
	CRI_CHARASE_LAYER_LY_TELEPORT_IN = 8,
	CRI_CHARASE_LAYER_LY_TELEPORT_OUT = 9,
	CRI_CHARASE_LAYER_LY_FOOT = 10
}
