public static class CharaSE_VAVAi
{
	public const int iCRI_CHARASE_VAVA_CUENUM = 10;

	public const int iCRI_CHARASE_VAVA_VA_JUMP = 1;

	public const int iCRI_CHARASE_VAVA_VA_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_VAVA_VA_CHAKUCHI = 3;

	public const int iCRI_CHARASE_VAVA_VA_DASH = 4;

	public const int iCRI_CHARASE_VAVA_VA_DASHEND = 5;

	public const int iCRI_CHARASE_VAVA_VA_KABEPETA = 6;

	public const int iCRI_CHARASE_VAVA_VA_KABEKERI = 7;

	public const int iCRI_CHARASE_VAVA_VA_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_VAVA_VA_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_VAVA_VA_FOOT = 10;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_CUENUM = CharaSE_VAVA.CRI_CHARASE_VAVA_CUENUM;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_VA_JUMP = CharaSE_VAVA.CRI_CHARASE_VAVA_VA_JUMP;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_VA_JUMP_HIGH = CharaSE_VAVA.CRI_CHARASE_VAVA_VA_JUMP_HIGH;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_VA_CHAKUCHI = CharaSE_VAVA.CRI_CHARASE_VAVA_VA_CHAKUCHI;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_VA_DASH = CharaSE_VAVA.CRI_CHARASE_VAVA_VA_DASH;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_VA_DASHEND = CharaSE_VAVA.CRI_CHARASE_VAVA_VA_DASHEND;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_VA_KABEPETA = CharaSE_VAVA.CRI_CHARASE_VAVA_VA_KABEPETA;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_VA_KABEKERI = CharaSE_VAVA.CRI_CHARASE_VAVA_VA_KABEKERI;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_VA_TELEPORT_IN = CharaSE_VAVA.CRI_CHARASE_VAVA_VA_TELEPORT_IN;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_VA_TELEPORT_OUT = CharaSE_VAVA.CRI_CHARASE_VAVA_VA_TELEPORT_OUT;

	public const CharaSE_VAVA CRI_CHARASE_VAVA_VA_FOOT = CharaSE_VAVA.CRI_CHARASE_VAVA_CUENUM;
}
