public static class CharaSE_ROCKVOLi
{
	public const int iCRI_CHARASE_ROCKVOL_CUENUM = 10;

	public const int iCRI_CHARASE_ROCKVOL_RV_JUMP = 1;

	public const int iCRI_CHARASE_ROCKVOL_RV_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ROCKVOL_RV_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ROCKVOL_RV_DASH = 4;

	public const int iCRI_CHARASE_ROCKVOL_RV_DASHEND = 5;

	public const int iCRI_CHARASE_ROCKVOL_RV_KABEPETA = 6;

	public const int iCRI_CHARASE_ROCKVOL_RV_KABEKERI = 7;

	public const int iCRI_CHARASE_ROCKVOL_RV_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ROCKVOL_RV_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ROCKVOL_RV_FOOT = 10;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_CUENUM = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_CUENUM;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_RV_JUMP = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_RV_JUMP;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_RV_JUMP_HIGH = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_RV_JUMP_HIGH;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_RV_CHAKUCHI = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_RV_CHAKUCHI;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_RV_DASH = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_RV_DASH;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_RV_DASHEND = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_RV_DASHEND;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_RV_KABEPETA = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_RV_KABEPETA;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_RV_KABEKERI = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_RV_KABEKERI;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_RV_TELEPORT_IN = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_RV_TELEPORT_IN;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_RV_TELEPORT_OUT = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_RV_TELEPORT_OUT;

	public const CharaSE_ROCKVOL CRI_CHARASE_ROCKVOL_RV_FOOT = CharaSE_ROCKVOL.CRI_CHARASE_ROCKVOL_CUENUM;
}
