public enum CharaSE_XGaia
{
	NONE = 0,
	CRI_CHARASE_XGAIA_CUENUM = 10,
	CRI_CHARASE_XGAIA_XG_JUMP = 1,
	CRI_CHARASE_XGAIA_XG_JUMP_HIGH = 2,
	CRI_CHARASE_XGAIA_XG_CHAKUCHI = 3,
	CRI_CHARASE_XGAIA_XG_DASH = 4,
	CRI_CHARASE_XGAIA_XG_DASHEND = 5,
	CRI_CHARASE_XGAIA_XG_KABEPETA = 6,
	CRI_CHARASE_XGAIA_XG_KABEKERI = 7,
	CRI_CHARASE_XGAIA_XG_TELEPORT_IN = 8,
	CRI_CHARASE_XGAIA_XG_TELEPORT_OUT = 9,
	CRI_CHARASE_XGAIA_XG_FOOT = 10
}
