public enum CharaSE_ALIA
{
	NONE = 0,
	CRI_CHARASE_ALIA_CUENUM = 10,
	CRI_CHARASE_ALIA_AA_JUMP = 1,
	CRI_CHARASE_ALIA_AA_JUMP_HIGH = 2,
	CRI_CHARASE_ALIA_AA_CHAKUCHI = 3,
	CRI_CHARASE_ALIA_AA_DASH = 4,
	CRI_CHARASE_ALIA_AA_DASHEND = 5,
	CRI_CHARASE_ALIA_AA_KABEPETA = 6,
	CRI_CHARASE_ALIA_AA_KABEKERI = 7,
	CRI_CHARASE_ALIA_AA_TELEPORT_IN = 8,
	CRI_CHARASE_ALIA_AA_TELEPORT_OUT = 9,
	CRI_CHARASE_ALIA_AA_FOOT = 10
}
