public enum CharaSE_VAVA
{
	NONE = 0,
	CRI_CHARASE_VAVA_CUENUM = 10,
	CRI_CHARASE_VAVA_VA_JUMP = 1,
	CRI_CHARASE_VAVA_VA_JUMP_HIGH = 2,
	CRI_CHARASE_VAVA_VA_CHAKUCHI = 3,
	CRI_CHARASE_VAVA_VA_DASH = 4,
	CRI_CHARASE_VAVA_VA_DASHEND = 5,
	CRI_CHARASE_VAVA_VA_KABEPETA = 6,
	CRI_CHARASE_VAVA_VA_KABEKERI = 7,
	CRI_CHARASE_VAVA_VA_TELEPORT_IN = 8,
	CRI_CHARASE_VAVA_VA_TELEPORT_OUT = 9,
	CRI_CHARASE_VAVA_VA_FOOT = 10
}
