public enum CharaSE_RMSS
{
	NONE = 0,
	CRI_CHARASE_RMSS_CUENUM = 10,
	CRI_CHARASE_RMSS_RS_JUMP = 1,
	CRI_CHARASE_RMSS_RS_JUMP_HIGH = 2,
	CRI_CHARASE_RMSS_RS_CHAKUCHI = 3,
	CRI_CHARASE_RMSS_RS_DASH = 4,
	CRI_CHARASE_RMSS_RS_DASHEND = 5,
	CRI_CHARASE_RMSS_RS_KABEPETA = 6,
	CRI_CHARASE_RMSS_RS_KABEKERI = 7,
	CRI_CHARASE_RMSS_RS_TELEPORT_IN = 8,
	CRI_CHARASE_RMSS_RS_TELEPORT_OUT = 9,
	CRI_CHARASE_RMSS_RS_FOOT = 10
}
