public static class CharaSE_AbsoZEROi
{
	public const int iCRI_CHARASE_ABSOZERO_CUENUM = 10;

	public const int iCRI_CHARASE_ABSOZERO_ZB_JUMP = 1;

	public const int iCRI_CHARASE_ABSOZERO_ZB_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ABSOZERO_ZB_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ABSOZERO_ZB_DASH = 4;

	public const int iCRI_CHARASE_ABSOZERO_ZB_DASHEND = 5;

	public const int iCRI_CHARASE_ABSOZERO_ZB_KABEPETA = 6;

	public const int iCRI_CHARASE_ABSOZERO_ZB_KABEKERI = 7;

	public const int iCRI_CHARASE_ABSOZERO_ZB_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ABSOZERO_ZB_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ABSOZERO_ZB_FOOT = 10;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_CUENUM = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_CUENUM;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_ZB_JUMP = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_ZB_JUMP;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_ZB_JUMP_HIGH = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_ZB_JUMP_HIGH;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_ZB_CHAKUCHI = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_ZB_CHAKUCHI;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_ZB_DASH = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_ZB_DASH;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_ZB_DASHEND = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_ZB_DASHEND;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_ZB_KABEPETA = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_ZB_KABEPETA;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_ZB_KABEKERI = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_ZB_KABEKERI;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_ZB_TELEPORT_IN = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_ZB_TELEPORT_IN;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_ZB_TELEPORT_OUT = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_ZB_TELEPORT_OUT;

	public const CharaSE_AbsoZERO CRI_CHARASE_ABSOZERO_ZB_FOOT = CharaSE_AbsoZERO.CRI_CHARASE_ABSOZERO_CUENUM;
}
