public static class CharaSE_XDive2i
{
	public const int iCRI_CHARASE_XDIVE2_CUENUM = 10;

	public const int iCRI_CHARASE_XDIVE2_XD2_JUMP = 1;

	public const int iCRI_CHARASE_XDIVE2_XD2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_XDIVE2_XD2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_XDIVE2_XD2_DASH = 4;

	public const int iCRI_CHARASE_XDIVE2_XD2_DASHEND = 5;

	public const int iCRI_CHARASE_XDIVE2_XD2_KABEPETA = 6;

	public const int iCRI_CHARASE_XDIVE2_XD2_KABEKERI = 7;

	public const int iCRI_CHARASE_XDIVE2_XD2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_XDIVE2_XD2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_XDIVE2_XD2_FOOT = 10;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_CUENUM = CharaSE_XDive2.CRI_CHARASE_XDIVE2_CUENUM;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_XD2_JUMP = CharaSE_XDive2.CRI_CHARASE_XDIVE2_XD2_JUMP;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_XD2_JUMP_HIGH = CharaSE_XDive2.CRI_CHARASE_XDIVE2_XD2_JUMP_HIGH;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_XD2_CHAKUCHI = CharaSE_XDive2.CRI_CHARASE_XDIVE2_XD2_CHAKUCHI;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_XD2_DASH = CharaSE_XDive2.CRI_CHARASE_XDIVE2_XD2_DASH;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_XD2_DASHEND = CharaSE_XDive2.CRI_CHARASE_XDIVE2_XD2_DASHEND;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_XD2_KABEPETA = CharaSE_XDive2.CRI_CHARASE_XDIVE2_XD2_KABEPETA;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_XD2_KABEKERI = CharaSE_XDive2.CRI_CHARASE_XDIVE2_XD2_KABEKERI;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_XD2_TELEPORT_IN = CharaSE_XDive2.CRI_CHARASE_XDIVE2_XD2_TELEPORT_IN;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_XD2_TELEPORT_OUT = CharaSE_XDive2.CRI_CHARASE_XDIVE2_XD2_TELEPORT_OUT;

	public const CharaSE_XDive2 CRI_CHARASE_XDIVE2_XD2_FOOT = CharaSE_XDive2.CRI_CHARASE_XDIVE2_CUENUM;
}
