public enum CharaSE_FORTE
{
	NONE = 0,
	CRI_CHARASE_FORTE_CUENUM = 10,
	CRI_CHARASE_FORTE_FO_JUMP = 1,
	CRI_CHARASE_FORTE_FO_JUMP_HIGH = 2,
	CRI_CHARASE_FORTE_FO_CHAKUCHI = 3,
	CRI_CHARASE_FORTE_FO_DASH = 4,
	CRI_CHARASE_FORTE_FO_DASHEND = 5,
	CRI_CHARASE_FORTE_FO_KABEPETA = 6,
	CRI_CHARASE_FORTE_FO_KABEKERI = 7,
	CRI_CHARASE_FORTE_FO_TELEPORT_IN = 8,
	CRI_CHARASE_FORTE_FO_TELEPORT_OUT = 9,
	CRI_CHARASE_FORTE_FO_FOOT = 10
}
