public static class CharaSE_FERHAMi
{
	public const int iCRI_CHARASE_FERHAM_CUENUM = 10;

	public const int iCRI_CHARASE_FERHAM_FM_JUMP = 1;

	public const int iCRI_CHARASE_FERHAM_FM_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_FERHAM_FM_CHAKUCHI = 3;

	public const int iCRI_CHARASE_FERHAM_FM_DASH = 4;

	public const int iCRI_CHARASE_FERHAM_FM_DASHEND = 5;

	public const int iCRI_CHARASE_FERHAM_FM_KABEPETA = 6;

	public const int iCRI_CHARASE_FERHAM_FM_KABEKERI = 7;

	public const int iCRI_CHARASE_FERHAM_FM_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_FERHAM_FM_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_FERHAM_FM_FOOT = 10;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_CUENUM = CharaSE_FERHAM.CRI_CHARASE_FERHAM_CUENUM;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_FM_JUMP = CharaSE_FERHAM.CRI_CHARASE_FERHAM_FM_JUMP;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_FM_JUMP_HIGH = CharaSE_FERHAM.CRI_CHARASE_FERHAM_FM_JUMP_HIGH;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_FM_CHAKUCHI = CharaSE_FERHAM.CRI_CHARASE_FERHAM_FM_CHAKUCHI;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_FM_DASH = CharaSE_FERHAM.CRI_CHARASE_FERHAM_FM_DASH;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_FM_DASHEND = CharaSE_FERHAM.CRI_CHARASE_FERHAM_FM_DASHEND;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_FM_KABEPETA = CharaSE_FERHAM.CRI_CHARASE_FERHAM_FM_KABEPETA;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_FM_KABEKERI = CharaSE_FERHAM.CRI_CHARASE_FERHAM_FM_KABEKERI;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_FM_TELEPORT_IN = CharaSE_FERHAM.CRI_CHARASE_FERHAM_FM_TELEPORT_IN;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_FM_TELEPORT_OUT = CharaSE_FERHAM.CRI_CHARASE_FERHAM_FM_TELEPORT_OUT;

	public const CharaSE_FERHAM CRI_CHARASE_FERHAM_FM_FOOT = CharaSE_FERHAM.CRI_CHARASE_FERHAM_CUENUM;
}
