public static class CharaSE_DYNAMOi
{
	public const int iCRI_CHARASE_DYNAMO_CUENUM = 10;

	public const int iCRI_CHARASE_DYNAMO_DY_JUMP = 1;

	public const int iCRI_CHARASE_DYNAMO_DY_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_DYNAMO_DY_CHAKUCHI = 3;

	public const int iCRI_CHARASE_DYNAMO_DY_DASH = 4;

	public const int iCRI_CHARASE_DYNAMO_DY_DASHEND = 5;

	public const int iCRI_CHARASE_DYNAMO_DY_KABEPETA = 6;

	public const int iCRI_CHARASE_DYNAMO_DY_KABEKERI = 7;

	public const int iCRI_CHARASE_DYNAMO_DY_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_DYNAMO_DY_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_DYNAMO_DY_FOOT = 10;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_CUENUM = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_CUENUM;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_DY_JUMP = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_DY_JUMP;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_DY_JUMP_HIGH = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_DY_JUMP_HIGH;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_DY_CHAKUCHI = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_DY_CHAKUCHI;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_DY_DASH = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_DY_DASH;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_DY_DASHEND = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_DY_DASHEND;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_DY_KABEPETA = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_DY_KABEPETA;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_DY_KABEKERI = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_DY_KABEKERI;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_DY_TELEPORT_IN = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_DY_TELEPORT_IN;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_DY_TELEPORT_OUT = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_DY_TELEPORT_OUT;

	public const CharaSE_DYNAMO CRI_CHARASE_DYNAMO_DY_FOOT = CharaSE_DYNAMO.CRI_CHARASE_DYNAMO_CUENUM;
}
