public enum CharaSE_X4thArmor
{
	NONE = 0,
	CRI_CHARASE_X4THARMOR_CUENUM = 10,
	CRI_CHARASE_X4THARMOR_X4_JUMP = 1,
	CRI_CHARASE_X4THARMOR_X4_JUMP_HIGH = 2,
	CRI_CHARASE_X4THARMOR_X4_CHAKUCHI = 3,
	CRI_CHARASE_X4THARMOR_X4_DASH = 4,
	CRI_CHARASE_X4THARMOR_X4_DASHEND = 5,
	CRI_CHARASE_X4THARMOR_X4_KABEPETA = 6,
	CRI_CHARASE_X4THARMOR_X4_KABEKERI = 7,
	CRI_CHARASE_X4THARMOR_X4_TELEPORT_IN = 8,
	CRI_CHARASE_X4THARMOR_X4_TELEPORT_OUT = 9,
	CRI_CHARASE_X4THARMOR_X4_FOOT = 10
}
