public static class CharaSE_RMSSi
{
	public const int iCRI_CHARASE_RMSS_CUENUM = 10;

	public const int iCRI_CHARASE_RMSS_RS_JUMP = 1;

	public const int iCRI_CHARASE_RMSS_RS_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_RMSS_RS_CHAKUCHI = 3;

	public const int iCRI_CHARASE_RMSS_RS_DASH = 4;

	public const int iCRI_CHARASE_RMSS_RS_DASHEND = 5;

	public const int iCRI_CHARASE_RMSS_RS_KABEPETA = 6;

	public const int iCRI_CHARASE_RMSS_RS_KABEKERI = 7;

	public const int iCRI_CHARASE_RMSS_RS_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_RMSS_RS_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_RMSS_RS_FOOT = 10;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_CUENUM = CharaSE_RMSS.CRI_CHARASE_RMSS_CUENUM;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_RS_JUMP = CharaSE_RMSS.CRI_CHARASE_RMSS_RS_JUMP;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_RS_JUMP_HIGH = CharaSE_RMSS.CRI_CHARASE_RMSS_RS_JUMP_HIGH;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_RS_CHAKUCHI = CharaSE_RMSS.CRI_CHARASE_RMSS_RS_CHAKUCHI;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_RS_DASH = CharaSE_RMSS.CRI_CHARASE_RMSS_RS_DASH;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_RS_DASHEND = CharaSE_RMSS.CRI_CHARASE_RMSS_RS_DASHEND;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_RS_KABEPETA = CharaSE_RMSS.CRI_CHARASE_RMSS_RS_KABEPETA;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_RS_KABEKERI = CharaSE_RMSS.CRI_CHARASE_RMSS_RS_KABEKERI;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_RS_TELEPORT_IN = CharaSE_RMSS.CRI_CHARASE_RMSS_RS_TELEPORT_IN;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_RS_TELEPORT_OUT = CharaSE_RMSS.CRI_CHARASE_RMSS_RS_TELEPORT_OUT;

	public const CharaSE_RMSS CRI_CHARASE_RMSS_RS_FOOT = CharaSE_RMSS.CRI_CHARASE_RMSS_CUENUM;
}
