public static class CharaSE_IRIS3i
{
	public const int iCRI_CHARASE_IRIS3_CUENUM = 10;

	public const int iCRI_CHARASE_IRIS3_IR3_JUMP = 1;

	public const int iCRI_CHARASE_IRIS3_IR3_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_IRIS3_IR3_CHAKUCHI = 3;

	public const int iCRI_CHARASE_IRIS3_IR3_DASH = 4;

	public const int iCRI_CHARASE_IRIS3_IR3_DASHEND = 5;

	public const int iCRI_CHARASE_IRIS3_IR3_KABEPETA = 6;

	public const int iCRI_CHARASE_IRIS3_IR3_KABEKERI = 7;

	public const int iCRI_CHARASE_IRIS3_IR3_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_IRIS3_IR3_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_IRIS3_IR3_FOOT = 10;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_CUENUM = CharaSE_IRIS3.CRI_CHARASE_IRIS3_CUENUM;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_IR3_JUMP = CharaSE_IRIS3.CRI_CHARASE_IRIS3_IR3_JUMP;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_IR3_JUMP_HIGH = CharaSE_IRIS3.CRI_CHARASE_IRIS3_IR3_JUMP_HIGH;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_IR3_CHAKUCHI = CharaSE_IRIS3.CRI_CHARASE_IRIS3_IR3_CHAKUCHI;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_IR3_DASH = CharaSE_IRIS3.CRI_CHARASE_IRIS3_IR3_DASH;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_IR3_DASHEND = CharaSE_IRIS3.CRI_CHARASE_IRIS3_IR3_DASHEND;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_IR3_KABEPETA = CharaSE_IRIS3.CRI_CHARASE_IRIS3_IR3_KABEPETA;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_IR3_KABEKERI = CharaSE_IRIS3.CRI_CHARASE_IRIS3_IR3_KABEKERI;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_IR3_TELEPORT_IN = CharaSE_IRIS3.CRI_CHARASE_IRIS3_IR3_TELEPORT_IN;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_IR3_TELEPORT_OUT = CharaSE_IRIS3.CRI_CHARASE_IRIS3_IR3_TELEPORT_OUT;

	public const CharaSE_IRIS3 CRI_CHARASE_IRIS3_IR3_FOOT = CharaSE_IRIS3.CRI_CHARASE_IRIS3_CUENUM;
}
