public enum CharaSE_Vajurila
{
	NONE = 0,
	CRI_CHARASE_VAJURILA_CUENUM = 10,
	CRI_CHARASE_VAJURILA_VJ_JUMP = 1,
	CRI_CHARASE_VAJURILA_VJ_JUMP_HIGH = 2,
	CRI_CHARASE_VAJURILA_VJ_CHAKUCHI = 3,
	CRI_CHARASE_VAJURILA_VJ_DASH = 4,
	CRI_CHARASE_VAJURILA_VJ_DASHEND = 5,
	CRI_CHARASE_VAJURILA_VJ_KABEPETA = 6,
	CRI_CHARASE_VAJURILA_VJ_KABEKERI = 7,
	CRI_CHARASE_VAJURILA_VJ_TELEPORT_IN = 8,
	CRI_CHARASE_VAJURILA_VJ_TELEPORT_OUT = 9,
	CRI_CHARASE_VAJURILA_VJ_FOOT = 10
}
