public static class CharaSE_DRAWERi
{
	public const int iCRI_CHARASE_DRAWER_CUENUM = 10;

	public const int iCRI_CHARASE_DRAWER_DR_JUMP = 1;

	public const int iCRI_CHARASE_DRAWER_DR_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_DRAWER_DR_CHAKUCHI = 3;

	public const int iCRI_CHARASE_DRAWER_DR_DASH = 4;

	public const int iCRI_CHARASE_DRAWER_DR_DASHEND = 5;

	public const int iCRI_CHARASE_DRAWER_DR_KABEPETA = 6;

	public const int iCRI_CHARASE_DRAWER_DR_KABEKERI = 7;

	public const int iCRI_CHARASE_DRAWER_DR_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_DRAWER_DR_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_DRAWER_DR_FOOT = 10;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_CUENUM = CharaSE_DRAWER.CRI_CHARASE_DRAWER_CUENUM;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_DR_JUMP = CharaSE_DRAWER.CRI_CHARASE_DRAWER_DR_JUMP;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_DR_JUMP_HIGH = CharaSE_DRAWER.CRI_CHARASE_DRAWER_DR_JUMP_HIGH;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_DR_CHAKUCHI = CharaSE_DRAWER.CRI_CHARASE_DRAWER_DR_CHAKUCHI;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_DR_DASH = CharaSE_DRAWER.CRI_CHARASE_DRAWER_DR_DASH;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_DR_DASHEND = CharaSE_DRAWER.CRI_CHARASE_DRAWER_DR_DASHEND;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_DR_KABEPETA = CharaSE_DRAWER.CRI_CHARASE_DRAWER_DR_KABEPETA;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_DR_KABEKERI = CharaSE_DRAWER.CRI_CHARASE_DRAWER_DR_KABEKERI;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_DR_TELEPORT_IN = CharaSE_DRAWER.CRI_CHARASE_DRAWER_DR_TELEPORT_IN;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_DR_TELEPORT_OUT = CharaSE_DRAWER.CRI_CHARASE_DRAWER_DR_TELEPORT_OUT;

	public const CharaSE_DRAWER CRI_CHARASE_DRAWER_DR_FOOT = CharaSE_DRAWER.CRI_CHARASE_DRAWER_CUENUM;
}
