public static class CharaSE_CIELi
{
	public const int iCRI_CHARASE_CIEL_CUENUM = 10;

	public const int iCRI_CHARASE_CIEL_CL_JUMP = 1;

	public const int iCRI_CHARASE_CIEL_CL_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_CIEL_CL_CHAKUCHI = 3;

	public const int iCRI_CHARASE_CIEL_CL_DASH = 4;

	public const int iCRI_CHARASE_CIEL_CL_DASHEND = 5;

	public const int iCRI_CHARASE_CIEL_CL_KABEPETA = 6;

	public const int iCRI_CHARASE_CIEL_CL_KABEKERI = 7;

	public const int iCRI_CHARASE_CIEL_CL_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_CIEL_CL_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_CIEL_CL_FOOT = 10;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CUENUM = CharaSE_CIEL.CRI_CHARASE_CIEL_CUENUM;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CL_JUMP = CharaSE_CIEL.CRI_CHARASE_CIEL_CL_JUMP;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CL_JUMP_HIGH = CharaSE_CIEL.CRI_CHARASE_CIEL_CL_JUMP_HIGH;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CL_CHAKUCHI = CharaSE_CIEL.CRI_CHARASE_CIEL_CL_CHAKUCHI;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CL_DASH = CharaSE_CIEL.CRI_CHARASE_CIEL_CL_DASH;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CL_DASHEND = CharaSE_CIEL.CRI_CHARASE_CIEL_CL_DASHEND;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CL_KABEPETA = CharaSE_CIEL.CRI_CHARASE_CIEL_CL_KABEPETA;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CL_KABEKERI = CharaSE_CIEL.CRI_CHARASE_CIEL_CL_KABEKERI;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CL_TELEPORT_IN = CharaSE_CIEL.CRI_CHARASE_CIEL_CL_TELEPORT_IN;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CL_TELEPORT_OUT = CharaSE_CIEL.CRI_CHARASE_CIEL_CL_TELEPORT_OUT;

	public const CharaSE_CIEL CRI_CHARASE_CIEL_CL_FOOT = CharaSE_CIEL.CRI_CHARASE_CIEL_CUENUM;
}
