public enum CharaSE_PANDORA
{
	NONE = 0,
	CRI_CHARASE_PANDORA_CUENUM = 10,
	CRI_CHARASE_PANDORA_PD_JUMP = 1,
	CRI_CHARASE_PANDORA_PD_JUMP_HIGH = 2,
	CRI_CHARASE_PANDORA_PD_CHAKUCHI = 3,
	CRI_CHARASE_PANDORA_PD_DASH = 4,
	CRI_CHARASE_PANDORA_PD_DASHEND = 5,
	CRI_CHARASE_PANDORA_PD_KABEPETA = 6,
	CRI_CHARASE_PANDORA_PD_KABEKERI = 7,
	CRI_CHARASE_PANDORA_PD_TELEPORT_IN = 8,
	CRI_CHARASE_PANDORA_PD_TELEPORT_OUT = 9,
	CRI_CHARASE_PANDORA_PD_FOOT = 10
}
