public static class CharaSE_KOBUNi
{
	public const int iCRI_CHARASE_KOBUN_CUENUM = 10;

	public const int iCRI_CHARASE_KOBUN_KB_JUMP = 1;

	public const int iCRI_CHARASE_KOBUN_KB_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_KOBUN_KB_CHAKUCHI = 3;

	public const int iCRI_CHARASE_KOBUN_KB_DASH = 4;

	public const int iCRI_CHARASE_KOBUN_KB_DASHEND = 5;

	public const int iCRI_CHARASE_KOBUN_KB_KABEPETA = 6;

	public const int iCRI_CHARASE_KOBUN_KB_KABEKERI = 7;

	public const int iCRI_CHARASE_KOBUN_KB_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_KOBUN_KB_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_KOBUN_KB_FOOT = 10;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_CUENUM = CharaSE_KOBUN.CRI_CHARASE_KOBUN_CUENUM;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_KB_JUMP = CharaSE_KOBUN.CRI_CHARASE_KOBUN_KB_JUMP;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_KB_JUMP_HIGH = CharaSE_KOBUN.CRI_CHARASE_KOBUN_KB_JUMP_HIGH;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_KB_CHAKUCHI = CharaSE_KOBUN.CRI_CHARASE_KOBUN_KB_CHAKUCHI;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_KB_DASH = CharaSE_KOBUN.CRI_CHARASE_KOBUN_KB_DASH;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_KB_DASHEND = CharaSE_KOBUN.CRI_CHARASE_KOBUN_KB_DASHEND;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_KB_KABEPETA = CharaSE_KOBUN.CRI_CHARASE_KOBUN_KB_KABEPETA;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_KB_KABEKERI = CharaSE_KOBUN.CRI_CHARASE_KOBUN_KB_KABEKERI;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_KB_TELEPORT_IN = CharaSE_KOBUN.CRI_CHARASE_KOBUN_KB_TELEPORT_IN;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_KB_TELEPORT_OUT = CharaSE_KOBUN.CRI_CHARASE_KOBUN_KB_TELEPORT_OUT;

	public const CharaSE_KOBUN CRI_CHARASE_KOBUN_KB_FOOT = CharaSE_KOBUN.CRI_CHARASE_KOBUN_CUENUM;
}
