public static class CharaSE_IRIS4i
{
	public const int iCRI_CHARASE_IRIS4_CUENUM = 10;

	public const int iCRI_CHARASE_IRIS4_IR4_JUMP = 1;

	public const int iCRI_CHARASE_IRIS4_IR4_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_IRIS4_IR4_CHAKUCHI = 3;

	public const int iCRI_CHARASE_IRIS4_IR4_DASH = 4;

	public const int iCRI_CHARASE_IRIS4_IR4_DASHEND = 5;

	public const int iCRI_CHARASE_IRIS4_IR4_KABEPETA = 6;

	public const int iCRI_CHARASE_IRIS4_IR4_KABEKERI = 7;

	public const int iCRI_CHARASE_IRIS4_IR4_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_IRIS4_IR4_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_IRIS4_IR4_FOOT = 10;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_CUENUM = CharaSE_IRIS4.CRI_CHARASE_IRIS4_CUENUM;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_IR4_JUMP = CharaSE_IRIS4.CRI_CHARASE_IRIS4_IR4_JUMP;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_IR4_JUMP_HIGH = CharaSE_IRIS4.CRI_CHARASE_IRIS4_IR4_JUMP_HIGH;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_IR4_CHAKUCHI = CharaSE_IRIS4.CRI_CHARASE_IRIS4_IR4_CHAKUCHI;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_IR4_DASH = CharaSE_IRIS4.CRI_CHARASE_IRIS4_IR4_DASH;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_IR4_DASHEND = CharaSE_IRIS4.CRI_CHARASE_IRIS4_IR4_DASHEND;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_IR4_KABEPETA = CharaSE_IRIS4.CRI_CHARASE_IRIS4_IR4_KABEPETA;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_IR4_KABEKERI = CharaSE_IRIS4.CRI_CHARASE_IRIS4_IR4_KABEKERI;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_IR4_TELEPORT_IN = CharaSE_IRIS4.CRI_CHARASE_IRIS4_IR4_TELEPORT_IN;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_IR4_TELEPORT_OUT = CharaSE_IRIS4.CRI_CHARASE_IRIS4_IR4_TELEPORT_OUT;

	public const CharaSE_IRIS4 CRI_CHARASE_IRIS4_IR4_FOOT = CharaSE_IRIS4.CRI_CHARASE_IRIS4_CUENUM;
}
