public static class CharaSE_RYUi
{
	public const int iCRI_CHARASE_RYU_CUENUM = 10;

	public const int iCRI_CHARASE_RYU_RY_JUMP = 1;

	public const int iCRI_CHARASE_RYU_RY_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_RYU_RY_CHAKUCHI = 3;

	public const int iCRI_CHARASE_RYU_RY_DASH = 4;

	public const int iCRI_CHARASE_RYU_RY_DASHEND = 5;

	public const int iCRI_CHARASE_RYU_RY_KABEPETA = 6;

	public const int iCRI_CHARASE_RYU_RY_KABEKERI = 7;

	public const int iCRI_CHARASE_RYU_RY_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_RYU_RY_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_RYU_RY_FOOT = 10;

	public const CharaSE_RYU CRI_CHARASE_RYU_CUENUM = CharaSE_RYU.CRI_CHARASE_RYU_CUENUM;

	public const CharaSE_RYU CRI_CHARASE_RYU_RY_JUMP = CharaSE_RYU.CRI_CHARASE_RYU_RY_JUMP;

	public const CharaSE_RYU CRI_CHARASE_RYU_RY_JUMP_HIGH = CharaSE_RYU.CRI_CHARASE_RYU_RY_JUMP_HIGH;

	public const CharaSE_RYU CRI_CHARASE_RYU_RY_CHAKUCHI = CharaSE_RYU.CRI_CHARASE_RYU_RY_CHAKUCHI;

	public const CharaSE_RYU CRI_CHARASE_RYU_RY_DASH = CharaSE_RYU.CRI_CHARASE_RYU_RY_DASH;

	public const CharaSE_RYU CRI_CHARASE_RYU_RY_DASHEND = CharaSE_RYU.CRI_CHARASE_RYU_RY_DASHEND;

	public const CharaSE_RYU CRI_CHARASE_RYU_RY_KABEPETA = CharaSE_RYU.CRI_CHARASE_RYU_RY_KABEPETA;

	public const CharaSE_RYU CRI_CHARASE_RYU_RY_KABEKERI = CharaSE_RYU.CRI_CHARASE_RYU_RY_KABEKERI;

	public const CharaSE_RYU CRI_CHARASE_RYU_RY_TELEPORT_IN = CharaSE_RYU.CRI_CHARASE_RYU_RY_TELEPORT_IN;

	public const CharaSE_RYU CRI_CHARASE_RYU_RY_TELEPORT_OUT = CharaSE_RYU.CRI_CHARASE_RYU_RY_TELEPORT_OUT;

	public const CharaSE_RYU CRI_CHARASE_RYU_RY_FOOT = CharaSE_RYU.CRI_CHARASE_RYU_CUENUM;
}
