public enum CharaSE_XFalcon
{
	NONE = 0,
	CRI_CHARASE_XFALCON_CUENUM = 10,
	CRI_CHARASE_XFALCON_XF_JUMP = 1,
	CRI_CHARASE_XFALCON_XF_JUMP_HIGH = 2,
	CRI_CHARASE_XFALCON_XF_CHAKUCHI = 3,
	CRI_CHARASE_XFALCON_XF_DASH = 4,
	CRI_CHARASE_XFALCON_XF_DASHEND = 5,
	CRI_CHARASE_XFALCON_XF_KABEPETA = 6,
	CRI_CHARASE_XFALCON_XF_KABEKERI = 7,
	CRI_CHARASE_XFALCON_XF_TELEPORT_IN = 8,
	CRI_CHARASE_XFALCON_XF_TELEPORT_OUT = 9,
	CRI_CHARASE_XFALCON_XF_FOOT = 10
}
