public enum CharaSE_DRAWER
{
	NONE = 0,
	CRI_CHARASE_DRAWER_CUENUM = 10,
	CRI_CHARASE_DRAWER_DR_JUMP = 1,
	CRI_CHARASE_DRAWER_DR_JUMP_HIGH = 2,
	CRI_CHARASE_DRAWER_DR_CHAKUCHI = 3,
	CRI_CHARASE_DRAWER_DR_DASH = 4,
	CRI_CHARASE_DRAWER_DR_DASHEND = 5,
	CRI_CHARASE_DRAWER_DR_KABEPETA = 6,
	CRI_CHARASE_DRAWER_DR_KABEKERI = 7,
	CRI_CHARASE_DRAWER_DR_TELEPORT_IN = 8,
	CRI_CHARASE_DRAWER_DR_TELEPORT_OUT = 9,
	CRI_CHARASE_DRAWER_DR_FOOT = 10
}
