public enum CharaSE_MH2
{
	NONE = 0,
	CRI_CHARASE_MH2_CUENUM = 10,
	CRI_CHARASE_MH2_MH2_JUMP = 1,
	CRI_CHARASE_MH2_MH2_JUMP_HIGH = 2,
	CRI_CHARASE_MH2_MH2_CHAKUCHI = 3,
	CRI_CHARASE_MH2_MH2_DASH = 4,
	CRI_CHARASE_MH2_MH2_DASHEND = 5,
	CRI_CHARASE_MH2_MH2_KABEPETA = 6,
	CRI_CHARASE_MH2_MH2_KABEKERI = 7,
	CRI_CHARASE_MH2_MH2_TELEPORT_IN = 8,
	CRI_CHARASE_MH2_MH2_TELEPORT_OUT = 9,
	CRI_CHARASE_MH2_MH2_FOOT = 10
}
