public static class CharaSE_CHUNLIi
{
	public const int iCRI_CHARASE_CHUNLI_CUENUM = 10;

	public const int iCRI_CHARASE_CHUNLI_CH_JUMP = 1;

	public const int iCRI_CHARASE_CHUNLI_CH_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_CHUNLI_CH_CHAKUCHI = 3;

	public const int iCRI_CHARASE_CHUNLI_CH_DASH = 4;

	public const int iCRI_CHARASE_CHUNLI_CH_DASHEND = 5;

	public const int iCRI_CHARASE_CHUNLI_CH_KABEPETA = 6;

	public const int iCRI_CHARASE_CHUNLI_CH_KABEKERI = 7;

	public const int iCRI_CHARASE_CHUNLI_CH_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_CHUNLI_CH_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_CHUNLI_CH_FOOT = 10;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CUENUM = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CUENUM;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CH_JUMP = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CH_JUMP;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CH_JUMP_HIGH = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CH_JUMP_HIGH;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CH_CHAKUCHI = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CH_CHAKUCHI;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CH_DASH = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CH_DASH;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CH_DASHEND = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CH_DASHEND;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CH_KABEPETA = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CH_KABEPETA;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CH_KABEKERI = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CH_KABEKERI;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CH_TELEPORT_IN = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CH_TELEPORT_IN;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CH_TELEPORT_OUT = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CH_TELEPORT_OUT;

	public const CharaSE_CHUNLI CRI_CHARASE_CHUNLI_CH_FOOT = CharaSE_CHUNLI.CRI_CHARASE_CHUNLI_CUENUM;
}
