public enum CharaSE_ROLLEXE
{
	NONE = 0,
	CRI_CHARASE_ROLLEXE_CUENUM = 10,
	CRI_CHARASE_ROLLEXE_RX_JUMP = 1,
	CRI_CHARASE_ROLLEXE_RX_JUMP_HIGH = 2,
	CRI_CHARASE_ROLLEXE_RX_CHAKUCHI = 3,
	CRI_CHARASE_ROLLEXE_RX_DASH = 4,
	CRI_CHARASE_ROLLEXE_RX_DASHEND = 5,
	CRI_CHARASE_ROLLEXE_RX_KABEPETA = 6,
	CRI_CHARASE_ROLLEXE_RX_KABEKERI = 7,
	CRI_CHARASE_ROLLEXE_RX_TELEPORT_IN = 8,
	CRI_CHARASE_ROLLEXE_RX_TELEPORT_OUT = 9,
	CRI_CHARASE_ROLLEXE_RX_FOOT = 10
}
