public static class CharaSE_IRISi
{
	public const int iCRI_CHARASE_IRIS_CUENUM = 10;

	public const int iCRI_CHARASE_IRIS_IR_JUMP = 1;

	public const int iCRI_CHARASE_IRIS_IR_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_IRIS_IR_CHAKUCHI = 3;

	public const int iCRI_CHARASE_IRIS_IR_DASH = 4;

	public const int iCRI_CHARASE_IRIS_IR_DASHEND = 5;

	public const int iCRI_CHARASE_IRIS_IR_KABEPETA = 6;

	public const int iCRI_CHARASE_IRIS_IR_KABEKERI = 7;

	public const int iCRI_CHARASE_IRIS_IR_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_IRIS_IR_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_IRIS_IR_FOOT = 10;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_CUENUM = CharaSE_IRIS.CRI_CHARASE_IRIS_CUENUM;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_IR_JUMP = CharaSE_IRIS.CRI_CHARASE_IRIS_IR_JUMP;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_IR_JUMP_HIGH = CharaSE_IRIS.CRI_CHARASE_IRIS_IR_JUMP_HIGH;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_IR_CHAKUCHI = CharaSE_IRIS.CRI_CHARASE_IRIS_IR_CHAKUCHI;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_IR_DASH = CharaSE_IRIS.CRI_CHARASE_IRIS_IR_DASH;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_IR_DASHEND = CharaSE_IRIS.CRI_CHARASE_IRIS_IR_DASHEND;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_IR_KABEPETA = CharaSE_IRIS.CRI_CHARASE_IRIS_IR_KABEPETA;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_IR_KABEKERI = CharaSE_IRIS.CRI_CHARASE_IRIS_IR_KABEKERI;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_IR_TELEPORT_IN = CharaSE_IRIS.CRI_CHARASE_IRIS_IR_TELEPORT_IN;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_IR_TELEPORT_OUT = CharaSE_IRIS.CRI_CHARASE_IRIS_IR_TELEPORT_OUT;

	public const CharaSE_IRIS CRI_CHARASE_IRIS_IR_FOOT = CharaSE_IRIS.CRI_CHARASE_IRIS_CUENUM;
}
