public static class CharaSE_MH2i
{
	public const int iCRI_CHARASE_MH2_CUENUM = 10;

	public const int iCRI_CHARASE_MH2_MH2_JUMP = 1;

	public const int iCRI_CHARASE_MH2_MH2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_MH2_MH2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_MH2_MH2_DASH = 4;

	public const int iCRI_CHARASE_MH2_MH2_DASHEND = 5;

	public const int iCRI_CHARASE_MH2_MH2_KABEPETA = 6;

	public const int iCRI_CHARASE_MH2_MH2_KABEKERI = 7;

	public const int iCRI_CHARASE_MH2_MH2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_MH2_MH2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_MH2_MH2_FOOT = 10;

	public const CharaSE_MH2 CRI_CHARASE_MH2_CUENUM = CharaSE_MH2.CRI_CHARASE_MH2_CUENUM;

	public const CharaSE_MH2 CRI_CHARASE_MH2_MH2_JUMP = CharaSE_MH2.CRI_CHARASE_MH2_MH2_JUMP;

	public const CharaSE_MH2 CRI_CHARASE_MH2_MH2_JUMP_HIGH = CharaSE_MH2.CRI_CHARASE_MH2_MH2_JUMP_HIGH;

	public const CharaSE_MH2 CRI_CHARASE_MH2_MH2_CHAKUCHI = CharaSE_MH2.CRI_CHARASE_MH2_MH2_CHAKUCHI;

	public const CharaSE_MH2 CRI_CHARASE_MH2_MH2_DASH = CharaSE_MH2.CRI_CHARASE_MH2_MH2_DASH;

	public const CharaSE_MH2 CRI_CHARASE_MH2_MH2_DASHEND = CharaSE_MH2.CRI_CHARASE_MH2_MH2_DASHEND;

	public const CharaSE_MH2 CRI_CHARASE_MH2_MH2_KABEPETA = CharaSE_MH2.CRI_CHARASE_MH2_MH2_KABEPETA;

	public const CharaSE_MH2 CRI_CHARASE_MH2_MH2_KABEKERI = CharaSE_MH2.CRI_CHARASE_MH2_MH2_KABEKERI;

	public const CharaSE_MH2 CRI_CHARASE_MH2_MH2_TELEPORT_IN = CharaSE_MH2.CRI_CHARASE_MH2_MH2_TELEPORT_IN;

	public const CharaSE_MH2 CRI_CHARASE_MH2_MH2_TELEPORT_OUT = CharaSE_MH2.CRI_CHARASE_MH2_MH2_TELEPORT_OUT;

	public const CharaSE_MH2 CRI_CHARASE_MH2_MH2_FOOT = CharaSE_MH2.CRI_CHARASE_MH2_CUENUM;
}
