public enum CharaSE_MH1
{
	NONE = 0,
	CRI_CHARASE_MH1_CUENUM = 10,
	CRI_CHARASE_MH1_MH1_JUMP = 1,
	CRI_CHARASE_MH1_MH1_JUMP_HIGH = 2,
	CRI_CHARASE_MH1_MH1_CHAKUCHI = 3,
	CRI_CHARASE_MH1_MH1_DASH = 4,
	CRI_CHARASE_MH1_MH1_DASHEND = 5,
	CRI_CHARASE_MH1_MH1_KABEPETA = 6,
	CRI_CHARASE_MH1_MH1_KABEKERI = 7,
	CRI_CHARASE_MH1_MH1_TELEPORT_IN = 8,
	CRI_CHARASE_MH1_MH1_TELEPORT_OUT = 9,
	CRI_CHARASE_MH1_MH1_FOOT = 10
}
