public enum CharaSE_TRON2
{
	NONE = 0,
	CRI_CHARASE_TRON2_CUENUM = 10,
	CRI_CHARASE_TRON2_TR2_JUMP = 1,
	CRI_CHARASE_TRON2_TR2_JUMP_HIGH = 2,
	CRI_CHARASE_TRON2_TR2_CHAKUCHI = 3,
	CRI_CHARASE_TRON2_TR2_DASH = 4,
	CRI_CHARASE_TRON2_TR2_DASHEND = 5,
	CRI_CHARASE_TRON2_TR2_KABEPETA = 6,
	CRI_CHARASE_TRON2_TR2_KABEKERI = 7,
	CRI_CHARASE_TRON2_TR2_TELEPORT_IN = 8,
	CRI_CHARASE_TRON2_TR2_TELEPORT_OUT = 9,
	CRI_CHARASE_TRON2_TR2_FOOT = 10
}
