public static class CharaSE_XFalconi
{
	public const int iCRI_CHARASE_XFALCON_CUENUM = 10;

	public const int iCRI_CHARASE_XFALCON_XF_JUMP = 1;

	public const int iCRI_CHARASE_XFALCON_XF_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_XFALCON_XF_CHAKUCHI = 3;

	public const int iCRI_CHARASE_XFALCON_XF_DASH = 4;

	public const int iCRI_CHARASE_XFALCON_XF_DASHEND = 5;

	public const int iCRI_CHARASE_XFALCON_XF_KABEPETA = 6;

	public const int iCRI_CHARASE_XFALCON_XF_KABEKERI = 7;

	public const int iCRI_CHARASE_XFALCON_XF_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_XFALCON_XF_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_XFALCON_XF_FOOT = 10;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_CUENUM = CharaSE_XFalcon.CRI_CHARASE_XFALCON_CUENUM;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_XF_JUMP = CharaSE_XFalcon.CRI_CHARASE_XFALCON_XF_JUMP;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_XF_JUMP_HIGH = CharaSE_XFalcon.CRI_CHARASE_XFALCON_XF_JUMP_HIGH;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_XF_CHAKUCHI = CharaSE_XFalcon.CRI_CHARASE_XFALCON_XF_CHAKUCHI;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_XF_DASH = CharaSE_XFalcon.CRI_CHARASE_XFALCON_XF_DASH;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_XF_DASHEND = CharaSE_XFalcon.CRI_CHARASE_XFALCON_XF_DASHEND;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_XF_KABEPETA = CharaSE_XFalcon.CRI_CHARASE_XFALCON_XF_KABEPETA;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_XF_KABEKERI = CharaSE_XFalcon.CRI_CHARASE_XFALCON_XF_KABEKERI;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_XF_TELEPORT_IN = CharaSE_XFalcon.CRI_CHARASE_XFALCON_XF_TELEPORT_IN;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_XF_TELEPORT_OUT = CharaSE_XFalcon.CRI_CHARASE_XFALCON_XF_TELEPORT_OUT;

	public const CharaSE_XFalcon CRI_CHARASE_XFALCON_XF_FOOT = CharaSE_XFalcon.CRI_CHARASE_XFALCON_CUENUM;
}
