public static class CharaSE_HARPYIAi
{
	public const int iCRI_CHARASE_HARPYIA_CUENUM = 10;

	public const int iCRI_CHARASE_HARPYIA_HA_JUMP = 1;

	public const int iCRI_CHARASE_HARPYIA_HA_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_HARPYIA_HA_CHAKUCHI = 3;

	public const int iCRI_CHARASE_HARPYIA_HA_DASH = 4;

	public const int iCRI_CHARASE_HARPYIA_HA_DASHEND = 5;

	public const int iCRI_CHARASE_HARPYIA_HA_KABEPETA = 6;

	public const int iCRI_CHARASE_HARPYIA_HA_KABEKERI = 7;

	public const int iCRI_CHARASE_HARPYIA_HA_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_HARPYIA_HA_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_HARPYIA_HA_FOOT = 10;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_CUENUM = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_CUENUM;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_HA_JUMP = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_HA_JUMP;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_HA_JUMP_HIGH = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_HA_JUMP_HIGH;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_HA_CHAKUCHI = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_HA_CHAKUCHI;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_HA_DASH = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_HA_DASH;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_HA_DASHEND = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_HA_DASHEND;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_HA_KABEPETA = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_HA_KABEPETA;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_HA_KABEKERI = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_HA_KABEKERI;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_HA_TELEPORT_IN = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_HA_TELEPORT_IN;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_HA_TELEPORT_OUT = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_HA_TELEPORT_OUT;

	public const CharaSE_HARPYIA CRI_CHARASE_HARPYIA_HA_FOOT = CharaSE_HARPYIA.CRI_CHARASE_HARPYIA_CUENUM;
}
