public enum CharaSE_RMZero
{
	NONE = 0,
	CRI_CHARASE_RMZERO_CUENUM = 10,
	CRI_CHARASE_RMZERO_ZZ_JUMP = 1,
	CRI_CHARASE_RMZERO_ZZ_JUMP_HIGH = 2,
	CRI_CHARASE_RMZERO_ZZ_CHAKUCHI = 3,
	CRI_CHARASE_RMZERO_ZZ_DASH = 4,
	CRI_CHARASE_RMZERO_ZZ_DASHEND = 5,
	CRI_CHARASE_RMZERO_ZZ_KABEPETA = 6,
	CRI_CHARASE_RMZERO_ZZ_KABEKERI = 7,
	CRI_CHARASE_RMZERO_ZZ_TELEPORT_IN = 8,
	CRI_CHARASE_RMZERO_ZZ_TELEPORT_OUT = 9,
	CRI_CHARASE_RMZERO_ZZ_FOOT = 10
}
