public enum CharaSE_Leviathan
{
	NONE = 0,
	CRI_CHARASE_LEVIATHAN_CUENUM = 10,
	CRI_CHARASE_LEVIATHAN_LV_JUMP = 1,
	CRI_CHARASE_LEVIATHAN_LV_JUMP_HIGH = 2,
	CRI_CHARASE_LEVIATHAN_LV_CHAKUCHI = 3,
	CRI_CHARASE_LEVIATHAN_LV_DASH = 4,
	CRI_CHARASE_LEVIATHAN_LV_DASHEND = 5,
	CRI_CHARASE_LEVIATHAN_LV_KABEPETA = 6,
	CRI_CHARASE_LEVIATHAN_LV_KABEKERI = 7,
	CRI_CHARASE_LEVIATHAN_LV_TELEPORT_IN = 8,
	CRI_CHARASE_LEVIATHAN_LV_TELEPORT_OUT = 9,
	CRI_CHARASE_LEVIATHAN_LV_FOOT = 10
}
