public enum CharaSE_HARPYIA
{
	NONE = 0,
	CRI_CHARASE_HARPYIA_CUENUM = 10,
	CRI_CHARASE_HARPYIA_HA_JUMP = 1,
	CRI_CHARASE_HARPYIA_HA_JUMP_HIGH = 2,
	CRI_CHARASE_HARPYIA_HA_CHAKUCHI = 3,
	CRI_CHARASE_HARPYIA_HA_DASH = 4,
	CRI_CHARASE_HARPYIA_HA_DASHEND = 5,
	CRI_CHARASE_HARPYIA_HA_KABEPETA = 6,
	CRI_CHARASE_HARPYIA_HA_KABEKERI = 7,
	CRI_CHARASE_HARPYIA_HA_TELEPORT_IN = 8,
	CRI_CHARASE_HARPYIA_HA_TELEPORT_OUT = 9,
	CRI_CHARASE_HARPYIA_HA_FOOT = 10
}
