public enum CharaSE_BURAI
{
	NONE = 0,
	CRI_CHARASE_BURAI_CUENUM = 10,
	CRI_CHARASE_BURAI_BU_JUMP = 1,
	CRI_CHARASE_BURAI_BU_JUMP_HIGH = 2,
	CRI_CHARASE_BURAI_BU_CHAKUCHI = 3,
	CRI_CHARASE_BURAI_BU_DASH = 4,
	CRI_CHARASE_BURAI_BU_DASHEND = 5,
	CRI_CHARASE_BURAI_BU_KABEPETA = 6,
	CRI_CHARASE_BURAI_BU_KABEKERI = 7,
	CRI_CHARASE_BURAI_BU_TELEPORT_IN = 8,
	CRI_CHARASE_BURAI_BU_TELEPORT_OUT = 9,
	CRI_CHARASE_BURAI_BU_FOOT = 10
}
