public static class CharaSE_ZEROMHi
{
	public const int iCRI_CHARASE_ZEROMH_CUENUM = 10;

	public const int iCRI_CHARASE_ZEROMH_ZM_JUMP = 1;

	public const int iCRI_CHARASE_ZEROMH_ZM_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ZEROMH_ZM_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ZEROMH_ZM_DASH = 4;

	public const int iCRI_CHARASE_ZEROMH_ZM_DASHEND = 5;

	public const int iCRI_CHARASE_ZEROMH_ZM_KABEPETA = 6;

	public const int iCRI_CHARASE_ZEROMH_ZM_KABEKERI = 7;

	public const int iCRI_CHARASE_ZEROMH_ZM_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ZEROMH_ZM_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ZEROMH_ZM_FOOT = 10;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_CUENUM = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_CUENUM;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_ZM_JUMP = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_ZM_JUMP;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_ZM_JUMP_HIGH = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_ZM_JUMP_HIGH;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_ZM_CHAKUCHI = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_ZM_CHAKUCHI;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_ZM_DASH = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_ZM_DASH;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_ZM_DASHEND = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_ZM_DASHEND;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_ZM_KABEPETA = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_ZM_KABEPETA;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_ZM_KABEKERI = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_ZM_KABEKERI;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_ZM_TELEPORT_IN = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_ZM_TELEPORT_IN;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_ZM_TELEPORT_OUT = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_ZM_TELEPORT_OUT;

	public const CharaSE_ZEROMH CRI_CHARASE_ZEROMH_ZM_FOOT = CharaSE_ZEROMH.CRI_CHARASE_ZEROMH_CUENUM;
}
