public enum CharaSE_XDive
{
	NONE = 0,
	CRI_CHARASE_XDIVE_CUENUM = 10,
	CRI_CHARASE_XDIVE_XD_JUMP = 1,
	CRI_CHARASE_XDIVE_XD_JUMP_HIGH = 2,
	CRI_CHARASE_XDIVE_XD_CHAKUCHI = 3,
	CRI_CHARASE_XDIVE_XD_DASH = 4,
	CRI_CHARASE_XDIVE_XD_DASHEND = 5,
	CRI_CHARASE_XDIVE_XD_KABEPETA = 6,
	CRI_CHARASE_XDIVE_XD_KABEKERI = 7,
	CRI_CHARASE_XDIVE_XD_TELEPORT_IN = 8,
	CRI_CHARASE_XDIVE_XD_TELEPORT_OUT = 9,
	CRI_CHARASE_XDIVE_XD_FOOT = 10
}
