public static class CharaSE_ICO2i
{
	public const int iCRI_CHARASE_ICO2_CUENUM = 10;

	public const int iCRI_CHARASE_ICO2_IC2_JUMP = 1;

	public const int iCRI_CHARASE_ICO2_IC2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ICO2_IC2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ICO2_IC2_DASH = 4;

	public const int iCRI_CHARASE_ICO2_IC2_DASHEND = 5;

	public const int iCRI_CHARASE_ICO2_IC2_KABEPETA = 6;

	public const int iCRI_CHARASE_ICO2_IC2_KABEKERI = 7;

	public const int iCRI_CHARASE_ICO2_IC2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ICO2_IC2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ICO2_IC2_FOOT = 10;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_CUENUM = CharaSE_ICO2.CRI_CHARASE_ICO2_CUENUM;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_IC2_JUMP = CharaSE_ICO2.CRI_CHARASE_ICO2_IC2_JUMP;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_IC2_JUMP_HIGH = CharaSE_ICO2.CRI_CHARASE_ICO2_IC2_JUMP_HIGH;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_IC2_CHAKUCHI = CharaSE_ICO2.CRI_CHARASE_ICO2_IC2_CHAKUCHI;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_IC2_DASH = CharaSE_ICO2.CRI_CHARASE_ICO2_IC2_DASH;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_IC2_DASHEND = CharaSE_ICO2.CRI_CHARASE_ICO2_IC2_DASHEND;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_IC2_KABEPETA = CharaSE_ICO2.CRI_CHARASE_ICO2_IC2_KABEPETA;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_IC2_KABEKERI = CharaSE_ICO2.CRI_CHARASE_ICO2_IC2_KABEKERI;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_IC2_TELEPORT_IN = CharaSE_ICO2.CRI_CHARASE_ICO2_IC2_TELEPORT_IN;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_IC2_TELEPORT_OUT = CharaSE_ICO2.CRI_CHARASE_ICO2_IC2_TELEPORT_OUT;

	public const CharaSE_ICO2 CRI_CHARASE_ICO2_IC2_FOOT = CharaSE_ICO2.CRI_CHARASE_ICO2_CUENUM;
}
