public static class CharaSE_BURAIi
{
	public const int iCRI_CHARASE_BURAI_CUENUM = 10;

	public const int iCRI_CHARASE_BURAI_BU_JUMP = 1;

	public const int iCRI_CHARASE_BURAI_BU_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_BURAI_BU_CHAKUCHI = 3;

	public const int iCRI_CHARASE_BURAI_BU_DASH = 4;

	public const int iCRI_CHARASE_BURAI_BU_DASHEND = 5;

	public const int iCRI_CHARASE_BURAI_BU_KABEPETA = 6;

	public const int iCRI_CHARASE_BURAI_BU_KABEKERI = 7;

	public const int iCRI_CHARASE_BURAI_BU_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_BURAI_BU_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_BURAI_BU_FOOT = 10;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_CUENUM = CharaSE_BURAI.CRI_CHARASE_BURAI_CUENUM;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_BU_JUMP = CharaSE_BURAI.CRI_CHARASE_BURAI_BU_JUMP;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_BU_JUMP_HIGH = CharaSE_BURAI.CRI_CHARASE_BURAI_BU_JUMP_HIGH;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_BU_CHAKUCHI = CharaSE_BURAI.CRI_CHARASE_BURAI_BU_CHAKUCHI;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_BU_DASH = CharaSE_BURAI.CRI_CHARASE_BURAI_BU_DASH;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_BU_DASHEND = CharaSE_BURAI.CRI_CHARASE_BURAI_BU_DASHEND;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_BU_KABEPETA = CharaSE_BURAI.CRI_CHARASE_BURAI_BU_KABEPETA;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_BU_KABEKERI = CharaSE_BURAI.CRI_CHARASE_BURAI_BU_KABEKERI;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_BU_TELEPORT_IN = CharaSE_BURAI.CRI_CHARASE_BURAI_BU_TELEPORT_IN;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_BU_TELEPORT_OUT = CharaSE_BURAI.CRI_CHARASE_BURAI_BU_TELEPORT_OUT;

	public const CharaSE_BURAI CRI_CHARASE_BURAI_BU_FOOT = CharaSE_BURAI.CRI_CHARASE_BURAI_CUENUM;
}
