public static class CharaSE_SIGMAi
{
	public const int iCRI_CHARASE_SIGMA_CUENUM = 10;

	public const int iCRI_CHARASE_SIGMA_SG_JUMP = 1;

	public const int iCRI_CHARASE_SIGMA_SG_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_SIGMA_SG_CHAKUCHI = 3;

	public const int iCRI_CHARASE_SIGMA_SG_DASH = 4;

	public const int iCRI_CHARASE_SIGMA_SG_DASHEND = 5;

	public const int iCRI_CHARASE_SIGMA_SG_KABEPETA = 6;

	public const int iCRI_CHARASE_SIGMA_SG_KABEKERI = 7;

	public const int iCRI_CHARASE_SIGMA_SG_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_SIGMA_SG_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_SIGMA_SG_FOOT = 10;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_CUENUM = CharaSE_SIGMA.CRI_CHARASE_SIGMA_CUENUM;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_SG_JUMP = CharaSE_SIGMA.CRI_CHARASE_SIGMA_SG_JUMP;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_SG_JUMP_HIGH = CharaSE_SIGMA.CRI_CHARASE_SIGMA_SG_JUMP_HIGH;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_SG_CHAKUCHI = CharaSE_SIGMA.CRI_CHARASE_SIGMA_SG_CHAKUCHI;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_SG_DASH = CharaSE_SIGMA.CRI_CHARASE_SIGMA_SG_DASH;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_SG_DASHEND = CharaSE_SIGMA.CRI_CHARASE_SIGMA_SG_DASHEND;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_SG_KABEPETA = CharaSE_SIGMA.CRI_CHARASE_SIGMA_SG_KABEPETA;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_SG_KABEKERI = CharaSE_SIGMA.CRI_CHARASE_SIGMA_SG_KABEKERI;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_SG_TELEPORT_IN = CharaSE_SIGMA.CRI_CHARASE_SIGMA_SG_TELEPORT_IN;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_SG_TELEPORT_OUT = CharaSE_SIGMA.CRI_CHARASE_SIGMA_SG_TELEPORT_OUT;

	public const CharaSE_SIGMA CRI_CHARASE_SIGMA_SG_FOOT = CharaSE_SIGMA.CRI_CHARASE_SIGMA_CUENUM;
}
