public static class CharaSE_BLUESi
{
	public const int iCRI_CHARASE_BLUES_CUENUM = 10;

	public const int iCRI_CHARASE_BLUES_BL_JUMP = 1;

	public const int iCRI_CHARASE_BLUES_BL_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_BLUES_BL_CHAKUCHI = 3;

	public const int iCRI_CHARASE_BLUES_BL_DASH = 4;

	public const int iCRI_CHARASE_BLUES_BL_DASHEND = 5;

	public const int iCRI_CHARASE_BLUES_BL_KABEPETA = 6;

	public const int iCRI_CHARASE_BLUES_BL_KABEKERI = 7;

	public const int iCRI_CHARASE_BLUES_BL_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_BLUES_BL_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_BLUES_BL_FOOT = 10;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_CUENUM = CharaSE_BLUES.CRI_CHARASE_BLUES_CUENUM;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_BL_JUMP = CharaSE_BLUES.CRI_CHARASE_BLUES_BL_JUMP;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_BL_JUMP_HIGH = CharaSE_BLUES.CRI_CHARASE_BLUES_BL_JUMP_HIGH;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_BL_CHAKUCHI = CharaSE_BLUES.CRI_CHARASE_BLUES_BL_CHAKUCHI;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_BL_DASH = CharaSE_BLUES.CRI_CHARASE_BLUES_BL_DASH;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_BL_DASHEND = CharaSE_BLUES.CRI_CHARASE_BLUES_BL_DASHEND;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_BL_KABEPETA = CharaSE_BLUES.CRI_CHARASE_BLUES_BL_KABEPETA;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_BL_KABEKERI = CharaSE_BLUES.CRI_CHARASE_BLUES_BL_KABEKERI;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_BL_TELEPORT_IN = CharaSE_BLUES.CRI_CHARASE_BLUES_BL_TELEPORT_IN;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_BL_TELEPORT_OUT = CharaSE_BLUES.CRI_CHARASE_BLUES_BL_TELEPORT_OUT;

	public const CharaSE_BLUES CRI_CHARASE_BLUES_BL_FOOT = CharaSE_BLUES.CRI_CHARASE_BLUES_CUENUM;
}
