public enum CharaSE_ERATO
{
	NONE = 0,
	CRI_CHARASE_ERATO_CUENUM = 10,
	CRI_CHARASE_ERATO_ER_JUMP = 1,
	CRI_CHARASE_ERATO_ER_JUMP_HIGH = 2,
	CRI_CHARASE_ERATO_ER_CHAKUCHI = 3,
	CRI_CHARASE_ERATO_ER_DASH = 4,
	CRI_CHARASE_ERATO_ER_DASHEND = 5,
	CRI_CHARASE_ERATO_ER_KABEPETA = 6,
	CRI_CHARASE_ERATO_ER_KABEKERI = 7,
	CRI_CHARASE_ERATO_ER_TELEPORT_IN = 8,
	CRI_CHARASE_ERATO_ER_TELEPORT_OUT = 9,
	CRI_CHARASE_ERATO_ER_FOOT = 10
}
