public enum CharaSE_XKai
{
	NONE = 0,
	CRI_CHARASE_XKAI_CUENUM = 10,
	CRI_CHARASE_XKAI_XK_FOOT = 10,
	CRI_CHARASE_XKAI_XK_JUMP = 1,
	CRI_CHARASE_XKAI_XK_JUMP_HIGH = 2,
	CRI_CHARASE_XKAI_XK_DASH = 4,
	CRI_CHARASE_XKAI_XK_CHAKUCHI = 3,
	CRI_CHARASE_XKAI_XK_DASHEND = 5,
	CRI_CHARASE_XKAI_XK_KABEPETA = 6,
	CRI_CHARASE_XKAI_XK_TELEPORT_IN = 8,
	CRI_CHARASE_XKAI_XK_TELEPORT_OUT = 9,
	CRI_CHARASE_XKAI_XK_KABEKERI = 7
}
