public enum CharaSE_IRIS
{
	NONE = 0,
	CRI_CHARASE_IRIS_CUENUM = 10,
	CRI_CHARASE_IRIS_IR_JUMP = 1,
	CRI_CHARASE_IRIS_IR_JUMP_HIGH = 2,
	CRI_CHARASE_IRIS_IR_CHAKUCHI = 3,
	CRI_CHARASE_IRIS_IR_DASH = 4,
	CRI_CHARASE_IRIS_IR_DASHEND = 5,
	CRI_CHARASE_IRIS_IR_KABEPETA = 6,
	CRI_CHARASE_IRIS_IR_KABEKERI = 7,
	CRI_CHARASE_IRIS_IR_TELEPORT_IN = 8,
	CRI_CHARASE_IRIS_IR_TELEPORT_OUT = 9,
	CRI_CHARASE_IRIS_IR_FOOT = 10
}
