public static class CharaSE_AwakenZeroi
{
	public const int iCRI_CHARASE_AWAKENZERO_CUENUM = 10;

	public const int iCRI_CHARASE_AWAKENZERO_ZA_JUMP = 1;

	public const int iCRI_CHARASE_AWAKENZERO_ZA_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_AWAKENZERO_ZA_CHAKUCHI = 3;

	public const int iCRI_CHARASE_AWAKENZERO_ZA_DASH = 4;

	public const int iCRI_CHARASE_AWAKENZERO_ZA_DASHEND = 5;

	public const int iCRI_CHARASE_AWAKENZERO_ZA_KABEPETA = 6;

	public const int iCRI_CHARASE_AWAKENZERO_ZA_KABEKERI = 7;

	public const int iCRI_CHARASE_AWAKENZERO_ZA_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_AWAKENZERO_ZA_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_AWAKENZERO_ZA_FOOT = 10;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_CUENUM = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_CUENUM;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_ZA_JUMP = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_ZA_JUMP;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_ZA_JUMP_HIGH = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_ZA_JUMP_HIGH;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_ZA_CHAKUCHI = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_ZA_CHAKUCHI;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_ZA_DASH = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_ZA_DASH;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_ZA_DASHEND = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_ZA_DASHEND;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_ZA_KABEPETA = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_ZA_KABEPETA;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_ZA_KABEKERI = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_ZA_KABEKERI;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_ZA_TELEPORT_IN = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_ZA_TELEPORT_IN;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_ZA_TELEPORT_OUT = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_ZA_TELEPORT_OUT;

	public const CharaSE_AwakenZero CRI_CHARASE_AWAKENZERO_ZA_FOOT = CharaSE_AwakenZero.CRI_CHARASE_AWAKENZERO_CUENUM;
}
