public enum CharaSE_ROCKVOL
{
	NONE = 0,
	CRI_CHARASE_ROCKVOL_CUENUM = 10,
	CRI_CHARASE_ROCKVOL_RV_JUMP = 1,
	CRI_CHARASE_ROCKVOL_RV_JUMP_HIGH = 2,
	CRI_CHARASE_ROCKVOL_RV_CHAKUCHI = 3,
	CRI_CHARASE_ROCKVOL_RV_DASH = 4,
	CRI_CHARASE_ROCKVOL_RV_DASHEND = 5,
	CRI_CHARASE_ROCKVOL_RV_KABEPETA = 6,
	CRI_CHARASE_ROCKVOL_RV_KABEKERI = 7,
	CRI_CHARASE_ROCKVOL_RV_TELEPORT_IN = 8,
	CRI_CHARASE_ROCKVOL_RV_TELEPORT_OUT = 9,
	CRI_CHARASE_ROCKVOL_RV_FOOT = 10
}
