public static class CharaSE_SIGMA02i
{
	public const int iCRI_CHARASE_SIGMA02_CUENUM = 10;

	public const int iCRI_CHARASE_SIGMA02_SG02_JUMP = 1;

	public const int iCRI_CHARASE_SIGMA02_SG02_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_SIGMA02_SG02_CHAKUCHI = 3;

	public const int iCRI_CHARASE_SIGMA02_SG02_DASH = 4;

	public const int iCRI_CHARASE_SIGMA02_SG02_DASHEND = 5;

	public const int iCRI_CHARASE_SIGMA02_SG02_KABEPETA = 6;

	public const int iCRI_CHARASE_SIGMA02_SG02_KABEKERI = 7;

	public const int iCRI_CHARASE_SIGMA02_SG02_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_SIGMA02_SG02_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_SIGMA02_SG02_FOOT = 10;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_CUENUM = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_CUENUM;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_SG02_JUMP = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_SG02_JUMP;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_SG02_JUMP_HIGH = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_SG02_JUMP_HIGH;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_SG02_CHAKUCHI = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_SG02_CHAKUCHI;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_SG02_DASH = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_SG02_DASH;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_SG02_DASHEND = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_SG02_DASHEND;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_SG02_KABEPETA = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_SG02_KABEPETA;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_SG02_KABEKERI = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_SG02_KABEKERI;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_SG02_TELEPORT_IN = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_SG02_TELEPORT_IN;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_SG02_TELEPORT_OUT = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_SG02_TELEPORT_OUT;

	public const CharaSE_SIGMA02 CRI_CHARASE_SIGMA02_SG02_FOOT = CharaSE_SIGMA02.CRI_CHARASE_SIGMA02_CUENUM;
}
