public enum CharaSE_X2ndArmor
{
	NONE = 0,
	CRI_CHARASE_X2NDARMOR_CUENUM = 10,
	CRI_CHARASE_X2NDARMOR_X2_JUMP = 1,
	CRI_CHARASE_X2NDARMOR_X2_JUMP_HIGH = 2,
	CRI_CHARASE_X2NDARMOR_X2_CHAKUCHI = 3,
	CRI_CHARASE_X2NDARMOR_X2_DASH = 4,
	CRI_CHARASE_X2NDARMOR_X2_DASHEND = 5,
	CRI_CHARASE_X2NDARMOR_X2_KABEPETA = 6,
	CRI_CHARASE_X2NDARMOR_X2_KABEKERI = 7,
	CRI_CHARASE_X2NDARMOR_X2_TELEPORT_IN = 8,
	CRI_CHARASE_X2NDARMOR_X2_TELEPORT_OUT = 9,
	CRI_CHARASE_X2NDARMOR_X2_FOOT = 10
}
