public enum CharaSE_ANGE
{
	NONE = 0,
	CRI_CHARASE_ANGE_CUENUM = 10,
	CRI_CHARASE_ANGE_AN_JUMP = 1,
	CRI_CHARASE_ANGE_AN_JUMP_HIGH = 2,
	CRI_CHARASE_ANGE_AN_CHAKUCHI = 3,
	CRI_CHARASE_ANGE_AN_DASH = 4,
	CRI_CHARASE_ANGE_AN_DASHEND = 5,
	CRI_CHARASE_ANGE_AN_KABEPETA = 6,
	CRI_CHARASE_ANGE_AN_KABEKERI = 7,
	CRI_CHARASE_ANGE_AN_TELEPORT_IN = 8,
	CRI_CHARASE_ANGE_AN_TELEPORT_OUT = 9,
	CRI_CHARASE_ANGE_AN_FOOT = 10
}
