public enum CharaSE_UltimateX
{
	NONE = 0,
	CRI_CHARASE_ULTIMATEX_CUENUM = 10,
	CRI_CHARASE_ULTIMATEX_XU_JUMP = 1,
	CRI_CHARASE_ULTIMATEX_XU_JUMP_HIGH = 2,
	CRI_CHARASE_ULTIMATEX_XU_CHAKUCHI = 3,
	CRI_CHARASE_ULTIMATEX_XU_DASH = 4,
	CRI_CHARASE_ULTIMATEX_XU_DASHEND = 5,
	CRI_CHARASE_ULTIMATEX_XU_KABEPETA = 6,
	CRI_CHARASE_ULTIMATEX_XU_KABEKERI = 7,
	CRI_CHARASE_ULTIMATEX_XU_TELEPORT_IN = 8,
	CRI_CHARASE_ULTIMATEX_XU_TELEPORT_OUT = 9,
	CRI_CHARASE_ULTIMATEX_XU_FOOT = 10
}
