public static class CharaSE_XDivei
{
	public const int iCRI_CHARASE_XDIVE_CUENUM = 10;

	public const int iCRI_CHARASE_XDIVE_XD_JUMP = 1;

	public const int iCRI_CHARASE_XDIVE_XD_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_XDIVE_XD_CHAKUCHI = 3;

	public const int iCRI_CHARASE_XDIVE_XD_DASH = 4;

	public const int iCRI_CHARASE_XDIVE_XD_DASHEND = 5;

	public const int iCRI_CHARASE_XDIVE_XD_KABEPETA = 6;

	public const int iCRI_CHARASE_XDIVE_XD_KABEKERI = 7;

	public const int iCRI_CHARASE_XDIVE_XD_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_XDIVE_XD_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_XDIVE_XD_FOOT = 10;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_CUENUM = CharaSE_XDive.CRI_CHARASE_XDIVE_CUENUM;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_XD_JUMP = CharaSE_XDive.CRI_CHARASE_XDIVE_XD_JUMP;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_XD_JUMP_HIGH = CharaSE_XDive.CRI_CHARASE_XDIVE_XD_JUMP_HIGH;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_XD_CHAKUCHI = CharaSE_XDive.CRI_CHARASE_XDIVE_XD_CHAKUCHI;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_XD_DASH = CharaSE_XDive.CRI_CHARASE_XDIVE_XD_DASH;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_XD_DASHEND = CharaSE_XDive.CRI_CHARASE_XDIVE_XD_DASHEND;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_XD_KABEPETA = CharaSE_XDive.CRI_CHARASE_XDIVE_XD_KABEPETA;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_XD_KABEKERI = CharaSE_XDive.CRI_CHARASE_XDIVE_XD_KABEKERI;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_XD_TELEPORT_IN = CharaSE_XDive.CRI_CHARASE_XDIVE_XD_TELEPORT_IN;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_XD_TELEPORT_OUT = CharaSE_XDive.CRI_CHARASE_XDIVE_XD_TELEPORT_OUT;

	public const CharaSE_XDive CRI_CHARASE_XDIVE_XD_FOOT = CharaSE_XDive.CRI_CHARASE_XDIVE_CUENUM;
}
