public enum CharaSE_RICO
{
	NONE = 0,
	CRI_CHARASE_RICO_CUENUM = 10,
	CRI_CHARASE_RICO_RI_JUMP = 1,
	CRI_CHARASE_RICO_RI_JUMP_HIGH = 2,
	CRI_CHARASE_RICO_RI_CHAKUCHI = 3,
	CRI_CHARASE_RICO_RI_DASH = 4,
	CRI_CHARASE_RICO_RI_DASHEND = 5,
	CRI_CHARASE_RICO_RI_KABEPETA = 6,
	CRI_CHARASE_RICO_RI_KABEKERI = 7,
	CRI_CHARASE_RICO_RI_TELEPORT_IN = 8,
	CRI_CHARASE_RICO_RI_TELEPORT_OUT = 9,
	CRI_CHARASE_RICO_RI_FOOT = 10
}
