public static class CharaSE_FORTEGSi
{
	public const int iCRI_CHARASE_FORTEGS_CUENUM = 10;

	public const int iCRI_CHARASE_FORTEGS_FG_JUMP = 1;

	public const int iCRI_CHARASE_FORTEGS_FG_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_FORTEGS_FG_CHAKUCHI = 3;

	public const int iCRI_CHARASE_FORTEGS_FG_DASH = 4;

	public const int iCRI_CHARASE_FORTEGS_FG_DASHEND = 5;

	public const int iCRI_CHARASE_FORTEGS_FG_KABEPETA = 6;

	public const int iCRI_CHARASE_FORTEGS_FG_KABEKERI = 7;

	public const int iCRI_CHARASE_FORTEGS_FG_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_FORTEGS_FG_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_FORTEGS_FG_FOOT = 10;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_CUENUM = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_CUENUM;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_FG_JUMP = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_FG_JUMP;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_FG_JUMP_HIGH = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_FG_JUMP_HIGH;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_FG_CHAKUCHI = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_FG_CHAKUCHI;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_FG_DASH = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_FG_DASH;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_FG_DASHEND = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_FG_DASHEND;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_FG_KABEPETA = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_FG_KABEPETA;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_FG_KABEKERI = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_FG_KABEKERI;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_FG_TELEPORT_IN = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_FG_TELEPORT_IN;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_FG_TELEPORT_OUT = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_FG_TELEPORT_OUT;

	public const CharaSE_FORTEGS CRI_CHARASE_FORTEGS_FG_FOOT = CharaSE_FORTEGS.CRI_CHARASE_FORTEGS_CUENUM;
}
