public enum CharaSE_CIEL
{
	NONE = 0,
	CRI_CHARASE_CIEL_CUENUM = 10,
	CRI_CHARASE_CIEL_CL_JUMP = 1,
	CRI_CHARASE_CIEL_CL_JUMP_HIGH = 2,
	CRI_CHARASE_CIEL_CL_CHAKUCHI = 3,
	CRI_CHARASE_CIEL_CL_DASH = 4,
	CRI_CHARASE_CIEL_CL_DASHEND = 5,
	CRI_CHARASE_CIEL_CL_KABEPETA = 6,
	CRI_CHARASE_CIEL_CL_KABEKERI = 7,
	CRI_CHARASE_CIEL_CL_TELEPORT_IN = 8,
	CRI_CHARASE_CIEL_CL_TELEPORT_OUT = 9,
	CRI_CHARASE_CIEL_CL_FOOT = 10
}
