public enum CharaSE_ZERONM
{
	NONE = 0,
	CRI_CHARASE_ZERONM_CUENUM = 10,
	CRI_CHARASE_ZERONM_ZN_JUMP = 1,
	CRI_CHARASE_ZERONM_ZN_JUMP_HIGH = 2,
	CRI_CHARASE_ZERONM_ZN_CHAKUCHI = 3,
	CRI_CHARASE_ZERONM_ZN_DASH = 4,
	CRI_CHARASE_ZERONM_ZN_DASHEND = 5,
	CRI_CHARASE_ZERONM_ZN_KABEPETA = 6,
	CRI_CHARASE_ZERONM_ZN_KABEKERI = 7,
	CRI_CHARASE_ZERONM_ZN_TELEPORT_IN = 8,
	CRI_CHARASE_ZERONM_ZN_TELEPORT_OUT = 9,
	CRI_CHARASE_ZERONM_ZN_FOOT = 10
}
