public static class CharaSE_FORTE2i
{
	public const int iCRI_CHARASE_FORTE2_CUENUM = 10;

	public const int iCRI_CHARASE_FORTE2_FO2_JUMP = 1;

	public const int iCRI_CHARASE_FORTE2_FO2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_FORTE2_FO2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_FORTE2_FO2_DASH = 4;

	public const int iCRI_CHARASE_FORTE2_FO2_DASHEND = 5;

	public const int iCRI_CHARASE_FORTE2_FO2_KABEPETA = 6;

	public const int iCRI_CHARASE_FORTE2_FO2_KABEKERI = 7;

	public const int iCRI_CHARASE_FORTE2_FO2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_FORTE2_FO2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_FORTE2_FO2_FOOT = 10;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_CUENUM = CharaSE_FORTE2.CRI_CHARASE_FORTE2_CUENUM;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_FO2_JUMP = CharaSE_FORTE2.CRI_CHARASE_FORTE2_FO2_JUMP;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_FO2_JUMP_HIGH = CharaSE_FORTE2.CRI_CHARASE_FORTE2_FO2_JUMP_HIGH;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_FO2_CHAKUCHI = CharaSE_FORTE2.CRI_CHARASE_FORTE2_FO2_CHAKUCHI;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_FO2_DASH = CharaSE_FORTE2.CRI_CHARASE_FORTE2_FO2_DASH;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_FO2_DASHEND = CharaSE_FORTE2.CRI_CHARASE_FORTE2_FO2_DASHEND;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_FO2_KABEPETA = CharaSE_FORTE2.CRI_CHARASE_FORTE2_FO2_KABEPETA;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_FO2_KABEKERI = CharaSE_FORTE2.CRI_CHARASE_FORTE2_FO2_KABEKERI;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_FO2_TELEPORT_IN = CharaSE_FORTE2.CRI_CHARASE_FORTE2_FO2_TELEPORT_IN;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_FO2_TELEPORT_OUT = CharaSE_FORTE2.CRI_CHARASE_FORTE2_FO2_TELEPORT_OUT;

	public const CharaSE_FORTE2 CRI_CHARASE_FORTE2_FO2_FOOT = CharaSE_FORTE2.CRI_CHARASE_FORTE2_CUENUM;
}
