public enum CharaSE_VIA
{
	NONE = 0,
	CRI_CHARASE_VIA_CUENUM = 10,
	CRI_CHARASE_VIA_VI_JUMP = 1,
	CRI_CHARASE_VIA_VI_JUMP_HIGH = 2,
	CRI_CHARASE_VIA_VI_CHAKUCHI = 3,
	CRI_CHARASE_VIA_VI_DASH = 4,
	CRI_CHARASE_VIA_VI_DASHEND = 5,
	CRI_CHARASE_VIA_VI_KABEPETA = 6,
	CRI_CHARASE_VIA_VI_KABEKERI = 7,
	CRI_CHARASE_VIA_VI_TELEPORT_IN = 8,
	CRI_CHARASE_VIA_VI_TELEPORT_OUT = 9,
	CRI_CHARASE_VIA_VI_FOOT = 10
}
