public static class CharaSE_NANAi
{
	public const int iCRI_CHARASE_NANA_CUENUM = 10;

	public const int iCRI_CHARASE_NANA_NA_JUMP = 1;

	public const int iCRI_CHARASE_NANA_NA_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_NANA_NA_CHAKUCHI = 3;

	public const int iCRI_CHARASE_NANA_NA_DASH = 4;

	public const int iCRI_CHARASE_NANA_NA_DASHEND = 5;

	public const int iCRI_CHARASE_NANA_NA_KABEPETA = 6;

	public const int iCRI_CHARASE_NANA_NA_KABEKERI = 7;

	public const int iCRI_CHARASE_NANA_NA_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_NANA_NA_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_NANA_NA_FOOT = 10;

	public const CharaSE_NANA CRI_CHARASE_NANA_CUENUM = CharaSE_NANA.CRI_CHARASE_NANA_CUENUM;

	public const CharaSE_NANA CRI_CHARASE_NANA_NA_JUMP = CharaSE_NANA.CRI_CHARASE_NANA_NA_JUMP;

	public const CharaSE_NANA CRI_CHARASE_NANA_NA_JUMP_HIGH = CharaSE_NANA.CRI_CHARASE_NANA_NA_JUMP_HIGH;

	public const CharaSE_NANA CRI_CHARASE_NANA_NA_CHAKUCHI = CharaSE_NANA.CRI_CHARASE_NANA_NA_CHAKUCHI;

	public const CharaSE_NANA CRI_CHARASE_NANA_NA_DASH = CharaSE_NANA.CRI_CHARASE_NANA_NA_DASH;

	public const CharaSE_NANA CRI_CHARASE_NANA_NA_DASHEND = CharaSE_NANA.CRI_CHARASE_NANA_NA_DASHEND;

	public const CharaSE_NANA CRI_CHARASE_NANA_NA_KABEPETA = CharaSE_NANA.CRI_CHARASE_NANA_NA_KABEPETA;

	public const CharaSE_NANA CRI_CHARASE_NANA_NA_KABEKERI = CharaSE_NANA.CRI_CHARASE_NANA_NA_KABEKERI;

	public const CharaSE_NANA CRI_CHARASE_NANA_NA_TELEPORT_IN = CharaSE_NANA.CRI_CHARASE_NANA_NA_TELEPORT_IN;

	public const CharaSE_NANA CRI_CHARASE_NANA_NA_TELEPORT_OUT = CharaSE_NANA.CRI_CHARASE_NANA_NA_TELEPORT_OUT;

	public const CharaSE_NANA CRI_CHARASE_NANA_NA_FOOT = CharaSE_NANA.CRI_CHARASE_NANA_CUENUM;
}
