public enum CharaSE_MARINO
{
	NONE = 0,
	CRI_CHARASE_MARINO_CUENUM = 10,
	CRI_CHARASE_MARINO_MR_JUMP = 1,
	CRI_CHARASE_MARINO_MR_JUMP_HIGH = 2,
	CRI_CHARASE_MARINO_MR_CHAKUCHI = 3,
	CRI_CHARASE_MARINO_MR_DASH = 4,
	CRI_CHARASE_MARINO_MR_DASHEND = 5,
	CRI_CHARASE_MARINO_MR_KABEPETA = 6,
	CRI_CHARASE_MARINO_MR_KABEKERI = 7,
	CRI_CHARASE_MARINO_MR_TELEPORT_IN = 8,
	CRI_CHARASE_MARINO_MR_TELEPORT_OUT = 9,
	CRI_CHARASE_MARINO_MR_FOOT = 10
}
