public enum CharaSE_ZERODive
{
	NONE = 0,
	CRI_CHARASE_ZERODIVE_CUENUM = 10,
	CRI_CHARASE_ZERODIVE_ZD_JUMP = 1,
	CRI_CHARASE_ZERODIVE_ZD_JUMP_HIGH = 2,
	CRI_CHARASE_ZERODIVE_ZD_CHAKUCHI = 3,
	CRI_CHARASE_ZERODIVE_ZD_DASH = 4,
	CRI_CHARASE_ZERODIVE_ZD_DASHEND = 5,
	CRI_CHARASE_ZERODIVE_ZD_KABEPETA = 6,
	CRI_CHARASE_ZERODIVE_ZD_KABEKERI = 7,
	CRI_CHARASE_ZERODIVE_ZD_TELEPORT_IN = 8,
	CRI_CHARASE_ZERODIVE_ZD_TELEPORT_OUT = 9,
	CRI_CHARASE_ZERODIVE_ZD_FOOT = 10
}
