public static class CharaSE_ZEROi
{
	public const int iCRI_CHARASE_ZERO_CUENUM = 10;

	public const int iCRI_CHARASE_ZERO_Z_JUMP = 1;

	public const int iCRI_CHARASE_ZERO_Z_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ZERO_Z_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ZERO_Z_DASH = 4;

	public const int iCRI_CHARASE_ZERO_Z_DASHEND = 5;

	public const int iCRI_CHARASE_ZERO_Z_KABEPETA = 6;

	public const int iCRI_CHARASE_ZERO_Z_KABEKERI = 7;

	public const int iCRI_CHARASE_ZERO_Z_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ZERO_Z_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ZERO_Z_FOOT = 10;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_CUENUM = CharaSE_ZERO.CRI_CHARASE_ZERO_CUENUM;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_Z_JUMP = CharaSE_ZERO.CRI_CHARASE_ZERO_Z_JUMP;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_Z_JUMP_HIGH = CharaSE_ZERO.CRI_CHARASE_ZERO_Z_JUMP_HIGH;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_Z_CHAKUCHI = CharaSE_ZERO.CRI_CHARASE_ZERO_Z_CHAKUCHI;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_Z_DASH = CharaSE_ZERO.CRI_CHARASE_ZERO_Z_DASH;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_Z_DASHEND = CharaSE_ZERO.CRI_CHARASE_ZERO_Z_DASHEND;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_Z_KABEPETA = CharaSE_ZERO.CRI_CHARASE_ZERO_Z_KABEPETA;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_Z_KABEKERI = CharaSE_ZERO.CRI_CHARASE_ZERO_Z_KABEKERI;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_Z_TELEPORT_IN = CharaSE_ZERO.CRI_CHARASE_ZERO_Z_TELEPORT_IN;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_Z_TELEPORT_OUT = CharaSE_ZERO.CRI_CHARASE_ZERO_Z_TELEPORT_OUT;

	public const CharaSE_ZERO CRI_CHARASE_ZERO_Z_FOOT = CharaSE_ZERO.CRI_CHARASE_ZERO_CUENUM;
}
