public enum CharaSE_NANA
{
	NONE = 0,
	CRI_CHARASE_NANA_CUENUM = 10,
	CRI_CHARASE_NANA_NA_JUMP = 1,
	CRI_CHARASE_NANA_NA_JUMP_HIGH = 2,
	CRI_CHARASE_NANA_NA_CHAKUCHI = 3,
	CRI_CHARASE_NANA_NA_DASH = 4,
	CRI_CHARASE_NANA_NA_DASHEND = 5,
	CRI_CHARASE_NANA_NA_KABEPETA = 6,
	CRI_CHARASE_NANA_NA_KABEKERI = 7,
	CRI_CHARASE_NANA_NA_TELEPORT_IN = 8,
	CRI_CHARASE_NANA_NA_TELEPORT_OUT = 9,
	CRI_CHARASE_NANA_NA_FOOT = 10
}
