public static class CharaSE_ERATO2i
{
	public const int iCRI_CHARASE_ERATO2_CUENUM = 10;

	public const int iCRI_CHARASE_ERATO2_ER2_JUMP = 1;

	public const int iCRI_CHARASE_ERATO2_ER2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ERATO2_ER2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ERATO2_ER2_DASH = 4;

	public const int iCRI_CHARASE_ERATO2_ER2_DASHEND = 5;

	public const int iCRI_CHARASE_ERATO2_ER2_KABEPETA = 6;

	public const int iCRI_CHARASE_ERATO2_ER2_KABEKERI = 7;

	public const int iCRI_CHARASE_ERATO2_ER2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ERATO2_ER2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ERATO2_ER2_FOOT = 10;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_CUENUM = CharaSE_ERATO2.CRI_CHARASE_ERATO2_CUENUM;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_ER2_JUMP = CharaSE_ERATO2.CRI_CHARASE_ERATO2_ER2_JUMP;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_ER2_JUMP_HIGH = CharaSE_ERATO2.CRI_CHARASE_ERATO2_ER2_JUMP_HIGH;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_ER2_CHAKUCHI = CharaSE_ERATO2.CRI_CHARASE_ERATO2_ER2_CHAKUCHI;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_ER2_DASH = CharaSE_ERATO2.CRI_CHARASE_ERATO2_ER2_DASH;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_ER2_DASHEND = CharaSE_ERATO2.CRI_CHARASE_ERATO2_ER2_DASHEND;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_ER2_KABEPETA = CharaSE_ERATO2.CRI_CHARASE_ERATO2_ER2_KABEPETA;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_ER2_KABEKERI = CharaSE_ERATO2.CRI_CHARASE_ERATO2_ER2_KABEKERI;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_ER2_TELEPORT_IN = CharaSE_ERATO2.CRI_CHARASE_ERATO2_ER2_TELEPORT_IN;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_ER2_TELEPORT_OUT = CharaSE_ERATO2.CRI_CHARASE_ERATO2_ER2_TELEPORT_OUT;

	public const CharaSE_ERATO2 CRI_CHARASE_ERATO2_ER2_FOOT = CharaSE_ERATO2.CRI_CHARASE_ERATO2_CUENUM;
}
