public static class CharaSE_ANGEi
{
	public const int iCRI_CHARASE_ANGE_CUENUM = 10;

	public const int iCRI_CHARASE_ANGE_AN_JUMP = 1;

	public const int iCRI_CHARASE_ANGE_AN_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ANGE_AN_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ANGE_AN_DASH = 4;

	public const int iCRI_CHARASE_ANGE_AN_DASHEND = 5;

	public const int iCRI_CHARASE_ANGE_AN_KABEPETA = 6;

	public const int iCRI_CHARASE_ANGE_AN_KABEKERI = 7;

	public const int iCRI_CHARASE_ANGE_AN_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ANGE_AN_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ANGE_AN_FOOT = 10;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_CUENUM = CharaSE_ANGE.CRI_CHARASE_ANGE_CUENUM;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_AN_JUMP = CharaSE_ANGE.CRI_CHARASE_ANGE_AN_JUMP;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_AN_JUMP_HIGH = CharaSE_ANGE.CRI_CHARASE_ANGE_AN_JUMP_HIGH;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_AN_CHAKUCHI = CharaSE_ANGE.CRI_CHARASE_ANGE_AN_CHAKUCHI;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_AN_DASH = CharaSE_ANGE.CRI_CHARASE_ANGE_AN_DASH;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_AN_DASHEND = CharaSE_ANGE.CRI_CHARASE_ANGE_AN_DASHEND;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_AN_KABEPETA = CharaSE_ANGE.CRI_CHARASE_ANGE_AN_KABEPETA;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_AN_KABEKERI = CharaSE_ANGE.CRI_CHARASE_ANGE_AN_KABEKERI;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_AN_TELEPORT_IN = CharaSE_ANGE.CRI_CHARASE_ANGE_AN_TELEPORT_IN;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_AN_TELEPORT_OUT = CharaSE_ANGE.CRI_CHARASE_ANGE_AN_TELEPORT_OUT;

	public const CharaSE_ANGE CRI_CHARASE_ANGE_AN_FOOT = CharaSE_ANGE.CRI_CHARASE_ANGE_CUENUM;
}
