public static class CharaSE_X4thArmori
{
	public const int iCRI_CHARASE_X4THARMOR_CUENUM = 10;

	public const int iCRI_CHARASE_X4THARMOR_X4_JUMP = 1;

	public const int iCRI_CHARASE_X4THARMOR_X4_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_X4THARMOR_X4_CHAKUCHI = 3;

	public const int iCRI_CHARASE_X4THARMOR_X4_DASH = 4;

	public const int iCRI_CHARASE_X4THARMOR_X4_DASHEND = 5;

	public const int iCRI_CHARASE_X4THARMOR_X4_KABEPETA = 6;

	public const int iCRI_CHARASE_X4THARMOR_X4_KABEKERI = 7;

	public const int iCRI_CHARASE_X4THARMOR_X4_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_X4THARMOR_X4_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_X4THARMOR_X4_FOOT = 10;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_CUENUM = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_CUENUM;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_X4_JUMP = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_X4_JUMP;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_X4_JUMP_HIGH = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_X4_JUMP_HIGH;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_X4_CHAKUCHI = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_X4_CHAKUCHI;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_X4_DASH = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_X4_DASH;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_X4_DASHEND = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_X4_DASHEND;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_X4_KABEPETA = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_X4_KABEPETA;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_X4_KABEKERI = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_X4_KABEKERI;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_X4_TELEPORT_IN = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_X4_TELEPORT_IN;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_X4_TELEPORT_OUT = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_X4_TELEPORT_OUT;

	public const CharaSE_X4thArmor CRI_CHARASE_X4THARMOR_X4_FOOT = CharaSE_X4thArmor.CRI_CHARASE_X4THARMOR_CUENUM;
}
