public enum CharaSE_XDMC
{
	NONE = 0,
	CRI_CHARASE_XDMC_CUENUM = 10,
	CRI_CHARASE_XDMC_XC_JUMP = 1,
	CRI_CHARASE_XDMC_XC_JUMP_HIGH = 2,
	CRI_CHARASE_XDMC_XC_CHAKUCHI = 3,
	CRI_CHARASE_XDMC_XC_DASH = 4,
	CRI_CHARASE_XDMC_XC_DASHEND = 5,
	CRI_CHARASE_XDMC_XC_KABEPETA = 6,
	CRI_CHARASE_XDMC_XC_KABEKERI = 7,
	CRI_CHARASE_XDMC_XC_TELEPORT_IN = 8,
	CRI_CHARASE_XDMC_XC_TELEPORT_OUT = 9,
	CRI_CHARASE_XDMC_XC_FOOT = 10
}
