public enum CharaSE_AbsoZERO
{
	NONE = 0,
	CRI_CHARASE_ABSOZERO_CUENUM = 10,
	CRI_CHARASE_ABSOZERO_ZB_JUMP = 1,
	CRI_CHARASE_ABSOZERO_ZB_JUMP_HIGH = 2,
	CRI_CHARASE_ABSOZERO_ZB_CHAKUCHI = 3,
	CRI_CHARASE_ABSOZERO_ZB_DASH = 4,
	CRI_CHARASE_ABSOZERO_ZB_DASHEND = 5,
	CRI_CHARASE_ABSOZERO_ZB_KABEPETA = 6,
	CRI_CHARASE_ABSOZERO_ZB_KABEKERI = 7,
	CRI_CHARASE_ABSOZERO_ZB_TELEPORT_IN = 8,
	CRI_CHARASE_ABSOZERO_ZB_TELEPORT_OUT = 9,
	CRI_CHARASE_ABSOZERO_ZB_FOOT = 10
}
