public static class CharaSE_X2ndArmori
{
	public const int iCRI_CHARASE_X2NDARMOR_CUENUM = 10;

	public const int iCRI_CHARASE_X2NDARMOR_X2_JUMP = 1;

	public const int iCRI_CHARASE_X2NDARMOR_X2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_X2NDARMOR_X2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_X2NDARMOR_X2_DASH = 4;

	public const int iCRI_CHARASE_X2NDARMOR_X2_DASHEND = 5;

	public const int iCRI_CHARASE_X2NDARMOR_X2_KABEPETA = 6;

	public const int iCRI_CHARASE_X2NDARMOR_X2_KABEKERI = 7;

	public const int iCRI_CHARASE_X2NDARMOR_X2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_X2NDARMOR_X2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_X2NDARMOR_X2_FOOT = 10;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_CUENUM = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_CUENUM;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_X2_JUMP = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_X2_JUMP;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_X2_JUMP_HIGH = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_X2_JUMP_HIGH;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_X2_CHAKUCHI = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_X2_CHAKUCHI;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_X2_DASH = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_X2_DASH;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_X2_DASHEND = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_X2_DASHEND;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_X2_KABEPETA = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_X2_KABEPETA;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_X2_KABEKERI = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_X2_KABEKERI;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_X2_TELEPORT_IN = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_X2_TELEPORT_IN;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_X2_TELEPORT_OUT = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_X2_TELEPORT_OUT;

	public const CharaSE_X2ndArmor CRI_CHARASE_X2NDARMOR_X2_FOOT = CharaSE_X2ndArmor.CRI_CHARASE_X2NDARMOR_CUENUM;
}
