public enum CharaSE_X1stArmor
{
	NONE = 0,
	CRI_CHARASE_X1STARMOR_CUENUM = 10,
	CRI_CHARASE_X1STARMOR_X1_JUMP = 1,
	CRI_CHARASE_X1STARMOR_X1_JUMP_HIGH = 2,
	CRI_CHARASE_X1STARMOR_X1_CHAKUCHI = 3,
	CRI_CHARASE_X1STARMOR_X1_DASH = 4,
	CRI_CHARASE_X1STARMOR_X1_DASHEND = 5,
	CRI_CHARASE_X1STARMOR_X1_KABEPETA = 6,
	CRI_CHARASE_X1STARMOR_X1_KABEKERI = 7,
	CRI_CHARASE_X1STARMOR_X1_TELEPORT_IN = 8,
	CRI_CHARASE_X1STARMOR_X1_TELEPORT_OUT = 9,
	CRI_CHARASE_X1STARMOR_X1_FOOT = 10
}
