public enum CharaSE_FORTEGS
{
	NONE = 0,
	CRI_CHARASE_FORTEGS_CUENUM = 10,
	CRI_CHARASE_FORTEGS_FG_JUMP = 1,
	CRI_CHARASE_FORTEGS_FG_JUMP_HIGH = 2,
	CRI_CHARASE_FORTEGS_FG_CHAKUCHI = 3,
	CRI_CHARASE_FORTEGS_FG_DASH = 4,
	CRI_CHARASE_FORTEGS_FG_DASHEND = 5,
	CRI_CHARASE_FORTEGS_FG_KABEPETA = 6,
	CRI_CHARASE_FORTEGS_FG_KABEKERI = 7,
	CRI_CHARASE_FORTEGS_FG_TELEPORT_IN = 8,
	CRI_CHARASE_FORTEGS_FG_TELEPORT_OUT = 9,
	CRI_CHARASE_FORTEGS_FG_FOOT = 10
}
