public static class CharaSE_RICO2i
{
	public const int iCRI_CHARASE_RICO2_CUENUM = 10;

	public const int iCRI_CHARASE_RICO2_RI2_JUMP = 1;

	public const int iCRI_CHARASE_RICO2_RI2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_RICO2_RI2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_RICO2_RI2_DASH = 4;

	public const int iCRI_CHARASE_RICO2_RI2_DASHEND = 5;

	public const int iCRI_CHARASE_RICO2_RI2_KABEPETA = 6;

	public const int iCRI_CHARASE_RICO2_RI2_KABEKERI = 7;

	public const int iCRI_CHARASE_RICO2_RI2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_RICO2_RI2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_RICO2_RI2_FOOT = 10;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_CUENUM = CharaSE_RICO2.CRI_CHARASE_RICO2_CUENUM;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_RI2_JUMP = CharaSE_RICO2.CRI_CHARASE_RICO2_RI2_JUMP;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_RI2_JUMP_HIGH = CharaSE_RICO2.CRI_CHARASE_RICO2_RI2_JUMP_HIGH;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_RI2_CHAKUCHI = CharaSE_RICO2.CRI_CHARASE_RICO2_RI2_CHAKUCHI;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_RI2_DASH = CharaSE_RICO2.CRI_CHARASE_RICO2_RI2_DASH;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_RI2_DASHEND = CharaSE_RICO2.CRI_CHARASE_RICO2_RI2_DASHEND;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_RI2_KABEPETA = CharaSE_RICO2.CRI_CHARASE_RICO2_RI2_KABEPETA;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_RI2_KABEKERI = CharaSE_RICO2.CRI_CHARASE_RICO2_RI2_KABEKERI;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_RI2_TELEPORT_IN = CharaSE_RICO2.CRI_CHARASE_RICO2_RI2_TELEPORT_IN;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_RI2_TELEPORT_OUT = CharaSE_RICO2.CRI_CHARASE_RICO2_RI2_TELEPORT_OUT;

	public const CharaSE_RICO2 CRI_CHARASE_RICO2_RI2_FOOT = CharaSE_RICO2.CRI_CHARASE_RICO2_CUENUM;
}
