public static class CharaSE_FORTEEXEi
{
	public const int iCRI_CHARASE_FORTEEXE_CUENUM = 10;

	public const int iCRI_CHARASE_FORTEEXE_FE_JUMP = 1;

	public const int iCRI_CHARASE_FORTEEXE_FE_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_FORTEEXE_FE_CHAKUCHI = 3;

	public const int iCRI_CHARASE_FORTEEXE_FE_DASH = 4;

	public const int iCRI_CHARASE_FORTEEXE_FE_DASHEND = 5;

	public const int iCRI_CHARASE_FORTEEXE_FE_KABEPETA = 6;

	public const int iCRI_CHARASE_FORTEEXE_FE_KABEKERI = 7;

	public const int iCRI_CHARASE_FORTEEXE_FE_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_FORTEEXE_FE_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_FORTEEXE_FE_FOOT = 10;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_CUENUM = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_CUENUM;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_FE_JUMP = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_FE_JUMP;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_FE_JUMP_HIGH = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_FE_JUMP_HIGH;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_FE_CHAKUCHI = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_FE_CHAKUCHI;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_FE_DASH = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_FE_DASH;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_FE_DASHEND = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_FE_DASHEND;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_FE_KABEPETA = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_FE_KABEPETA;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_FE_KABEKERI = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_FE_KABEKERI;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_FE_TELEPORT_IN = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_FE_TELEPORT_IN;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_FE_TELEPORT_OUT = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_FE_TELEPORT_OUT;

	public const CharaSE_FORTEEXE CRI_CHARASE_FORTEEXE_FE_FOOT = CharaSE_FORTEEXE.CRI_CHARASE_FORTEEXE_CUENUM;
}
