public static class CharaSE_UltimateXi
{
	public const int iCRI_CHARASE_ULTIMATEX_CUENUM = 10;

	public const int iCRI_CHARASE_ULTIMATEX_XU_JUMP = 1;

	public const int iCRI_CHARASE_ULTIMATEX_XU_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ULTIMATEX_XU_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ULTIMATEX_XU_DASH = 4;

	public const int iCRI_CHARASE_ULTIMATEX_XU_DASHEND = 5;

	public const int iCRI_CHARASE_ULTIMATEX_XU_KABEPETA = 6;

	public const int iCRI_CHARASE_ULTIMATEX_XU_KABEKERI = 7;

	public const int iCRI_CHARASE_ULTIMATEX_XU_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ULTIMATEX_XU_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ULTIMATEX_XU_FOOT = 10;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_CUENUM = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_CUENUM;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_XU_JUMP = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_XU_JUMP;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_XU_JUMP_HIGH = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_XU_JUMP_HIGH;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_XU_CHAKUCHI = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_XU_CHAKUCHI;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_XU_DASH = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_XU_DASH;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_XU_DASHEND = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_XU_DASHEND;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_XU_KABEPETA = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_XU_KABEPETA;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_XU_KABEKERI = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_XU_KABEKERI;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_XU_TELEPORT_IN = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_XU_TELEPORT_IN;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_XU_TELEPORT_OUT = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_XU_TELEPORT_OUT;

	public const CharaSE_UltimateX CRI_CHARASE_ULTIMATEX_XU_FOOT = CharaSE_UltimateX.CRI_CHARASE_ULTIMATEX_CUENUM;
}
