public static class CharaSE_BlackZEROi
{
	public const int iCRI_CHARASE_BLACKZERO_CUENUM = 10;

	public const int iCRI_CHARASE_BLACKZERO_ZU_JUMP = 1;

	public const int iCRI_CHARASE_BLACKZERO_ZU_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_BLACKZERO_ZU_CHAKUCHI = 3;

	public const int iCRI_CHARASE_BLACKZERO_ZU_DASH = 4;

	public const int iCRI_CHARASE_BLACKZERO_ZU_DASHEND = 5;

	public const int iCRI_CHARASE_BLACKZERO_ZU_KABEPETA = 6;

	public const int iCRI_CHARASE_BLACKZERO_ZU_KABEKERI = 7;

	public const int iCRI_CHARASE_BLACKZERO_ZU_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_BLACKZERO_ZU_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_BLACKZERO_ZU_FOOT = 10;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_CUENUM = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_CUENUM;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_ZU_JUMP = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_ZU_JUMP;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_ZU_JUMP_HIGH = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_ZU_JUMP_HIGH;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_ZU_CHAKUCHI = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_ZU_CHAKUCHI;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_ZU_DASH = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_ZU_DASH;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_ZU_DASHEND = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_ZU_DASHEND;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_ZU_KABEPETA = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_ZU_KABEPETA;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_ZU_KABEKERI = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_ZU_KABEKERI;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_ZU_TELEPORT_IN = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_ZU_TELEPORT_IN;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_ZU_TELEPORT_OUT = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_ZU_TELEPORT_OUT;

	public const CharaSE_BlackZERO CRI_CHARASE_BLACKZERO_ZU_FOOT = CharaSE_BlackZERO.CRI_CHARASE_BLACKZERO_CUENUM;
}
