public static class CharaSE_XDMCi
{
	public const int iCRI_CHARASE_XDMC_CUENUM = 10;

	public const int iCRI_CHARASE_XDMC_XC_JUMP = 1;

	public const int iCRI_CHARASE_XDMC_XC_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_XDMC_XC_CHAKUCHI = 3;

	public const int iCRI_CHARASE_XDMC_XC_DASH = 4;

	public const int iCRI_CHARASE_XDMC_XC_DASHEND = 5;

	public const int iCRI_CHARASE_XDMC_XC_KABEPETA = 6;

	public const int iCRI_CHARASE_XDMC_XC_KABEKERI = 7;

	public const int iCRI_CHARASE_XDMC_XC_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_XDMC_XC_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_XDMC_XC_FOOT = 10;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_CUENUM = CharaSE_XDMC.CRI_CHARASE_XDMC_CUENUM;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_XC_JUMP = CharaSE_XDMC.CRI_CHARASE_XDMC_XC_JUMP;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_XC_JUMP_HIGH = CharaSE_XDMC.CRI_CHARASE_XDMC_XC_JUMP_HIGH;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_XC_CHAKUCHI = CharaSE_XDMC.CRI_CHARASE_XDMC_XC_CHAKUCHI;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_XC_DASH = CharaSE_XDMC.CRI_CHARASE_XDMC_XC_DASH;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_XC_DASHEND = CharaSE_XDMC.CRI_CHARASE_XDMC_XC_DASHEND;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_XC_KABEPETA = CharaSE_XDMC.CRI_CHARASE_XDMC_XC_KABEPETA;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_XC_KABEKERI = CharaSE_XDMC.CRI_CHARASE_XDMC_XC_KABEKERI;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_XC_TELEPORT_IN = CharaSE_XDMC.CRI_CHARASE_XDMC_XC_TELEPORT_IN;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_XC_TELEPORT_OUT = CharaSE_XDMC.CRI_CHARASE_XDMC_XC_TELEPORT_OUT;

	public const CharaSE_XDMC CRI_CHARASE_XDMC_XC_FOOT = CharaSE_XDMC.CRI_CHARASE_XDMC_CUENUM;
}
