public enum CharaSE_RICO2
{
	NONE = 0,
	CRI_CHARASE_RICO2_CUENUM = 10,
	CRI_CHARASE_RICO2_RI2_JUMP = 1,
	CRI_CHARASE_RICO2_RI2_JUMP_HIGH = 2,
	CRI_CHARASE_RICO2_RI2_CHAKUCHI = 3,
	CRI_CHARASE_RICO2_RI2_DASH = 4,
	CRI_CHARASE_RICO2_RI2_DASHEND = 5,
	CRI_CHARASE_RICO2_RI2_KABEPETA = 6,
	CRI_CHARASE_RICO2_RI2_KABEKERI = 7,
	CRI_CHARASE_RICO2_RI2_TELEPORT_IN = 8,
	CRI_CHARASE_RICO2_RI2_TELEPORT_OUT = 9,
	CRI_CHARASE_RICO2_RI2_FOOT = 10
}
