public static class CharaSE_ZERONMi
{
	public const int iCRI_CHARASE_ZERONM_CUENUM = 10;

	public const int iCRI_CHARASE_ZERONM_ZN_JUMP = 1;

	public const int iCRI_CHARASE_ZERONM_ZN_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ZERONM_ZN_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ZERONM_ZN_DASH = 4;

	public const int iCRI_CHARASE_ZERONM_ZN_DASHEND = 5;

	public const int iCRI_CHARASE_ZERONM_ZN_KABEPETA = 6;

	public const int iCRI_CHARASE_ZERONM_ZN_KABEKERI = 7;

	public const int iCRI_CHARASE_ZERONM_ZN_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ZERONM_ZN_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ZERONM_ZN_FOOT = 10;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_CUENUM = CharaSE_ZERONM.CRI_CHARASE_ZERONM_CUENUM;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_ZN_JUMP = CharaSE_ZERONM.CRI_CHARASE_ZERONM_ZN_JUMP;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_ZN_JUMP_HIGH = CharaSE_ZERONM.CRI_CHARASE_ZERONM_ZN_JUMP_HIGH;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_ZN_CHAKUCHI = CharaSE_ZERONM.CRI_CHARASE_ZERONM_ZN_CHAKUCHI;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_ZN_DASH = CharaSE_ZERONM.CRI_CHARASE_ZERONM_ZN_DASH;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_ZN_DASHEND = CharaSE_ZERONM.CRI_CHARASE_ZERONM_ZN_DASHEND;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_ZN_KABEPETA = CharaSE_ZERONM.CRI_CHARASE_ZERONM_ZN_KABEPETA;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_ZN_KABEKERI = CharaSE_ZERONM.CRI_CHARASE_ZERONM_ZN_KABEKERI;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_ZN_TELEPORT_IN = CharaSE_ZERONM.CRI_CHARASE_ZERONM_ZN_TELEPORT_IN;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_ZN_TELEPORT_OUT = CharaSE_ZERONM.CRI_CHARASE_ZERONM_ZN_TELEPORT_OUT;

	public const CharaSE_ZERONM CRI_CHARASE_ZERONM_ZN_FOOT = CharaSE_ZERONM.CRI_CHARASE_ZERONM_CUENUM;
}
