public enum CharaSE_ROLLCAS
{
	NONE = 0,
	CRI_CHARASE_ROLLCAS_CUENUM = 10,
	CRI_CHARASE_ROLLCAS_RC_JUMP = 1,
	CRI_CHARASE_ROLLCAS_RC_JUMP_HIGH = 2,
	CRI_CHARASE_ROLLCAS_RC_CHAKUCHI = 3,
	CRI_CHARASE_ROLLCAS_RC_DASH = 4,
	CRI_CHARASE_ROLLCAS_RC_DASHEND = 5,
	CRI_CHARASE_ROLLCAS_RC_KABEPETA = 6,
	CRI_CHARASE_ROLLCAS_RC_KABEKERI = 7,
	CRI_CHARASE_ROLLCAS_RC_TELEPORT_IN = 8,
	CRI_CHARASE_ROLLCAS_RC_TELEPORT_OUT = 9,
	CRI_CHARASE_ROLLCAS_RC_FOOT = 10
}
