public enum CharaSE_IRIS4
{
	NONE = 0,
	CRI_CHARASE_IRIS4_CUENUM = 10,
	CRI_CHARASE_IRIS4_IR4_JUMP = 1,
	CRI_CHARASE_IRIS4_IR4_JUMP_HIGH = 2,
	CRI_CHARASE_IRIS4_IR4_CHAKUCHI = 3,
	CRI_CHARASE_IRIS4_IR4_DASH = 4,
	CRI_CHARASE_IRIS4_IR4_DASHEND = 5,
	CRI_CHARASE_IRIS4_IR4_KABEPETA = 6,
	CRI_CHARASE_IRIS4_IR4_KABEKERI = 7,
	CRI_CHARASE_IRIS4_IR4_TELEPORT_IN = 8,
	CRI_CHARASE_IRIS4_IR4_TELEPORT_OUT = 9,
	CRI_CHARASE_IRIS4_IR4_FOOT = 10
}
