public static class CharaSE_ROLLEXEi
{
	public const int iCRI_CHARASE_ROLLEXE_CUENUM = 10;

	public const int iCRI_CHARASE_ROLLEXE_RX_JUMP = 1;

	public const int iCRI_CHARASE_ROLLEXE_RX_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ROLLEXE_RX_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ROLLEXE_RX_DASH = 4;

	public const int iCRI_CHARASE_ROLLEXE_RX_DASHEND = 5;

	public const int iCRI_CHARASE_ROLLEXE_RX_KABEPETA = 6;

	public const int iCRI_CHARASE_ROLLEXE_RX_KABEKERI = 7;

	public const int iCRI_CHARASE_ROLLEXE_RX_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ROLLEXE_RX_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ROLLEXE_RX_FOOT = 10;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_CUENUM = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_CUENUM;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_RX_JUMP = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_RX_JUMP;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_RX_JUMP_HIGH = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_RX_JUMP_HIGH;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_RX_CHAKUCHI = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_RX_CHAKUCHI;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_RX_DASH = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_RX_DASH;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_RX_DASHEND = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_RX_DASHEND;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_RX_KABEPETA = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_RX_KABEPETA;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_RX_KABEKERI = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_RX_KABEKERI;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_RX_TELEPORT_IN = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_RX_TELEPORT_IN;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_RX_TELEPORT_OUT = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_RX_TELEPORT_OUT;

	public const CharaSE_ROLLEXE CRI_CHARASE_ROLLEXE_RX_FOOT = CharaSE_ROLLEXE.CRI_CHARASE_ROLLEXE_CUENUM;
}
