public enum CharaSE_ZEROMH
{
	NONE = 0,
	CRI_CHARASE_ZEROMH_CUENUM = 10,
	CRI_CHARASE_ZEROMH_ZM_JUMP = 1,
	CRI_CHARASE_ZEROMH_ZM_JUMP_HIGH = 2,
	CRI_CHARASE_ZEROMH_ZM_CHAKUCHI = 3,
	CRI_CHARASE_ZEROMH_ZM_DASH = 4,
	CRI_CHARASE_ZEROMH_ZM_DASHEND = 5,
	CRI_CHARASE_ZEROMH_ZM_KABEPETA = 6,
	CRI_CHARASE_ZEROMH_ZM_KABEKERI = 7,
	CRI_CHARASE_ZEROMH_ZM_TELEPORT_IN = 8,
	CRI_CHARASE_ZEROMH_ZM_TELEPORT_OUT = 9,
	CRI_CHARASE_ZEROMH_ZM_FOOT = 10
}
