public enum CharaSE_DRAGOON
{
	NONE = 0,
	CRI_CHARASE_DRAGOON_CUENUM = 10,
	CRI_CHARASE_DRAGOON_DG_JUMP = 1,
	CRI_CHARASE_DRAGOON_DG_JUMP_HIGH = 2,
	CRI_CHARASE_DRAGOON_DG_CHAKUCHI = 3,
	CRI_CHARASE_DRAGOON_DG_DASH = 4,
	CRI_CHARASE_DRAGOON_DG_DASHEND = 5,
	CRI_CHARASE_DRAGOON_DG_KABEPETA = 6,
	CRI_CHARASE_DRAGOON_DG_KABEKERI = 7,
	CRI_CHARASE_DRAGOON_DG_TELEPORT_IN = 8,
	CRI_CHARASE_DRAGOON_DG_TELEPORT_OUT = 9,
	CRI_CHARASE_DRAGOON_DG_FOOT = 10
}
