public static class CharaSE_ROLLCASi
{
	public const int iCRI_CHARASE_ROLLCAS_CUENUM = 10;

	public const int iCRI_CHARASE_ROLLCAS_RC_JUMP = 1;

	public const int iCRI_CHARASE_ROLLCAS_RC_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ROLLCAS_RC_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ROLLCAS_RC_DASH = 4;

	public const int iCRI_CHARASE_ROLLCAS_RC_DASHEND = 5;

	public const int iCRI_CHARASE_ROLLCAS_RC_KABEPETA = 6;

	public const int iCRI_CHARASE_ROLLCAS_RC_KABEKERI = 7;

	public const int iCRI_CHARASE_ROLLCAS_RC_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ROLLCAS_RC_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ROLLCAS_RC_FOOT = 10;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_CUENUM = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_CUENUM;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_RC_JUMP = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_RC_JUMP;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_RC_JUMP_HIGH = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_RC_JUMP_HIGH;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_RC_CHAKUCHI = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_RC_CHAKUCHI;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_RC_DASH = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_RC_DASH;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_RC_DASHEND = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_RC_DASHEND;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_RC_KABEPETA = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_RC_KABEPETA;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_RC_KABEKERI = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_RC_KABEKERI;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_RC_TELEPORT_IN = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_RC_TELEPORT_IN;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_RC_TELEPORT_OUT = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_RC_TELEPORT_OUT;

	public const CharaSE_ROLLCAS CRI_CHARASE_ROLLCAS_RC_FOOT = CharaSE_ROLLCAS.CRI_CHARASE_ROLLCAS_CUENUM;
}
