public static class CharaSE_ROCKMAN2i
{
	public const int iCRI_CHARASE_ROCKMAN2_CUENUM = 10;

	public const int iCRI_CHARASE_ROCKMAN2_RM2_JUMP = 1;

	public const int iCRI_CHARASE_ROCKMAN2_RM2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ROCKMAN2_RM2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ROCKMAN2_RM2_DASH = 4;

	public const int iCRI_CHARASE_ROCKMAN2_RM2_DASHEND = 5;

	public const int iCRI_CHARASE_ROCKMAN2_RM2_KABEPETA = 6;

	public const int iCRI_CHARASE_ROCKMAN2_RM2_KABEKERI = 7;

	public const int iCRI_CHARASE_ROCKMAN2_RM2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ROCKMAN2_RM2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ROCKMAN2_RM2_FOOT = 10;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_CUENUM = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_CUENUM;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_RM2_JUMP = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_RM2_JUMP;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_RM2_JUMP_HIGH = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_RM2_JUMP_HIGH;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_RM2_CHAKUCHI = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_RM2_CHAKUCHI;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_RM2_DASH = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_RM2_DASH;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_RM2_DASHEND = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_RM2_DASHEND;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_RM2_KABEPETA = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_RM2_KABEPETA;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_RM2_KABEKERI = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_RM2_KABEKERI;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_RM2_TELEPORT_IN = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_RM2_TELEPORT_IN;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_RM2_TELEPORT_OUT = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_RM2_TELEPORT_OUT;

	public const CharaSE_ROCKMAN2 CRI_CHARASE_ROCKMAN2_RM2_FOOT = CharaSE_ROCKMAN2.CRI_CHARASE_ROCKMAN2_CUENUM;
}
