public static class CharaSE_CIEL2i
{
	public const int iCRI_CHARASE_CIEL2_CUENUM = 10;

	public const int iCRI_CHARASE_CIEL2_CL2_JUMP = 1;

	public const int iCRI_CHARASE_CIEL2_CL2_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_CIEL2_CL2_CHAKUCHI = 3;

	public const int iCRI_CHARASE_CIEL2_CL2_DASH = 4;

	public const int iCRI_CHARASE_CIEL2_CL2_DASHEND = 5;

	public const int iCRI_CHARASE_CIEL2_CL2_KABEPETA = 6;

	public const int iCRI_CHARASE_CIEL2_CL2_KABEKERI = 7;

	public const int iCRI_CHARASE_CIEL2_CL2_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_CIEL2_CL2_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_CIEL2_CL2_FOOT = 10;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CUENUM = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CUENUM;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CL2_JUMP = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CL2_JUMP;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CL2_JUMP_HIGH = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CL2_JUMP_HIGH;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CL2_CHAKUCHI = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CL2_CHAKUCHI;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CL2_DASH = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CL2_DASH;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CL2_DASHEND = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CL2_DASHEND;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CL2_KABEPETA = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CL2_KABEPETA;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CL2_KABEKERI = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CL2_KABEKERI;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CL2_TELEPORT_IN = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CL2_TELEPORT_IN;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CL2_TELEPORT_OUT = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CL2_TELEPORT_OUT;

	public const CharaSE_CIEL2 CRI_CHARASE_CIEL2_CL2_FOOT = CharaSE_CIEL2.CRI_CHARASE_CIEL2_CUENUM;
}
