public enum CharaSE_CIEL3
{
	NONE = 0,
	CRI_CHARASE_CIEL3_CUENUM = 10,
	CRI_CHARASE_CIEL3_CL3_JUMP = 1,
	CRI_CHARASE_CIEL3_CL3_JUMP_HIGH = 2,
	CRI_CHARASE_CIEL3_CL3_CHAKUCHI = 3,
	CRI_CHARASE_CIEL3_CL3_DASH = 4,
	CRI_CHARASE_CIEL3_CL3_DASHEND = 5,
	CRI_CHARASE_CIEL3_CL3_KABEPETA = 6,
	CRI_CHARASE_CIEL3_CL3_KABEKERI = 7,
	CRI_CHARASE_CIEL3_CL3_TELEPORT_IN = 8,
	CRI_CHARASE_CIEL3_CL3_TELEPORT_OUT = 9,
	CRI_CHARASE_CIEL3_CL3_FOOT = 10
}
