public static class CharaSE_ZERODMCi
{
	public const int iCRI_CHARASE_ZERODMC_CUENUM = 10;

	public const int iCRI_CHARASE_ZERODMC_ZC_JUMP = 1;

	public const int iCRI_CHARASE_ZERODMC_ZC_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_ZERODMC_ZC_CHAKUCHI = 3;

	public const int iCRI_CHARASE_ZERODMC_ZC_DASH = 4;

	public const int iCRI_CHARASE_ZERODMC_ZC_DASHEND = 5;

	public const int iCRI_CHARASE_ZERODMC_ZC_KABEPETA = 6;

	public const int iCRI_CHARASE_ZERODMC_ZC_KABEKERI = 7;

	public const int iCRI_CHARASE_ZERODMC_ZC_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_ZERODMC_ZC_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_ZERODMC_ZC_FOOT = 10;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_CUENUM = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_CUENUM;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_ZC_JUMP = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_ZC_JUMP;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_ZC_JUMP_HIGH = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_ZC_JUMP_HIGH;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_ZC_CHAKUCHI = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_ZC_CHAKUCHI;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_ZC_DASH = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_ZC_DASH;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_ZC_DASHEND = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_ZC_DASHEND;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_ZC_KABEPETA = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_ZC_KABEPETA;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_ZC_KABEKERI = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_ZC_KABEKERI;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_ZC_TELEPORT_IN = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_ZC_TELEPORT_IN;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_ZC_TELEPORT_OUT = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_ZC_TELEPORT_OUT;

	public const CharaSE_ZERODMC CRI_CHARASE_ZERODMC_ZC_FOOT = CharaSE_ZERODMC.CRI_CHARASE_ZERODMC_CUENUM;
}
