public static class CharaSE_RICOi
{
	public const int iCRI_CHARASE_RICO_CUENUM = 10;

	public const int iCRI_CHARASE_RICO_RI_JUMP = 1;

	public const int iCRI_CHARASE_RICO_RI_JUMP_HIGH = 2;

	public const int iCRI_CHARASE_RICO_RI_CHAKUCHI = 3;

	public const int iCRI_CHARASE_RICO_RI_DASH = 4;

	public const int iCRI_CHARASE_RICO_RI_DASHEND = 5;

	public const int iCRI_CHARASE_RICO_RI_KABEPETA = 6;

	public const int iCRI_CHARASE_RICO_RI_KABEKERI = 7;

	public const int iCRI_CHARASE_RICO_RI_TELEPORT_IN = 8;

	public const int iCRI_CHARASE_RICO_RI_TELEPORT_OUT = 9;

	public const int iCRI_CHARASE_RICO_RI_FOOT = 10;

	public const CharaSE_RICO CRI_CHARASE_RICO_CUENUM = CharaSE_RICO.CRI_CHARASE_RICO_CUENUM;

	public const CharaSE_RICO CRI_CHARASE_RICO_RI_JUMP = CharaSE_RICO.CRI_CHARASE_RICO_RI_JUMP;

	public const CharaSE_RICO CRI_CHARASE_RICO_RI_JUMP_HIGH = CharaSE_RICO.CRI_CHARASE_RICO_RI_JUMP_HIGH;

	public const CharaSE_RICO CRI_CHARASE_RICO_RI_CHAKUCHI = CharaSE_RICO.CRI_CHARASE_RICO_RI_CHAKUCHI;

	public const CharaSE_RICO CRI_CHARASE_RICO_RI_DASH = CharaSE_RICO.CRI_CHARASE_RICO_RI_DASH;

	public const CharaSE_RICO CRI_CHARASE_RICO_RI_DASHEND = CharaSE_RICO.CRI_CHARASE_RICO_RI_DASHEND;

	public const CharaSE_RICO CRI_CHARASE_RICO_RI_KABEPETA = CharaSE_RICO.CRI_CHARASE_RICO_RI_KABEPETA;

	public const CharaSE_RICO CRI_CHARASE_RICO_RI_KABEKERI = CharaSE_RICO.CRI_CHARASE_RICO_RI_KABEKERI;

	public const CharaSE_RICO CRI_CHARASE_RICO_RI_TELEPORT_IN = CharaSE_RICO.CRI_CHARASE_RICO_RI_TELEPORT_IN;

	public const CharaSE_RICO CRI_CHARASE_RICO_RI_TELEPORT_OUT = CharaSE_RICO.CRI_CHARASE_RICO_RI_TELEPORT_OUT;

	public const CharaSE_RICO CRI_CHARASE_RICO_RI_FOOT = CharaSE_RICO.CRI_CHARASE_RICO_CUENUM;
}
