public enum CharaSE_KARNEL
{
	NONE = 0,
	CRI_CHARASE_KARNEL_CUENUM = 10,
	CRI_CHARASE_KARNEL_KN_JUMP = 1,
	CRI_CHARASE_KARNEL_KN_JUMP_HIGH = 2,
	CRI_CHARASE_KARNEL_KN_CHAKUCHI = 3,
	CRI_CHARASE_KARNEL_KN_DASH = 4,
	CRI_CHARASE_KARNEL_KN_DASHEND = 5,
	CRI_CHARASE_KARNEL_KN_KABEPETA = 6,
	CRI_CHARASE_KARNEL_KN_KABEKERI = 7,
	CRI_CHARASE_KARNEL_KN_TELEPORT_IN = 8,
	CRI_CHARASE_KARNEL_KN_TELEPORT_OUT = 9,
	CRI_CHARASE_KARNEL_KN_FOOT = 10
}
