using System;

public class CharacterControlFactory
{
	public static Type GetCharacterControlType(EControlCharacter character, int subID)
	{
		switch (character)
		{
		case EControlCharacter.X:
			if (subID == 1)
			{
				return typeof(CH001_001_Controller);
			}
			return typeof(RMXController);
		case EControlCharacter.ZERO:
			return typeof(ZeroController);
		case EControlCharacter.ALIA:
			return typeof(AliaController);
		case EControlCharacter.BLACK_ZERO:
			return typeof(BlackZeroController);
		case EControlCharacter.MASSIMO:
			return typeof(MassimoController);
		case EControlCharacter.AXL:
			return typeof(AxlController);
		case EControlCharacter.FERHAM:
			return typeof(FerhamController);
		case EControlCharacter.ULTIMATE_ARMOR_X:
			return typeof(UltimateXController);
		case EControlCharacter.SECOND_ARMOR_X:
			return typeof(SecondArmorController);
		case EControlCharacter.VILE:
			return typeof(VavaController);
		case EControlCharacter.CINNAMON:
			return typeof(CinnamonController);
		case EControlCharacter.MARINO:
			return typeof(MarinoController);
		case EControlCharacter.PALLETTE:
			return typeof(PaletteController);
		case EControlCharacter.FIRST_ARMOR_X:
			return typeof(FirstArmorController);
		case EControlCharacter.WHITEDAY_ALIA:
			return typeof(AliaLoverController);
		case EControlCharacter.WHITEDAY_CINNAMON:
			return typeof(CinnamonLoverController);
		case EControlCharacter.ULTIMATE_ARMOR_X_CM:
			return typeof(CMUltimateXController);
		case EControlCharacter.LAYER:
			return typeof(LayerController);
		case EControlCharacter.ROCKMAN:
			return typeof(RockmanController);
		case EControlCharacter.BLUES:
			return typeof(BluesController);
		case EControlCharacter.SUPER_ROCKMAN:
			return typeof(SuperRockmanController);
		case EControlCharacter.ROLL:
			return typeof(RollController);
		case EControlCharacter.IRIS:
			return typeof(IrisController);
		case EControlCharacter.ZERO_Z:
			return typeof(RMZ_ZeroController);
		case EControlCharacter.LEVIATHAN:
			return typeof(LeviathanController);
		case EControlCharacter.AWAKENED_ZERO:
			return typeof(AwakenZeroController);
		case EControlCharacter.SIGMA:
			return typeof(SigmaX1Controller);
		case EControlCharacter.SWIMSUIT_LAYER:
			return typeof(CH041_Controller);
		case EControlCharacter.SWIMSUIT_ROLL:
			return typeof(CH040_Controller);
		case EControlCharacter.SWIMSUIT_IRIS:
			return typeof(CH042_Controller);
		case EControlCharacter.CIEL:
			return typeof(CH031_Controller);
		case EControlCharacter.AILE:
			return typeof(CH033_Controller);
		case EControlCharacter.PANDORA:
			return typeof(CH032_Controller);
		case EControlCharacter.MATSURI_ZERO:
			return typeof(CH044_Controller);
		case EControlCharacter.ROCK_VOLNUTT:
			return typeof(CH036_Controller);
		case EControlCharacter.TRON:
			return typeof(CH037_Controller);
		case EControlCharacter.THIRD_ARMOR_X:
			return typeof(CH043_Controller);
		case EControlCharacter.VAVA_HALLOWEEN:
			return typeof(CH047_Controller);
		case EControlCharacter.MARINO_HALLOWEEN:
			return typeof(CH045_Controller);
		case EControlCharacter.AILE_HALLOWEEN:
			return typeof(CH046_Controller);
		case EControlCharacter.COPY_X:
			return typeof(CH035_Controller);
		case EControlCharacter.OMEGA_ZERO:
			return typeof(CH034_Controller);
		case EControlCharacter.ROCKMAN_EXE:
			return typeof(CH049_Controller);
		case EControlCharacter.BLUES_EXE:
			return typeof(CH050_Controller);
		case EControlCharacter.FORTE_EXE:
			return typeof(CH051_Controller);
		case EControlCharacter.LEVIATHAN_XMAS:
			return typeof(CH053_Controller);
		case EControlCharacter.VAJURILA_FF:
			return typeof(CH052_Controller);
		case EControlCharacter.CINNAMON_NEWYEAR:
			return typeof(CH054_Controller);
		case EControlCharacter.SIGMA_X4_SECOND:
			return typeof(CH048_Controller);
		case EControlCharacter.MAGMA_DRAGOON:
			return typeof(CH055_Controller);
		case EControlCharacter.ABSOLUTE_ZERO:
			return typeof(CH019_Controller);
		case EControlCharacter.IRIS_VALENTINE:
			return typeof(CH058_Controller);
		case EControlCharacter.CIEL_VALENTINE:
			return typeof(CH057_Controller);
		case EControlCharacter.FORTE_GS:
			return typeof(CH059_Controller);
		case EControlCharacter.SAGE_HARPUIA:
			return typeof(CH060_Controller);
		case EControlCharacter.AXL_VALENTINE:
			return typeof(CH061_Controller);
		case EControlCharacter.RiCO:
			return typeof(CH039_Controller);
		case EControlCharacter.X_FIRE:
			return typeof(CH071_Controller);
		case EControlCharacter.ROCK_VOLNUTT_DARK:
			return typeof(CH064_Controller);
		case EControlCharacter.SERVBOT:
			return typeof(CH066_Controller);
		case EControlCharacter.ROLL_DASH:
			return typeof(CH065_Controller);
		case EControlCharacter.X_FALCOM_ARMOR:
			return typeof(CH067_Controller);
		case EControlCharacter.COLONEL:
			return typeof(CH070_Controller);
		case EControlCharacter.IRIS_ANOTHER:
			return typeof(CH069_Controller);
		case EControlCharacter.FORTE:
			return typeof(CH021_Controller);
		case EControlCharacter.ROCKMAN_TB:
			return typeof(CH072_Controller);
		case EControlCharacter.VAVA_MK2:
			return typeof(CH068_Controller);
		case EControlCharacter.ZERO_NIGHTMARE:
			return typeof(CH073_Controller);
		case EControlCharacter.ALIA_BRIDE:
			return typeof(CH075_Controller);
		case EControlCharacter.LAYER_BRIDE:
			return typeof(CH076_Controller);
		case EControlCharacter.MHR_MALE_HUNTER:
			return typeof(CH092_Controller);
		case EControlCharacter.MHR_FEMALE_HUNTER:
			return typeof(CH091_Controller);
		case EControlCharacter.X_REUS_ARMOR:
		case EControlCharacter.NPC_X_REUS_ARMOR:
			return typeof(CH093_Controller);
		case EControlCharacter.ROCKMAN_DARK:
			return typeof(CH086_Controller);
		case EControlCharacter.SWIMSUIT_FERHAM:
			return typeof(CH088_Controller);
		case EControlCharacter.SWIMSUIT_PALLETTE:
			return typeof(CH089_Controller);
		case EControlCharacter.SWIMSUIT_TRON:
			return typeof(CH090_Controller);
		case EControlCharacter.SUPER_FORTE:
			return typeof(CH087_Controller);
		case EControlCharacter.X_KAI:
			return typeof(CH074_Controller);
		case EControlCharacter.LEVIATHAN_MATSURI:
			return typeof(CH094_Controller);
		case EControlCharacter.DIVE_ARMOR_X:
			return typeof(CH062_Controller);
		case EControlCharacter.ROCKMAN_STARFORCE:
			return typeof(CH081_Controller);
		case EControlCharacter.HARP_NOTE:
			return typeof(CH082_Controller);
		case EControlCharacter.ROGUE:
			return typeof(CH083_Controller);
		case EControlCharacter.SFV_RYU:
			return typeof(CH098_Controller);
		case EControlCharacter.SFV_CHUN_LI:
			return typeof(CH099_Controller);
		case EControlCharacter.SFV_AKUMA:
			return typeof(CH100_Controller);
		case EControlCharacter.iCO:
			return typeof(CH063_Controller);
		case EControlCharacter.SIGMA_HALLOWEEN:
			return typeof(CH095_Controller);
		case EControlCharacter.ROLL_HALLOWEEN:
			return typeof(CH096_Controller);
		case EControlCharacter.PANDORA_HALLOWEEN:
			return typeof(CH097_Controller);
		case EControlCharacter.DYNAMO:
			return typeof(CH084_Controller);
		case EControlCharacter.FORTE_XX:
			return typeof(CH101_Controller);
		case EControlCharacter.ROCKMAN_EXE_HUB_STYLE:
			return typeof(CH079_Controller);
		case EControlCharacter.ROLL_EXE:
			return typeof(CH080_Controller);
		case EControlCharacter.RICO_XMAS:
			return typeof(CH103_Controller);
		case EControlCharacter.CIEL_XMAS:
			return typeof(CH102_Controller);
		case EControlCharacter.IRIS_NEWYEAR:
			return typeof(CH104_Controller);
		case EControlCharacter.X_FORCE_ARMOR:
			return typeof(CH077_Controller);
		case EControlCharacter.DROITCLAIR:
			return typeof(CH105_Controller);
		case EControlCharacter.ZERO_HUNTER:
			return typeof(CH106_Controller);
		case EControlCharacter.IRIS_HUNTER:
			return typeof(CH107_Controller);
		case EControlCharacter.RiCO_VALENTINE:
			return typeof(CH108_Controller);
		case EControlCharacter.iCO_VALENTINE:
			return typeof(CH109_Controller);
		case EControlCharacter.ANJUPITOR:
			return typeof(CH110_Controller);
		case EControlCharacter.GATE:
			return typeof(CH085_Controller);
		case EControlCharacter.TRON_LAB_COAT:
			return typeof(CH111_Controller);
		case EControlCharacter.ViA:
			return typeof(CH113_Controller);
		case EControlCharacter.DIVE_RICO:
			return typeof(CH115_Controller);
		case EControlCharacter.X_GAEA_ARMOR:
			return typeof(CH078_Controller);
		case EControlCharacter.ROLL_EASTER:
			return typeof(CH116_Controller);
		case EControlCharacter.ERATOEIR:
			return typeof(CH112_Controller);
		case EControlCharacter.NANA:
			return typeof(CH022_Controller);
		case EControlCharacter.ZERO_Q:
			return typeof(CH117_Controller);
		case EControlCharacter.SECOND_ARMOR_X_Q:
			return typeof(CH118_Controller);
		case EControlCharacter.LIGHT_MARTIALIST:
			return typeof(CH119_Controller);
		case EControlCharacter.FORTE_CROSS_ROCKMAN:
			return typeof(CH120_Controller);
		case EControlCharacter.iCO_SWIMSUIT:
			return typeof(CH121_Controller);
		case EControlCharacter.CIEL_SWIMSUIT:
			return typeof(CH122_Controller);
		case EControlCharacter.DIVE_ARMOR_ZERO:
			return typeof(CH123_Controller);
		case EControlCharacter.AILE_ZX:
			return typeof(CH124_Controller);
		case EControlCharacter.DIVE_ARMOR_AXL:
			return typeof(CH125_Controller);
		case EControlCharacter.SIGMA_TAICHO:
			return typeof(CH126_Controller);
		case EControlCharacter.ERATOEIR_DOKUZON:
			return typeof(CH127_Controller);
		case EControlCharacter.X_SHADOW_ARMOR:
			return typeof(CH131_Controller);
		case EControlCharacter.DIVE_ARMOR_ROCKMAN_EXE:
			return typeof(CH128_Controller);
		case EControlCharacter.MHRSB_X:
			return typeof(CH129_Controller);
		case EControlCharacter.MHRSB_iCO:
			return typeof(CH130_Controller);
		case EControlCharacter.ViA_HALLOWEEN:
			return typeof(CH132_Controller);
		case EControlCharacter.ZERO_HALLOWEEN:
			return typeof(CH133_Controller);
		case EControlCharacter.FORTE_AND_GOSPEL:
			return typeof(CH134_Controller);
		case EControlCharacter.iCO_XMAS:
			return typeof(CH135_Controller);
		case EControlCharacter.X_S:
			return typeof(CH143_Controller);
		case EControlCharacter.RiCO_DIVE_ARMOR:
			return typeof(CH136_Controller);
		case EControlCharacter.IRIS_DIVE_ARMOR:
			return typeof(CH137_Controller);
		case EControlCharacter.VIA_QED:
			return typeof(CH138_Controller);
		case EControlCharacter.Z_S:
			return typeof(CH144_Controller);
		case EControlCharacter.iCO_DIVE_ARMOR:
			return typeof(CH139_Controller);
		case EControlCharacter.X_DMC:
			return typeof(CH140_Controller);
		case EControlCharacter.Z_DMC:
			return typeof(CH141_Controller);
		case EControlCharacter.X__DIVE_ARMOR_SP:
			return typeof(CH142_Controller);
		case EControlCharacter.NPC_Y:
			return typeof(ZeroController);
		case EControlCharacter.NPC_Y_BROKEN:
			return typeof(ZeroController);
		default:
			throw new Exception("未定義的Player類型:" + (int)character);
		}
	}
}
