public static class NAVI_MENUi
{
	public const int iCRI_NAVI_MENU_CUENUM = 30;

	public const int iCRI_NAVI_MENU_RICO_TITLE01 = 1;

	public const int iCRI_NAVI_MENU_RICO_MENU01 = 5;

	public const int iCRI_NAVI_MENU_RICO_MENU02 = 6;

	public const int iCRI_NAVI_MENU_RICO_MENU09 = 13;

	public const int iCRI_NAVI_MENU_RICO_MENU14 = 18;

	public const int iCRI_NAVI_MENU_RICO_MENU13 = 17;

	public const int iCRI_NAVI_MENU_RICO_MENU15 = 19;

	public const int iCRI_NAVI_MENU_RICO_MENU17 = 21;

	public const int iCRI_NAVI_MENU_RICO_MENU16 = 20;

	public const int iCRI_NAVI_MENU_RICO_MENU18 = 22;

	public const int iCRI_NAVI_MENU_RICO_MENU19 = 23;

	public const int iCRI_NAVI_MENU_RICO_MENU20 = 24;

	public const int iCRI_NAVI_MENU_RICO_MENU21 = 25;

	public const int iCRI_NAVI_MENU_RICO_MENU22 = 26;

	public const int iCRI_NAVI_MENU_RICO_MENU23 = 27;

	public const int iCRI_NAVI_MENU_RICO_MENU24 = 28;

	public const int iCRI_NAVI_MENU_RICO_MENU44 = 48;

	public const int iCRI_NAVI_MENU_RICO_MENU26 = 30;

	public const int iCRI_NAVI_MENU_RICO_MENU27 = 31;

	public const int iCRI_NAVI_MENU_RICO_MENU28 = 32;

	public const int iCRI_NAVI_MENU_RICO_MENU29 = 33;

	public const int iCRI_NAVI_MENU_RICO_MENU35 = 39;

	public const int iCRI_NAVI_MENU_RICO_MENU38 = 42;

	public const int iCRI_NAVI_MENU_RICO_MENU39 = 43;

	public const int iCRI_NAVI_MENU_RICO_MENU40 = 44;

	public const int iCRI_NAVI_MENU_RICO_MENU42 = 46;

	public const int iCRI_NAVI_MENU_RICO_MENU43 = 47;

	public const int iCRI_NAVI_MENU_RICO_MENU05 = 9;

	public const int iCRI_NAVI_MENU_RICO_MENU12 = 16;

	public const int iCRI_NAVI_MENU_RICO_MENU04 = 8;

	public const NAVI_MENU CRI_NAVI_MENU_CUENUM = NAVI_MENU.CRI_NAVI_MENU_CUENUM;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_TITLE01 = NAVI_MENU.CRI_NAVI_MENU_RICO_TITLE01;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU01 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU01;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU02 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU02;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU09 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU09;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU14 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU14;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU13 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU13;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU15 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU15;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU17 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU17;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU16 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU16;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU18 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU18;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU19 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU19;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU20 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU20;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU21 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU21;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU22 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU22;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU23 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU23;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU24 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU24;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU44 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU44;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU26 = NAVI_MENU.CRI_NAVI_MENU_CUENUM;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU27 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU27;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU28 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU28;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU29 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU29;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU35 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU35;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU38 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU38;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU39 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU39;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU40 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU40;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU42 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU42;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU43 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU43;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU05 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU05;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU12 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU12;

	public const NAVI_MENU CRI_NAVI_MENU_RICO_MENU04 = NAVI_MENU.CRI_NAVI_MENU_RICO_MENU04;
}
