public static class NAVI_TEXTi
{
	public const int iCRI_NAVI_TEXT_CUENUM = 100;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI01 = 1;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI02 = 2;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI03 = 3;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI04 = 4;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI05 = 5;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI06 = 6;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI07 = 7;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI08 = 8;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI09 = 9;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI10 = 10;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI11 = 11;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI12 = 12;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI13 = 13;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI14 = 14;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI18 = 18;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI19 = 19;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI20 = 20;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI21 = 21;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI22 = 22;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI23 = 23;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI24 = 24;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI25 = 25;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI26 = 26;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI27 = 27;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI30 = 30;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI31 = 31;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI32 = 32;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI33 = 33;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI34 = 34;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI35 = 35;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI36 = 36;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI37 = 37;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI38 = 38;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI39 = 39;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI40 = 40;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI41 = 41;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI42 = 42;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI44 = 44;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI45 = 45;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI46 = 46;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI47 = 47;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI48 = 48;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI49 = 49;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI50 = 50;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI51 = 51;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI52 = 52;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI53 = 53;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI54 = 54;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI55 = 55;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI56 = 56;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI57 = 57;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI58 = 58;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI59 = 59;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI60 = 60;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI61 = 61;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI62 = 62;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI63 = 63;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI64 = 64;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI65 = 65;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI66 = 66;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI67 = 67;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI68 = 68;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI69 = 69;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI70 = 70;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI71 = 71;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI72 = 72;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI73 = 73;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI74 = 74;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI75 = 75;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI76 = 76;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI77 = 77;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI78 = 78;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI79 = 79;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI80 = 80;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI81 = 81;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI82 = 82;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI83 = 83;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI84 = 84;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI85 = 85;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI86 = 86;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI87 = 87;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI88 = 88;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI89 = 89;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI90 = 90;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI91 = 91;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI92 = 92;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI93 = 93;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI94 = 94;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI96 = 96;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI95 = 95;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI97 = 97;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI98 = 98;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI99 = 99;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI43 = 43;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI100 = 100;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI101 = 101;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI102 = 102;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI103 = 103;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI104 = 104;

	public const int iCRI_NAVI_TEXT_RICO_TUTORI105 = 105;

	public const NAVI_TEXT CRI_NAVI_TEXT_CUENUM = NAVI_TEXT.CRI_NAVI_TEXT_CUENUM;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI01 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI01;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI02 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI02;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI03 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI03;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI04 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI04;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI05 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI05;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI06 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI06;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI07 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI07;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI08 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI08;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI09 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI09;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI10 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI10;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI11 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI11;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI12 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI12;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI13 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI13;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI14 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI14;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI18 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI18;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI19 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI19;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI20 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI20;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI21 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI21;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI22 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI22;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI23 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI23;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI24 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI24;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI25 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI25;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI26 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI26;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI27 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI27;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI30 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI30;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI31 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI31;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI32 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI32;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI33 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI33;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI34 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI34;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI35 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI35;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI36 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI36;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI37 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI37;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI38 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI38;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI39 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI39;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI40 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI40;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI41 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI41;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI42 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI42;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI44 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI44;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI45 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI45;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI46 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI46;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI47 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI47;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI48 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI48;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI49 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI49;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI50 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI50;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI51 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI51;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI52 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI52;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI53 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI53;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI54 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI54;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI55 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI55;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI56 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI56;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI57 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI57;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI58 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI58;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI59 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI59;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI60 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI60;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI61 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI61;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI62 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI62;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI63 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI63;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI64 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI64;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI65 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI65;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI66 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI66;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI67 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI67;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI68 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI68;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI69 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI69;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI70 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI70;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI71 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI71;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI72 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI72;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI73 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI73;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI74 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI74;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI75 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI75;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI76 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI76;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI77 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI77;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI78 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI78;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI79 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI79;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI80 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI80;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI81 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI81;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI82 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI82;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI83 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI83;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI84 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI84;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI85 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI85;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI86 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI86;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI87 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI87;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI88 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI88;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI89 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI89;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI90 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI90;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI91 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI91;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI92 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI92;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI93 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI93;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI94 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI94;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI96 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI96;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI95 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI95;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI97 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI97;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI98 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI98;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI99 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI99;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI43 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI43;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI100 = NAVI_TEXT.CRI_NAVI_TEXT_CUENUM;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI101 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI101;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI102 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI102;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI103 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI103;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI104 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI104;

	public const NAVI_TEXT CRI_NAVI_TEXT_RICO_TUTORI105 = NAVI_TEXT.CRI_NAVI_TEXT_RICO_TUTORI105;
}
