public enum RuntimeSyncInputData : short
{
	RUNTIME_BUTTON_STATUS = 1,
	RUNTIME_PRESSTIMER = 8,
	RUNTIME_ANALOGSTICK_VALUE = 0x10,
	RUNTIME_ANALOGSTICK_VALUE_PREV = 0x20,
	RUNTIME_TOUCHCHAIN_COUNT = 0x40,
	RUNTIME_SHOOT_DIR = 0x80,
	RUNTIME_UPDATE_POS = 0x100,
	RUNTIME_LOCK_INPUT = 0x200,
	RUNTIME_RECORD_NO = 0x400,
	RUNTIME_OCSYNCDATA = 0x800
}
