public static class SkillSE_CIEL2i
{
	public const int iCRI_SKILLSE_CIEL2_CUENUM = 19;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELF01_LP = 1;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELFT03 = 15;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELFT02_STOP = 14;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELFT02_LP = 13;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELFT01 = 12;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELFX03 = 20;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELFX02_STOP = 19;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELFX02_LP = 18;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELFX01 = 17;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELF01_STOP = 2;

	public const int iCRI_SKILLSE_CIEL2_CL2_ELF02 = 3;

	public const int iCRI_SKILLSE_CIEL2_CL2_SYSTEM01 = 4;

	public const int iCRI_SKILLSE_CIEL2_CL2_SYSTEM02_LP = 5;

	public const int iCRI_SKILLSE_CIEL2_CL2_SYSTEM02_STOP = 6;

	public const int iCRI_SKILLSE_CIEL2_CL2_CHOCO01 = 7;

	public const int iCRI_SKILLSE_CIEL2_CL2_CHARA01 = 40;

	public const int iCRI_SKILLSE_CIEL2_CL2_CHARA02 = 41;

	public const int iCRI_SKILLSE_CIEL2_CL2_START02 = 81;

	public const int iCRI_SKILLSE_CIEL2_CL2_START01 = 80;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CUENUM = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CUENUM;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELF01_LP = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_ELF01_LP;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELFT03 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_ELFT03;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELFT02_STOP = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_ELFT02_STOP;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELFT02_LP = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_ELFT02_LP;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELFT01 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_ELFT01;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELFX03 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_ELFX03;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELFX02_STOP = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CUENUM;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELFX02_LP = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_ELFX02_LP;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELFX01 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_ELFX01;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELF01_STOP = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_ELF01_STOP;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_ELF02 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_ELF02;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_SYSTEM01 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_SYSTEM01;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_SYSTEM02_LP = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_SYSTEM02_LP;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_SYSTEM02_STOP = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_SYSTEM02_STOP;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_CHOCO01 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_CHOCO01;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_CHARA01 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_CHARA01;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_CHARA02 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_CHARA02;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_START02 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_START02;

	public const SkillSE_CIEL2 CRI_SKILLSE_CIEL2_CL2_START01 = SkillSE_CIEL2.CRI_SKILLSE_CIEL2_CL2_START01;
}
