public enum SkillSE_XGaia
{
	NONE = 0,
	CRI_SKILLSE_XGAIA_CUENUM = 8,
	CRI_SKILLSE_XGAIA_XG_CHARGESHOT_S = 3,
	CRI_SKILLSE_XGAIA_XG_CHARGESHOT_M = 4,
	CRI_SKILLSE_XGAIA_XG_CHARGESHOT_L = 5,
	CRI_SKILLSE_XGAIA_XG_CHARGE_LP = 1,
	CRI_SKILLSE_XGAIA_XG_CHARGE_STOP = 2,
	CRI_SKILLSE_XGAIA_XG_CHARGEMAX = 6,
	CRI_SKILLSE_XGAIA_XG_GIGA01 = 8,
	CRI_SKILLSE_XGAIA_XG_CHARA01 = 40
}
