public static class SkillSE_IRIS2i
{
	public const int iCRI_SKILLSE_IRIS2_CUENUM = 5;

	public const int iCRI_SKILLSE_IRIS2_IR2_ZINRAISEN01 = 1;

	public const int iCRI_SKILLSE_IRIS2_IR2_ZINRAISEN02 = 2;

	public const int iCRI_SKILLSE_IRIS2_IR2_HANGEKI01 = 4;

	public const int iCRI_SKILLSE_IRIS2_IR2_HANGEKI02 = 5;

	public const int iCRI_SKILLSE_IRIS2_IR2_CHARA01 = 40;

	public const SkillSE_IRIS2 CRI_SKILLSE_IRIS2_CUENUM = SkillSE_IRIS2.CRI_SKILLSE_IRIS2_CUENUM;

	public const SkillSE_IRIS2 CRI_SKILLSE_IRIS2_IR2_ZINRAISEN01 = SkillSE_IRIS2.CRI_SKILLSE_IRIS2_IR2_ZINRAISEN01;

	public const SkillSE_IRIS2 CRI_SKILLSE_IRIS2_IR2_ZINRAISEN02 = SkillSE_IRIS2.CRI_SKILLSE_IRIS2_IR2_ZINRAISEN02;

	public const SkillSE_IRIS2 CRI_SKILLSE_IRIS2_IR2_HANGEKI01 = SkillSE_IRIS2.CRI_SKILLSE_IRIS2_IR2_HANGEKI01;

	public const SkillSE_IRIS2 CRI_SKILLSE_IRIS2_IR2_HANGEKI02 = SkillSE_IRIS2.CRI_SKILLSE_IRIS2_CUENUM;

	public const SkillSE_IRIS2 CRI_SKILLSE_IRIS2_IR2_CHARA01 = SkillSE_IRIS2.CRI_SKILLSE_IRIS2_IR2_CHARA01;
}
