public static class SkillSE_IRISi
{
	public const int iCRI_SKILLSE_IRIS_CUENUM = 16;

	public const int iCRI_SKILLSE_IRIS_IR_CHARA01 = 8;

	public const int iCRI_SKILLSE_IRIS_IR_FUYU01 = 1;

	public const int iCRI_SKILLSE_IRIS_IR_KATSUBOU = 3;

	public const int iCRI_SKILLSE_IRIS_IR_FUYU02 = 2;

	public const int iCRI_SKILLSE_IRIS_IR_HEARTBEAM = 4;

	public const int iCRI_SKILLSE_IRIS_IR_VTGIFT01 = 5;

	public const int iCRI_SKILLSE_IRIS_IR_VTGIFT02_LG = 6;

	public const int iCRI_SKILLSE_IRIS_IR_VTGIFT02_STOP = 7;

	public const int iCRI_SKILLSE_IRIS_IR_CHARA02 = 40;

	public const int iCRI_SKILLSE_IRIS_IR_START01 = 80;

	public const int iCRI_SKILLSE_IRIS_IR_CHARA03 = 41;

	public const int iCRI_SKILLSE_IRIS_IR_START03 = 82;

	public const int iCRI_SKILLSE_IRIS_IR_HAMAYA01 = 9;

	public const int iCRI_SKILLSE_IRIS_IR_HAMAYA02 = 10;

	public const int iCRI_SKILLSE_IRIS_IR_HINODE01 = 12;

	public const int iCRI_SKILLSE_IRIS_IR_HINODE02 = 13;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_CUENUM = SkillSE_IRIS.CRI_SKILLSE_IRIS_CUENUM;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_CHARA01 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_CHARA01;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_FUYU01 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_FUYU01;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_KATSUBOU = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_KATSUBOU;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_FUYU02 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_FUYU02;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_HEARTBEAM = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_HEARTBEAM;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_VTGIFT01 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_VTGIFT01;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_VTGIFT02_LG = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_VTGIFT02_LG;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_VTGIFT02_STOP = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_VTGIFT02_STOP;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_CHARA02 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_CHARA02;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_START01 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_START01;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_CHARA03 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_CHARA03;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_START03 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_START03;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_HAMAYA01 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_HAMAYA01;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_HAMAYA02 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_HAMAYA02;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_HINODE01 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_HINODE01;

	public const SkillSE_IRIS CRI_SKILLSE_IRIS_IR_HINODE02 = SkillSE_IRIS.CRI_SKILLSE_IRIS_IR_HINODE02;
}
