public enum SkillSE_VIA
{
	NONE = 0,
	CRI_SKILLSE_VIA_CUENUM = 17,
	CRI_SKILLSE_VIA_VI_SOU02 = 2,
	CRI_SKILLSE_VIA_VI_SOU01 = 1,
	CRI_SKILLSE_VIA_VI_SOU03_LP = 3,
	CRI_SKILLSE_VIA_VI_SOU03_STOP = 4,
	CRI_SKILLSE_VIA_VI_KIZIN = 9,
	CRI_SKILLSE_VIA_VI_CHARA01 = 40,
	CRI_SKILLSE_VIA_VI_START01 = 80,
	CRI_SKILLSE_VIA_VI_START02 = 81,
	CRI_SKILLSE_VIA_VI_ZIN02 = 7,
	CRI_SKILLSE_VIA_VI_ZIN01 = 6,
	CRI_SKILLSE_VIA_VI_CHARA02 = 41,
	CRI_SKILLSE_VIA_VI_GOAST01 = 11,
	CRI_SKILLSE_VIA_VI_GOAST02 = 12,
	CRI_SKILLSE_VIA_VI_PUMPKIN01 = 14,
	CRI_SKILLSE_VIA_VI_PUMPKIN02_LP = 15,
	CRI_SKILLSE_VIA_VI_PUMPKIN03 = 17,
	CRI_SKILLSE_VIA_VI_PUMPKIN02_STOP = 16
}
