public static class SkillSE_KOBUNi
{
	public const int iCRI_SKILLSE_KOBUN_CUENUM = 6;

	public const int iCRI_SKILLSE_KOBUN_KB_CURRY = 1;

	public const int iCRI_SKILLSE_KOBUN_KB_NAKAMA01 = 3;

	public const int iCRI_SKILLSE_KOBUN_KB_NAKAMA02 = 4;

	public const int iCRI_SKILLSE_KOBUN_KB_NAKAMA03 = 5;

	public const int iCRI_SKILLSE_KOBUN_KB_CHARA01 = 40;

	public const int iCRI_SKILLSE_KOBUN_KB_START01 = 80;

	public const SkillSE_KOBUN CRI_SKILLSE_KOBUN_CUENUM = SkillSE_KOBUN.CRI_SKILLSE_KOBUN_CUENUM;

	public const SkillSE_KOBUN CRI_SKILLSE_KOBUN_KB_CURRY = SkillSE_KOBUN.CRI_SKILLSE_KOBUN_KB_CURRY;

	public const SkillSE_KOBUN CRI_SKILLSE_KOBUN_KB_NAKAMA01 = SkillSE_KOBUN.CRI_SKILLSE_KOBUN_KB_NAKAMA01;

	public const SkillSE_KOBUN CRI_SKILLSE_KOBUN_KB_NAKAMA02 = SkillSE_KOBUN.CRI_SKILLSE_KOBUN_KB_NAKAMA02;

	public const SkillSE_KOBUN CRI_SKILLSE_KOBUN_KB_NAKAMA03 = SkillSE_KOBUN.CRI_SKILLSE_KOBUN_KB_NAKAMA03;

	public const SkillSE_KOBUN CRI_SKILLSE_KOBUN_KB_CHARA01 = SkillSE_KOBUN.CRI_SKILLSE_KOBUN_KB_CHARA01;

	public const SkillSE_KOBUN CRI_SKILLSE_KOBUN_KB_START01 = SkillSE_KOBUN.CRI_SKILLSE_KOBUN_KB_START01;
}
