public static class SkillSE_DYNAMOi
{
	public const int iCRI_SKILLSE_DYNAMO_CUENUM = 6;

	public const int iCRI_SKILLSE_DYNAMO_DY_DBLADE_LP = 1;

	public const int iCRI_SKILLSE_DYNAMO_DY_DBLADE_STOP = 2;

	public const int iCRI_SKILLSE_DYNAMO_DY_TSUBAME = 4;

	public const int iCRI_SKILLSE_DYNAMO_DY_CHARA01 = 40;

	public const int iCRI_SKILLSE_DYNAMO_DY_TRICK01 = 6;

	public const int iCRI_SKILLSE_DYNAMO_DY_TRICK02 = 7;

	public const SkillSE_DYNAMO CRI_SKILLSE_DYNAMO_CUENUM = SkillSE_DYNAMO.CRI_SKILLSE_DYNAMO_CUENUM;

	public const SkillSE_DYNAMO CRI_SKILLSE_DYNAMO_DY_DBLADE_LP = SkillSE_DYNAMO.CRI_SKILLSE_DYNAMO_DY_DBLADE_LP;

	public const SkillSE_DYNAMO CRI_SKILLSE_DYNAMO_DY_DBLADE_STOP = SkillSE_DYNAMO.CRI_SKILLSE_DYNAMO_DY_DBLADE_STOP;

	public const SkillSE_DYNAMO CRI_SKILLSE_DYNAMO_DY_TSUBAME = SkillSE_DYNAMO.CRI_SKILLSE_DYNAMO_DY_TSUBAME;

	public const SkillSE_DYNAMO CRI_SKILLSE_DYNAMO_DY_CHARA01 = SkillSE_DYNAMO.CRI_SKILLSE_DYNAMO_DY_CHARA01;

	public const SkillSE_DYNAMO CRI_SKILLSE_DYNAMO_DY_TRICK01 = SkillSE_DYNAMO.CRI_SKILLSE_DYNAMO_CUENUM;

	public const SkillSE_DYNAMO CRI_SKILLSE_DYNAMO_DY_TRICK02 = SkillSE_DYNAMO.CRI_SKILLSE_DYNAMO_DY_TRICK02;
}
