public static class SkillSE_ALIAi
{
	public const int iCRI_SKILLSE_ALIA_CUENUM = 10;

	public const int iCRI_SKILLSE_ALIA_AA_MELTCREEPER = 1;

	public const int iCRI_SKILLSE_ALIA_AA_GREENSPINNER = 3;

	public const int iCRI_SKILLSE_ALIA_AA_HEART = 6;

	public const int iCRI_SKILLSE_ALIA_AA_KISS01 = 4;

	public const int iCRI_SKILLSE_ALIA_AA_KISS02 = 5;

	public const int iCRI_SKILLSE_ALIA_AA_START01 = 80;

	public const int iCRI_SKILLSE_ALIA_AA_CHARA01 = 40;

	public const int iCRI_SKILLSE_ALIA_AA_KANE_LP = 7;

	public const int iCRI_SKILLSE_ALIA_AA_KANE_STOP = 8;

	public const int iCRI_SKILLSE_ALIA_AA_BOUQUET = 9;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_CUENUM = SkillSE_ALIA.CRI_SKILLSE_ALIA_CUENUM;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_AA_MELTCREEPER = SkillSE_ALIA.CRI_SKILLSE_ALIA_AA_MELTCREEPER;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_AA_GREENSPINNER = SkillSE_ALIA.CRI_SKILLSE_ALIA_AA_GREENSPINNER;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_AA_HEART = SkillSE_ALIA.CRI_SKILLSE_ALIA_AA_HEART;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_AA_KISS01 = SkillSE_ALIA.CRI_SKILLSE_ALIA_AA_KISS01;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_AA_KISS02 = SkillSE_ALIA.CRI_SKILLSE_ALIA_AA_KISS02;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_AA_START01 = SkillSE_ALIA.CRI_SKILLSE_ALIA_AA_START01;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_AA_CHARA01 = SkillSE_ALIA.CRI_SKILLSE_ALIA_AA_CHARA01;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_AA_KANE_LP = SkillSE_ALIA.CRI_SKILLSE_ALIA_AA_KANE_LP;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_AA_KANE_STOP = SkillSE_ALIA.CRI_SKILLSE_ALIA_AA_KANE_STOP;

	public const SkillSE_ALIA CRI_SKILLSE_ALIA_AA_BOUQUET = SkillSE_ALIA.CRI_SKILLSE_ALIA_AA_BOUQUET;
}
