public static class SkillSE_ZERODMCi
{
	public const int iCRI_SKILLSE_ZERODMC_CUENUM = 9;

	public const int iCRI_SKILLSE_ZERODMC_ZC_CHARA01 = 40;

	public const int iCRI_SKILLSE_ZERODMC_ZC_EARTH01 = 1;

	public const int iCRI_SKILLSE_ZERODMC_ZC_EARTH02 = 2;

	public const int iCRI_SKILLSE_ZERODMC_ZC_MAJIN02 = 9;

	public const int iCRI_SKILLSE_ZERODMC_ZC_MAJIN01 = 8;

	public const int iCRI_SKILLSE_ZERODMC_ZC_JIGEN01 = 4;

	public const int iCRI_SKILLSE_ZERODMC_ZC_JIGEN03 = 6;

	public const int iCRI_SKILLSE_ZERODMC_ZC_JIGEN02 = 5;

	public const int iCRI_SKILLSE_ZERODMC_ZC_START01 = 80;

	public const SkillSE_ZERODMC CRI_SKILLSE_ZERODMC_CUENUM = SkillSE_ZERODMC.CRI_SKILLSE_ZERODMC_CUENUM;

	public const SkillSE_ZERODMC CRI_SKILLSE_ZERODMC_ZC_CHARA01 = SkillSE_ZERODMC.CRI_SKILLSE_ZERODMC_ZC_CHARA01;

	public const SkillSE_ZERODMC CRI_SKILLSE_ZERODMC_ZC_EARTH01 = SkillSE_ZERODMC.CRI_SKILLSE_ZERODMC_ZC_EARTH01;

	public const SkillSE_ZERODMC CRI_SKILLSE_ZERODMC_ZC_EARTH02 = SkillSE_ZERODMC.CRI_SKILLSE_ZERODMC_ZC_EARTH02;

	public const SkillSE_ZERODMC CRI_SKILLSE_ZERODMC_ZC_MAJIN02 = SkillSE_ZERODMC.CRI_SKILLSE_ZERODMC_CUENUM;

	public const SkillSE_ZERODMC CRI_SKILLSE_ZERODMC_ZC_MAJIN01 = SkillSE_ZERODMC.CRI_SKILLSE_ZERODMC_ZC_MAJIN01;

	public const SkillSE_ZERODMC CRI_SKILLSE_ZERODMC_ZC_JIGEN01 = SkillSE_ZERODMC.CRI_SKILLSE_ZERODMC_ZC_JIGEN01;

	public const SkillSE_ZERODMC CRI_SKILLSE_ZERODMC_ZC_JIGEN03 = SkillSE_ZERODMC.CRI_SKILLSE_ZERODMC_ZC_JIGEN03;

	public const SkillSE_ZERODMC CRI_SKILLSE_ZERODMC_ZC_JIGEN02 = SkillSE_ZERODMC.CRI_SKILLSE_ZERODMC_ZC_JIGEN02;

	public const SkillSE_ZERODMC CRI_SKILLSE_ZERODMC_ZC_START01 = SkillSE_ZERODMC.CRI_SKILLSE_ZERODMC_ZC_START01;
}
