public enum SkillSE_ZEROMH
{
	NONE = 0,
	CRI_SKILLSE_ZEROMH_CUENUM = 10,
	CRI_SKILLSE_ZEROMH_ZM_KAKUYOU = 1,
	CRI_SKILLSE_ZEROMH_ZM_RYUKI02 = 10,
	CRI_SKILLSE_ZEROMH_ZM_DASH = 5,
	CRI_SKILLSE_ZEROMH_ZM_KYOUSEI = 6,
	CRI_SKILLSE_ZEROMH_ZM_CHARA01 = 40,
	CRI_SKILLSE_ZEROMH_ZM_START01 = 80,
	CRI_SKILLSE_ZEROMH_ZM_SUISEI = 2,
	CRI_SKILLSE_ZEROMH_ZM_RYUKI01_LP = 8,
	CRI_SKILLSE_ZEROMH_ZM_RYUKI01_STOP = 9,
	CRI_SKILLSE_ZEROMH_ZM_BOUSOU = 3
}
