public static class SkillSE_ZERODivei
{
	public const int iCRI_SKILLSE_ZERODIVE_CUENUM = 6;

	public const int iCRI_SKILLSE_ZERODIVE_ZD_DRAGON01 = 1;

	public const int iCRI_SKILLSE_ZERODIVE_ZD_ZANRIN = 6;

	public const int iCRI_SKILLSE_ZERODIVE_ZD_CHARA01 = 40;

	public const int iCRI_SKILLSE_ZERODIVE_ZD_DRAGON02 = 2;

	public const int iCRI_SKILLSE_ZERODIVE_ZD_DRAGON03_LP = 3;

	public const int iCRI_SKILLSE_ZERODIVE_ZD_DRAGON03_STOP = 4;

	public const SkillSE_ZERODive CRI_SKILLSE_ZERODIVE_CUENUM = SkillSE_ZERODive.CRI_SKILLSE_ZERODIVE_CUENUM;

	public const SkillSE_ZERODive CRI_SKILLSE_ZERODIVE_ZD_DRAGON01 = SkillSE_ZERODive.CRI_SKILLSE_ZERODIVE_ZD_DRAGON01;

	public const SkillSE_ZERODive CRI_SKILLSE_ZERODIVE_ZD_ZANRIN = SkillSE_ZERODive.CRI_SKILLSE_ZERODIVE_CUENUM;

	public const SkillSE_ZERODive CRI_SKILLSE_ZERODIVE_ZD_CHARA01 = SkillSE_ZERODive.CRI_SKILLSE_ZERODIVE_ZD_CHARA01;

	public const SkillSE_ZERODive CRI_SKILLSE_ZERODIVE_ZD_DRAGON02 = SkillSE_ZERODive.CRI_SKILLSE_ZERODIVE_ZD_DRAGON02;

	public const SkillSE_ZERODive CRI_SKILLSE_ZERODIVE_ZD_DRAGON03_LP = SkillSE_ZERODive.CRI_SKILLSE_ZERODIVE_ZD_DRAGON03_LP;

	public const SkillSE_ZERODive CRI_SKILLSE_ZERODIVE_ZD_DRAGON03_STOP = SkillSE_ZERODive.CRI_SKILLSE_ZERODIVE_ZD_DRAGON03_STOP;
}
