public enum SkillSE_XDive2
{
	NONE = 0,
	CRI_SKILLSE_XDIVE2_CUENUM = 17,
	CRI_SKILLSE_XDIVE2_XD2_CHARGE_LP = 1,
	CRI_SKILLSE_XDIVE2_XD2_CHARGE_STOP = 2,
	CRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_S = 3,
	CRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_M = 4,
	CRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_L = 5,
	CRI_SKILLSE_XDIVE2_XD2_FIELD_LP = 17,
	CRI_SKILLSE_XDIVE2_XD2_PLASMA_LP = 8,
	CRI_SKILLSE_XDIVE2_XD2_PLASMA_STOP = 9,
	CRI_SKILLSE_XDIVE2_XD2_FIELD_STOP = 18,
	CRI_SKILLSE_XDIVE2_XD2_CHARA01 = 40,
	CRI_SKILLSE_XDIVE2_XD2_CHARGELVUP = 6,
	CRI_SKILLSE_XDIVE2_XD2_CHARGEMAX = 7,
	CRI_SKILLSE_XDIVE2_XD2_WORLD02 = 12,
	CRI_SKILLSE_XDIVE2_XD2_WORLD01 = 11,
	CRI_SKILLSE_XDIVE2_XD2_NOVA = 14,
	CRI_SKILLSE_XDIVE2_XD2_SWORD = 16,
	CRI_SKILLSE_XDIVE2_XD2_START01 = 80
}
