public static class SkillSE_ICOi
{
	public const int iCRI_SKILLSE_ICO_CUENUM = 38;

	public const int iCRI_SKILLSE_ICO_IC_CHARA01 = 40;

	public const int iCRI_SKILLSE_ICO_IC_CHARA04 = 44;

	public const int iCRI_SKILLSE_ICO_IC_REPLO02_LP = 2;

	public const int iCRI_SKILLSE_ICO_IC_REPLO02_STOP = 3;

	public const int iCRI_SKILLSE_ICO_IC_REPLO05_STOP = 8;

	public const int iCRI_SKILLSE_ICO_IC_REPLO01 = 1;

	public const int iCRI_SKILLSE_ICO_IC_ANALYZE01 = 9;

	public const int iCRI_SKILLSE_ICO_IC_ANALYZE02 = 10;

	public const int iCRI_SKILLSE_ICO_IC_REPLO03 = 4;

	public const int iCRI_SKILLSE_ICO_IC_REPLO04_1 = 5;

	public const int iCRI_SKILLSE_ICO_IC_REPLO04_2 = 6;

	public const int iCRI_SKILLSE_ICO_IC_REPLO05_LP = 7;

	public const int iCRI_SKILLSE_ICO_IC_DATACUBE = 11;

	public const int iCRI_SKILLSE_ICO_IC_RIBBON01 = 13;

	public const int iCRI_SKILLSE_ICO_IC_RIBBON02 = 14;

	public const int iCRI_SKILLSE_ICO_IC_ALLFOR01 = 16;

	public const int iCRI_SKILLSE_ICO_IC_ALLFOR02 = 17;

	public const int iCRI_SKILLSE_ICO_IC_START02 = 80;

	public const int iCRI_SKILLSE_ICO_IC_CHARA02 = 41;

	public const int iCRI_SKILLSE_ICO_IC_SURF01 = 19;

	public const int iCRI_SKILLSE_ICO_IC_SURF02 = 20;

	public const int iCRI_SKILLSE_ICO_IC_WATER01 = 22;

	public const int iCRI_SKILLSE_ICO_IC_WATER02_LP = 23;

	public const int iCRI_SKILLSE_ICO_IC_WATER03 = 25;

	public const int iCRI_SKILLSE_ICO_IC_WATER02_STOP = 24;

	public const int iCRI_SKILLSE_ICO_IC_CHARA03_1 = 42;

	public const int iCRI_SKILLSE_ICO_IC_START03 = 81;

	public const int iCRI_SKILLSE_ICO_IC_CHARA03_2 = 43;

	public const int iCRI_SKILLSE_ICO_IC_REINDEER02 = 28;

	public const int iCRI_SKILLSE_ICO_IC_REINDEER01 = 27;

	public const int iCRI_SKILLSE_ICO_IC_BOX01 = 30;

	public const int iCRI_SKILLSE_ICO_IC_BOX02 = 31;

	public const int iCRI_SKILLSE_ICO_IC_START05 = 82;

	public const int iCRI_SKILLSE_ICO_IC_CHARA05 = 45;

	public const int iCRI_SKILLSE_ICO_IC_LAZER01 = 33;

	public const int iCRI_SKILLSE_ICO_IC_LAZER02_LP = 34;

	public const int iCRI_SKILLSE_ICO_IC_LAZER02_STOP = 35;

	public const int iCRI_SKILLSE_ICO_IC_DELETE01 = 37;

	public const SkillSE_ICO CRI_SKILLSE_ICO_CUENUM = SkillSE_ICO.CRI_SKILLSE_ICO_CUENUM;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_CHARA01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_CHARA01;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_CHARA04 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_CHARA04;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_REPLO02_LP = SkillSE_ICO.CRI_SKILLSE_ICO_IC_REPLO02_LP;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_REPLO02_STOP = SkillSE_ICO.CRI_SKILLSE_ICO_IC_REPLO02_STOP;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_REPLO05_STOP = SkillSE_ICO.CRI_SKILLSE_ICO_IC_REPLO05_STOP;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_REPLO01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_REPLO01;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_ANALYZE01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_ANALYZE01;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_ANALYZE02 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_ANALYZE02;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_REPLO03 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_REPLO03;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_REPLO04_1 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_REPLO04_1;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_REPLO04_2 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_REPLO04_2;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_REPLO05_LP = SkillSE_ICO.CRI_SKILLSE_ICO_IC_REPLO05_LP;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_DATACUBE = SkillSE_ICO.CRI_SKILLSE_ICO_IC_DATACUBE;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_RIBBON01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_RIBBON01;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_RIBBON02 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_RIBBON02;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_ALLFOR01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_ALLFOR01;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_ALLFOR02 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_ALLFOR02;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_START02 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_START02;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_CHARA02 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_CHARA02;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_SURF01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_SURF01;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_SURF02 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_SURF02;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_WATER01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_WATER01;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_WATER02_LP = SkillSE_ICO.CRI_SKILLSE_ICO_IC_WATER02_LP;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_WATER03 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_WATER03;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_WATER02_STOP = SkillSE_ICO.CRI_SKILLSE_ICO_IC_WATER02_STOP;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_CHARA03_1 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_CHARA03_1;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_START03 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_START03;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_CHARA03_2 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_CHARA03_2;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_REINDEER02 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_REINDEER02;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_REINDEER01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_REINDEER01;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_BOX01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_BOX01;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_BOX02 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_BOX02;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_START05 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_START05;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_CHARA05 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_CHARA05;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_LAZER01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_LAZER01;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_LAZER02_LP = SkillSE_ICO.CRI_SKILLSE_ICO_IC_LAZER02_LP;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_LAZER02_STOP = SkillSE_ICO.CRI_SKILLSE_ICO_IC_LAZER02_STOP;

	public const SkillSE_ICO CRI_SKILLSE_ICO_IC_DELETE01 = SkillSE_ICO.CRI_SKILLSE_ICO_IC_DELETE01;
}
