public static class SkillSE_X2ndArmori
{
	public const int iCRI_SKILLSE_X2NDARMOR_CUENUM = 11;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_CHARGE02_STOP = 10;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_CHARGE02_LP = 9;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_L = 7;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_GIGA01 = 5;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_GIGA02 = 6;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_M = 4;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_CHARA01 = 40;

	public const int iCRI_SKILLSE_X2NDARMOR_X2_GIGA03 = 8;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_CUENUM = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_CUENUM;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_CHARGE_LP = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_CHARGE_LP;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_CHARGE02_STOP = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_CHARGE02_STOP;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_CHARGE02_LP = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_CHARGE02_LP;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_CHARGE_STOP = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_CHARGE_STOP;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_L = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_L;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_GIGA01 = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_GIGA01;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_GIGA02 = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_GIGA02;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_M = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_M;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_S = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_S;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_CHARA01 = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_CHARA01;

	public const SkillSE_X2ndArmor CRI_SKILLSE_X2NDARMOR_X2_GIGA03 = SkillSE_X2ndArmor.CRI_SKILLSE_X2NDARMOR_X2_GIGA03;
}
