public enum SkillSE_NANA
{
	NONE = 0,
	CRI_SKILLSE_NANA_CUENUM = 8,
	CRI_SKILLSE_NANA_NA_CHARA01 = 40,
	CRI_SKILLSE_NANA_NA_START01 = 80,
	CRI_SKILLSE_NANA_NA_DOMEGA01 = 1,
	CRI_SKILLSE_NANA_NA_SCAN01 = 6,
	CRI_SKILLSE_NANA_NA_DOMEGA03 = 3,
	CRI_SKILLSE_NANA_NA_DOMEGA04 = 4,
	CRI_SKILLSE_NANA_NA_DOMEGA02 = 2,
	CRI_SKILLSE_NANA_NA_SCAN02 = 7
}
