public static class SkillSE_BlackZEROi
{
	public const int iCRI_SKILLSE_BLACKZERO_CUENUM = 2;

	public const int iCRI_SKILLSE_BLACKZERO_ZU_RAIKOUSEN = 1;

	public const int iCRI_SKILLSE_BLACKZERO_ZU_MESSENKOU = 3;

	public const SkillSE_BlackZERO CRI_SKILLSE_BLACKZERO_CUENUM = SkillSE_BlackZERO.CRI_SKILLSE_BLACKZERO_CUENUM;

	public const SkillSE_BlackZERO CRI_SKILLSE_BLACKZERO_ZU_RAIKOUSEN = SkillSE_BlackZERO.CRI_SKILLSE_BLACKZERO_ZU_RAIKOUSEN;

	public const SkillSE_BlackZERO CRI_SKILLSE_BLACKZERO_ZU_MESSENKOU = SkillSE_BlackZERO.CRI_SKILLSE_BLACKZERO_ZU_MESSENKOU;
}
