public static class SkillSE_LAYERi
{
	public const int iCRI_SKILLSE_LAYER_CUENUM = 19;

	public const int iCRI_SKILLSE_LAYER_LY_TENSHOHA01_LG = 4;

	public const int iCRI_SKILLSE_LAYER_LY_TENSHOHA02_LG = 6;

	public const int iCRI_SKILLSE_LAYER_LY_TENSHOHA01_STOP = 5;

	public const int iCRI_SKILLSE_LAYER_LY_TENSHOHA02_STOP = 7;

	public const int iCRI_SKILLSE_LAYER_LY_RENYODAN02 = 2;

	public const int iCRI_SKILLSE_LAYER_LY_RENYODAN01 = 1;

	public const int iCRI_SKILLSE_LAYER_LY_HISUISYOU = 9;

	public const int iCRI_SKILLSE_LAYER_LY_MELONCUT01 = 10;

	public const int iCRI_SKILLSE_LAYER_LY_MELONCUT02 = 11;

	public const int iCRI_SKILLSE_LAYER_LY_CHARA01 = 13;

	public const int iCRI_SKILLSE_LAYER_LY_CHARA02 = 14;

	public const int iCRI_SKILLSE_LAYER_LY_CHARA03 = 15;

	public const int iCRI_SKILLSE_LAYER_LY_CHARA04 = 16;

	public const int iCRI_SKILLSE_LAYER_LY_START01 = 80;

	public const int iCRI_SKILLSE_LAYER_LY_CHARA05 = 40;

	public const int iCRI_SKILLSE_LAYER_LY_HEART01 = 17;

	public const int iCRI_SKILLSE_LAYER_LY_RING01_LP = 18;

	public const int iCRI_SKILLSE_LAYER_LY_RING01_STOP = 19;

	public const int iCRI_SKILLSE_LAYER_LY_CAKE01 = 12;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_CUENUM = SkillSE_LAYER.CRI_SKILLSE_LAYER_CUENUM;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_TENSHOHA01_LG = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_TENSHOHA01_LG;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_TENSHOHA02_LG = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_TENSHOHA02_LG;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_TENSHOHA01_STOP = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_TENSHOHA01_STOP;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_TENSHOHA02_STOP = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_TENSHOHA02_STOP;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_RENYODAN02 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_RENYODAN02;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_RENYODAN01 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_RENYODAN01;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_HISUISYOU = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_HISUISYOU;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_MELONCUT01 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_MELONCUT01;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_MELONCUT02 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_MELONCUT02;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_CHARA01 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_CHARA01;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_CHARA02 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_CHARA02;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_CHARA03 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_CHARA03;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_CHARA04 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_CHARA04;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_START01 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_START01;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_CHARA05 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_CHARA05;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_HEART01 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_HEART01;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_RING01_LP = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_RING01_LP;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_RING01_STOP = SkillSE_LAYER.CRI_SKILLSE_LAYER_CUENUM;

	public const SkillSE_LAYER CRI_SKILLSE_LAYER_LY_CAKE01 = SkillSE_LAYER.CRI_SKILLSE_LAYER_LY_CAKE01;
}
