public static class SkillSE_MH1i
{
	public const int iCRI_SKILLSE_MH1_CUENUM = 6;

	public const int iCRI_SKILLSE_MH1_MH1_CHARA01 = 40;

	public const int iCRI_SKILLSE_MH1_MH1_IAI02 = 2;

	public const int iCRI_SKILLSE_MH1_MH1_IAI01 = 1;

	public const int iCRI_SKILLSE_MH1_MH1_HISYO01 = 4;

	public const int iCRI_SKILLSE_MH1_MH1_START01 = 80;

	public const int iCRI_SKILLSE_MH1_MH1_HISYO02 = 5;

	public const SkillSE_MH1 CRI_SKILLSE_MH1_CUENUM = SkillSE_MH1.CRI_SKILLSE_MH1_CUENUM;

	public const SkillSE_MH1 CRI_SKILLSE_MH1_MH1_CHARA01 = SkillSE_MH1.CRI_SKILLSE_MH1_MH1_CHARA01;

	public const SkillSE_MH1 CRI_SKILLSE_MH1_MH1_IAI02 = SkillSE_MH1.CRI_SKILLSE_MH1_MH1_IAI02;

	public const SkillSE_MH1 CRI_SKILLSE_MH1_MH1_IAI01 = SkillSE_MH1.CRI_SKILLSE_MH1_MH1_IAI01;

	public const SkillSE_MH1 CRI_SKILLSE_MH1_MH1_HISYO01 = SkillSE_MH1.CRI_SKILLSE_MH1_MH1_HISYO01;

	public const SkillSE_MH1 CRI_SKILLSE_MH1_MH1_START01 = SkillSE_MH1.CRI_SKILLSE_MH1_MH1_START01;

	public const SkillSE_MH1 CRI_SKILLSE_MH1_MH1_HISYO02 = SkillSE_MH1.CRI_SKILLSE_MH1_MH1_HISYO02;
}
