public static class SkillSE_ERATO2i
{
	public const int iCRI_SKILLSE_ERATO2_CUENUM = 6;

	public const int iCRI_SKILLSE_ERATO2_ER2_CHARA01 = 40;

	public const int iCRI_SKILLSE_ERATO2_ER2_EMPRESS01 = 1;

	public const int iCRI_SKILLSE_ERATO2_ER2_EMPRESS02 = 2;

	public const int iCRI_SKILLSE_ERATO2_ER2_EMPRESS03_LP = 3;

	public const int iCRI_SKILLSE_ERATO2_ER2_EMPRESS03_STOP = 4;

	public const int iCRI_SKILLSE_ERATO2_ER2_BANCHO = 6;

	public const SkillSE_ERATO2 CRI_SKILLSE_ERATO2_CUENUM = SkillSE_ERATO2.CRI_SKILLSE_ERATO2_CUENUM;

	public const SkillSE_ERATO2 CRI_SKILLSE_ERATO2_ER2_CHARA01 = SkillSE_ERATO2.CRI_SKILLSE_ERATO2_ER2_CHARA01;

	public const SkillSE_ERATO2 CRI_SKILLSE_ERATO2_ER2_EMPRESS01 = SkillSE_ERATO2.CRI_SKILLSE_ERATO2_ER2_EMPRESS01;

	public const SkillSE_ERATO2 CRI_SKILLSE_ERATO2_ER2_EMPRESS02 = SkillSE_ERATO2.CRI_SKILLSE_ERATO2_ER2_EMPRESS02;

	public const SkillSE_ERATO2 CRI_SKILLSE_ERATO2_ER2_EMPRESS03_LP = SkillSE_ERATO2.CRI_SKILLSE_ERATO2_ER2_EMPRESS03_LP;

	public const SkillSE_ERATO2 CRI_SKILLSE_ERATO2_ER2_EMPRESS03_STOP = SkillSE_ERATO2.CRI_SKILLSE_ERATO2_ER2_EMPRESS03_STOP;

	public const SkillSE_ERATO2 CRI_SKILLSE_ERATO2_ER2_BANCHO = SkillSE_ERATO2.CRI_SKILLSE_ERATO2_CUENUM;
}
