public static class SkillSE_RMZeroi
{
	public const int iCRI_SKILLSE_RMZERO_CUENUM = 4;

	public const int iCRI_SKILLSE_RMZERO_ZZ_KNUCKLE = 1;

	public const int iCRI_SKILLSE_RMZERO_ZZ_BOOMERANG01 = 2;

	public const int iCRI_SKILLSE_RMZERO_ZZ_BOOMERANG02_LP = 3;

	public const int iCRI_SKILLSE_RMZERO_ZZ_BOOMERANG02_STOP = 4;

	public const SkillSE_RMZero CRI_SKILLSE_RMZERO_CUENUM = SkillSE_RMZero.CRI_SKILLSE_RMZERO_CUENUM;

	public const SkillSE_RMZero CRI_SKILLSE_RMZERO_ZZ_KNUCKLE = SkillSE_RMZero.CRI_SKILLSE_RMZERO_ZZ_KNUCKLE;

	public const SkillSE_RMZero CRI_SKILLSE_RMZERO_ZZ_BOOMERANG01 = SkillSE_RMZero.CRI_SKILLSE_RMZERO_ZZ_BOOMERANG01;

	public const SkillSE_RMZero CRI_SKILLSE_RMZERO_ZZ_BOOMERANG02_LP = SkillSE_RMZero.CRI_SKILLSE_RMZERO_ZZ_BOOMERANG02_LP;

	public const SkillSE_RMZero CRI_SKILLSE_RMZERO_ZZ_BOOMERANG02_STOP = SkillSE_RMZero.CRI_SKILLSE_RMZERO_CUENUM;
}
