public enum SkillSE_DRAWER
{
	NONE = 0,
	CRI_SKILLSE_DRAWER_CUENUM = 10,
	CRI_SKILLSE_DRAWER_DR_MONDE01 = 1,
	CRI_SKILLSE_DRAWER_DR_DEFONS = 9,
	CRI_SKILLSE_DRAWER_DR_IMPULSION = 11,
	CRI_SKILLSE_DRAWER_DR_MONDE03 = 3,
	CRI_SKILLSE_DRAWER_DR_REFUS01 = 5,
	CRI_SKILLSE_DRAWER_DR_CHARA01 = 40,
	CRI_SKILLSE_DRAWER_DR_START01 = 80,
	CRI_SKILLSE_DRAWER_DR_MONDE02 = 2,
	CRI_SKILLSE_DRAWER_DR_REFUS02_LP = 6,
	CRI_SKILLSE_DRAWER_DR_REFUS02_STOP = 7
}
