public static class SkillSE_XFalconi
{
	public const int iCRI_SKILLSE_XFALCON_CUENUM = 10;

	public const int iCRI_SKILLSE_XFALCON_XF_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_XFALCON_XF_CHARGESHOT_M = 4;

	public const int iCRI_SKILLSE_XFALCON_XF_CHARGESHOT_L = 5;

	public const int iCRI_SKILLSE_XFALCON_XF_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_XFALCON_XF_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_XFALCON_XF_FREEMOVE_LP = 7;

	public const int iCRI_SKILLSE_XFALCON_XF_FREEMOVE_STOP = 8;

	public const int iCRI_SKILLSE_XFALCON_XF_CHARGEMAX = 6;

	public const int iCRI_SKILLSE_XFALCON_XF_GIGA01 = 9;

	public const int iCRI_SKILLSE_XFALCON_XF_CHARA01 = 40;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_CUENUM = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_CUENUM;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_XF_CHARGESHOT_S = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_XF_CHARGESHOT_S;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_XF_CHARGESHOT_M = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_XF_CHARGESHOT_M;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_XF_CHARGESHOT_L = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_XF_CHARGESHOT_L;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_XF_CHARGE_LP = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_XF_CHARGE_LP;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_XF_CHARGE_STOP = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_XF_CHARGE_STOP;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_XF_FREEMOVE_LP = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_XF_FREEMOVE_LP;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_XF_FREEMOVE_STOP = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_XF_FREEMOVE_STOP;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_XF_CHARGEMAX = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_XF_CHARGEMAX;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_XF_GIGA01 = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_XF_GIGA01;

	public const SkillSE_XFalcon CRI_SKILLSE_XFALCON_XF_CHARA01 = SkillSE_XFalcon.CRI_SKILLSE_XFALCON_XF_CHARA01;
}
