public static class SkillSE_CHUNLIi
{
	public const int iCRI_SKILLSE_CHUNLI_CUENUM = 5;

	public const int iCRI_SKILLSE_CHUNLI_CH_CHARA01 = 40;

	public const int iCRI_SKILLSE_CHUNLI_CH_START01 = 80;

	public const int iCRI_SKILLSE_CHUNLI_CH_SPINING_LG = 1;

	public const int iCRI_SKILLSE_CHUNLI_CH_HOYOKUSEN = 3;

	public const int iCRI_SKILLSE_CHUNLI_CH_SPINING_STOP = 2;

	public const SkillSE_CHUNLI CRI_SKILLSE_CHUNLI_CUENUM = SkillSE_CHUNLI.CRI_SKILLSE_CHUNLI_CUENUM;

	public const SkillSE_CHUNLI CRI_SKILLSE_CHUNLI_CH_CHARA01 = SkillSE_CHUNLI.CRI_SKILLSE_CHUNLI_CH_CHARA01;

	public const SkillSE_CHUNLI CRI_SKILLSE_CHUNLI_CH_START01 = SkillSE_CHUNLI.CRI_SKILLSE_CHUNLI_CH_START01;

	public const SkillSE_CHUNLI CRI_SKILLSE_CHUNLI_CH_SPINING_LG = SkillSE_CHUNLI.CRI_SKILLSE_CHUNLI_CH_SPINING_LG;

	public const SkillSE_CHUNLI CRI_SKILLSE_CHUNLI_CH_HOYOKUSEN = SkillSE_CHUNLI.CRI_SKILLSE_CHUNLI_CH_HOYOKUSEN;

	public const SkillSE_CHUNLI CRI_SKILLSE_CHUNLI_CH_SPINING_STOP = SkillSE_CHUNLI.CRI_SKILLSE_CHUNLI_CH_SPINING_STOP;
}
