public static class SkillSE_ROCKVOLi
{
	public const int iCRI_SKILLSE_ROCKVOL_CUENUM = 9;

	public const int iCRI_SKILLSE_ROCKVOL_RV_LAZER = 1;

	public const int iCRI_SKILLSE_ROCKVOL_RV_CRUSHER_LP = 2;

	public const int iCRI_SKILLSE_ROCKVOL_RV_CRUSHER_STOP = 3;

	public const int iCRI_SKILLSE_ROCKVOL_RV_CHARA01 = 40;

	public const int iCRI_SKILLSE_ROCKVOL_RV_ZIHANKI01 = 5;

	public const int iCRI_SKILLSE_ROCKVOL_RV_ZIHANKI02 = 6;

	public const int iCRI_SKILLSE_ROCKVOL_RV_HAIJO = 8;

	public const int iCRI_SKILLSE_ROCKVOL_RV_CHARA02 = 41;

	public const int iCRI_SKILLSE_ROCKVOL_RV_START01 = 80;

	public const SkillSE_ROCKVOL CRI_SKILLSE_ROCKVOL_CUENUM = SkillSE_ROCKVOL.CRI_SKILLSE_ROCKVOL_CUENUM;

	public const SkillSE_ROCKVOL CRI_SKILLSE_ROCKVOL_RV_LAZER = SkillSE_ROCKVOL.CRI_SKILLSE_ROCKVOL_RV_LAZER;

	public const SkillSE_ROCKVOL CRI_SKILLSE_ROCKVOL_RV_CRUSHER_LP = SkillSE_ROCKVOL.CRI_SKILLSE_ROCKVOL_RV_CRUSHER_LP;

	public const SkillSE_ROCKVOL CRI_SKILLSE_ROCKVOL_RV_CRUSHER_STOP = SkillSE_ROCKVOL.CRI_SKILLSE_ROCKVOL_RV_CRUSHER_STOP;

	public const SkillSE_ROCKVOL CRI_SKILLSE_ROCKVOL_RV_CHARA01 = SkillSE_ROCKVOL.CRI_SKILLSE_ROCKVOL_RV_CHARA01;

	public const SkillSE_ROCKVOL CRI_SKILLSE_ROCKVOL_RV_ZIHANKI01 = SkillSE_ROCKVOL.CRI_SKILLSE_ROCKVOL_RV_ZIHANKI01;

	public const SkillSE_ROCKVOL CRI_SKILLSE_ROCKVOL_RV_ZIHANKI02 = SkillSE_ROCKVOL.CRI_SKILLSE_ROCKVOL_RV_ZIHANKI02;

	public const SkillSE_ROCKVOL CRI_SKILLSE_ROCKVOL_RV_HAIJO = SkillSE_ROCKVOL.CRI_SKILLSE_ROCKVOL_RV_HAIJO;

	public const SkillSE_ROCKVOL CRI_SKILLSE_ROCKVOL_RV_CHARA02 = SkillSE_ROCKVOL.CRI_SKILLSE_ROCKVOL_RV_CHARA02;

	public const SkillSE_ROCKVOL CRI_SKILLSE_ROCKVOL_RV_START01 = SkillSE_ROCKVOL.CRI_SKILLSE_ROCKVOL_RV_START01;
}
