public static class SkillSE_CIEL3i
{
	public const int iCRI_SKILLSE_CIEL3_CUENUM = 9;

	public const int iCRI_SKILLSE_CIEL3_CL3_ELF03 = 4;

	public const int iCRI_SKILLSE_CIEL3_CL3_ELF02_STOP = 3;

	public const int iCRI_SKILLSE_CIEL3_CL3_ELF02_LP = 2;

	public const int iCRI_SKILLSE_CIEL3_CL3_ELF01 = 1;

	public const int iCRI_SKILLSE_CIEL3_CL3_BMR01 = 6;

	public const int iCRI_SKILLSE_CIEL3_CL3_BMR02_STOP = 8;

	public const int iCRI_SKILLSE_CIEL3_CL3_BMR02_LP = 7;

	public const int iCRI_SKILLSE_CIEL3_CL3_CHARA01 = 40;

	public const int iCRI_SKILLSE_CIEL3_CL3_START01 = 80;

	public const SkillSE_CIEL3 CRI_SKILLSE_CIEL3_CUENUM = SkillSE_CIEL3.CRI_SKILLSE_CIEL3_CUENUM;

	public const SkillSE_CIEL3 CRI_SKILLSE_CIEL3_CL3_ELF03 = SkillSE_CIEL3.CRI_SKILLSE_CIEL3_CL3_ELF03;

	public const SkillSE_CIEL3 CRI_SKILLSE_CIEL3_CL3_ELF02_STOP = SkillSE_CIEL3.CRI_SKILLSE_CIEL3_CL3_ELF02_STOP;

	public const SkillSE_CIEL3 CRI_SKILLSE_CIEL3_CL3_ELF02_LP = SkillSE_CIEL3.CRI_SKILLSE_CIEL3_CL3_ELF02_LP;

	public const SkillSE_CIEL3 CRI_SKILLSE_CIEL3_CL3_ELF01 = SkillSE_CIEL3.CRI_SKILLSE_CIEL3_CL3_ELF01;

	public const SkillSE_CIEL3 CRI_SKILLSE_CIEL3_CL3_BMR01 = SkillSE_CIEL3.CRI_SKILLSE_CIEL3_CL3_BMR01;

	public const SkillSE_CIEL3 CRI_SKILLSE_CIEL3_CL3_BMR02_STOP = SkillSE_CIEL3.CRI_SKILLSE_CIEL3_CL3_BMR02_STOP;

	public const SkillSE_CIEL3 CRI_SKILLSE_CIEL3_CL3_BMR02_LP = SkillSE_CIEL3.CRI_SKILLSE_CIEL3_CL3_BMR02_LP;

	public const SkillSE_CIEL3 CRI_SKILLSE_CIEL3_CL3_CHARA01 = SkillSE_CIEL3.CRI_SKILLSE_CIEL3_CL3_CHARA01;

	public const SkillSE_CIEL3 CRI_SKILLSE_CIEL3_CL3_START01 = SkillSE_CIEL3.CRI_SKILLSE_CIEL3_CL3_START01;
}
