public static class SkillSE_AXLi
{
	public const int iCRI_SKILLSE_AXL_CUENUM = 12;

	public const int iCRI_SKILLSE_AXL_A_MAGNUM = 1;

	public const int iCRI_SKILLSE_AXL_A_HANA01 = 3;

	public const int iCRI_SKILLSE_AXL_A_HYOTEKI01 = 5;

	public const int iCRI_SKILLSE_AXL_A_HYOTEKI03 = 8;

	public const int iCRI_SKILLSE_AXL_A_CHARA01 = 40;

	public const int iCRI_SKILLSE_AXL_A_START01 = 80;

	public const int iCRI_SKILLSE_AXL_A_KRONOS01 = 10;

	public const int iCRI_SKILLSE_AXL_A_CODA02 = 13;

	public const int iCRI_SKILLSE_AXL_A_CODA03 = 14;

	public const int iCRI_SKILLSE_AXL_A_CHARA02 = 41;

	public const int iCRI_SKILLSE_AXL_A_KRONOS02 = 11;

	public const int iCRI_SKILLSE_AXL_A_CODA01 = 12;

	public const SkillSE_AXL CRI_SKILLSE_AXL_CUENUM = SkillSE_AXL.CRI_SKILLSE_AXL_CUENUM;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_MAGNUM = SkillSE_AXL.CRI_SKILLSE_AXL_A_MAGNUM;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_HANA01 = SkillSE_AXL.CRI_SKILLSE_AXL_A_HANA01;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_HYOTEKI01 = SkillSE_AXL.CRI_SKILLSE_AXL_A_HYOTEKI01;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_HYOTEKI03 = SkillSE_AXL.CRI_SKILLSE_AXL_A_HYOTEKI03;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_CHARA01 = SkillSE_AXL.CRI_SKILLSE_AXL_A_CHARA01;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_START01 = SkillSE_AXL.CRI_SKILLSE_AXL_A_START01;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_KRONOS01 = SkillSE_AXL.CRI_SKILLSE_AXL_A_KRONOS01;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_CODA02 = SkillSE_AXL.CRI_SKILLSE_AXL_A_CODA02;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_CODA03 = SkillSE_AXL.CRI_SKILLSE_AXL_A_CODA03;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_CHARA02 = SkillSE_AXL.CRI_SKILLSE_AXL_A_CHARA02;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_KRONOS02 = SkillSE_AXL.CRI_SKILLSE_AXL_A_KRONOS02;

	public const SkillSE_AXL CRI_SKILLSE_AXL_A_CODA01 = SkillSE_AXL.CRI_SKILLSE_AXL_CUENUM;
}
