public static class SkillSE_KARNELi
{
	public const int iCRI_SKILLSE_KARNEL_CUENUM = 4;

	public const int iCRI_SKILLSE_KARNEL_KN_TELEPORT01 = 1;

	public const int iCRI_SKILLSE_KARNEL_KN_TELEPORT02 = 2;

	public const int iCRI_SKILLSE_KARNEL_KN_GROUND01 = 4;

	public const int iCRI_SKILLSE_KARNEL_KN_CHARA01 = 40;

	public const SkillSE_KARNEL CRI_SKILLSE_KARNEL_CUENUM = SkillSE_KARNEL.CRI_SKILLSE_KARNEL_CUENUM;

	public const SkillSE_KARNEL CRI_SKILLSE_KARNEL_KN_TELEPORT01 = SkillSE_KARNEL.CRI_SKILLSE_KARNEL_KN_TELEPORT01;

	public const SkillSE_KARNEL CRI_SKILLSE_KARNEL_KN_TELEPORT02 = SkillSE_KARNEL.CRI_SKILLSE_KARNEL_KN_TELEPORT02;

	public const SkillSE_KARNEL CRI_SKILLSE_KARNEL_KN_GROUND01 = SkillSE_KARNEL.CRI_SKILLSE_KARNEL_CUENUM;

	public const SkillSE_KARNEL CRI_SKILLSE_KARNEL_KN_CHARA01 = SkillSE_KARNEL.CRI_SKILLSE_KARNEL_KN_CHARA01;
}
