public static class SkillSE_X1stArmori
{
	public const int iCRI_SKILLSE_X1STARMOR_CUENUM = 7;

	public const int iCRI_SKILLSE_X1STARMOR_X1_SCBUSTER_S = 3;

	public const int iCRI_SKILLSE_X1STARMOR_X1_SCBUSTER_M = 4;

	public const int iCRI_SKILLSE_X1STARMOR_X1_SCBUSTER_L = 5;

	public const int iCRI_SKILLSE_X1STARMOR_X1_SCBUSTER_O = 6;

	public const int iCRI_SKILLSE_X1STARMOR_X1_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_X1STARMOR_X1_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_X1STARMOR_X1_HEADCRUSH = 7;

	public const SkillSE_X1stArmor CRI_SKILLSE_X1STARMOR_CUENUM = SkillSE_X1stArmor.CRI_SKILLSE_X1STARMOR_CUENUM;

	public const SkillSE_X1stArmor CRI_SKILLSE_X1STARMOR_X1_SCBUSTER_S = SkillSE_X1stArmor.CRI_SKILLSE_X1STARMOR_X1_SCBUSTER_S;

	public const SkillSE_X1stArmor CRI_SKILLSE_X1STARMOR_X1_SCBUSTER_M = SkillSE_X1stArmor.CRI_SKILLSE_X1STARMOR_X1_SCBUSTER_M;

	public const SkillSE_X1stArmor CRI_SKILLSE_X1STARMOR_X1_SCBUSTER_L = SkillSE_X1stArmor.CRI_SKILLSE_X1STARMOR_X1_SCBUSTER_L;

	public const SkillSE_X1stArmor CRI_SKILLSE_X1STARMOR_X1_SCBUSTER_O = SkillSE_X1stArmor.CRI_SKILLSE_X1STARMOR_X1_SCBUSTER_O;

	public const SkillSE_X1stArmor CRI_SKILLSE_X1STARMOR_X1_CHARGE_LP = SkillSE_X1stArmor.CRI_SKILLSE_X1STARMOR_X1_CHARGE_LP;

	public const SkillSE_X1stArmor CRI_SKILLSE_X1STARMOR_X1_CHARGE_STOP = SkillSE_X1stArmor.CRI_SKILLSE_X1STARMOR_X1_CHARGE_STOP;

	public const SkillSE_X1stArmor CRI_SKILLSE_X1STARMOR_X1_HEADCRUSH = SkillSE_X1stArmor.CRI_SKILLSE_X1STARMOR_CUENUM;
}
