public enum SkillSE_RYU
{
	NONE = 0,
	CRI_SKILLSE_RYU_CUENUM = 8,
	CRI_SKILLSE_RYU_RY_CHARA01 = 40,
	CRI_SKILLSE_RYU_RY_START01 = 80,
	CRI_SKILLSE_RYU_RY_DENZINRENKI = 5,
	CRI_SKILLSE_RYU_RY_DENZINHADO = 3,
	CRI_SKILLSE_RYU_RY_SHINKUHADO = 1,
	CRI_SKILLSE_RYU_RY_DENZIN_LP = 6,
	CRI_SKILLSE_RYU_RY_DENZIN_STOP = 7,
	CRI_SKILLSE_RYU_RY_SATSUI = 4
}
