public enum SkillSE_ZERODive
{
	NONE = 0,
	CRI_SKILLSE_ZERODIVE_CUENUM = 6,
	CRI_SKILLSE_ZERODIVE_ZD_DRAGON01 = 1,
	CRI_SKILLSE_ZERODIVE_ZD_ZANRIN = 6,
	CRI_SKILLSE_ZERODIVE_ZD_CHARA01 = 40,
	CRI_SKILLSE_ZERODIVE_ZD_DRAGON02 = 2,
	CRI_SKILLSE_ZERODIVE_ZD_DRAGON03_LP = 3,
	CRI_SKILLSE_ZERODIVE_ZD_DRAGON03_STOP = 4
}
