public static class SkillSE_UltimateXi
{
	public const int iCRI_SKILLSE_ULTIMATEX_CUENUM = 8;

	public const int iCRI_SKILLSE_ULTIMATEX_XU_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_ULTIMATEX_XU_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_L = 5;

	public const int iCRI_SKILLSE_ULTIMATEX_XU_NOVASTRIKE = 7;

	public const int iCRI_SKILLSE_ULTIMATEX_XU_PLASMA_LP = 6;

	public const int iCRI_SKILLSE_ULTIMATEX_XU_PLASMA_STOP = 8;

	public const int iCRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_M = 4;

	public const SkillSE_UltimateX CRI_SKILLSE_ULTIMATEX_CUENUM = SkillSE_UltimateX.CRI_SKILLSE_ULTIMATEX_CUENUM;

	public const SkillSE_UltimateX CRI_SKILLSE_ULTIMATEX_XU_CHARGE_LP = SkillSE_UltimateX.CRI_SKILLSE_ULTIMATEX_XU_CHARGE_LP;

	public const SkillSE_UltimateX CRI_SKILLSE_ULTIMATEX_XU_CHARGE_STOP = SkillSE_UltimateX.CRI_SKILLSE_ULTIMATEX_XU_CHARGE_STOP;

	public const SkillSE_UltimateX CRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_L = SkillSE_UltimateX.CRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_L;

	public const SkillSE_UltimateX CRI_SKILLSE_ULTIMATEX_XU_NOVASTRIKE = SkillSE_UltimateX.CRI_SKILLSE_ULTIMATEX_XU_NOVASTRIKE;

	public const SkillSE_UltimateX CRI_SKILLSE_ULTIMATEX_XU_PLASMA_LP = SkillSE_UltimateX.CRI_SKILLSE_ULTIMATEX_XU_PLASMA_LP;

	public const SkillSE_UltimateX CRI_SKILLSE_ULTIMATEX_XU_PLASMA_STOP = SkillSE_UltimateX.CRI_SKILLSE_ULTIMATEX_CUENUM;

	public const SkillSE_UltimateX CRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_S = SkillSE_UltimateX.CRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_S;

	public const SkillSE_UltimateX CRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_M = SkillSE_UltimateX.CRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_M;
}
