public static class SkillSE_FORTEGSi
{
	public const int iCRI_SKILLSE_FORTEGS_CUENUM = 24;

	public const int iCRI_SKILLSE_FORTEGS_FG_CHARA01 = 40;

	public const int iCRI_SKILLSE_FORTEGS_FG_CHARA02 = 41;

	public const int iCRI_SKILLSE_FORTEGS_FG_START01 = 80;

	public const int iCRI_SKILLSE_FORTEGS_FG_GOSPEL02 = 2;

	public const int iCRI_SKILLSE_FORTEGS_FG_GOSPEL01 = 1;

	public const int iCRI_SKILLSE_FORTEGS_FG_VANISH = 4;

	public const int iCRI_SKILLSE_FORTEGS_FG_SHOOTING = 6;

	public const int iCRI_SKILLSE_FORTEGS_FG_CHARGE_LP = 8;

	public const int iCRI_SKILLSE_FORTEGS_FG_CHARGESHOT_L = 12;

	public const int iCRI_SKILLSE_FORTEGS_FG_CHARGESHOT_M = 11;

	public const int iCRI_SKILLSE_FORTEGS_FG_CHARGESHOT_S = 10;

	public const int iCRI_SKILLSE_FORTEGS_FG_CHARGE_STOP = 9;

	public const int iCRI_SKILLSE_FORTEGS_FG_KICK = 15;

	public const int iCRI_SKILLSE_FORTEGS_FG_CHARA03 = 42;

	public const int iCRI_SKILLSE_FORTEGS_FG_START02 = 81;

	public const int iCRI_SKILLSE_FORTEGS_FG_BUSTER01 = 17;

	public const int iCRI_SKILLSE_FORTEGS_FG_LAZER = 20;

	public const int iCRI_SKILLSE_FORTEGS_FG_BUSTER02 = 18;

	public const int iCRI_SKILLSE_FORTEGS_FG_CHARA04 = 43;

	public const int iCRI_SKILLSE_FORTEGS_FG_CHAOS = 24;

	public const int iCRI_SKILLSE_FORTEGS_FG_ROLLING01 = 21;

	public const int iCRI_SKILLSE_FORTEGS_FG_ROLLING02_LP = 22;

	public const int iCRI_SKILLSE_FORTEGS_FG_ROLLING02_STOP = 23;

	public const int iCRI_SKILLSE_FORTEGS_FG_START03 = 82;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_CUENUM = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_CUENUM;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_CHARA01 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_CHARA01;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_CHARA02 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_CHARA02;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_START01 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_START01;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_GOSPEL02 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_GOSPEL02;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_GOSPEL01 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_GOSPEL01;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_VANISH = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_VANISH;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_SHOOTING = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_SHOOTING;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_CHARGE_LP = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_CHARGE_LP;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_CHARGESHOT_L = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_CHARGESHOT_L;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_CHARGESHOT_M = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_CHARGESHOT_M;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_CHARGESHOT_S = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_CHARGESHOT_S;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_CHARGE_STOP = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_CHARGE_STOP;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_KICK = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_KICK;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_CHARA03 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_CHARA03;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_START02 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_START02;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_BUSTER01 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_BUSTER01;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_LAZER = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_LAZER;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_BUSTER02 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_BUSTER02;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_CHARA04 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_CHARA04;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_CHAOS = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_CUENUM;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_ROLLING01 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_ROLLING01;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_ROLLING02_LP = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_ROLLING02_LP;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_ROLLING02_STOP = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_ROLLING02_STOP;

	public const SkillSE_FORTEGS CRI_SKILLSE_FORTEGS_FG_START03 = SkillSE_FORTEGS.CRI_SKILLSE_FORTEGS_FG_START03;
}
