public static class SkillSE_IRIS3i
{
	public const int iCRI_SKILLSE_IRIS3_CUENUM = 11;

	public const int iCRI_SKILLSE_IRIS3_IR3_RAIKOU = 1;

	public const int iCRI_SKILLSE_IRIS3_IR3_SOUKOU01 = 8;

	public const int iCRI_SKILLSE_IRIS3_IR3_TAIDEN01 = 5;

	public const int iCRI_SKILLSE_IRIS3_IR3_CHARA01 = 40;

	public const int iCRI_SKILLSE_IRIS3_IR3_START01 = 80;

	public const int iCRI_SKILLSE_IRIS3_IR3_RAIGEKI = 3;

	public const int iCRI_SKILLSE_IRIS3_IR3_TAIDEN02_LP = 6;

	public const int iCRI_SKILLSE_IRIS3_IR3_TAIDEN02_STOP = 7;

	public const int iCRI_SKILLSE_IRIS3_IR3_SOUKOU02_STOP = 10;

	public const int iCRI_SKILLSE_IRIS3_IR3_SOUKOU02_LG = 9;

	public const int iCRI_SKILLSE_IRIS3_IR3_SOUKOU03 = 11;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_CUENUM = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_CUENUM;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_RAIKOU = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_IR3_RAIKOU;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_SOUKOU01 = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_IR3_SOUKOU01;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_TAIDEN01 = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_IR3_TAIDEN01;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_CHARA01 = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_IR3_CHARA01;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_START01 = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_IR3_START01;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_RAIGEKI = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_IR3_RAIGEKI;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_TAIDEN02_LP = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_IR3_TAIDEN02_LP;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_TAIDEN02_STOP = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_IR3_TAIDEN02_STOP;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_SOUKOU02_STOP = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_IR3_SOUKOU02_STOP;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_SOUKOU02_LG = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_IR3_SOUKOU02_LG;

	public const SkillSE_IRIS3 CRI_SKILLSE_IRIS3_IR3_SOUKOU03 = SkillSE_IRIS3.CRI_SKILLSE_IRIS3_CUENUM;
}
