public static class SkillSE_ERATOi
{
	public const int iCRI_SKILLSE_ERATO_CUENUM = 10;

	public const int iCRI_SKILLSE_ERATO_ER_START01 = 80;

	public const int iCRI_SKILLSE_ERATO_ER_CHARA01 = 40;

	public const int iCRI_SKILLSE_ERATO_ER_GHOST02_LP = 5;

	public const int iCRI_SKILLSE_ERATO_ER_GHOST02_STOP = 6;

	public const int iCRI_SKILLSE_ERATO_ER_HOLY02_STOP = 3;

	public const int iCRI_SKILLSE_ERATO_ER_GHOST03 = 7;

	public const int iCRI_SKILLSE_ERATO_ER_GHOST01 = 4;

	public const int iCRI_SKILLSE_ERATO_ER_HOLY01 = 1;

	public const int iCRI_SKILLSE_ERATO_ER_HOLY02_LP = 2;

	public const int iCRI_SKILLSE_ERATO_ER_GOD = 8;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_CUENUM = SkillSE_ERATO.CRI_SKILLSE_ERATO_CUENUM;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_ER_START01 = SkillSE_ERATO.CRI_SKILLSE_ERATO_ER_START01;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_ER_CHARA01 = SkillSE_ERATO.CRI_SKILLSE_ERATO_ER_CHARA01;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_ER_GHOST02_LP = SkillSE_ERATO.CRI_SKILLSE_ERATO_ER_GHOST02_LP;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_ER_GHOST02_STOP = SkillSE_ERATO.CRI_SKILLSE_ERATO_ER_GHOST02_STOP;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_ER_HOLY02_STOP = SkillSE_ERATO.CRI_SKILLSE_ERATO_ER_HOLY02_STOP;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_ER_GHOST03 = SkillSE_ERATO.CRI_SKILLSE_ERATO_ER_GHOST03;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_ER_GHOST01 = SkillSE_ERATO.CRI_SKILLSE_ERATO_ER_GHOST01;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_ER_HOLY01 = SkillSE_ERATO.CRI_SKILLSE_ERATO_ER_HOLY01;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_ER_HOLY02_LP = SkillSE_ERATO.CRI_SKILLSE_ERATO_ER_HOLY02_LP;

	public const SkillSE_ERATO CRI_SKILLSE_ERATO_ER_GOD = SkillSE_ERATO.CRI_SKILLSE_ERATO_ER_GOD;
}
