public enum SkillSE_CINNAMON
{
	NONE = 0,
	CRI_SKILLSE_CINNAMON_CUENUM = 9,
	CRI_SKILLSE_CINNAMON_CM_HEART01 = 2,
	CRI_SKILLSE_CINNAMON_CM_HEART02 = 4,
	CRI_SKILLSE_CINNAMON_CM_ENGEL = 1,
	CRI_SKILLSE_CINNAMON_CM_INJECTION = 3,
	CRI_SKILLSE_CINNAMON_CM_LOVE = 5,
	CRI_SKILLSE_CINNAMON_CM_CHARA01 = 9,
	CRI_SKILLSE_CINNAMON_CM_START01 = 10,
	CRI_SKILLSE_CINNAMON_CM_BATSU = 6,
	CRI_SKILLSE_CINNAMON_CM_HANE = 7
}
