public static class SkillSE_ICO2i
{
	public const int iCRI_SKILLSE_ICO2_CUENUM = 11;

	public const int iCRI_SKILLSE_ICO2_IC2_KISS03_LP = 3;

	public const int iCRI_SKILLSE_ICO2_IC2_KISS03_STOP = 4;

	public const int iCRI_SKILLSE_ICO2_IC2_KISS01 = 1;

	public const int iCRI_SKILLSE_ICO2_IC2_HUG01 = 5;

	public const int iCRI_SKILLSE_ICO2_IC2_HUG02 = 6;

	public const int iCRI_SKILLSE_ICO2_IC2_BLACK01_LP = 9;

	public const int iCRI_SKILLSE_ICO2_IC2_BLACK01_STOP = 10;

	public const int iCRI_SKILLSE_ICO2_IC2_HUG03 = 7;

	public const int iCRI_SKILLSE_ICO2_IC2_CHARA01 = 40;

	public const int iCRI_SKILLSE_ICO2_IC2_START01 = 80;

	public const int iCRI_SKILLSE_ICO2_IC2_KISS02 = 2;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_CUENUM = SkillSE_ICO2.CRI_SKILLSE_ICO2_CUENUM;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_KISS03_LP = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_KISS03_LP;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_KISS03_STOP = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_KISS03_STOP;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_KISS01 = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_KISS01;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_HUG01 = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_HUG01;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_HUG02 = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_HUG02;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_BLACK01_LP = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_BLACK01_LP;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_BLACK01_STOP = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_BLACK01_STOP;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_HUG03 = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_HUG03;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_CHARA01 = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_CHARA01;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_START01 = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_START01;

	public const SkillSE_ICO2 CRI_SKILLSE_ICO2_IC2_KISS02 = SkillSE_ICO2.CRI_SKILLSE_ICO2_IC2_KISS02;
}
