public enum SkillSE_KOBUN
{
	NONE = 0,
	CRI_SKILLSE_KOBUN_CUENUM = 6,
	CRI_SKILLSE_KOBUN_KB_CURRY = 1,
	CRI_SKILLSE_KOBUN_KB_NAKAMA01 = 3,
	CRI_SKILLSE_KOBUN_KB_NAKAMA02 = 4,
	CRI_SKILLSE_KOBUN_KB_NAKAMA03 = 5,
	CRI_SKILLSE_KOBUN_KB_CHARA01 = 40,
	CRI_SKILLSE_KOBUN_KB_START01 = 80
}
