public static class SkillSE_GATEi
{
	public const int iCRI_SKILLSE_GATE_CUENUM = 6;

	public const int iCRI_SKILLSE_GATE_GT_HOLE01 = 1;

	public const int iCRI_SKILLSE_GATE_GT_HOLE02_LP = 2;

	public const int iCRI_SKILLSE_GATE_GT_HOLE02_STOP = 3;

	public const int iCRI_SKILLSE_GATE_GT_STRIKE = 5;

	public const int iCRI_SKILLSE_GATE_GT_CHARA01 = 40;

	public const int iCRI_SKILLSE_GATE_GT_START01 = 80;

	public const SkillSE_GATE CRI_SKILLSE_GATE_CUENUM = SkillSE_GATE.CRI_SKILLSE_GATE_CUENUM;

	public const SkillSE_GATE CRI_SKILLSE_GATE_GT_HOLE01 = SkillSE_GATE.CRI_SKILLSE_GATE_GT_HOLE01;

	public const SkillSE_GATE CRI_SKILLSE_GATE_GT_HOLE02_LP = SkillSE_GATE.CRI_SKILLSE_GATE_GT_HOLE02_LP;

	public const SkillSE_GATE CRI_SKILLSE_GATE_GT_HOLE02_STOP = SkillSE_GATE.CRI_SKILLSE_GATE_GT_HOLE02_STOP;

	public const SkillSE_GATE CRI_SKILLSE_GATE_GT_STRIKE = SkillSE_GATE.CRI_SKILLSE_GATE_GT_STRIKE;

	public const SkillSE_GATE CRI_SKILLSE_GATE_GT_CHARA01 = SkillSE_GATE.CRI_SKILLSE_GATE_GT_CHARA01;

	public const SkillSE_GATE CRI_SKILLSE_GATE_GT_START01 = SkillSE_GATE.CRI_SKILLSE_GATE_GT_START01;
}
