public enum SkillSE_MASSIMO
{
	NONE = 0,
	CRI_SKILLSE_MASSIMO_CUENUM = 4,
	CRI_SKILLSE_MASSIMO_MS_SENPUZAN = 3,
	CRI_SKILLSE_MASSIMO_MS_BERSERKER01 = 1,
	CRI_SKILLSE_MASSIMO_MS_BERSERKER02 = 2,
	CRI_SKILLSE_MASSIMO_MS_CHARA01 = 40
}
