public static class SkillSE_ROLLi
{
	public const int iCRI_SKILLSE_ROLL_CUENUM = 27;

	public const int iCRI_SKILLSE_ROLL_RL_CLEAN01 = 1;

	public const int iCRI_SKILLSE_ROLL_RL_CLEAN02 = 2;

	public const int iCRI_SKILLSE_ROLL_RL_EDY01 = 4;

	public const int iCRI_SKILLSE_ROLL_RL_EDY02 = 5;

	public const int iCRI_SKILLSE_ROLL_RL_RING01 = 6;

	public const int iCRI_SKILLSE_ROLL_RL_RING02 = 7;

	public const int iCRI_SKILLSE_ROLL_RL_SHIELD_LP = 8;

	public const int iCRI_SKILLSE_ROLL_RL_SHIELD_STOP = 9;

	public const int iCRI_SKILLSE_ROLL_RL_CHARA01 = 10;

	public const int iCRI_SKILLSE_ROLL_RL_CHARA02 = 11;

	public const int iCRI_SKILLSE_ROLL_RL_CHARA03 = 12;

	public const int iCRI_SKILLSE_ROLL_RL_CHARA04 = 13;

	public const int iCRI_SKILLSE_ROLL_RL_START01 = 80;

	public const int iCRI_SKILLSE_ROLL_RL_CHARA05 = 40;

	public const int iCRI_SKILLSE_ROLL_RL_CHARA06 = 41;

	public const int iCRI_SKILLSE_ROLL_RL_BEAM = 14;

	public const int iCRI_SKILLSE_ROLL_RL_SPHERE02_LP = 17;

	public const int iCRI_SKILLSE_ROLL_RL_EGGDASH03 = 24;

	public const int iCRI_SKILLSE_ROLL_RL_EGGDASH02_STOP = 23;

	public const int iCRI_SKILLSE_ROLL_RL_EGGDASH02_LP = 22;

	public const int iCRI_SKILLSE_ROLL_RL_SPHERE02_STOP = 18;

	public const int iCRI_SKILLSE_ROLL_RL_SPHERE03 = 19;

	public const int iCRI_SKILLSE_ROLL_RL_SPHERE01 = 16;

	public const int iCRI_SKILLSE_ROLL_RL_SETEGG01 = 26;

	public const int iCRI_SKILLSE_ROLL_RL_SETEGG02 = 27;

	public const int iCRI_SKILLSE_ROLL_RL_EGGDASH01 = 21;

	public const int iCRI_SKILLSE_ROLL_RL_SETEGG03 = 28;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_CUENUM = SkillSE_ROLL.CRI_SKILLSE_ROLL_CUENUM;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_CLEAN01 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_CLEAN01;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_CLEAN02 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_CLEAN02;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_EDY01 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_EDY01;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_EDY02 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_EDY02;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_RING01 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_RING01;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_RING02 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_RING02;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_SHIELD_LP = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_SHIELD_LP;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_SHIELD_STOP = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_SHIELD_STOP;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_CHARA01 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_CHARA01;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_CHARA02 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_CHARA02;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_CHARA03 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_CHARA03;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_CHARA04 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_CHARA04;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_START01 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_START01;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_CHARA05 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_CHARA05;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_CHARA06 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_CHARA06;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_BEAM = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_BEAM;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_SPHERE02_LP = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_SPHERE02_LP;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_EGGDASH03 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_EGGDASH03;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_EGGDASH02_STOP = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_EGGDASH02_STOP;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_EGGDASH02_LP = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_EGGDASH02_LP;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_SPHERE02_STOP = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_SPHERE02_STOP;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_SPHERE03 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_SPHERE03;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_SPHERE01 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_SPHERE01;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_SETEGG01 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_SETEGG01;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_SETEGG02 = SkillSE_ROLL.CRI_SKILLSE_ROLL_CUENUM;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_EGGDASH01 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_EGGDASH01;

	public const SkillSE_ROLL CRI_SKILLSE_ROLL_RL_SETEGG03 = SkillSE_ROLL.CRI_SKILLSE_ROLL_RL_SETEGG03;
}
