public enum SkillSE_VAVA
{
	NONE = 0,
	CRI_SKILLSE_VAVA_CUENUM = 10,
	CRI_SKILLSE_VAVA_VA_SAKURETSU = 1,
	CRI_SKILLSE_VAVA_VA_DENGEKI = 2,
	CRI_SKILLSE_VAVA_VA_WINGBOOMERANG = 3,
	CRI_SKILLSE_VAVA_VA_PBOMB = 4,
	CRI_SKILLSE_VAVA_VA_CHARA01 = 5,
	CRI_SKILLSE_VAVA_VA_START01 = 6,
	CRI_SKILLSE_VAVA_VA_BB01 = 7,
	CRI_SKILLSE_VAVA_VA_BB02 = 8,
	CRI_SKILLSE_VAVA_VA_FIRE = 9,
	CRI_SKILLSE_VAVA_VA_CHARA02 = 40
}
