public static class SkillSE_FORTE2i
{
	public const int iCRI_SKILLSE_FORTE2_CUENUM = 10;

	public const int iCRI_SKILLSE_FORTE2_FO2_CHARA01 = 40;

	public const int iCRI_SKILLSE_FORTE2_FO2_GOSATTACK01 = 3;

	public const int iCRI_SKILLSE_FORTE2_FO2_START01 = 80;

	public const int iCRI_SKILLSE_FORTE2_FO2_SHOOTING = 8;

	public const int iCRI_SKILLSE_FORTE2_FO2_ROLLING01 = 5;

	public const int iCRI_SKILLSE_FORTE2_FO2_ROLLING02_LP = 6;

	public const int iCRI_SKILLSE_FORTE2_FO2_ROLLING02_STOP = 7;

	public const int iCRI_SKILLSE_FORTE2_FO2_GOSRUSH = 1;

	public const int iCRI_SKILLSE_FORTE2_FO2_RETURN = 10;

	public const int iCRI_SKILLSE_FORTE2_FO2_GOSATTACK02 = 4;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_CUENUM = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_CUENUM;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_FO2_CHARA01 = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_FO2_CHARA01;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_FO2_GOSATTACK01 = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_FO2_GOSATTACK01;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_FO2_START01 = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_FO2_START01;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_FO2_SHOOTING = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_FO2_SHOOTING;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_FO2_ROLLING01 = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_FO2_ROLLING01;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_FO2_ROLLING02_LP = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_FO2_ROLLING02_LP;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_FO2_ROLLING02_STOP = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_FO2_ROLLING02_STOP;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_FO2_GOSRUSH = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_FO2_GOSRUSH;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_FO2_RETURN = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_CUENUM;

	public const SkillSE_FORTE2 CRI_SKILLSE_FORTE2_FO2_GOSATTACK02 = SkillSE_FORTE2.CRI_SKILLSE_FORTE2_FO2_GOSATTACK02;
}
