public enum SkillSE_AXL
{
	NONE = 0,
	CRI_SKILLSE_AXL_CUENUM = 12,
	CRI_SKILLSE_AXL_A_MAGNUM = 1,
	CRI_SKILLSE_AXL_A_HANA01 = 3,
	CRI_SKILLSE_AXL_A_HYOTEKI01 = 5,
	CRI_SKILLSE_AXL_A_HYOTEKI03 = 8,
	CRI_SKILLSE_AXL_A_CHARA01 = 40,
	CRI_SKILLSE_AXL_A_START01 = 80,
	CRI_SKILLSE_AXL_A_KRONOS01 = 10,
	CRI_SKILLSE_AXL_A_CODA02 = 13,
	CRI_SKILLSE_AXL_A_CODA03 = 14,
	CRI_SKILLSE_AXL_A_CHARA02 = 41,
	CRI_SKILLSE_AXL_A_KRONOS02 = 11,
	CRI_SKILLSE_AXL_A_CODA01 = 12
}
