public enum SkillSE_LAYER
{
	NONE = 0,
	CRI_SKILLSE_LAYER_CUENUM = 19,
	CRI_SKILLSE_LAYER_LY_TENSHOHA01_LG = 4,
	CRI_SKILLSE_LAYER_LY_TENSHOHA02_LG = 6,
	CRI_SKILLSE_LAYER_LY_TENSHOHA01_STOP = 5,
	CRI_SKILLSE_LAYER_LY_TENSHOHA02_STOP = 7,
	CRI_SKILLSE_LAYER_LY_RENYODAN02 = 2,
	CRI_SKILLSE_LAYER_LY_RENYODAN01 = 1,
	CRI_SKILLSE_LAYER_LY_HISUISYOU = 9,
	CRI_SKILLSE_LAYER_LY_MELONCUT01 = 10,
	CRI_SKILLSE_LAYER_LY_MELONCUT02 = 11,
	CRI_SKILLSE_LAYER_LY_CHARA01 = 13,
	CRI_SKILLSE_LAYER_LY_CHARA02 = 14,
	CRI_SKILLSE_LAYER_LY_CHARA03 = 15,
	CRI_SKILLSE_LAYER_LY_CHARA04 = 16,
	CRI_SKILLSE_LAYER_LY_START01 = 80,
	CRI_SKILLSE_LAYER_LY_CHARA05 = 40,
	CRI_SKILLSE_LAYER_LY_HEART01 = 17,
	CRI_SKILLSE_LAYER_LY_RING01_LP = 18,
	CRI_SKILLSE_LAYER_LY_RING01_STOP = 19,
	CRI_SKILLSE_LAYER_LY_CAKE01 = 12
}
