public enum SkillSE_MARINO
{
	NONE = 0,
	CRI_SKILLSE_MARINO_CUENUM = 9,
	CRI_SKILLSE_MARINO_MR_DASH = 1,
	CRI_SKILLSE_MARINO_MR_SYURIKEN = 3,
	CRI_SKILLSE_MARINO_MR_SHINOBI_LG = 4,
	CRI_SKILLSE_MARINO_MR_SHINOBI_STOP = 5,
	CRI_SKILLSE_MARINO_MR_KICK = 6,
	CRI_SKILLSE_MARINO_MR_SANGE01 = 7,
	CRI_SKILLSE_MARINO_MR_SANGE02 = 8,
	CRI_SKILLSE_MARINO_MR_CHARA01 = 9,
	CRI_SKILLSE_MARINO_MR_START01 = 10
}
