public enum SkillSE_X2ndArmor
{
	NONE = 0,
	CRI_SKILLSE_X2NDARMOR_CUENUM = 11,
	CRI_SKILLSE_X2NDARMOR_X2_CHARGE_LP = 1,
	CRI_SKILLSE_X2NDARMOR_X2_CHARGE02_STOP = 10,
	CRI_SKILLSE_X2NDARMOR_X2_CHARGE02_LP = 9,
	CRI_SKILLSE_X2NDARMOR_X2_CHARGE_STOP = 2,
	CRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_L = 7,
	CRI_SKILLSE_X2NDARMOR_X2_GIGA01 = 5,
	CRI_SKILLSE_X2NDARMOR_X2_GIGA02 = 6,
	CRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_M = 4,
	CRI_SKILLSE_X2NDARMOR_X2_W_CHARGESHOT_S = 3,
	CRI_SKILLSE_X2NDARMOR_X2_CHARA01 = 40,
	CRI_SKILLSE_X2NDARMOR_X2_GIGA03 = 8
}
