public static class SkillSE_RMEXE2i
{
	public const int iCRI_SKILLSE_RMEXE2_CUENUM = 5;

	public const int iCRI_SKILLSE_RMEXE2_RE2_START01 = 80;

	public const int iCRI_SKILLSE_RMEXE2_RE2_CHARA01 = 40;

	public const int iCRI_SKILLSE_RMEXE2_RE2_SWORD01 = 1;

	public const int iCRI_SKILLSE_RMEXE2_RE2_THUNDER_LP = 3;

	public const int iCRI_SKILLSE_RMEXE2_RE2_THUNDER_STOP = 4;

	public const SkillSE_RMEXE2 CRI_SKILLSE_RMEXE2_CUENUM = SkillSE_RMEXE2.CRI_SKILLSE_RMEXE2_CUENUM;

	public const SkillSE_RMEXE2 CRI_SKILLSE_RMEXE2_RE2_START01 = SkillSE_RMEXE2.CRI_SKILLSE_RMEXE2_RE2_START01;

	public const SkillSE_RMEXE2 CRI_SKILLSE_RMEXE2_RE2_CHARA01 = SkillSE_RMEXE2.CRI_SKILLSE_RMEXE2_RE2_CHARA01;

	public const SkillSE_RMEXE2 CRI_SKILLSE_RMEXE2_RE2_SWORD01 = SkillSE_RMEXE2.CRI_SKILLSE_RMEXE2_RE2_SWORD01;

	public const SkillSE_RMEXE2 CRI_SKILLSE_RMEXE2_RE2_THUNDER_LP = SkillSE_RMEXE2.CRI_SKILLSE_RMEXE2_RE2_THUNDER_LP;

	public const SkillSE_RMEXE2 CRI_SKILLSE_RMEXE2_RE2_THUNDER_STOP = SkillSE_RMEXE2.CRI_SKILLSE_RMEXE2_RE2_THUNDER_STOP;
}
