public enum SkillSE_XDive
{
	NONE = 0,
	CRI_SKILLSE_XDIVE_CUENUM = 11,
	CRI_SKILLSE_XDIVE_XD_CHARGE_LP = 1,
	CRI_SKILLSE_XDIVE_XD_CHARGE_STOP = 2,
	CRI_SKILLSE_XDIVE_XD_CHARGESHOT_L = 5,
	CRI_SKILLSE_XDIVE_XD_NOVARING_LP = 9,
	CRI_SKILLSE_XDIVE_XD_FIELD_LP = 6,
	CRI_SKILLSE_XDIVE_XD_FIELD_STOP = 7,
	CRI_SKILLSE_XDIVE_XD_CHARGESHOT_S = 3,
	CRI_SKILLSE_XDIVE_XD_CHARGESHOT_M = 4,
	CRI_SKILLSE_XDIVE_XD_NOVARING_STOP = 10,
	CRI_SKILLSE_XDIVE_XD_CHARA01 = 40,
	CRI_SKILLSE_XDIVE_XD_NOVARING02 = 11
}
