public static class SkillSE_ROLLEXEi
{
	public const int iCRI_SKILLSE_ROLLEXE_CUENUM = 5;

	public const int iCRI_SKILLSE_ROLLEXE_RX_CHARA01 = 40;

	public const int iCRI_SKILLSE_ROLLEXE_RX_START01 = 80;

	public const int iCRI_SKILLSE_ROLLEXE_RX_ROLLARROW = 4;

	public const int iCRI_SKILLSE_ROLLEXE_RX_ROLLWHIP01 = 1;

	public const int iCRI_SKILLSE_ROLLEXE_RX_ROLLWHIP02 = 2;

	public const SkillSE_ROLLEXE CRI_SKILLSE_ROLLEXE_CUENUM = SkillSE_ROLLEXE.CRI_SKILLSE_ROLLEXE_CUENUM;

	public const SkillSE_ROLLEXE CRI_SKILLSE_ROLLEXE_RX_CHARA01 = SkillSE_ROLLEXE.CRI_SKILLSE_ROLLEXE_RX_CHARA01;

	public const SkillSE_ROLLEXE CRI_SKILLSE_ROLLEXE_RX_START01 = SkillSE_ROLLEXE.CRI_SKILLSE_ROLLEXE_RX_START01;

	public const SkillSE_ROLLEXE CRI_SKILLSE_ROLLEXE_RX_ROLLARROW = SkillSE_ROLLEXE.CRI_SKILLSE_ROLLEXE_RX_ROLLARROW;

	public const SkillSE_ROLLEXE CRI_SKILLSE_ROLLEXE_RX_ROLLWHIP01 = SkillSE_ROLLEXE.CRI_SKILLSE_ROLLEXE_RX_ROLLWHIP01;

	public const SkillSE_ROLLEXE CRI_SKILLSE_ROLLEXE_RX_ROLLWHIP02 = SkillSE_ROLLEXE.CRI_SKILLSE_ROLLEXE_RX_ROLLWHIP02;
}
