public static class SkillSE_RYUi
{
	public const int iCRI_SKILLSE_RYU_CUENUM = 8;

	public const int iCRI_SKILLSE_RYU_RY_CHARA01 = 40;

	public const int iCRI_SKILLSE_RYU_RY_START01 = 80;

	public const int iCRI_SKILLSE_RYU_RY_DENZINRENKI = 5;

	public const int iCRI_SKILLSE_RYU_RY_DENZINHADO = 3;

	public const int iCRI_SKILLSE_RYU_RY_SHINKUHADO = 1;

	public const int iCRI_SKILLSE_RYU_RY_DENZIN_LP = 6;

	public const int iCRI_SKILLSE_RYU_RY_DENZIN_STOP = 7;

	public const int iCRI_SKILLSE_RYU_RY_SATSUI = 4;

	public const SkillSE_RYU CRI_SKILLSE_RYU_CUENUM = SkillSE_RYU.CRI_SKILLSE_RYU_CUENUM;

	public const SkillSE_RYU CRI_SKILLSE_RYU_RY_CHARA01 = SkillSE_RYU.CRI_SKILLSE_RYU_RY_CHARA01;

	public const SkillSE_RYU CRI_SKILLSE_RYU_RY_START01 = SkillSE_RYU.CRI_SKILLSE_RYU_RY_START01;

	public const SkillSE_RYU CRI_SKILLSE_RYU_RY_DENZINRENKI = SkillSE_RYU.CRI_SKILLSE_RYU_RY_DENZINRENKI;

	public const SkillSE_RYU CRI_SKILLSE_RYU_RY_DENZINHADO = SkillSE_RYU.CRI_SKILLSE_RYU_RY_DENZINHADO;

	public const SkillSE_RYU CRI_SKILLSE_RYU_RY_SHINKUHADO = SkillSE_RYU.CRI_SKILLSE_RYU_RY_SHINKUHADO;

	public const SkillSE_RYU CRI_SKILLSE_RYU_RY_DENZIN_LP = SkillSE_RYU.CRI_SKILLSE_RYU_RY_DENZIN_LP;

	public const SkillSE_RYU CRI_SKILLSE_RYU_RY_DENZIN_STOP = SkillSE_RYU.CRI_SKILLSE_RYU_RY_DENZIN_STOP;

	public const SkillSE_RYU CRI_SKILLSE_RYU_RY_SATSUI = SkillSE_RYU.CRI_SKILLSE_RYU_RY_SATSUI;
}
