public static class SkillSE_HARPYIAi
{
	public const int iCRI_SKILLSE_HARPYIA_CUENUM = 6;

	public const int iCRI_SKILLSE_HARPYIA_HA_CHARA01 = 40;

	public const int iCRI_SKILLSE_HARPYIA_HA_START01 = 80;

	public const int iCRI_SKILLSE_HARPYIA_HA_SANDAN01 = 1;

	public const int iCRI_SKILLSE_HARPYIA_HA_SANDAN02 = 2;

	public const int iCRI_SKILLSE_HARPYIA_HA_SONIC01 = 4;

	public const int iCRI_SKILLSE_HARPYIA_HA_SONIC02 = 5;

	public const SkillSE_HARPYIA CRI_SKILLSE_HARPYIA_CUENUM = SkillSE_HARPYIA.CRI_SKILLSE_HARPYIA_CUENUM;

	public const SkillSE_HARPYIA CRI_SKILLSE_HARPYIA_HA_CHARA01 = SkillSE_HARPYIA.CRI_SKILLSE_HARPYIA_HA_CHARA01;

	public const SkillSE_HARPYIA CRI_SKILLSE_HARPYIA_HA_START01 = SkillSE_HARPYIA.CRI_SKILLSE_HARPYIA_HA_START01;

	public const SkillSE_HARPYIA CRI_SKILLSE_HARPYIA_HA_SANDAN01 = SkillSE_HARPYIA.CRI_SKILLSE_HARPYIA_HA_SANDAN01;

	public const SkillSE_HARPYIA CRI_SKILLSE_HARPYIA_HA_SANDAN02 = SkillSE_HARPYIA.CRI_SKILLSE_HARPYIA_HA_SANDAN02;

	public const SkillSE_HARPYIA CRI_SKILLSE_HARPYIA_HA_SONIC01 = SkillSE_HARPYIA.CRI_SKILLSE_HARPYIA_HA_SONIC01;

	public const SkillSE_HARPYIA CRI_SKILLSE_HARPYIA_HA_SONIC02 = SkillSE_HARPYIA.CRI_SKILLSE_HARPYIA_HA_SONIC02;
}
