public static class SkillSE_X4thArmori
{
	public const int iCRI_SKILLSE_X4THARMOR_CUENUM = 8;

	public const int iCRI_SKILLSE_X4THARMOR_X4_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_X4THARMOR_X4_CHARGESHOT_M = 4;

	public const int iCRI_SKILLSE_X4THARMOR_X4_CHARGESHOT_L = 5;

	public const int iCRI_SKILLSE_X4THARMOR_X4_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_X4THARMOR_X4_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_X4THARMOR_X4_NOVASTRIKE = 7;

	public const int iCRI_SKILLSE_X4THARMOR_X4_START01 = 80;

	public const int iCRI_SKILLSE_X4THARMOR_X4_CHARA01 = 40;

	public const SkillSE_X4thArmor CRI_SKILLSE_X4THARMOR_CUENUM = SkillSE_X4thArmor.CRI_SKILLSE_X4THARMOR_CUENUM;

	public const SkillSE_X4thArmor CRI_SKILLSE_X4THARMOR_X4_CHARGESHOT_S = SkillSE_X4thArmor.CRI_SKILLSE_X4THARMOR_X4_CHARGESHOT_S;

	public const SkillSE_X4thArmor CRI_SKILLSE_X4THARMOR_X4_CHARGESHOT_M = SkillSE_X4thArmor.CRI_SKILLSE_X4THARMOR_X4_CHARGESHOT_M;

	public const SkillSE_X4thArmor CRI_SKILLSE_X4THARMOR_X4_CHARGESHOT_L = SkillSE_X4thArmor.CRI_SKILLSE_X4THARMOR_X4_CHARGESHOT_L;

	public const SkillSE_X4thArmor CRI_SKILLSE_X4THARMOR_X4_CHARGE_LP = SkillSE_X4thArmor.CRI_SKILLSE_X4THARMOR_X4_CHARGE_LP;

	public const SkillSE_X4thArmor CRI_SKILLSE_X4THARMOR_X4_CHARGE_STOP = SkillSE_X4thArmor.CRI_SKILLSE_X4THARMOR_X4_CHARGE_STOP;

	public const SkillSE_X4thArmor CRI_SKILLSE_X4THARMOR_X4_NOVASTRIKE = SkillSE_X4thArmor.CRI_SKILLSE_X4THARMOR_X4_NOVASTRIKE;

	public const SkillSE_X4thArmor CRI_SKILLSE_X4THARMOR_X4_START01 = SkillSE_X4thArmor.CRI_SKILLSE_X4THARMOR_X4_START01;

	public const SkillSE_X4thArmor CRI_SKILLSE_X4THARMOR_X4_CHARA01 = SkillSE_X4thArmor.CRI_SKILLSE_X4THARMOR_X4_CHARA01;
}
