public static class SkillSE_MH2i
{
	public const int iCRI_SKILLSE_MH2_CUENUM = 11;

	public const int iCRI_SKILLSE_MH2_MH2_CHARA01 = 40;

	public const int iCRI_SKILLSE_MH2_MH2_TAMA01 = 1;

	public const int iCRI_SKILLSE_MH2_MH2_TAMA02_LP = 2;

	public const int iCRI_SKILLSE_MH2_MH2_TAMA02_STOP = 3;

	public const int iCRI_SKILLSE_MH2_MH2_TAMA03 = 4;

	public const int iCRI_SKILLSE_MH2_MH2_TAMA05 = 6;

	public const int iCRI_SKILLSE_MH2_MH2_TAMA04 = 5;

	public const int iCRI_SKILLSE_MH2_MH2_ANCHOR01_LP = 8;

	public const int iCRI_SKILLSE_MH2_MH2_ANCHOR01_STOP = 9;

	public const int iCRI_SKILLSE_MH2_MH2_ANCHOR02 = 10;

	public const int iCRI_SKILLSE_MH2_MH2_START01 = 80;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_CUENUM = SkillSE_MH2.CRI_SKILLSE_MH2_CUENUM;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_CHARA01 = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_CHARA01;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_TAMA01 = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_TAMA01;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_TAMA02_LP = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_TAMA02_LP;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_TAMA02_STOP = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_TAMA02_STOP;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_TAMA03 = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_TAMA03;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_TAMA05 = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_TAMA05;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_TAMA04 = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_TAMA04;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_ANCHOR01_LP = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_ANCHOR01_LP;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_ANCHOR01_STOP = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_ANCHOR01_STOP;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_ANCHOR02 = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_ANCHOR02;

	public const SkillSE_MH2 CRI_SKILLSE_MH2_MH2_START01 = SkillSE_MH2.CRI_SKILLSE_MH2_MH2_START01;
}
