public enum SkillSE_DRRIGHT
{
	NONE = 0,
	CRI_SKILLSE_DRRIGHT_CUENUM = 7,
	CRI_SKILLSE_DRRIGHT_DR_CHARA01 = 40,
	CRI_SKILLSE_DRRIGHT_DR_START01 = 80,
	CRI_SKILLSE_DRRIGHT_DR_HADOU01 = 1,
	CRI_SKILLSE_DRRIGHT_DR_HADOU03 = 3,
	CRI_SKILLSE_DRRIGHT_DR_HADOU02 = 2,
	CRI_SKILLSE_DRRIGHT_DR_RENDA01 = 5,
	CRI_SKILLSE_DRRIGHT_DR_RENDA02 = 6
}
