public static class SkillSE_AILE2i
{
	public const int iCRI_SKILLSE_AILE2_CUENUM = 15;

	public const int iCRI_SKILLSE_AILE2_AI2_CHARGE01_LP = 1;

	public const int iCRI_SKILLSE_AILE2_AI2_CHARGE01_STOP = 2;

	public const int iCRI_SKILLSE_AILE2_AI2_CHARGE02 = 3;

	public const int iCRI_SKILLSE_AILE2_AI2_CHARGE02_STOP = 4;

	public const int iCRI_SKILLSE_AILE2_AI2_CHARGESHOT_S = 5;

	public const int iCRI_SKILLSE_AILE2_AI2_CHARGESHOT_M = 6;

	public const int iCRI_SKILLSE_AILE2_AI2_CHARGESHOT_L = 7;

	public const int iCRI_SKILLSE_AILE2_AI2_CHARA01 = 40;

	public const int iCRI_SKILLSE_AILE2_AI2_START01 = 80;

	public const int iCRI_SKILLSE_AILE2_AI2_CRASH01 = 8;

	public const int iCRI_SKILLSE_AILE2_AI2_SYURIKEN01 = 9;

	public const int iCRI_SKILLSE_AILE2_AI2_SABER01 = 11;

	public const int iCRI_SKILLSE_AILE2_AI2_SABER02 = 12;

	public const int iCRI_SKILLSE_AILE2_AI2_SABER03 = 13;

	public const int iCRI_SKILLSE_AILE2_AI2_SABER04 = 14;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_CUENUM = SkillSE_AILE2.CRI_SKILLSE_AILE2_CUENUM;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_CHARGE01_LP = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_CHARGE01_LP;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_CHARGE01_STOP = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_CHARGE01_STOP;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_CHARGE02 = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_CHARGE02;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_CHARGE02_STOP = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_CHARGE02_STOP;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_CHARGESHOT_S = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_CHARGESHOT_S;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_CHARGESHOT_M = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_CHARGESHOT_M;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_CHARGESHOT_L = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_CHARGESHOT_L;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_CHARA01 = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_CHARA01;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_START01 = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_START01;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_CRASH01 = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_CRASH01;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_SYURIKEN01 = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_SYURIKEN01;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_SABER01 = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_SABER01;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_SABER02 = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_SABER02;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_SABER03 = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_SABER03;

	public const SkillSE_AILE2 CRI_SKILLSE_AILE2_AI2_SABER04 = SkillSE_AILE2.CRI_SKILLSE_AILE2_AI2_SABER04;
}
