public enum SkillSE_CHUNLI
{
	NONE = 0,
	CRI_SKILLSE_CHUNLI_CUENUM = 5,
	CRI_SKILLSE_CHUNLI_CH_CHARA01 = 40,
	CRI_SKILLSE_CHUNLI_CH_START01 = 80,
	CRI_SKILLSE_CHUNLI_CH_SPINING_LG = 1,
	CRI_SKILLSE_CHUNLI_CH_HOYOKUSEN = 3,
	CRI_SKILLSE_CHUNLI_CH_SPINING_STOP = 2
}
