public static class SkillSE_XMHi
{
	public const int iCRI_SKILLSE_XMH_CUENUM = 9;

	public const int iCRI_SKILLSE_XMH_XM_CHARA01 = 40;

	public const int iCRI_SKILLSE_XMH_XM_START01 = 80;

	public const int iCRI_SKILLSE_XMH_XM_TAME01 = 1;

	public const int iCRI_SKILLSE_XMH_XM_FIREBREATH01 = 4;

	public const int iCRI_SKILLSE_XMH_XM_FIREBREATH02 = 5;

	public const int iCRI_SKILLSE_XMH_XM_TAME02 = 2;

	public const int iCRI_SKILLSE_XMH_XM_RENGOKU_LP = 6;

	public const int iCRI_SKILLSE_XMH_XM_RENGOKU_STOP = 7;

	public const int iCRI_SKILLSE_XMH_XM_STORY01 = 60;

	public const SkillSE_XMH CRI_SKILLSE_XMH_CUENUM = SkillSE_XMH.CRI_SKILLSE_XMH_CUENUM;

	public const SkillSE_XMH CRI_SKILLSE_XMH_XM_CHARA01 = SkillSE_XMH.CRI_SKILLSE_XMH_XM_CHARA01;

	public const SkillSE_XMH CRI_SKILLSE_XMH_XM_START01 = SkillSE_XMH.CRI_SKILLSE_XMH_XM_START01;

	public const SkillSE_XMH CRI_SKILLSE_XMH_XM_TAME01 = SkillSE_XMH.CRI_SKILLSE_XMH_XM_TAME01;

	public const SkillSE_XMH CRI_SKILLSE_XMH_XM_FIREBREATH01 = SkillSE_XMH.CRI_SKILLSE_XMH_XM_FIREBREATH01;

	public const SkillSE_XMH CRI_SKILLSE_XMH_XM_FIREBREATH02 = SkillSE_XMH.CRI_SKILLSE_XMH_XM_FIREBREATH02;

	public const SkillSE_XMH CRI_SKILLSE_XMH_XM_TAME02 = SkillSE_XMH.CRI_SKILLSE_XMH_XM_TAME02;

	public const SkillSE_XMH CRI_SKILLSE_XMH_XM_RENGOKU_LP = SkillSE_XMH.CRI_SKILLSE_XMH_XM_RENGOKU_LP;

	public const SkillSE_XMH CRI_SKILLSE_XMH_XM_RENGOKU_STOP = SkillSE_XMH.CRI_SKILLSE_XMH_XM_RENGOKU_STOP;

	public const SkillSE_XMH CRI_SKILLSE_XMH_XM_STORY01 = SkillSE_XMH.CRI_SKILLSE_XMH_XM_STORY01;
}
