public enum SkillSE_ROCKMAN
{
	NONE = 0,
	CRI_SKILLSE_ROCKMAN_CUENUM = 11,
	CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_O = 7,
	CRI_SKILLSE_ROCKMAN_RM_REAF01 = 9,
	CRI_SKILLSE_ROCKMAN_RM_REAF02 = 10,
	CRI_SKILLSE_ROCKMAN_RM_CHARGE_LP = 1,
	CRI_SKILLSE_ROCKMAN_RM_CHARGE_STOP = 2,
	CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_L = 5,
	CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_M = 4,
	CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_S = 3,
	CRI_SKILLSE_ROCKMAN_RM_CHARGEMAX = 6,
	CRI_SKILLSE_ROCKMAN_RM_LIGHTNING = 14,
	CRI_SKILLSE_ROCKMAN_RM_THUNDER = 12
}
