public enum SkillSE_ROLLCAS
{
	NONE = 0,
	CRI_SKILLSE_ROLLCAS_CUENUM = 4,
	CRI_SKILLSE_ROLLCAS_RC_WRENCH = 1,
	CRI_SKILLSE_ROLLCAS_RC_CHARA01 = 40,
	CRI_SKILLSE_ROLLCAS_RC_START01 = 80,
	CRI_SKILLSE_ROLLCAS_RC_REMOTE = 3
}
