public static class SkillSE_PANDORAi
{
	public const int iCRI_SKILLSE_PANDORA_CUENUM = 7;

	public const int iCRI_SKILLSE_PANDORA_PD_FLYING = 1;

	public const int iCRI_SKILLSE_PANDORA_PD_MAJOU01 = 3;

	public const int iCRI_SKILLSE_PANDORA_PD_MAJOU02_LP = 4;

	public const int iCRI_SKILLSE_PANDORA_PD_MAJOU02_STOP = 5;

	public const int iCRI_SKILLSE_PANDORA_PD_MAJOU03 = 6;

	public const int iCRI_SKILLSE_PANDORA_PD_CHARA01 = 40;

	public const int iCRI_SKILLSE_PANDORA_PD_START01 = 80;

	public const SkillSE_PANDORA CRI_SKILLSE_PANDORA_CUENUM = SkillSE_PANDORA.CRI_SKILLSE_PANDORA_CUENUM;

	public const SkillSE_PANDORA CRI_SKILLSE_PANDORA_PD_FLYING = SkillSE_PANDORA.CRI_SKILLSE_PANDORA_PD_FLYING;

	public const SkillSE_PANDORA CRI_SKILLSE_PANDORA_PD_MAJOU01 = SkillSE_PANDORA.CRI_SKILLSE_PANDORA_PD_MAJOU01;

	public const SkillSE_PANDORA CRI_SKILLSE_PANDORA_PD_MAJOU02_LP = SkillSE_PANDORA.CRI_SKILLSE_PANDORA_PD_MAJOU02_LP;

	public const SkillSE_PANDORA CRI_SKILLSE_PANDORA_PD_MAJOU02_STOP = SkillSE_PANDORA.CRI_SKILLSE_PANDORA_PD_MAJOU02_STOP;

	public const SkillSE_PANDORA CRI_SKILLSE_PANDORA_PD_MAJOU03 = SkillSE_PANDORA.CRI_SKILLSE_PANDORA_PD_MAJOU03;

	public const SkillSE_PANDORA CRI_SKILLSE_PANDORA_PD_CHARA01 = SkillSE_PANDORA.CRI_SKILLSE_PANDORA_PD_CHARA01;

	public const SkillSE_PANDORA CRI_SKILLSE_PANDORA_PD_START01 = SkillSE_PANDORA.CRI_SKILLSE_PANDORA_PD_START01;
}
