public enum SkillSE_DYNAMO
{
	NONE = 0,
	CRI_SKILLSE_DYNAMO_CUENUM = 6,
	CRI_SKILLSE_DYNAMO_DY_DBLADE_LP = 1,
	CRI_SKILLSE_DYNAMO_DY_DBLADE_STOP = 2,
	CRI_SKILLSE_DYNAMO_DY_TSUBAME = 4,
	CRI_SKILLSE_DYNAMO_DY_CHARA01 = 40,
	CRI_SKILLSE_DYNAMO_DY_TRICK01 = 6,
	CRI_SKILLSE_DYNAMO_DY_TRICK02 = 7
}
