public static class SkillSE_MASSIMOi
{
	public const int iCRI_SKILLSE_MASSIMO_CUENUM = 4;

	public const int iCRI_SKILLSE_MASSIMO_MS_SENPUZAN = 3;

	public const int iCRI_SKILLSE_MASSIMO_MS_BERSERKER01 = 1;

	public const int iCRI_SKILLSE_MASSIMO_MS_BERSERKER02 = 2;

	public const int iCRI_SKILLSE_MASSIMO_MS_CHARA01 = 40;

	public const SkillSE_MASSIMO CRI_SKILLSE_MASSIMO_CUENUM = SkillSE_MASSIMO.CRI_SKILLSE_MASSIMO_CUENUM;

	public const SkillSE_MASSIMO CRI_SKILLSE_MASSIMO_MS_SENPUZAN = SkillSE_MASSIMO.CRI_SKILLSE_MASSIMO_MS_SENPUZAN;

	public const SkillSE_MASSIMO CRI_SKILLSE_MASSIMO_MS_BERSERKER01 = SkillSE_MASSIMO.CRI_SKILLSE_MASSIMO_MS_BERSERKER01;

	public const SkillSE_MASSIMO CRI_SKILLSE_MASSIMO_MS_BERSERKER02 = SkillSE_MASSIMO.CRI_SKILLSE_MASSIMO_MS_BERSERKER02;

	public const SkillSE_MASSIMO CRI_SKILLSE_MASSIMO_MS_CHARA01 = SkillSE_MASSIMO.CRI_SKILLSE_MASSIMO_MS_CHARA01;
}
