public static class SkillSE_FERHAMi
{
	public const int iCRI_SKILLSE_FERHAM_CUENUM = 10;

	public const int iCRI_SKILLSE_FERHAM_FM_BLOODYSNAKE = 1;

	public const int iCRI_SKILLSE_FERHAM_FM_START01 = 80;

	public const int iCRI_SKILLSE_FERHAM_FM_CRIMSON01 = 3;

	public const int iCRI_SKILLSE_FERHAM_FM_CRIMSON02 = 4;

	public const int iCRI_SKILLSE_FERHAM_FM_MUCHI = 10;

	public const int iCRI_SKILLSE_FERHAM_FM_CHAINTRAP01_LP = 6;

	public const int iCRI_SKILLSE_FERHAM_FM_CHAINTRAP01 = 5;

	public const int iCRI_SKILLSE_FERHAM_FM_CHAINTRAP01_STOP = 7;

	public const int iCRI_SKILLSE_FERHAM_FM_CHAINTRAP02 = 8;

	public const int iCRI_SKILLSE_FERHAM_FM_CHARA01 = 40;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_CUENUM = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_CUENUM;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_FM_BLOODYSNAKE = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_FM_BLOODYSNAKE;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_FM_START01 = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_FM_START01;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_FM_CRIMSON01 = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_FM_CRIMSON01;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_FM_CRIMSON02 = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_FM_CRIMSON02;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_FM_MUCHI = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_CUENUM;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_FM_CHAINTRAP01_LP = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_FM_CHAINTRAP01_LP;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_FM_CHAINTRAP01 = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_FM_CHAINTRAP01;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_FM_CHAINTRAP01_STOP = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_FM_CHAINTRAP01_STOP;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_FM_CHAINTRAP02 = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_FM_CHAINTRAP02;

	public const SkillSE_FERHAM CRI_SKILLSE_FERHAM_FM_CHARA01 = SkillSE_FERHAM.CRI_SKILLSE_FERHAM_FM_CHARA01;
}
