public static class SkillSE_DRAWERi
{
	public const int iCRI_SKILLSE_DRAWER_CUENUM = 10;

	public const int iCRI_SKILLSE_DRAWER_DR_MONDE01 = 1;

	public const int iCRI_SKILLSE_DRAWER_DR_DEFONS = 9;

	public const int iCRI_SKILLSE_DRAWER_DR_IMPULSION = 11;

	public const int iCRI_SKILLSE_DRAWER_DR_MONDE03 = 3;

	public const int iCRI_SKILLSE_DRAWER_DR_REFUS01 = 5;

	public const int iCRI_SKILLSE_DRAWER_DR_CHARA01 = 40;

	public const int iCRI_SKILLSE_DRAWER_DR_START01 = 80;

	public const int iCRI_SKILLSE_DRAWER_DR_MONDE02 = 2;

	public const int iCRI_SKILLSE_DRAWER_DR_REFUS02_LP = 6;

	public const int iCRI_SKILLSE_DRAWER_DR_REFUS02_STOP = 7;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_CUENUM = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_CUENUM;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_DR_MONDE01 = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_DR_MONDE01;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_DR_DEFONS = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_DR_DEFONS;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_DR_IMPULSION = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_DR_IMPULSION;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_DR_MONDE03 = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_DR_MONDE03;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_DR_REFUS01 = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_DR_REFUS01;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_DR_CHARA01 = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_DR_CHARA01;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_DR_START01 = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_DR_START01;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_DR_MONDE02 = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_DR_MONDE02;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_DR_REFUS02_LP = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_DR_REFUS02_LP;

	public const SkillSE_DRAWER CRI_SKILLSE_DRAWER_DR_REFUS02_STOP = SkillSE_DRAWER.CRI_SKILLSE_DRAWER_DR_REFUS02_STOP;
}
