public static class SkillSE_HARPNOTEi
{
	public const int iCRI_SKILLSE_HARPNOTE_CUENUM = 10;

	public const int iCRI_SKILLSE_HARPNOTE_HN_STRING02 = 2;

	public const int iCRI_SKILLSE_HARPNOTE_HN_STRING01 = 1;

	public const int iCRI_SKILLSE_HARPNOTE_HN_PULSESONG01 = 4;

	public const int iCRI_SKILLSE_HARPNOTE_HN_SPEAKER01_LP = 7;

	public const int iCRI_SKILLSE_HARPNOTE_HN_SPEAKER01_STOP = 8;

	public const int iCRI_SKILLSE_HARPNOTE_HN_PULSESONG03 = 6;

	public const int iCRI_SKILLSE_HARPNOTE_HN_PULSESONG02 = 5;

	public const int iCRI_SKILLSE_HARPNOTE_HN_SPEAKER02 = 9;

	public const int iCRI_SKILLSE_HARPNOTE_HN_CHARA01 = 40;

	public const int iCRI_SKILLSE_HARPNOTE_HN_START01 = 80;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_CUENUM = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_CUENUM;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_HN_STRING02 = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_HN_STRING02;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_HN_STRING01 = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_HN_STRING01;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_HN_PULSESONG01 = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_HN_PULSESONG01;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_HN_SPEAKER01_LP = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_HN_SPEAKER01_LP;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_HN_SPEAKER01_STOP = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_HN_SPEAKER01_STOP;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_HN_PULSESONG03 = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_HN_PULSESONG03;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_HN_PULSESONG02 = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_HN_PULSESONG02;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_HN_SPEAKER02 = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_HN_SPEAKER02;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_HN_CHARA01 = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_HN_CHARA01;

	public const SkillSE_HARPNOTE CRI_SKILLSE_HARPNOTE_HN_START01 = SkillSE_HARPNOTE.CRI_SKILLSE_HARPNOTE_HN_START01;
}
