public static class SkillSE_IRISSUMMERi
{
	public const int iCRI_SKILLSE_IRISSUMMER_CUENUM = 9;

	public const int iCRI_SKILLSE_IRISSUMMER_IRS_BEACHBALL01 = 1;

	public const int iCRI_SKILLSE_IRISSUMMER_IRS_BEACHBALL02 = 2;

	public const int iCRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL01 = 3;

	public const int iCRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL02 = 4;

	public const int iCRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL03 = 5;

	public const int iCRI_SKILLSE_IRISSUMMER_IRS_CHARA01 = 7;

	public const int iCRI_SKILLSE_IRISSUMMER_IRS_CHARA02 = 8;

	public const int iCRI_SKILLSE_IRISSUMMER_IRS_CHARA03 = 9;

	public const int iCRI_SKILLSE_IRISSUMMER_IRS_CHARA04 = 10;

	public const SkillSE_IRISSUMMER CRI_SKILLSE_IRISSUMMER_CUENUM = SkillSE_IRISSUMMER.CRI_SKILLSE_IRISSUMMER_CUENUM;

	public const SkillSE_IRISSUMMER CRI_SKILLSE_IRISSUMMER_IRS_BEACHBALL01 = SkillSE_IRISSUMMER.CRI_SKILLSE_IRISSUMMER_IRS_BEACHBALL01;

	public const SkillSE_IRISSUMMER CRI_SKILLSE_IRISSUMMER_IRS_BEACHBALL02 = SkillSE_IRISSUMMER.CRI_SKILLSE_IRISSUMMER_IRS_BEACHBALL02;

	public const SkillSE_IRISSUMMER CRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL01 = SkillSE_IRISSUMMER.CRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL01;

	public const SkillSE_IRISSUMMER CRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL02 = SkillSE_IRISSUMMER.CRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL02;

	public const SkillSE_IRISSUMMER CRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL03 = SkillSE_IRISSUMMER.CRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL03;

	public const SkillSE_IRISSUMMER CRI_SKILLSE_IRISSUMMER_IRS_CHARA01 = SkillSE_IRISSUMMER.CRI_SKILLSE_IRISSUMMER_IRS_CHARA01;

	public const SkillSE_IRISSUMMER CRI_SKILLSE_IRISSUMMER_IRS_CHARA02 = SkillSE_IRISSUMMER.CRI_SKILLSE_IRISSUMMER_IRS_CHARA02;

	public const SkillSE_IRISSUMMER CRI_SKILLSE_IRISSUMMER_IRS_CHARA03 = SkillSE_IRISSUMMER.CRI_SKILLSE_IRISSUMMER_CUENUM;

	public const SkillSE_IRISSUMMER CRI_SKILLSE_IRISSUMMER_IRS_CHARA04 = SkillSE_IRISSUMMER.CRI_SKILLSE_IRISSUMMER_IRS_CHARA04;
}
