public enum SkillSE_HARPYIA
{
	NONE = 0,
	CRI_SKILLSE_HARPYIA_CUENUM = 6,
	CRI_SKILLSE_HARPYIA_HA_CHARA01 = 40,
	CRI_SKILLSE_HARPYIA_HA_START01 = 80,
	CRI_SKILLSE_HARPYIA_HA_SANDAN01 = 1,
	CRI_SKILLSE_HARPYIA_HA_SANDAN02 = 2,
	CRI_SKILLSE_HARPYIA_HA_SONIC01 = 4,
	CRI_SKILLSE_HARPYIA_HA_SONIC02 = 5
}
