public static class SkillSE_UltimateX2i
{
	public const int iCRI_SKILLSE_ULTIMATEX2_CUENUM = 4;

	public const int iCRI_SKILLSE_ULTIMATEX2_XU2_BUSO01 = 1;

	public const int iCRI_SKILLSE_ULTIMATEX2_XU2_BUSO02 = 2;

	public const int iCRI_SKILLSE_ULTIMATEX2_XU2_ZENDAN01 = 4;

	public const int iCRI_SKILLSE_ULTIMATEX2_XU2_ZENDAN02 = 5;

	public const SkillSE_UltimateX2 CRI_SKILLSE_ULTIMATEX2_CUENUM = SkillSE_UltimateX2.CRI_SKILLSE_ULTIMATEX2_CUENUM;

	public const SkillSE_UltimateX2 CRI_SKILLSE_ULTIMATEX2_XU2_BUSO01 = SkillSE_UltimateX2.CRI_SKILLSE_ULTIMATEX2_XU2_BUSO01;

	public const SkillSE_UltimateX2 CRI_SKILLSE_ULTIMATEX2_XU2_BUSO02 = SkillSE_UltimateX2.CRI_SKILLSE_ULTIMATEX2_XU2_BUSO02;

	public const SkillSE_UltimateX2 CRI_SKILLSE_ULTIMATEX2_XU2_ZENDAN01 = SkillSE_UltimateX2.CRI_SKILLSE_ULTIMATEX2_CUENUM;

	public const SkillSE_UltimateX2 CRI_SKILLSE_ULTIMATEX2_XU2_ZENDAN02 = SkillSE_UltimateX2.CRI_SKILLSE_ULTIMATEX2_XU2_ZENDAN02;
}
