public static class SkillSE_ANGEi
{
	public const int iCRI_SKILLSE_ANGE_CUENUM = 6;

	public const int iCRI_SKILLSE_ANGE_AN_MATINEE01 = 1;

	public const int iCRI_SKILLSE_ANGE_AN_MATINEE02_LP = 2;

	public const int iCRI_SKILLSE_ANGE_AN_MATINEE02_STOP = 3;

	public const int iCRI_SKILLSE_ANGE_AN_SOIREE01 = 5;

	public const int iCRI_SKILLSE_ANGE_AN_CHARA01 = 40;

	public const int iCRI_SKILLSE_ANGE_AN_START01 = 80;

	public const SkillSE_ANGE CRI_SKILLSE_ANGE_CUENUM = SkillSE_ANGE.CRI_SKILLSE_ANGE_CUENUM;

	public const SkillSE_ANGE CRI_SKILLSE_ANGE_AN_MATINEE01 = SkillSE_ANGE.CRI_SKILLSE_ANGE_AN_MATINEE01;

	public const SkillSE_ANGE CRI_SKILLSE_ANGE_AN_MATINEE02_LP = SkillSE_ANGE.CRI_SKILLSE_ANGE_AN_MATINEE02_LP;

	public const SkillSE_ANGE CRI_SKILLSE_ANGE_AN_MATINEE02_STOP = SkillSE_ANGE.CRI_SKILLSE_ANGE_AN_MATINEE02_STOP;

	public const SkillSE_ANGE CRI_SKILLSE_ANGE_AN_SOIREE01 = SkillSE_ANGE.CRI_SKILLSE_ANGE_AN_SOIREE01;

	public const SkillSE_ANGE CRI_SKILLSE_ANGE_AN_CHARA01 = SkillSE_ANGE.CRI_SKILLSE_ANGE_AN_CHARA01;

	public const SkillSE_ANGE CRI_SKILLSE_ANGE_AN_START01 = SkillSE_ANGE.CRI_SKILLSE_ANGE_AN_START01;
}
