public static class SkillSE_MARINOi
{
	public const int iCRI_SKILLSE_MARINO_CUENUM = 9;

	public const int iCRI_SKILLSE_MARINO_MR_DASH = 1;

	public const int iCRI_SKILLSE_MARINO_MR_SYURIKEN = 3;

	public const int iCRI_SKILLSE_MARINO_MR_SHINOBI_LG = 4;

	public const int iCRI_SKILLSE_MARINO_MR_SHINOBI_STOP = 5;

	public const int iCRI_SKILLSE_MARINO_MR_KICK = 6;

	public const int iCRI_SKILLSE_MARINO_MR_SANGE01 = 7;

	public const int iCRI_SKILLSE_MARINO_MR_SANGE02 = 8;

	public const int iCRI_SKILLSE_MARINO_MR_CHARA01 = 9;

	public const int iCRI_SKILLSE_MARINO_MR_START01 = 10;

	public const SkillSE_MARINO CRI_SKILLSE_MARINO_CUENUM = SkillSE_MARINO.CRI_SKILLSE_MARINO_CUENUM;

	public const SkillSE_MARINO CRI_SKILLSE_MARINO_MR_DASH = SkillSE_MARINO.CRI_SKILLSE_MARINO_MR_DASH;

	public const SkillSE_MARINO CRI_SKILLSE_MARINO_MR_SYURIKEN = SkillSE_MARINO.CRI_SKILLSE_MARINO_MR_SYURIKEN;

	public const SkillSE_MARINO CRI_SKILLSE_MARINO_MR_SHINOBI_LG = SkillSE_MARINO.CRI_SKILLSE_MARINO_MR_SHINOBI_LG;

	public const SkillSE_MARINO CRI_SKILLSE_MARINO_MR_SHINOBI_STOP = SkillSE_MARINO.CRI_SKILLSE_MARINO_MR_SHINOBI_STOP;

	public const SkillSE_MARINO CRI_SKILLSE_MARINO_MR_KICK = SkillSE_MARINO.CRI_SKILLSE_MARINO_MR_KICK;

	public const SkillSE_MARINO CRI_SKILLSE_MARINO_MR_SANGE01 = SkillSE_MARINO.CRI_SKILLSE_MARINO_MR_SANGE01;

	public const SkillSE_MARINO CRI_SKILLSE_MARINO_MR_SANGE02 = SkillSE_MARINO.CRI_SKILLSE_MARINO_MR_SANGE02;

	public const SkillSE_MARINO CRI_SKILLSE_MARINO_MR_CHARA01 = SkillSE_MARINO.CRI_SKILLSE_MARINO_CUENUM;

	public const SkillSE_MARINO CRI_SKILLSE_MARINO_MR_START01 = SkillSE_MARINO.CRI_SKILLSE_MARINO_MR_START01;
}
