public enum SkillSE_IRISSUMMER
{
	NONE = 0,
	CRI_SKILLSE_IRISSUMMER_CUENUM = 9,
	CRI_SKILLSE_IRISSUMMER_IRS_BEACHBALL01 = 1,
	CRI_SKILLSE_IRISSUMMER_IRS_BEACHBALL02 = 2,
	CRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL01 = 3,
	CRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL02 = 4,
	CRI_SKILLSE_IRISSUMMER_IRS_CRYSTAL03 = 5,
	CRI_SKILLSE_IRISSUMMER_IRS_CHARA01 = 7,
	CRI_SKILLSE_IRISSUMMER_IRS_CHARA02 = 8,
	CRI_SKILLSE_IRISSUMMER_IRS_CHARA03 = 9,
	CRI_SKILLSE_IRISSUMMER_IRS_CHARA04 = 10
}
