public static class SkillSE_XDivei
{
	public const int iCRI_SKILLSE_XDIVE_CUENUM = 11;

	public const int iCRI_SKILLSE_XDIVE_XD_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_XDIVE_XD_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_XDIVE_XD_CHARGESHOT_L = 5;

	public const int iCRI_SKILLSE_XDIVE_XD_NOVARING_LP = 9;

	public const int iCRI_SKILLSE_XDIVE_XD_FIELD_LP = 6;

	public const int iCRI_SKILLSE_XDIVE_XD_FIELD_STOP = 7;

	public const int iCRI_SKILLSE_XDIVE_XD_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_XDIVE_XD_CHARGESHOT_M = 4;

	public const int iCRI_SKILLSE_XDIVE_XD_NOVARING_STOP = 10;

	public const int iCRI_SKILLSE_XDIVE_XD_CHARA01 = 40;

	public const int iCRI_SKILLSE_XDIVE_XD_NOVARING02 = 11;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_CUENUM = SkillSE_XDive.CRI_SKILLSE_XDIVE_CUENUM;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_CHARGE_LP = SkillSE_XDive.CRI_SKILLSE_XDIVE_XD_CHARGE_LP;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_CHARGE_STOP = SkillSE_XDive.CRI_SKILLSE_XDIVE_XD_CHARGE_STOP;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_CHARGESHOT_L = SkillSE_XDive.CRI_SKILLSE_XDIVE_XD_CHARGESHOT_L;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_NOVARING_LP = SkillSE_XDive.CRI_SKILLSE_XDIVE_XD_NOVARING_LP;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_FIELD_LP = SkillSE_XDive.CRI_SKILLSE_XDIVE_XD_FIELD_LP;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_FIELD_STOP = SkillSE_XDive.CRI_SKILLSE_XDIVE_XD_FIELD_STOP;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_CHARGESHOT_S = SkillSE_XDive.CRI_SKILLSE_XDIVE_XD_CHARGESHOT_S;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_CHARGESHOT_M = SkillSE_XDive.CRI_SKILLSE_XDIVE_XD_CHARGESHOT_M;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_NOVARING_STOP = SkillSE_XDive.CRI_SKILLSE_XDIVE_XD_NOVARING_STOP;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_CHARA01 = SkillSE_XDive.CRI_SKILLSE_XDIVE_XD_CHARA01;

	public const SkillSE_XDive CRI_SKILLSE_XDIVE_XD_NOVARING02 = SkillSE_XDive.CRI_SKILLSE_XDIVE_CUENUM;
}
