public enum SkillSE_ERATO
{
	NONE = 0,
	CRI_SKILLSE_ERATO_CUENUM = 10,
	CRI_SKILLSE_ERATO_ER_START01 = 80,
	CRI_SKILLSE_ERATO_ER_CHARA01 = 40,
	CRI_SKILLSE_ERATO_ER_GHOST02_LP = 5,
	CRI_SKILLSE_ERATO_ER_GHOST02_STOP = 6,
	CRI_SKILLSE_ERATO_ER_HOLY02_STOP = 3,
	CRI_SKILLSE_ERATO_ER_GHOST03 = 7,
	CRI_SKILLSE_ERATO_ER_GHOST01 = 4,
	CRI_SKILLSE_ERATO_ER_HOLY01 = 1,
	CRI_SKILLSE_ERATO_ER_HOLY02_LP = 2,
	CRI_SKILLSE_ERATO_ER_GOD = 8
}
