public static class SkillSE_SIGMAi
{
	public const int iCRI_SKILLSE_SIGMA_CUENUM = 16;

	public const int iCRI_SKILLSE_SIGMA_SG_CHARA01 = 40;

	public const int iCRI_SKILLSE_SIGMA_SG_CHARA03 = 42;

	public const int iCRI_SKILLSE_SIGMA_SG_START02 = 80;

	public const int iCRI_SKILLSE_SIGMA_SG_CHARA02 = 41;

	public const int iCRI_SKILLSE_SIGMA_SG_BLADE01 = 1;

	public const int iCRI_SKILLSE_SIGMA_SG_MAGNUM01 = 3;

	public const int iCRI_SKILLSE_SIGMA_SG_BLADE02 = 2;

	public const int iCRI_SKILLSE_SIGMA_SG_BAT = 4;

	public const int iCRI_SKILLSE_SIGMA_SG_ONIBI01_LP = 5;

	public const int iCRI_SKILLSE_SIGMA_SG_ONIBI01_STOP = 6;

	public const int iCRI_SKILLSE_SIGMA_SG_COMBO01 = 13;

	public const int iCRI_SKILLSE_SIGMA_SG_DUEL03 = 11;

	public const int iCRI_SKILLSE_SIGMA_SG_DUEL01 = 8;

	public const int iCRI_SKILLSE_SIGMA_SG_DUEL02_LP = 9;

	public const int iCRI_SKILLSE_SIGMA_SG_DUEL02_STOP = 10;

	public const int iCRI_SKILLSE_SIGMA_SG_COMBO02 = 14;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_CUENUM = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_CUENUM;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_CHARA01 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_CHARA01;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_CHARA03 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_CHARA03;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_START02 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_START02;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_CHARA02 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_CHARA02;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_BLADE01 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_BLADE01;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_MAGNUM01 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_MAGNUM01;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_BLADE02 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_BLADE02;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_BAT = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_BAT;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_ONIBI01_LP = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_ONIBI01_LP;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_ONIBI01_STOP = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_ONIBI01_STOP;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_COMBO01 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_COMBO01;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_DUEL03 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_DUEL03;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_DUEL01 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_DUEL01;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_DUEL02_LP = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_DUEL02_LP;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_DUEL02_STOP = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_DUEL02_STOP;

	public const SkillSE_SIGMA CRI_SKILLSE_SIGMA_SG_COMBO02 = SkillSE_SIGMA.CRI_SKILLSE_SIGMA_SG_COMBO02;
}
