public enum SkillSE_ANGE
{
	NONE = 0,
	CRI_SKILLSE_ANGE_CUENUM = 6,
	CRI_SKILLSE_ANGE_AN_MATINEE01 = 1,
	CRI_SKILLSE_ANGE_AN_MATINEE02_LP = 2,
	CRI_SKILLSE_ANGE_AN_MATINEE02_STOP = 3,
	CRI_SKILLSE_ANGE_AN_SOIREE01 = 5,
	CRI_SKILLSE_ANGE_AN_CHARA01 = 40,
	CRI_SKILLSE_ANGE_AN_START01 = 80
}
