public enum SkillSE_FORTE
{
	NONE = 0,
	CRI_SKILLSE_FORTE_CUENUM = 12,
	CRI_SKILLSE_FORTE_FO_CHARA01 = 40,
	CRI_SKILLSE_FORTE_FO_CHARGE_LP = 1,
	CRI_SKILLSE_FORTE_FO_CHARGESHOT_L = 5,
	CRI_SKILLSE_FORTE_FO_CHARGESHOT_M = 4,
	CRI_SKILLSE_FORTE_FO_CHARGESHOT_S = 3,
	CRI_SKILLSE_FORTE_FO_CHARGE_STOP = 2,
	CRI_SKILLSE_FORTE_FO_KICK = 7,
	CRI_SKILLSE_FORTE_FO_CHARA02 = 41,
	CRI_SKILLSE_FORTE_FO_START02 = 81,
	CRI_SKILLSE_FORTE_FO_BUSTER01 = 9,
	CRI_SKILLSE_FORTE_FO_LAZER = 12,
	CRI_SKILLSE_FORTE_FO_BUSTER02 = 10
}
