public static class SkillSE_ROCKMANi
{
	public const int iCRI_SKILLSE_ROCKMAN_CUENUM = 11;

	public const int iCRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_O = 7;

	public const int iCRI_SKILLSE_ROCKMAN_RM_REAF01 = 9;

	public const int iCRI_SKILLSE_ROCKMAN_RM_REAF02 = 10;

	public const int iCRI_SKILLSE_ROCKMAN_RM_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_ROCKMAN_RM_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_L = 5;

	public const int iCRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_M = 4;

	public const int iCRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_ROCKMAN_RM_CHARGEMAX = 6;

	public const int iCRI_SKILLSE_ROCKMAN_RM_LIGHTNING = 14;

	public const int iCRI_SKILLSE_ROCKMAN_RM_THUNDER = 12;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_CUENUM = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_CUENUM;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_O = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_O;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_REAF01 = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_REAF01;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_REAF02 = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_REAF02;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_CHARGE_LP = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_CHARGE_LP;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_CHARGE_STOP = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_CHARGE_STOP;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_L = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_L;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_M = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_M;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_S = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_CHARGESHOT_S;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_CHARGEMAX = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_CHARGEMAX;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_LIGHTNING = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_LIGHTNING;

	public const SkillSE_ROCKMAN CRI_SKILLSE_ROCKMAN_RM_THUNDER = SkillSE_ROCKMAN.CRI_SKILLSE_ROCKMAN_RM_THUNDER;
}
