public enum SkillSE_XArk
{
	NONE = 0,
	CRI_SKILLSE_XARK_CUENUM = 10,
	CRI_SKILLSE_XARK_XA_CRY01 = 1,
	CRI_SKILLSE_XARK_XA_KARA01 = 3,
	CRI_SKILLSE_XARK_XA_KARA02 = 4,
	CRI_SKILLSE_XARK_XA_KARA03_LP = 5,
	CRI_SKILLSE_XARK_XA_KARA03_STOP = 6,
	CRI_SKILLSE_XARK_XA_ARK02_LP = 9,
	CRI_SKILLSE_XARK_XA_ARK02_STOP = 10,
	CRI_SKILLSE_XARK_XA_ARK01 = 8,
	CRI_SKILLSE_XARK_XA_KINSOKU = 11,
	CRI_SKILLSE_XARK_XA_CHARA01 = 40
}
