public static class SkillSE_FORTEEXEi
{
	public const int iCRI_SKILLSE_FORTEEXE_CUENUM = 8;

	public const int iCRI_SKILLSE_FORTEEXE_FE_AIRBURST01 = 1;

	public const int iCRI_SKILLSE_FORTEEXE_FE_AIRBURST02 = 2;

	public const int iCRI_SKILLSE_FORTEEXE_FE_EXPLOSION = 3;

	public const int iCRI_SKILLSE_FORTEEXE_FE_EVOLVE = 4;

	public const int iCRI_SKILLSE_FORTEEXE_FE_AURA_LP = 5;

	public const int iCRI_SKILLSE_FORTEEXE_FE_AURA_STOP = 6;

	public const int iCRI_SKILLSE_FORTEEXE_FE_CHARA01 = 40;

	public const int iCRI_SKILLSE_FORTEEXE_FE_START01 = 80;

	public const SkillSE_FORTEEXE CRI_SKILLSE_FORTEEXE_CUENUM = SkillSE_FORTEEXE.CRI_SKILLSE_FORTEEXE_CUENUM;

	public const SkillSE_FORTEEXE CRI_SKILLSE_FORTEEXE_FE_AIRBURST01 = SkillSE_FORTEEXE.CRI_SKILLSE_FORTEEXE_FE_AIRBURST01;

	public const SkillSE_FORTEEXE CRI_SKILLSE_FORTEEXE_FE_AIRBURST02 = SkillSE_FORTEEXE.CRI_SKILLSE_FORTEEXE_FE_AIRBURST02;

	public const SkillSE_FORTEEXE CRI_SKILLSE_FORTEEXE_FE_EXPLOSION = SkillSE_FORTEEXE.CRI_SKILLSE_FORTEEXE_FE_EXPLOSION;

	public const SkillSE_FORTEEXE CRI_SKILLSE_FORTEEXE_FE_EVOLVE = SkillSE_FORTEEXE.CRI_SKILLSE_FORTEEXE_FE_EVOLVE;

	public const SkillSE_FORTEEXE CRI_SKILLSE_FORTEEXE_FE_AURA_LP = SkillSE_FORTEEXE.CRI_SKILLSE_FORTEEXE_FE_AURA_LP;

	public const SkillSE_FORTEEXE CRI_SKILLSE_FORTEEXE_FE_AURA_STOP = SkillSE_FORTEEXE.CRI_SKILLSE_FORTEEXE_FE_AURA_STOP;

	public const SkillSE_FORTEEXE CRI_SKILLSE_FORTEEXE_FE_CHARA01 = SkillSE_FORTEEXE.CRI_SKILLSE_FORTEEXE_FE_CHARA01;

	public const SkillSE_FORTEEXE CRI_SKILLSE_FORTEEXE_FE_START01 = SkillSE_FORTEEXE.CRI_SKILLSE_FORTEEXE_FE_START01;
}
