public static class SkillSE_BLUESi
{
	public const int iCRI_SKILLSE_BLUES_CUENUM = 10;

	public const int iCRI_SKILLSE_BLUES_BL_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_BLUES_BL_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_BLUES_BL_CHARGESHOT_L = 5;

	public const int iCRI_SKILLSE_BLUES_BL_SHIELD01 = 7;

	public const int iCRI_SKILLSE_BLUES_BL_SHIELD02 = 8;

	public const int iCRI_SKILLSE_BLUES_BL_SHIELD03 = 9;

	public const int iCRI_SKILLSE_BLUES_BL_CHARGESHOT_M = 4;

	public const int iCRI_SKILLSE_BLUES_BL_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_BLUES_BL_CHARGEMAX = 6;

	public const int iCRI_SKILLSE_BLUES_BL_KUCHIBUE = 11;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_CUENUM = SkillSE_BLUES.CRI_SKILLSE_BLUES_CUENUM;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_BL_CHARGE_LP = SkillSE_BLUES.CRI_SKILLSE_BLUES_BL_CHARGE_LP;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_BL_CHARGE_STOP = SkillSE_BLUES.CRI_SKILLSE_BLUES_BL_CHARGE_STOP;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_BL_CHARGESHOT_L = SkillSE_BLUES.CRI_SKILLSE_BLUES_BL_CHARGESHOT_L;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_BL_SHIELD01 = SkillSE_BLUES.CRI_SKILLSE_BLUES_BL_SHIELD01;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_BL_SHIELD02 = SkillSE_BLUES.CRI_SKILLSE_BLUES_BL_SHIELD02;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_BL_SHIELD03 = SkillSE_BLUES.CRI_SKILLSE_BLUES_BL_SHIELD03;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_BL_CHARGESHOT_M = SkillSE_BLUES.CRI_SKILLSE_BLUES_BL_CHARGESHOT_M;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_BL_CHARGESHOT_S = SkillSE_BLUES.CRI_SKILLSE_BLUES_BL_CHARGESHOT_S;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_BL_CHARGEMAX = SkillSE_BLUES.CRI_SKILLSE_BLUES_BL_CHARGEMAX;

	public const SkillSE_BLUES CRI_SKILLSE_BLUES_BL_KUCHIBUE = SkillSE_BLUES.CRI_SKILLSE_BLUES_BL_KUCHIBUE;
}
