public static class SkillSE_XKaii
{
	public const int iCRI_SKILLSE_XKAI_CUENUM = 9;

	public const int iCRI_SKILLSE_XKAI_XK_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_XKAI_XK_CHARGE_STOP = 3;

	public const int iCRI_SKILLSE_XKAI_XK_CHARGE02_LP = 2;

	public const int iCRI_SKILLSE_XKAI_XK_CHARGESHOT_M = 5;

	public const int iCRI_SKILLSE_XKAI_XK_HOMING01 = 8;

	public const int iCRI_SKILLSE_XKAI_XK_HOMING02 = 10;

	public const int iCRI_SKILLSE_XKAI_XK_CHARA01 = 40;

	public const int iCRI_SKILLSE_XKAI_XK_CHARGESHOT_L = 6;

	public const int iCRI_SKILLSE_XKAI_XK_CHARGESHOT_S = 4;

	public const SkillSE_XKai CRI_SKILLSE_XKAI_CUENUM = SkillSE_XKai.CRI_SKILLSE_XKAI_CUENUM;

	public const SkillSE_XKai CRI_SKILLSE_XKAI_XK_CHARGE_LP = SkillSE_XKai.CRI_SKILLSE_XKAI_XK_CHARGE_LP;

	public const SkillSE_XKai CRI_SKILLSE_XKAI_XK_CHARGE_STOP = SkillSE_XKai.CRI_SKILLSE_XKAI_XK_CHARGE_STOP;

	public const SkillSE_XKai CRI_SKILLSE_XKAI_XK_CHARGE02_LP = SkillSE_XKai.CRI_SKILLSE_XKAI_XK_CHARGE02_LP;

	public const SkillSE_XKai CRI_SKILLSE_XKAI_XK_CHARGESHOT_M = SkillSE_XKai.CRI_SKILLSE_XKAI_XK_CHARGESHOT_M;

	public const SkillSE_XKai CRI_SKILLSE_XKAI_XK_HOMING01 = SkillSE_XKai.CRI_SKILLSE_XKAI_XK_HOMING01;

	public const SkillSE_XKai CRI_SKILLSE_XKAI_XK_HOMING02 = SkillSE_XKai.CRI_SKILLSE_XKAI_XK_HOMING02;

	public const SkillSE_XKai CRI_SKILLSE_XKAI_XK_CHARA01 = SkillSE_XKai.CRI_SKILLSE_XKAI_XK_CHARA01;

	public const SkillSE_XKai CRI_SKILLSE_XKAI_XK_CHARGESHOT_L = SkillSE_XKai.CRI_SKILLSE_XKAI_XK_CHARGESHOT_L;

	public const SkillSE_XKai CRI_SKILLSE_XKAI_XK_CHARGESHOT_S = SkillSE_XKai.CRI_SKILLSE_XKAI_XK_CHARGESHOT_S;
}
