public static class SkillSE_AbsoZEROi
{
	public const int iCRI_SKILLSE_ABSOZERO_CUENUM = 6;

	public const int iCRI_SKILLSE_ABSOZERO_ZB_START01 = 80;

	public const int iCRI_SKILLSE_ABSOZERO_ZB_KARA01 = 5;

	public const int iCRI_SKILLSE_ABSOZERO_ZB_CRIMZON01 = 1;

	public const int iCRI_SKILLSE_ABSOZERO_ZB_KARA02_LG = 6;

	public const int iCRI_SKILLSE_ABSOZERO_ZB_CHARA01 = 40;

	public const int iCRI_SKILLSE_ABSOZERO_ZB_KARA02_STOP = 7;

	public const SkillSE_AbsoZERO CRI_SKILLSE_ABSOZERO_CUENUM = SkillSE_AbsoZERO.CRI_SKILLSE_ABSOZERO_CUENUM;

	public const SkillSE_AbsoZERO CRI_SKILLSE_ABSOZERO_ZB_START01 = SkillSE_AbsoZERO.CRI_SKILLSE_ABSOZERO_ZB_START01;

	public const SkillSE_AbsoZERO CRI_SKILLSE_ABSOZERO_ZB_KARA01 = SkillSE_AbsoZERO.CRI_SKILLSE_ABSOZERO_ZB_KARA01;

	public const SkillSE_AbsoZERO CRI_SKILLSE_ABSOZERO_ZB_CRIMZON01 = SkillSE_AbsoZERO.CRI_SKILLSE_ABSOZERO_ZB_CRIMZON01;

	public const SkillSE_AbsoZERO CRI_SKILLSE_ABSOZERO_ZB_KARA02_LG = SkillSE_AbsoZERO.CRI_SKILLSE_ABSOZERO_CUENUM;

	public const SkillSE_AbsoZERO CRI_SKILLSE_ABSOZERO_ZB_CHARA01 = SkillSE_AbsoZERO.CRI_SKILLSE_ABSOZERO_ZB_CHARA01;

	public const SkillSE_AbsoZERO CRI_SKILLSE_ABSOZERO_ZB_KARA02_STOP = SkillSE_AbsoZERO.CRI_SKILLSE_ABSOZERO_ZB_KARA02_STOP;
}
