public enum SkillSE_Leviathan
{
	NONE = 0,
	CRI_SKILLSE_LEVIATHAN_CUENUM = 16,
	CRI_SKILLSE_LEVIATHAN_LV_SLASH = 1,
	CRI_SKILLSE_LEVIATHAN_LV_OCEAN01 = 2,
	CRI_SKILLSE_LEVIATHAN_LV_OCEAN02 = 3,
	CRI_SKILLSE_LEVIATHAN_LV_CRYSTAL01 = 4,
	CRI_SKILLSE_LEVIATHAN_LV_CRYSTAL02 = 5,
	CRI_SKILLSE_LEVIATHAN_LV_CHARA01 = 6,
	CRI_SKILLSE_LEVIATHAN_LV_CHARA02 = 7,
	CRI_SKILLSE_LEVIATHAN_LV_CHARA03 = 8,
	CRI_SKILLSE_LEVIATHAN_LV_START01 = 13,
	CRI_SKILLSE_LEVIATHAN_LV_ICERING = 10,
	CRI_SKILLSE_LEVIATHAN_LV_ICEJAVE = 11,
	CRI_SKILLSE_LEVIATHAN_LV_CHARA04 = 14,
	CRI_SKILLSE_LEVIATHAN_LV_CHARA05 = 40,
	CRI_SKILLSE_LEVIATHAN_LV_FISH02 = 19,
	CRI_SKILLSE_LEVIATHAN_LV_FISH01 = 18,
	CRI_SKILLSE_LEVIATHAN_LV_SPLASH01 = 16
}
