public static class SkillSE_GOUKIi
{
	public const int iCRI_SKILLSE_GOUKI_CUENUM = 6;

	public const int iCRI_SKILLSE_GOUKI_GO_CHARA01 = 40;

	public const int iCRI_SKILLSE_GOUKI_GO_START01 = 80;

	public const int iCRI_SKILLSE_GOUKI_GO_SPINING = 1;

	public const int iCRI_SKILLSE_GOUKI_GO_SHUNGOKUSATSU03 = 5;

	public const int iCRI_SKILLSE_GOUKI_GO_SHUNGOKUSATSU01 = 3;

	public const int iCRI_SKILLSE_GOUKI_GO_SHUNGOKUSATSU02 = 4;

	public const SkillSE_GOUKI CRI_SKILLSE_GOUKI_CUENUM = SkillSE_GOUKI.CRI_SKILLSE_GOUKI_CUENUM;

	public const SkillSE_GOUKI CRI_SKILLSE_GOUKI_GO_CHARA01 = SkillSE_GOUKI.CRI_SKILLSE_GOUKI_GO_CHARA01;

	public const SkillSE_GOUKI CRI_SKILLSE_GOUKI_GO_START01 = SkillSE_GOUKI.CRI_SKILLSE_GOUKI_GO_START01;

	public const SkillSE_GOUKI CRI_SKILLSE_GOUKI_GO_SPINING = SkillSE_GOUKI.CRI_SKILLSE_GOUKI_GO_SPINING;

	public const SkillSE_GOUKI CRI_SKILLSE_GOUKI_GO_SHUNGOKUSATSU03 = SkillSE_GOUKI.CRI_SKILLSE_GOUKI_GO_SHUNGOKUSATSU03;

	public const SkillSE_GOUKI CRI_SKILLSE_GOUKI_GO_SHUNGOKUSATSU01 = SkillSE_GOUKI.CRI_SKILLSE_GOUKI_GO_SHUNGOKUSATSU01;

	public const SkillSE_GOUKI CRI_SKILLSE_GOUKI_GO_SHUNGOKUSATSU02 = SkillSE_GOUKI.CRI_SKILLSE_GOUKI_GO_SHUNGOKUSATSU02;
}
