public static class SkillSE_FORTEi
{
	public const int iCRI_SKILLSE_FORTE_CUENUM = 12;

	public const int iCRI_SKILLSE_FORTE_FO_CHARA01 = 40;

	public const int iCRI_SKILLSE_FORTE_FO_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_FORTE_FO_CHARGESHOT_L = 5;

	public const int iCRI_SKILLSE_FORTE_FO_CHARGESHOT_M = 4;

	public const int iCRI_SKILLSE_FORTE_FO_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_FORTE_FO_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_FORTE_FO_KICK = 7;

	public const int iCRI_SKILLSE_FORTE_FO_CHARA02 = 41;

	public const int iCRI_SKILLSE_FORTE_FO_START02 = 81;

	public const int iCRI_SKILLSE_FORTE_FO_BUSTER01 = 9;

	public const int iCRI_SKILLSE_FORTE_FO_LAZER = 12;

	public const int iCRI_SKILLSE_FORTE_FO_BUSTER02 = 10;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_CUENUM = SkillSE_FORTE.CRI_SKILLSE_FORTE_CUENUM;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_CHARA01 = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_CHARA01;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_CHARGE_LP = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_CHARGE_LP;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_CHARGESHOT_L = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_CHARGESHOT_L;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_CHARGESHOT_M = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_CHARGESHOT_M;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_CHARGESHOT_S = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_CHARGESHOT_S;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_CHARGE_STOP = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_CHARGE_STOP;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_KICK = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_KICK;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_CHARA02 = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_CHARA02;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_START02 = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_START02;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_BUSTER01 = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_BUSTER01;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_LAZER = SkillSE_FORTE.CRI_SKILLSE_FORTE_CUENUM;

	public const SkillSE_FORTE CRI_SKILLSE_FORTE_FO_BUSTER02 = SkillSE_FORTE.CRI_SKILLSE_FORTE_FO_BUSTER02;
}
