public enum SkillSE_ROCKMAN2
{
	NONE = 0,
	CRI_SKILLSE_ROCKMAN2_CUENUM = 7,
	CRI_SKILLSE_ROCKMAN2_RM2_CHARGE_LP = 1,
	CRI_SKILLSE_ROCKMAN2_RM2_CHARGE_STOP = 2,
	CRI_SKILLSE_ROCKMAN2_RM2_CHARGESHOT_L = 5,
	CRI_SKILLSE_ROCKMAN2_RM2_CHARGESHOT_S = 3,
	CRI_SKILLSE_ROCKMAN2_RM2_BEAT01 = 7,
	CRI_SKILLSE_ROCKMAN2_RM2_JUMP_3 = 6,
	CRI_SKILLSE_ROCKMAN2_RM2_CHARGEMAX = 4
}
