public enum SkillSE_KARNEL
{
	NONE = 0,
	CRI_SKILLSE_KARNEL_CUENUM = 4,
	CRI_SKILLSE_KARNEL_KN_TELEPORT01 = 1,
	CRI_SKILLSE_KARNEL_KN_TELEPORT02 = 2,
	CRI_SKILLSE_KARNEL_KN_GROUND01 = 4,
	CRI_SKILLSE_KARNEL_KN_CHARA01 = 40
}
