public enum SkillSE_RMSS
{
	NONE = 0,
	CRI_SKILLSE_RMSS_CUENUM = 8,
	CRI_SKILLSE_RMSS_RS_CHARGESHOT_S = 1,
	CRI_SKILLSE_RMSS_RS_CHARGESHOT_M = 2,
	CRI_SKILLSE_RMSS_RS_CHARGESHOT_L = 3,
	CRI_SKILLSE_RMSS_RS_CHARGE_LP = 4,
	CRI_SKILLSE_RMSS_RS_CHARGE_STOP = 5,
	CRI_SKILLSE_RMSS_RS_AIRSPREAD01 = 7,
	CRI_SKILLSE_RMSS_RS_CHARA01 = 40,
	CRI_SKILLSE_RMSS_RS_START01 = 80
}
