public enum SkillSE_PALETTE
{
	NONE = 0,
	CRI_SKILLSE_PALETTE_CUENUM = 8,
	CRI_SKILLSE_PALETTE_PL_PLASMAGUN = 1,
	CRI_SKILLSE_PALETTE_PL_BLACKARROW = 4,
	CRI_SKILLSE_PALETTE_PL_PLASMAGUN02 = 2,
	CRI_SKILLSE_PALETTE_PL_CHARA01 = 40,
	CRI_SKILLSE_PALETTE_PL_ICEMISSILE01 = 6,
	CRI_SKILLSE_PALETTE_PL_WATERGUN02 = 9,
	CRI_SKILLSE_PALETTE_PL_WATERGUN01 = 8,
	CRI_SKILLSE_PALETTE_PL_START01 = 80
}
