public static class SkillSE_AwakenZeroi
{
	public const int iCRI_SKILLSE_AWAKENZERO_CUENUM = 16;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU01 = 1;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU02_LP = 2;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU02_STOP = 3;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_GENMU01 = 4;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_GENMU02_LP = 5;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_GENMU02_STOP = 6;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_CHARA01 = 7;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_CHARA04 = 40;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_CHARA02 = 8;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_RED02 = 11;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_BLOOD = 17;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_START04 = 80;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_RING01 = 13;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_RED01 = 10;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_RING02_LP = 14;

	public const int iCRI_SKILLSE_AWAKENZERO_ZA_RING02_STOP = 15;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_CUENUM = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_CUENUM;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU01 = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU01;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU02_LP = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU02_LP;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU02_STOP = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU02_STOP;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_GENMU01 = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_GENMU01;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_GENMU02_LP = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_GENMU02_LP;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_GENMU02_STOP = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_GENMU02_STOP;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_CHARA01 = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_CHARA01;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_CHARA04 = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_CHARA04;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_CHARA02 = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_CHARA02;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_RED02 = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_RED02;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_BLOOD = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_BLOOD;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_START04 = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_START04;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_RING01 = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_RING01;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_RED01 = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_RED01;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_RING02_LP = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_RING02_LP;

	public const SkillSE_AwakenZero CRI_SKILLSE_AWAKENZERO_ZA_RING02_STOP = SkillSE_AwakenZero.CRI_SKILLSE_AWAKENZERO_ZA_RING02_STOP;
}
