public static class SkillSE_RICO2i
{
	public const int iCRI_SKILLSE_RICO2_CUENUM = 23;

	public const int iCRI_SKILLSE_RICO2_RI2_CHARA01_1 = 40;

	public const int iCRI_SKILLSE_RICO2_RI2_CHARA01_2 = 41;

	public const int iCRI_SKILLSE_RICO2_RI2_START01 = 80;

	public const int iCRI_SKILLSE_RICO2_RI2_FIRE01 = 4;

	public const int iCRI_SKILLSE_RICO2_RI2_FIRE02 = 5;

	public const int iCRI_SKILLSE_RICO2_RI2_ICE01 = 1;

	public const int iCRI_SKILLSE_RICO2_RI2_ICE02 = 2;

	public const int iCRI_SKILLSE_RICO2_RI2_START02 = 81;

	public const int iCRI_SKILLSE_RICO2_RI2_PLASMA01 = 7;

	public const int iCRI_SKILLSE_RICO2_RI2_PLASMA02_LP = 8;

	public const int iCRI_SKILLSE_RICO2_RI2_PLASMA02_STOP = 9;

	public const int iCRI_SKILLSE_RICO2_RI2_CROSS01 = 10;

	public const int iCRI_SKILLSE_RICO2_RI2_CROSS02 = 11;

	public const int iCRI_SKILLSE_RICO2_RI2_CROSS03 = 12;

	public const int iCRI_SKILLSE_RICO2_RI2_BUSTER = 13;

	public const int iCRI_SKILLSE_RICO2_RI2_GENMU01 = 15;

	public const int iCRI_SKILLSE_RICO2_RI2_GENMU02 = 16;

	public const int iCRI_SKILLSE_RICO2_RI2_RAIKOU = 17;

	public const int iCRI_SKILLSE_RICO2_RI2_REKKOU = 18;

	public const int iCRI_SKILLSE_RICO2_RI2_FIELD_LP = 20;

	public const int iCRI_SKILLSE_RICO2_RI2_FIELD_STOP = 21;

	public const int iCRI_SKILLSE_RICO2_RI2_MISSILE = 22;

	public const int iCRI_SKILLSE_RICO2_RI2_CHARA02 = 42;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_CUENUM = SkillSE_RICO2.CRI_SKILLSE_RICO2_CUENUM;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_CHARA01_1 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_CHARA01_1;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_CHARA01_2 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_CHARA01_2;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_START01 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_START01;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_FIRE01 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_FIRE01;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_FIRE02 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_FIRE02;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_ICE01 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_ICE01;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_ICE02 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_ICE02;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_START02 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_START02;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_PLASMA01 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_PLASMA01;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_PLASMA02_LP = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_PLASMA02_LP;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_PLASMA02_STOP = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_PLASMA02_STOP;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_CROSS01 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_CROSS01;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_CROSS02 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_CROSS02;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_CROSS03 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_CROSS03;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_BUSTER = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_BUSTER;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_GENMU01 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_GENMU01;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_GENMU02 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_GENMU02;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_RAIKOU = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_RAIKOU;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_REKKOU = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_REKKOU;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_FIELD_LP = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_FIELD_LP;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_FIELD_STOP = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_FIELD_STOP;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_MISSILE = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_MISSILE;

	public const SkillSE_RICO2 CRI_SKILLSE_RICO2_RI2_CHARA02 = SkillSE_RICO2.CRI_SKILLSE_RICO2_RI2_CHARA02;
}
