public enum SkillSE_XMH
{
	NONE = 0,
	CRI_SKILLSE_XMH_CUENUM = 9,
	CRI_SKILLSE_XMH_XM_CHARA01 = 40,
	CRI_SKILLSE_XMH_XM_START01 = 80,
	CRI_SKILLSE_XMH_XM_TAME01 = 1,
	CRI_SKILLSE_XMH_XM_FIREBREATH01 = 4,
	CRI_SKILLSE_XMH_XM_FIREBREATH02 = 5,
	CRI_SKILLSE_XMH_XM_TAME02 = 2,
	CRI_SKILLSE_XMH_XM_RENGOKU_LP = 6,
	CRI_SKILLSE_XMH_XM_RENGOKU_STOP = 7,
	CRI_SKILLSE_XMH_XM_STORY01 = 60
}
