public static class SkillSE_ROLLCASi
{
	public const int iCRI_SKILLSE_ROLLCAS_CUENUM = 4;

	public const int iCRI_SKILLSE_ROLLCAS_RC_WRENCH = 1;

	public const int iCRI_SKILLSE_ROLLCAS_RC_CHARA01 = 40;

	public const int iCRI_SKILLSE_ROLLCAS_RC_START01 = 80;

	public const int iCRI_SKILLSE_ROLLCAS_RC_REMOTE = 3;

	public const SkillSE_ROLLCAS CRI_SKILLSE_ROLLCAS_CUENUM = SkillSE_ROLLCAS.CRI_SKILLSE_ROLLCAS_CUENUM;

	public const SkillSE_ROLLCAS CRI_SKILLSE_ROLLCAS_RC_WRENCH = SkillSE_ROLLCAS.CRI_SKILLSE_ROLLCAS_RC_WRENCH;

	public const SkillSE_ROLLCAS CRI_SKILLSE_ROLLCAS_RC_CHARA01 = SkillSE_ROLLCAS.CRI_SKILLSE_ROLLCAS_RC_CHARA01;

	public const SkillSE_ROLLCAS CRI_SKILLSE_ROLLCAS_RC_START01 = SkillSE_ROLLCAS.CRI_SKILLSE_ROLLCAS_RC_START01;

	public const SkillSE_ROLLCAS CRI_SKILLSE_ROLLCAS_RC_REMOTE = SkillSE_ROLLCAS.CRI_SKILLSE_ROLLCAS_RC_REMOTE;
}
