public static class SkillSE_XDive2i
{
	public const int iCRI_SKILLSE_XDIVE2_CUENUM = 17;

	public const int iCRI_SKILLSE_XDIVE2_XD2_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_XDIVE2_XD2_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_M = 4;

	public const int iCRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_L = 5;

	public const int iCRI_SKILLSE_XDIVE2_XD2_FIELD_LP = 17;

	public const int iCRI_SKILLSE_XDIVE2_XD2_PLASMA_LP = 8;

	public const int iCRI_SKILLSE_XDIVE2_XD2_PLASMA_STOP = 9;

	public const int iCRI_SKILLSE_XDIVE2_XD2_FIELD_STOP = 18;

	public const int iCRI_SKILLSE_XDIVE2_XD2_CHARA01 = 40;

	public const int iCRI_SKILLSE_XDIVE2_XD2_CHARGELVUP = 6;

	public const int iCRI_SKILLSE_XDIVE2_XD2_CHARGEMAX = 7;

	public const int iCRI_SKILLSE_XDIVE2_XD2_WORLD02 = 12;

	public const int iCRI_SKILLSE_XDIVE2_XD2_WORLD01 = 11;

	public const int iCRI_SKILLSE_XDIVE2_XD2_NOVA = 14;

	public const int iCRI_SKILLSE_XDIVE2_XD2_SWORD = 16;

	public const int iCRI_SKILLSE_XDIVE2_XD2_START01 = 80;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_CUENUM = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_CUENUM;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_CHARGE_LP = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_CHARGE_LP;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_CHARGE_STOP = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_CHARGE_STOP;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_S = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_S;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_M = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_M;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_L = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_CHARGESHOT_L;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_FIELD_LP = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_CUENUM;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_PLASMA_LP = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_PLASMA_LP;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_PLASMA_STOP = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_PLASMA_STOP;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_FIELD_STOP = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_FIELD_STOP;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_CHARA01 = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_CHARA01;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_CHARGELVUP = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_CHARGELVUP;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_CHARGEMAX = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_CHARGEMAX;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_WORLD02 = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_WORLD02;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_WORLD01 = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_WORLD01;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_NOVA = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_NOVA;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_SWORD = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_SWORD;

	public const SkillSE_XDive2 CRI_SKILLSE_XDIVE2_XD2_START01 = SkillSE_XDive2.CRI_SKILLSE_XDIVE2_XD2_START01;
}
