public enum SkillSE_AwakenZero
{
	NONE = 0,
	CRI_SKILLSE_AWAKENZERO_CUENUM = 16,
	CRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU01 = 1,
	CRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU02_LP = 2,
	CRI_SKILLSE_AWAKENZERO_ZA_SHINGETSU02_STOP = 3,
	CRI_SKILLSE_AWAKENZERO_ZA_GENMU01 = 4,
	CRI_SKILLSE_AWAKENZERO_ZA_GENMU02_LP = 5,
	CRI_SKILLSE_AWAKENZERO_ZA_GENMU02_STOP = 6,
	CRI_SKILLSE_AWAKENZERO_ZA_CHARA01 = 7,
	CRI_SKILLSE_AWAKENZERO_ZA_CHARA04 = 40,
	CRI_SKILLSE_AWAKENZERO_ZA_CHARA02 = 8,
	CRI_SKILLSE_AWAKENZERO_ZA_RED02 = 11,
	CRI_SKILLSE_AWAKENZERO_ZA_BLOOD = 17,
	CRI_SKILLSE_AWAKENZERO_ZA_START04 = 80,
	CRI_SKILLSE_AWAKENZERO_ZA_RING01 = 13,
	CRI_SKILLSE_AWAKENZERO_ZA_RED01 = 10,
	CRI_SKILLSE_AWAKENZERO_ZA_RING02_LP = 14,
	CRI_SKILLSE_AWAKENZERO_ZA_RING02_STOP = 15
}
