public enum SkillSE_ZERO
{
	NONE = 0,
	CRI_SKILLSE_ZERO_CUENUM = 9,
	CRI_SKILLSE_ZERO_Z_RYUEN = 1,
	CRI_SKILLSE_ZERO_Z_RAKUOU = 7,
	CRI_SKILLSE_ZERO_Z_DASH01 = 2,
	CRI_SKILLSE_ZERO_Z_DASH03 = 4,
	CRI_SKILLSE_ZERO_Z_DASH02 = 3,
	CRI_SKILLSE_ZERO_Z_BLADE = 6,
	CRI_SKILLSE_ZERO_Z_CHARA02 = 41,
	CRI_SKILLSE_ZERO_Z_RYUENBU = 8,
	CRI_SKILLSE_ZERO_Z_CHARA03 = 42
}
