public enum SkillSE_ROCKVOL
{
	NONE = 0,
	CRI_SKILLSE_ROCKVOL_CUENUM = 9,
	CRI_SKILLSE_ROCKVOL_RV_LAZER = 1,
	CRI_SKILLSE_ROCKVOL_RV_CRUSHER_LP = 2,
	CRI_SKILLSE_ROCKVOL_RV_CRUSHER_STOP = 3,
	CRI_SKILLSE_ROCKVOL_RV_CHARA01 = 40,
	CRI_SKILLSE_ROCKVOL_RV_ZIHANKI01 = 5,
	CRI_SKILLSE_ROCKVOL_RV_ZIHANKI02 = 6,
	CRI_SKILLSE_ROCKVOL_RV_HAIJO = 8,
	CRI_SKILLSE_ROCKVOL_RV_CHARA02 = 41,
	CRI_SKILLSE_ROCKVOL_RV_START01 = 80
}
