public enum SkillSE_AbsoZERO
{
	NONE = 0,
	CRI_SKILLSE_ABSOZERO_CUENUM = 6,
	CRI_SKILLSE_ABSOZERO_ZB_START01 = 80,
	CRI_SKILLSE_ABSOZERO_ZB_KARA01 = 5,
	CRI_SKILLSE_ABSOZERO_ZB_CRIMZON01 = 1,
	CRI_SKILLSE_ABSOZERO_ZB_KARA02_LG = 6,
	CRI_SKILLSE_ABSOZERO_ZB_CHARA01 = 40,
	CRI_SKILLSE_ABSOZERO_ZB_KARA02_STOP = 7
}
