public static class SkillSE_IRIS4i
{
	public const int iCRI_SKILLSE_IRIS4_CUENUM = 6;

	public const int iCRI_SKILLSE_IRIS4_IR4_CHARA01 = 40;

	public const int iCRI_SKILLSE_IRIS4_IR4_RING = 1;

	public const int iCRI_SKILLSE_IRIS4_IR4_BLADE01 = 3;

	public const int iCRI_SKILLSE_IRIS4_IR4_BLADE03 = 5;

	public const int iCRI_SKILLSE_IRIS4_IR4_START01 = 80;

	public const int iCRI_SKILLSE_IRIS4_IR4_ELECTRIC = 8;

	public const SkillSE_IRIS4 CRI_SKILLSE_IRIS4_CUENUM = SkillSE_IRIS4.CRI_SKILLSE_IRIS4_CUENUM;

	public const SkillSE_IRIS4 CRI_SKILLSE_IRIS4_IR4_CHARA01 = SkillSE_IRIS4.CRI_SKILLSE_IRIS4_IR4_CHARA01;

	public const SkillSE_IRIS4 CRI_SKILLSE_IRIS4_IR4_RING = SkillSE_IRIS4.CRI_SKILLSE_IRIS4_IR4_RING;

	public const SkillSE_IRIS4 CRI_SKILLSE_IRIS4_IR4_BLADE01 = SkillSE_IRIS4.CRI_SKILLSE_IRIS4_IR4_BLADE01;

	public const SkillSE_IRIS4 CRI_SKILLSE_IRIS4_IR4_BLADE03 = SkillSE_IRIS4.CRI_SKILLSE_IRIS4_IR4_BLADE03;

	public const SkillSE_IRIS4 CRI_SKILLSE_IRIS4_IR4_START01 = SkillSE_IRIS4.CRI_SKILLSE_IRIS4_IR4_START01;

	public const SkillSE_IRIS4 CRI_SKILLSE_IRIS4_IR4_ELECTRIC = SkillSE_IRIS4.CRI_SKILLSE_IRIS4_IR4_ELECTRIC;
}
