public static class SkillSE_VAVAi
{
	public const int iCRI_SKILLSE_VAVA_CUENUM = 10;

	public const int iCRI_SKILLSE_VAVA_VA_SAKURETSU = 1;

	public const int iCRI_SKILLSE_VAVA_VA_DENGEKI = 2;

	public const int iCRI_SKILLSE_VAVA_VA_WINGBOOMERANG = 3;

	public const int iCRI_SKILLSE_VAVA_VA_PBOMB = 4;

	public const int iCRI_SKILLSE_VAVA_VA_CHARA01 = 5;

	public const int iCRI_SKILLSE_VAVA_VA_START01 = 6;

	public const int iCRI_SKILLSE_VAVA_VA_BB01 = 7;

	public const int iCRI_SKILLSE_VAVA_VA_BB02 = 8;

	public const int iCRI_SKILLSE_VAVA_VA_FIRE = 9;

	public const int iCRI_SKILLSE_VAVA_VA_CHARA02 = 40;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_CUENUM = SkillSE_VAVA.CRI_SKILLSE_VAVA_CUENUM;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_VA_SAKURETSU = SkillSE_VAVA.CRI_SKILLSE_VAVA_VA_SAKURETSU;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_VA_DENGEKI = SkillSE_VAVA.CRI_SKILLSE_VAVA_VA_DENGEKI;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_VA_WINGBOOMERANG = SkillSE_VAVA.CRI_SKILLSE_VAVA_VA_WINGBOOMERANG;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_VA_PBOMB = SkillSE_VAVA.CRI_SKILLSE_VAVA_VA_PBOMB;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_VA_CHARA01 = SkillSE_VAVA.CRI_SKILLSE_VAVA_VA_CHARA01;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_VA_START01 = SkillSE_VAVA.CRI_SKILLSE_VAVA_VA_START01;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_VA_BB01 = SkillSE_VAVA.CRI_SKILLSE_VAVA_VA_BB01;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_VA_BB02 = SkillSE_VAVA.CRI_SKILLSE_VAVA_VA_BB02;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_VA_FIRE = SkillSE_VAVA.CRI_SKILLSE_VAVA_VA_FIRE;

	public const SkillSE_VAVA CRI_SKILLSE_VAVA_VA_CHARA02 = SkillSE_VAVA.CRI_SKILLSE_VAVA_VA_CHARA02;
}
