public static class SkillSE_ROCKMAN2i
{
	public const int iCRI_SKILLSE_ROCKMAN2_CUENUM = 7;

	public const int iCRI_SKILLSE_ROCKMAN2_RM2_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_ROCKMAN2_RM2_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_ROCKMAN2_RM2_CHARGESHOT_L = 5;

	public const int iCRI_SKILLSE_ROCKMAN2_RM2_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_ROCKMAN2_RM2_BEAT01 = 7;

	public const int iCRI_SKILLSE_ROCKMAN2_RM2_JUMP_3 = 6;

	public const int iCRI_SKILLSE_ROCKMAN2_RM2_CHARGEMAX = 4;

	public const SkillSE_ROCKMAN2 CRI_SKILLSE_ROCKMAN2_CUENUM = SkillSE_ROCKMAN2.CRI_SKILLSE_ROCKMAN2_CUENUM;

	public const SkillSE_ROCKMAN2 CRI_SKILLSE_ROCKMAN2_RM2_CHARGE_LP = SkillSE_ROCKMAN2.CRI_SKILLSE_ROCKMAN2_RM2_CHARGE_LP;

	public const SkillSE_ROCKMAN2 CRI_SKILLSE_ROCKMAN2_RM2_CHARGE_STOP = SkillSE_ROCKMAN2.CRI_SKILLSE_ROCKMAN2_RM2_CHARGE_STOP;

	public const SkillSE_ROCKMAN2 CRI_SKILLSE_ROCKMAN2_RM2_CHARGESHOT_L = SkillSE_ROCKMAN2.CRI_SKILLSE_ROCKMAN2_RM2_CHARGESHOT_L;

	public const SkillSE_ROCKMAN2 CRI_SKILLSE_ROCKMAN2_RM2_CHARGESHOT_S = SkillSE_ROCKMAN2.CRI_SKILLSE_ROCKMAN2_RM2_CHARGESHOT_S;

	public const SkillSE_ROCKMAN2 CRI_SKILLSE_ROCKMAN2_RM2_BEAT01 = SkillSE_ROCKMAN2.CRI_SKILLSE_ROCKMAN2_CUENUM;

	public const SkillSE_ROCKMAN2 CRI_SKILLSE_ROCKMAN2_RM2_JUMP_3 = SkillSE_ROCKMAN2.CRI_SKILLSE_ROCKMAN2_RM2_JUMP_3;

	public const SkillSE_ROCKMAN2 CRI_SKILLSE_ROCKMAN2_RM2_CHARGEMAX = SkillSE_ROCKMAN2.CRI_SKILLSE_ROCKMAN2_RM2_CHARGEMAX;
}
