public static class SkillSE_CINNAMONi
{
	public const int iCRI_SKILLSE_CINNAMON_CUENUM = 9;

	public const int iCRI_SKILLSE_CINNAMON_CM_HEART01 = 2;

	public const int iCRI_SKILLSE_CINNAMON_CM_HEART02 = 4;

	public const int iCRI_SKILLSE_CINNAMON_CM_ENGEL = 1;

	public const int iCRI_SKILLSE_CINNAMON_CM_INJECTION = 3;

	public const int iCRI_SKILLSE_CINNAMON_CM_LOVE = 5;

	public const int iCRI_SKILLSE_CINNAMON_CM_CHARA01 = 9;

	public const int iCRI_SKILLSE_CINNAMON_CM_START01 = 10;

	public const int iCRI_SKILLSE_CINNAMON_CM_BATSU = 6;

	public const int iCRI_SKILLSE_CINNAMON_CM_HANE = 7;

	public const SkillSE_CINNAMON CRI_SKILLSE_CINNAMON_CUENUM = SkillSE_CINNAMON.CRI_SKILLSE_CINNAMON_CUENUM;

	public const SkillSE_CINNAMON CRI_SKILLSE_CINNAMON_CM_HEART01 = SkillSE_CINNAMON.CRI_SKILLSE_CINNAMON_CM_HEART01;

	public const SkillSE_CINNAMON CRI_SKILLSE_CINNAMON_CM_HEART02 = SkillSE_CINNAMON.CRI_SKILLSE_CINNAMON_CM_HEART02;

	public const SkillSE_CINNAMON CRI_SKILLSE_CINNAMON_CM_ENGEL = SkillSE_CINNAMON.CRI_SKILLSE_CINNAMON_CM_ENGEL;

	public const SkillSE_CINNAMON CRI_SKILLSE_CINNAMON_CM_INJECTION = SkillSE_CINNAMON.CRI_SKILLSE_CINNAMON_CM_INJECTION;

	public const SkillSE_CINNAMON CRI_SKILLSE_CINNAMON_CM_LOVE = SkillSE_CINNAMON.CRI_SKILLSE_CINNAMON_CM_LOVE;

	public const SkillSE_CINNAMON CRI_SKILLSE_CINNAMON_CM_CHARA01 = SkillSE_CINNAMON.CRI_SKILLSE_CINNAMON_CUENUM;

	public const SkillSE_CINNAMON CRI_SKILLSE_CINNAMON_CM_START01 = SkillSE_CINNAMON.CRI_SKILLSE_CINNAMON_CM_START01;

	public const SkillSE_CINNAMON CRI_SKILLSE_CINNAMON_CM_BATSU = SkillSE_CINNAMON.CRI_SKILLSE_CINNAMON_CM_BATSU;

	public const SkillSE_CINNAMON CRI_SKILLSE_CINNAMON_CM_HANE = SkillSE_CINNAMON.CRI_SKILLSE_CINNAMON_CM_HANE;
}
