public enum SkillSE_HARPNOTE
{
	NONE = 0,
	CRI_SKILLSE_HARPNOTE_CUENUM = 10,
	CRI_SKILLSE_HARPNOTE_HN_STRING02 = 2,
	CRI_SKILLSE_HARPNOTE_HN_STRING01 = 1,
	CRI_SKILLSE_HARPNOTE_HN_PULSESONG01 = 4,
	CRI_SKILLSE_HARPNOTE_HN_SPEAKER01_LP = 7,
	CRI_SKILLSE_HARPNOTE_HN_SPEAKER01_STOP = 8,
	CRI_SKILLSE_HARPNOTE_HN_PULSESONG03 = 6,
	CRI_SKILLSE_HARPNOTE_HN_PULSESONG02 = 5,
	CRI_SKILLSE_HARPNOTE_HN_SPEAKER02 = 9,
	CRI_SKILLSE_HARPNOTE_HN_CHARA01 = 40,
	CRI_SKILLSE_HARPNOTE_HN_START01 = 80
}
