public static class SkillSE_VIAi
{
	public const int iCRI_SKILLSE_VIA_CUENUM = 17;

	public const int iCRI_SKILLSE_VIA_VI_SOU02 = 2;

	public const int iCRI_SKILLSE_VIA_VI_SOU01 = 1;

	public const int iCRI_SKILLSE_VIA_VI_SOU03_LP = 3;

	public const int iCRI_SKILLSE_VIA_VI_SOU03_STOP = 4;

	public const int iCRI_SKILLSE_VIA_VI_KIZIN = 9;

	public const int iCRI_SKILLSE_VIA_VI_CHARA01 = 40;

	public const int iCRI_SKILLSE_VIA_VI_START01 = 80;

	public const int iCRI_SKILLSE_VIA_VI_START02 = 81;

	public const int iCRI_SKILLSE_VIA_VI_ZIN02 = 7;

	public const int iCRI_SKILLSE_VIA_VI_ZIN01 = 6;

	public const int iCRI_SKILLSE_VIA_VI_CHARA02 = 41;

	public const int iCRI_SKILLSE_VIA_VI_GOAST01 = 11;

	public const int iCRI_SKILLSE_VIA_VI_GOAST02 = 12;

	public const int iCRI_SKILLSE_VIA_VI_PUMPKIN01 = 14;

	public const int iCRI_SKILLSE_VIA_VI_PUMPKIN02_LP = 15;

	public const int iCRI_SKILLSE_VIA_VI_PUMPKIN03 = 17;

	public const int iCRI_SKILLSE_VIA_VI_PUMPKIN02_STOP = 16;

	public const SkillSE_VIA CRI_SKILLSE_VIA_CUENUM = SkillSE_VIA.CRI_SKILLSE_VIA_CUENUM;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_SOU02 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_SOU02;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_SOU01 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_SOU01;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_SOU03_LP = SkillSE_VIA.CRI_SKILLSE_VIA_VI_SOU03_LP;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_SOU03_STOP = SkillSE_VIA.CRI_SKILLSE_VIA_VI_SOU03_STOP;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_KIZIN = SkillSE_VIA.CRI_SKILLSE_VIA_VI_KIZIN;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_CHARA01 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_CHARA01;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_START01 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_START01;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_START02 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_START02;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_ZIN02 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_ZIN02;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_ZIN01 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_ZIN01;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_CHARA02 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_CHARA02;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_GOAST01 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_GOAST01;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_GOAST02 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_GOAST02;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_PUMPKIN01 = SkillSE_VIA.CRI_SKILLSE_VIA_VI_PUMPKIN01;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_PUMPKIN02_LP = SkillSE_VIA.CRI_SKILLSE_VIA_VI_PUMPKIN02_LP;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_PUMPKIN03 = SkillSE_VIA.CRI_SKILLSE_VIA_CUENUM;

	public const SkillSE_VIA CRI_SKILLSE_VIA_VI_PUMPKIN02_STOP = SkillSE_VIA.CRI_SKILLSE_VIA_VI_PUMPKIN02_STOP;
}
