public static class SkillSE_DRRIGHTi
{
	public const int iCRI_SKILLSE_DRRIGHT_CUENUM = 7;

	public const int iCRI_SKILLSE_DRRIGHT_DR_CHARA01 = 40;

	public const int iCRI_SKILLSE_DRRIGHT_DR_START01 = 80;

	public const int iCRI_SKILLSE_DRRIGHT_DR_HADOU01 = 1;

	public const int iCRI_SKILLSE_DRRIGHT_DR_HADOU03 = 3;

	public const int iCRI_SKILLSE_DRRIGHT_DR_HADOU02 = 2;

	public const int iCRI_SKILLSE_DRRIGHT_DR_RENDA01 = 5;

	public const int iCRI_SKILLSE_DRRIGHT_DR_RENDA02 = 6;

	public const SkillSE_DRRIGHT CRI_SKILLSE_DRRIGHT_CUENUM = SkillSE_DRRIGHT.CRI_SKILLSE_DRRIGHT_CUENUM;

	public const SkillSE_DRRIGHT CRI_SKILLSE_DRRIGHT_DR_CHARA01 = SkillSE_DRRIGHT.CRI_SKILLSE_DRRIGHT_DR_CHARA01;

	public const SkillSE_DRRIGHT CRI_SKILLSE_DRRIGHT_DR_START01 = SkillSE_DRRIGHT.CRI_SKILLSE_DRRIGHT_DR_START01;

	public const SkillSE_DRRIGHT CRI_SKILLSE_DRRIGHT_DR_HADOU01 = SkillSE_DRRIGHT.CRI_SKILLSE_DRRIGHT_DR_HADOU01;

	public const SkillSE_DRRIGHT CRI_SKILLSE_DRRIGHT_DR_HADOU03 = SkillSE_DRRIGHT.CRI_SKILLSE_DRRIGHT_DR_HADOU03;

	public const SkillSE_DRRIGHT CRI_SKILLSE_DRRIGHT_DR_HADOU02 = SkillSE_DRRIGHT.CRI_SKILLSE_DRRIGHT_DR_HADOU02;

	public const SkillSE_DRRIGHT CRI_SKILLSE_DRRIGHT_DR_RENDA01 = SkillSE_DRRIGHT.CRI_SKILLSE_DRRIGHT_DR_RENDA01;

	public const SkillSE_DRRIGHT CRI_SKILLSE_DRRIGHT_DR_RENDA02 = SkillSE_DRRIGHT.CRI_SKILLSE_DRRIGHT_DR_RENDA02;
}
