public enum SkillSE_IRIS
{
	NONE = 0,
	CRI_SKILLSE_IRIS_CUENUM = 16,
	CRI_SKILLSE_IRIS_IR_CHARA01 = 8,
	CRI_SKILLSE_IRIS_IR_FUYU01 = 1,
	CRI_SKILLSE_IRIS_IR_KATSUBOU = 3,
	CRI_SKILLSE_IRIS_IR_FUYU02 = 2,
	CRI_SKILLSE_IRIS_IR_HEARTBEAM = 4,
	CRI_SKILLSE_IRIS_IR_VTGIFT01 = 5,
	CRI_SKILLSE_IRIS_IR_VTGIFT02_LG = 6,
	CRI_SKILLSE_IRIS_IR_VTGIFT02_STOP = 7,
	CRI_SKILLSE_IRIS_IR_CHARA02 = 40,
	CRI_SKILLSE_IRIS_IR_START01 = 80,
	CRI_SKILLSE_IRIS_IR_CHARA03 = 41,
	CRI_SKILLSE_IRIS_IR_START03 = 82,
	CRI_SKILLSE_IRIS_IR_HAMAYA01 = 9,
	CRI_SKILLSE_IRIS_IR_HAMAYA02 = 10,
	CRI_SKILLSE_IRIS_IR_HINODE01 = 12,
	CRI_SKILLSE_IRIS_IR_HINODE02 = 13
}
