public enum SkillSE_XFalcon
{
	NONE = 0,
	CRI_SKILLSE_XFALCON_CUENUM = 10,
	CRI_SKILLSE_XFALCON_XF_CHARGESHOT_S = 3,
	CRI_SKILLSE_XFALCON_XF_CHARGESHOT_M = 4,
	CRI_SKILLSE_XFALCON_XF_CHARGESHOT_L = 5,
	CRI_SKILLSE_XFALCON_XF_CHARGE_LP = 1,
	CRI_SKILLSE_XFALCON_XF_CHARGE_STOP = 2,
	CRI_SKILLSE_XFALCON_XF_FREEMOVE_LP = 7,
	CRI_SKILLSE_XFALCON_XF_FREEMOVE_STOP = 8,
	CRI_SKILLSE_XFALCON_XF_CHARGEMAX = 6,
	CRI_SKILLSE_XFALCON_XF_GIGA01 = 9,
	CRI_SKILLSE_XFALCON_XF_CHARA01 = 40
}
