public enum SkillSE_UltimateX
{
	NONE = 0,
	CRI_SKILLSE_ULTIMATEX_CUENUM = 8,
	CRI_SKILLSE_ULTIMATEX_XU_CHARGE_LP = 1,
	CRI_SKILLSE_ULTIMATEX_XU_CHARGE_STOP = 2,
	CRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_L = 5,
	CRI_SKILLSE_ULTIMATEX_XU_NOVASTRIKE = 7,
	CRI_SKILLSE_ULTIMATEX_XU_PLASMA_LP = 6,
	CRI_SKILLSE_ULTIMATEX_XU_PLASMA_STOP = 8,
	CRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_S = 3,
	CRI_SKILLSE_ULTIMATEX_XU_CHARGESHOT_M = 4
}
