public enum SkillSE_UltimateX2
{
	NONE = 0,
	CRI_SKILLSE_ULTIMATEX2_CUENUM = 4,
	CRI_SKILLSE_ULTIMATEX2_XU2_BUSO01 = 1,
	CRI_SKILLSE_ULTIMATEX2_XU2_BUSO02 = 2,
	CRI_SKILLSE_ULTIMATEX2_XU2_ZENDAN01 = 4,
	CRI_SKILLSE_ULTIMATEX2_XU2_ZENDAN02 = 5
}
