public static class SkillSE_RMSSi
{
	public const int iCRI_SKILLSE_RMSS_CUENUM = 8;

	public const int iCRI_SKILLSE_RMSS_RS_CHARGESHOT_S = 1;

	public const int iCRI_SKILLSE_RMSS_RS_CHARGESHOT_M = 2;

	public const int iCRI_SKILLSE_RMSS_RS_CHARGESHOT_L = 3;

	public const int iCRI_SKILLSE_RMSS_RS_CHARGE_LP = 4;

	public const int iCRI_SKILLSE_RMSS_RS_CHARGE_STOP = 5;

	public const int iCRI_SKILLSE_RMSS_RS_AIRSPREAD01 = 7;

	public const int iCRI_SKILLSE_RMSS_RS_CHARA01 = 40;

	public const int iCRI_SKILLSE_RMSS_RS_START01 = 80;

	public const SkillSE_RMSS CRI_SKILLSE_RMSS_CUENUM = SkillSE_RMSS.CRI_SKILLSE_RMSS_CUENUM;

	public const SkillSE_RMSS CRI_SKILLSE_RMSS_RS_CHARGESHOT_S = SkillSE_RMSS.CRI_SKILLSE_RMSS_RS_CHARGESHOT_S;

	public const SkillSE_RMSS CRI_SKILLSE_RMSS_RS_CHARGESHOT_M = SkillSE_RMSS.CRI_SKILLSE_RMSS_RS_CHARGESHOT_M;

	public const SkillSE_RMSS CRI_SKILLSE_RMSS_RS_CHARGESHOT_L = SkillSE_RMSS.CRI_SKILLSE_RMSS_RS_CHARGESHOT_L;

	public const SkillSE_RMSS CRI_SKILLSE_RMSS_RS_CHARGE_LP = SkillSE_RMSS.CRI_SKILLSE_RMSS_RS_CHARGE_LP;

	public const SkillSE_RMSS CRI_SKILLSE_RMSS_RS_CHARGE_STOP = SkillSE_RMSS.CRI_SKILLSE_RMSS_RS_CHARGE_STOP;

	public const SkillSE_RMSS CRI_SKILLSE_RMSS_RS_AIRSPREAD01 = SkillSE_RMSS.CRI_SKILLSE_RMSS_RS_AIRSPREAD01;

	public const SkillSE_RMSS CRI_SKILLSE_RMSS_RS_CHARA01 = SkillSE_RMSS.CRI_SKILLSE_RMSS_RS_CHARA01;

	public const SkillSE_RMSS CRI_SKILLSE_RMSS_RS_START01 = SkillSE_RMSS.CRI_SKILLSE_RMSS_RS_START01;
}
