public static class SkillSE_TRON2i
{
	public const int iCRI_SKILLSE_TRON2_CUENUM = 12;

	public const int iCRI_SKILLSE_TRON2_TR2_B01 = 1;

	public const int iCRI_SKILLSE_TRON2_TR2_B02 = 2;

	public const int iCRI_SKILLSE_TRON2_TR2_B03 = 3;

	public const int iCRI_SKILLSE_TRON2_TR2_Y01_LP = 5;

	public const int iCRI_SKILLSE_TRON2_TR2_Y01_STOP = 6;

	public const int iCRI_SKILLSE_TRON2_TR2_KBMOLE02_STOP = 9;

	public const int iCRI_SKILLSE_TRON2_TR2_CHARA01 = 40;

	public const int iCRI_SKILLSE_TRON2_TR2_CHARA02 = 41;

	public const int iCRI_SKILLSE_TRON2_TR2_KBMOLE02_LP = 8;

	public const int iCRI_SKILLSE_TRON2_TR2_KBMOLE01 = 7;

	public const int iCRI_SKILLSE_TRON2_TR2_CANNON01 = 11;

	public const int iCRI_SKILLSE_TRON2_TR2_CANNON02 = 12;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_CUENUM = SkillSE_TRON2.CRI_SKILLSE_TRON2_CUENUM;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_B01 = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_B01;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_B02 = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_B02;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_B03 = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_B03;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_Y01_LP = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_Y01_LP;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_Y01_STOP = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_Y01_STOP;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_KBMOLE02_STOP = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_KBMOLE02_STOP;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_CHARA01 = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_CHARA01;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_CHARA02 = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_CHARA02;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_KBMOLE02_LP = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_KBMOLE02_LP;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_KBMOLE01 = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_KBMOLE01;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_CANNON01 = SkillSE_TRON2.CRI_SKILLSE_TRON2_TR2_CANNON01;

	public const SkillSE_TRON2 CRI_SKILLSE_TRON2_TR2_CANNON02 = SkillSE_TRON2.CRI_SKILLSE_TRON2_CUENUM;
}
