public static class SkillSE_RMEXEi
{
	public const int iCRI_SKILLSE_RMEXE_CUENUM = 39;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGE_LP = 1;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGE_STOP = 2;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGESHOT_S = 3;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGESHOT_M = 4;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGESHOT_L = 5;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARA01 = 40;

	public const int iCRI_SKILLSE_RMEXE_RE_START01 = 80;

	public const int iCRI_SKILLSE_RMEXE_RE_BURST = 7;

	public const int iCRI_SKILLSE_RMEXE_RE_BODYGUARD01 = 8;

	public const int iCRI_SKILLSE_RMEXE_RE_BODYGUARD02 = 9;

	public const int iCRI_SKILLSE_RMEXE_RE_POISON_LP = 10;

	public const int iCRI_SKILLSE_RMEXE_RE_POISON_STOP = 11;

	public const int iCRI_SKILLSE_RMEXE_RE_DREAMSWORD = 12;

	public const int iCRI_SKILLSE_RMEXE_RE_PANEL01 = 6;

	public const int iCRI_SKILLSE_RMEXE_RE_PANEL02_1 = 13;

	public const int iCRI_SKILLSE_RMEXE_RE_PANEL02_2 = 14;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGESHOT02_M = 19;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGESHOT02_L = 20;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGE02_LP = 16;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGE02_STOP = 17;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGEMAX02 = 18;

	public const int iCRI_SKILLSE_RMEXE_RE_ROLLING_LP = 21;

	public const int iCRI_SKILLSE_RMEXE_RE_ROLLING_STOP = 22;

	public const int iCRI_SKILLSE_RMEXE_RE_NEOWORLD01 = 24;

	public const int iCRI_SKILLSE_RMEXE_RE_NEOWORLD02 = 25;

	public const int iCRI_SKILLSE_RMEXE_RE_NEOWORLD03 = 26;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARA02 = 41;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGE03_LP = 28;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGE03_STOP = 29;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGESHOT03_S = 30;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGESHOT03_M = 31;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGESHOT03_L = 32;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARGEMAX03 = 33;

	public const int iCRI_SKILLSE_RMEXE_RE_CHARA03 = 42;

	public const int iCRI_SKILLSE_RMEXE_RE_START03 = 82;

	public const int iCRI_SKILLSE_RMEXE_RE_STRIKE = 34;

	public const int iCRI_SKILLSE_RMEXE_RE_DOUBLEDREAM03 = 38;

	public const int iCRI_SKILLSE_RMEXE_RE_DOUBLEDREAM01 = 36;

	public const int iCRI_SKILLSE_RMEXE_RE_DOUBLEDREAM02 = 37;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_CUENUM = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_CUENUM;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGE_LP = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGE_LP;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGE_STOP = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGE_STOP;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGESHOT_S = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGESHOT_S;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGESHOT_M = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGESHOT_M;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGESHOT_L = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGESHOT_L;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARA01 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARA01;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_START01 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_START01;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_BURST = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_BURST;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_BODYGUARD01 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_BODYGUARD01;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_BODYGUARD02 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_BODYGUARD02;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_POISON_LP = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_POISON_LP;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_POISON_STOP = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_POISON_STOP;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_DREAMSWORD = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_DREAMSWORD;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_PANEL01 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_PANEL01;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_PANEL02_1 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_PANEL02_1;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_PANEL02_2 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_PANEL02_2;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGESHOT02_M = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGESHOT02_M;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGESHOT02_L = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGESHOT02_L;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGE02_LP = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGE02_LP;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGE02_STOP = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGE02_STOP;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGEMAX02 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGEMAX02;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_ROLLING_LP = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_ROLLING_LP;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_ROLLING_STOP = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_ROLLING_STOP;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_NEOWORLD01 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_NEOWORLD01;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_NEOWORLD02 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_NEOWORLD02;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_NEOWORLD03 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_NEOWORLD03;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARA02 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARA02;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGE03_LP = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGE03_LP;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGE03_STOP = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGE03_STOP;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGESHOT03_S = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGESHOT03_S;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGESHOT03_M = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGESHOT03_M;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGESHOT03_L = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGESHOT03_L;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARGEMAX03 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARGEMAX03;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_CHARA03 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_CHARA03;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_START03 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_START03;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_STRIKE = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_STRIKE;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_DOUBLEDREAM03 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_DOUBLEDREAM03;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_DOUBLEDREAM01 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_DOUBLEDREAM01;

	public const SkillSE_RMEXE CRI_SKILLSE_RMEXE_RE_DOUBLEDREAM02 = SkillSE_RMEXE.CRI_SKILLSE_RMEXE_RE_DOUBLEDREAM02;
}
