public static class SkillSE_BURAIi
{
	public const int iCRI_SKILLSE_BURAI_CUENUM = 7;

	public const int iCRI_SKILLSE_BURAI_BU_BURAIBRAKE01 = 4;

	public const int iCRI_SKILLSE_BURAI_BU_BURAIBRAKE02 = 5;

	public const int iCRI_SKILLSE_BURAI_BU_CHARA01 = 40;

	public const int iCRI_SKILLSE_BURAI_BU_START01 = 80;

	public const int iCRI_SKILLSE_BURAI_BU_BURAIARTS02 = 3;

	public const int iCRI_SKILLSE_BURAI_BU_BURAIARTS01_1 = 1;

	public const int iCRI_SKILLSE_BURAI_BU_BURAIARTS01_2 = 2;

	public const SkillSE_BURAI CRI_SKILLSE_BURAI_CUENUM = SkillSE_BURAI.CRI_SKILLSE_BURAI_CUENUM;

	public const SkillSE_BURAI CRI_SKILLSE_BURAI_BU_BURAIBRAKE01 = SkillSE_BURAI.CRI_SKILLSE_BURAI_BU_BURAIBRAKE01;

	public const SkillSE_BURAI CRI_SKILLSE_BURAI_BU_BURAIBRAKE02 = SkillSE_BURAI.CRI_SKILLSE_BURAI_BU_BURAIBRAKE02;

	public const SkillSE_BURAI CRI_SKILLSE_BURAI_BU_CHARA01 = SkillSE_BURAI.CRI_SKILLSE_BURAI_BU_CHARA01;

	public const SkillSE_BURAI CRI_SKILLSE_BURAI_BU_START01 = SkillSE_BURAI.CRI_SKILLSE_BURAI_BU_START01;

	public const SkillSE_BURAI CRI_SKILLSE_BURAI_BU_BURAIARTS02 = SkillSE_BURAI.CRI_SKILLSE_BURAI_BU_BURAIARTS02;

	public const SkillSE_BURAI CRI_SKILLSE_BURAI_BU_BURAIARTS01_1 = SkillSE_BURAI.CRI_SKILLSE_BURAI_BU_BURAIARTS01_1;

	public const SkillSE_BURAI CRI_SKILLSE_BURAI_BU_BURAIARTS01_2 = SkillSE_BURAI.CRI_SKILLSE_BURAI_BU_BURAIARTS01_2;
}
