public enum SkillSE_ROLLEXE
{
	NONE = 0,
	CRI_SKILLSE_ROLLEXE_CUENUM = 5,
	CRI_SKILLSE_ROLLEXE_RX_CHARA01 = 40,
	CRI_SKILLSE_ROLLEXE_RX_START01 = 80,
	CRI_SKILLSE_ROLLEXE_RX_ROLLARROW = 4,
	CRI_SKILLSE_ROLLEXE_RX_ROLLWHIP01 = 1,
	CRI_SKILLSE_ROLLEXE_RX_ROLLWHIP02 = 2
}
