public static class SkillSE_PALETTEi
{
	public const int iCRI_SKILLSE_PALETTE_CUENUM = 8;

	public const int iCRI_SKILLSE_PALETTE_PL_PLASMAGUN = 1;

	public const int iCRI_SKILLSE_PALETTE_PL_BLACKARROW = 4;

	public const int iCRI_SKILLSE_PALETTE_PL_PLASMAGUN02 = 2;

	public const int iCRI_SKILLSE_PALETTE_PL_CHARA01 = 40;

	public const int iCRI_SKILLSE_PALETTE_PL_ICEMISSILE01 = 6;

	public const int iCRI_SKILLSE_PALETTE_PL_WATERGUN02 = 9;

	public const int iCRI_SKILLSE_PALETTE_PL_WATERGUN01 = 8;

	public const int iCRI_SKILLSE_PALETTE_PL_START01 = 80;

	public const SkillSE_PALETTE CRI_SKILLSE_PALETTE_CUENUM = SkillSE_PALETTE.CRI_SKILLSE_PALETTE_CUENUM;

	public const SkillSE_PALETTE CRI_SKILLSE_PALETTE_PL_PLASMAGUN = SkillSE_PALETTE.CRI_SKILLSE_PALETTE_PL_PLASMAGUN;

	public const SkillSE_PALETTE CRI_SKILLSE_PALETTE_PL_BLACKARROW = SkillSE_PALETTE.CRI_SKILLSE_PALETTE_PL_BLACKARROW;

	public const SkillSE_PALETTE CRI_SKILLSE_PALETTE_PL_PLASMAGUN02 = SkillSE_PALETTE.CRI_SKILLSE_PALETTE_PL_PLASMAGUN02;

	public const SkillSE_PALETTE CRI_SKILLSE_PALETTE_PL_CHARA01 = SkillSE_PALETTE.CRI_SKILLSE_PALETTE_PL_CHARA01;

	public const SkillSE_PALETTE CRI_SKILLSE_PALETTE_PL_ICEMISSILE01 = SkillSE_PALETTE.CRI_SKILLSE_PALETTE_PL_ICEMISSILE01;

	public const SkillSE_PALETTE CRI_SKILLSE_PALETTE_PL_WATERGUN02 = SkillSE_PALETTE.CRI_SKILLSE_PALETTE_PL_WATERGUN02;

	public const SkillSE_PALETTE CRI_SKILLSE_PALETTE_PL_WATERGUN01 = SkillSE_PALETTE.CRI_SKILLSE_PALETTE_CUENUM;

	public const SkillSE_PALETTE CRI_SKILLSE_PALETTE_PL_START01 = SkillSE_PALETTE.CRI_SKILLSE_PALETTE_PL_START01;
}
