public enum SkillSE_FERHAM
{
	NONE = 0,
	CRI_SKILLSE_FERHAM_CUENUM = 10,
	CRI_SKILLSE_FERHAM_FM_BLOODYSNAKE = 1,
	CRI_SKILLSE_FERHAM_FM_START01 = 80,
	CRI_SKILLSE_FERHAM_FM_CRIMSON01 = 3,
	CRI_SKILLSE_FERHAM_FM_CRIMSON02 = 4,
	CRI_SKILLSE_FERHAM_FM_MUCHI = 10,
	CRI_SKILLSE_FERHAM_FM_CHAINTRAP01_LP = 6,
	CRI_SKILLSE_FERHAM_FM_CHAINTRAP01 = 5,
	CRI_SKILLSE_FERHAM_FM_CHAINTRAP01_STOP = 7,
	CRI_SKILLSE_FERHAM_FM_CHAINTRAP02 = 8,
	CRI_SKILLSE_FERHAM_FM_CHARA01 = 40
}
