public static class SkillSE_ZEROi
{
	public const int iCRI_SKILLSE_ZERO_CUENUM = 9;

	public const int iCRI_SKILLSE_ZERO_Z_RYUEN = 1;

	public const int iCRI_SKILLSE_ZERO_Z_RAKUOU = 7;

	public const int iCRI_SKILLSE_ZERO_Z_DASH01 = 2;

	public const int iCRI_SKILLSE_ZERO_Z_DASH03 = 4;

	public const int iCRI_SKILLSE_ZERO_Z_DASH02 = 3;

	public const int iCRI_SKILLSE_ZERO_Z_BLADE = 6;

	public const int iCRI_SKILLSE_ZERO_Z_CHARA02 = 41;

	public const int iCRI_SKILLSE_ZERO_Z_RYUENBU = 8;

	public const int iCRI_SKILLSE_ZERO_Z_CHARA03 = 42;

	public const SkillSE_ZERO CRI_SKILLSE_ZERO_CUENUM = SkillSE_ZERO.CRI_SKILLSE_ZERO_CUENUM;

	public const SkillSE_ZERO CRI_SKILLSE_ZERO_Z_RYUEN = SkillSE_ZERO.CRI_SKILLSE_ZERO_Z_RYUEN;

	public const SkillSE_ZERO CRI_SKILLSE_ZERO_Z_RAKUOU = SkillSE_ZERO.CRI_SKILLSE_ZERO_Z_RAKUOU;

	public const SkillSE_ZERO CRI_SKILLSE_ZERO_Z_DASH01 = SkillSE_ZERO.CRI_SKILLSE_ZERO_Z_DASH01;

	public const SkillSE_ZERO CRI_SKILLSE_ZERO_Z_DASH03 = SkillSE_ZERO.CRI_SKILLSE_ZERO_Z_DASH03;

	public const SkillSE_ZERO CRI_SKILLSE_ZERO_Z_DASH02 = SkillSE_ZERO.CRI_SKILLSE_ZERO_Z_DASH02;

	public const SkillSE_ZERO CRI_SKILLSE_ZERO_Z_BLADE = SkillSE_ZERO.CRI_SKILLSE_ZERO_Z_BLADE;

	public const SkillSE_ZERO CRI_SKILLSE_ZERO_Z_CHARA02 = SkillSE_ZERO.CRI_SKILLSE_ZERO_Z_CHARA02;

	public const SkillSE_ZERO CRI_SKILLSE_ZERO_Z_RYUENBU = SkillSE_ZERO.CRI_SKILLSE_ZERO_Z_RYUENBU;

	public const SkillSE_ZERO CRI_SKILLSE_ZERO_Z_CHARA03 = SkillSE_ZERO.CRI_SKILLSE_ZERO_Z_CHARA03;
}
