public static class SkillSE_XDMCi
{
	public const int iCRI_SKILLSE_XDMC_CUENUM = 11;

	public const int iCRI_SKILLSE_XDMC_XC_CHARA01 = 40;

	public const int iCRI_SKILLSE_XDMC_XC_MAJIN01 = 10;

	public const int iCRI_SKILLSE_XDMC_XC_MAJIN02 = 11;

	public const int iCRI_SKILLSE_XDMC_XC_STINGER03 = 3;

	public const int iCRI_SKILLSE_XDMC_XC_STINGER02 = 2;

	public const int iCRI_SKILLSE_XDMC_XC_STINGER01 = 1;

	public const int iCRI_SKILLSE_XDMC_XC_STINGER04 = 4;

	public const int iCRI_SKILLSE_XDMC_XC_RAIN02 = 7;

	public const int iCRI_SKILLSE_XDMC_XC_START01 = 80;

	public const int iCRI_SKILLSE_XDMC_XC_RAIN04 = 9;

	public const int iCRI_SKILLSE_XDMC_XC_MAJIN03 = 81;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_CUENUM = SkillSE_XDMC.CRI_SKILLSE_XDMC_CUENUM;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_CHARA01 = SkillSE_XDMC.CRI_SKILLSE_XDMC_XC_CHARA01;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_MAJIN01 = SkillSE_XDMC.CRI_SKILLSE_XDMC_XC_MAJIN01;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_MAJIN02 = SkillSE_XDMC.CRI_SKILLSE_XDMC_CUENUM;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_STINGER03 = SkillSE_XDMC.CRI_SKILLSE_XDMC_XC_STINGER03;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_STINGER02 = SkillSE_XDMC.CRI_SKILLSE_XDMC_XC_STINGER02;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_STINGER01 = SkillSE_XDMC.CRI_SKILLSE_XDMC_XC_STINGER01;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_STINGER04 = SkillSE_XDMC.CRI_SKILLSE_XDMC_XC_STINGER04;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_RAIN02 = SkillSE_XDMC.CRI_SKILLSE_XDMC_XC_RAIN02;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_START01 = SkillSE_XDMC.CRI_SKILLSE_XDMC_XC_START01;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_RAIN04 = SkillSE_XDMC.CRI_SKILLSE_XDMC_XC_RAIN04;

	public const SkillSE_XDMC CRI_SKILLSE_XDMC_XC_MAJIN03 = SkillSE_XDMC.CRI_SKILLSE_XDMC_XC_MAJIN03;
}
