public static class SkillSE_DRAGOONi
{
	public const int iCRI_SKILLSE_DRAGOON_CUENUM = 4;

	public const int iCRI_SKILLSE_DRAGOON_DG_HADOKEN = 1;

	public const int iCRI_SKILLSE_DRAGOON_DG_RISING = 3;

	public const int iCRI_SKILLSE_DRAGOON_DG_CHARA01 = 40;

	public const int iCRI_SKILLSE_DRAGOON_DG_START01 = 80;

	public const SkillSE_DRAGOON CRI_SKILLSE_DRAGOON_CUENUM = SkillSE_DRAGOON.CRI_SKILLSE_DRAGOON_CUENUM;

	public const SkillSE_DRAGOON CRI_SKILLSE_DRAGOON_DG_HADOKEN = SkillSE_DRAGOON.CRI_SKILLSE_DRAGOON_DG_HADOKEN;

	public const SkillSE_DRAGOON CRI_SKILLSE_DRAGOON_DG_RISING = SkillSE_DRAGOON.CRI_SKILLSE_DRAGOON_DG_RISING;

	public const SkillSE_DRAGOON CRI_SKILLSE_DRAGOON_DG_CHARA01 = SkillSE_DRAGOON.CRI_SKILLSE_DRAGOON_DG_CHARA01;

	public const SkillSE_DRAGOON CRI_SKILLSE_DRAGOON_DG_START01 = SkillSE_DRAGOON.CRI_SKILLSE_DRAGOON_DG_START01;
}
