public enum SkillSE_GATE
{
	NONE = 0,
	CRI_SKILLSE_GATE_CUENUM = 6,
	CRI_SKILLSE_GATE_GT_HOLE01 = 1,
	CRI_SKILLSE_GATE_GT_HOLE02_LP = 2,
	CRI_SKILLSE_GATE_GT_HOLE02_STOP = 3,
	CRI_SKILLSE_GATE_GT_STRIKE = 5,
	CRI_SKILLSE_GATE_GT_CHARA01 = 40,
	CRI_SKILLSE_GATE_GT_START01 = 80
}
