public enum SkillSE_RMZero
{
	NONE = 0,
	CRI_SKILLSE_RMZERO_CUENUM = 4,
	CRI_SKILLSE_RMZERO_ZZ_KNUCKLE = 1,
	CRI_SKILLSE_RMZERO_ZZ_BOOMERANG01 = 2,
	CRI_SKILLSE_RMZERO_ZZ_BOOMERANG02_LP = 3,
	CRI_SKILLSE_RMZERO_ZZ_BOOMERANG02_STOP = 4
}
