public enum SkillSE_PANDORA
{
	NONE = 0,
	CRI_SKILLSE_PANDORA_CUENUM = 7,
	CRI_SKILLSE_PANDORA_PD_FLYING = 1,
	CRI_SKILLSE_PANDORA_PD_MAJOU01 = 3,
	CRI_SKILLSE_PANDORA_PD_MAJOU02_LP = 4,
	CRI_SKILLSE_PANDORA_PD_MAJOU02_STOP = 5,
	CRI_SKILLSE_PANDORA_PD_MAJOU03 = 6,
	CRI_SKILLSE_PANDORA_PD_CHARA01 = 40,
	CRI_SKILLSE_PANDORA_PD_START01 = 80
}
