public enum SkillSE_DRAGOON
{
	NONE = 0,
	CRI_SKILLSE_DRAGOON_CUENUM = 4,
	CRI_SKILLSE_DRAGOON_DG_HADOKEN = 1,
	CRI_SKILLSE_DRAGOON_DG_RISING = 3,
	CRI_SKILLSE_DRAGOON_DG_CHARA01 = 40,
	CRI_SKILLSE_DRAGOON_DG_START01 = 80
}
