public static class SkillSE_Leviathani
{
	public const int iCRI_SKILLSE_LEVIATHAN_CUENUM = 16;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_SLASH = 1;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_OCEAN01 = 2;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_OCEAN02 = 3;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_CRYSTAL01 = 4;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_CRYSTAL02 = 5;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_CHARA01 = 6;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_CHARA02 = 7;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_CHARA03 = 8;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_START01 = 13;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_ICERING = 10;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_ICEJAVE = 11;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_CHARA04 = 14;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_CHARA05 = 40;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_FISH02 = 19;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_FISH01 = 18;

	public const int iCRI_SKILLSE_LEVIATHAN_LV_SPLASH01 = 16;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_CUENUM = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_CUENUM;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_SLASH = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_SLASH;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_OCEAN01 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_OCEAN01;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_OCEAN02 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_OCEAN02;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_CRYSTAL01 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_CRYSTAL01;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_CRYSTAL02 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_CRYSTAL02;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_CHARA01 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_CHARA01;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_CHARA02 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_CHARA02;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_CHARA03 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_CHARA03;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_START01 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_START01;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_ICERING = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_ICERING;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_ICEJAVE = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_ICEJAVE;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_CHARA04 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_CHARA04;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_CHARA05 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_CHARA05;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_FISH02 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_FISH02;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_FISH01 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_LV_FISH01;

	public const SkillSE_Leviathan CRI_SKILLSE_LEVIATHAN_LV_SPLASH01 = SkillSE_Leviathan.CRI_SKILLSE_LEVIATHAN_CUENUM;
}
