public enum SkillSE_XKai
{
	NONE = 0,
	CRI_SKILLSE_XKAI_CUENUM = 9,
	CRI_SKILLSE_XKAI_XK_CHARGE_LP = 1,
	CRI_SKILLSE_XKAI_XK_CHARGE_STOP = 3,
	CRI_SKILLSE_XKAI_XK_CHARGE02_LP = 2,
	CRI_SKILLSE_XKAI_XK_CHARGESHOT_M = 5,
	CRI_SKILLSE_XKAI_XK_HOMING01 = 8,
	CRI_SKILLSE_XKAI_XK_HOMING02 = 10,
	CRI_SKILLSE_XKAI_XK_CHARA01 = 40,
	CRI_SKILLSE_XKAI_XK_CHARGESHOT_L = 6,
	CRI_SKILLSE_XKAI_XK_CHARGESHOT_S = 4
}
