public enum SkillSE_X
{
	NONE = 0,
	CRI_SKILLSE_X_CUENUM = 12,
	CRI_SKILLSE_X_X_CHARGESHOT_S = 1,
	CRI_SKILLSE_X_X_CHARGESHOT_M = 3,
	CRI_SKILLSE_X_X_CHARGESHOT_L = 5,
	CRI_SKILLSE_X_X_CHARGEMAX = 6,
	CRI_SKILLSE_X_X_CHARGE_LP = 7,
	CRI_SKILLSE_X_X_CHARGE_STOP = 8,
	CRI_SKILLSE_X_X_ROCKET = 9,
	CRI_SKILLSE_X_X_RISING = 12,
	CRI_SKILLSE_X_X_HADO = 11,
	CRI_SKILLSE_X_X_BLAZE_LP = 13,
	CRI_SKILLSE_X_X_BLAZE_STOP = 14,
	CRI_SKILLSE_X_X_CHARA01 = 40
}
