public static class SkillSE_NANAi
{
	public const int iCRI_SKILLSE_NANA_CUENUM = 8;

	public const int iCRI_SKILLSE_NANA_NA_CHARA01 = 40;

	public const int iCRI_SKILLSE_NANA_NA_START01 = 80;

	public const int iCRI_SKILLSE_NANA_NA_DOMEGA01 = 1;

	public const int iCRI_SKILLSE_NANA_NA_SCAN01 = 6;

	public const int iCRI_SKILLSE_NANA_NA_DOMEGA03 = 3;

	public const int iCRI_SKILLSE_NANA_NA_DOMEGA04 = 4;

	public const int iCRI_SKILLSE_NANA_NA_DOMEGA02 = 2;

	public const int iCRI_SKILLSE_NANA_NA_SCAN02 = 7;

	public const SkillSE_NANA CRI_SKILLSE_NANA_CUENUM = SkillSE_NANA.CRI_SKILLSE_NANA_CUENUM;

	public const SkillSE_NANA CRI_SKILLSE_NANA_NA_CHARA01 = SkillSE_NANA.CRI_SKILLSE_NANA_NA_CHARA01;

	public const SkillSE_NANA CRI_SKILLSE_NANA_NA_START01 = SkillSE_NANA.CRI_SKILLSE_NANA_NA_START01;

	public const SkillSE_NANA CRI_SKILLSE_NANA_NA_DOMEGA01 = SkillSE_NANA.CRI_SKILLSE_NANA_NA_DOMEGA01;

	public const SkillSE_NANA CRI_SKILLSE_NANA_NA_SCAN01 = SkillSE_NANA.CRI_SKILLSE_NANA_NA_SCAN01;

	public const SkillSE_NANA CRI_SKILLSE_NANA_NA_DOMEGA03 = SkillSE_NANA.CRI_SKILLSE_NANA_NA_DOMEGA03;

	public const SkillSE_NANA CRI_SKILLSE_NANA_NA_DOMEGA04 = SkillSE_NANA.CRI_SKILLSE_NANA_NA_DOMEGA04;

	public const SkillSE_NANA CRI_SKILLSE_NANA_NA_DOMEGA02 = SkillSE_NANA.CRI_SKILLSE_NANA_NA_DOMEGA02;

	public const SkillSE_NANA CRI_SKILLSE_NANA_NA_SCAN02 = SkillSE_NANA.CRI_SKILLSE_NANA_NA_SCAN02;
}
