public enum SkillSE_BURAI
{
	NONE = 0,
	CRI_SKILLSE_BURAI_CUENUM = 7,
	CRI_SKILLSE_BURAI_BU_BURAIBRAKE01 = 4,
	CRI_SKILLSE_BURAI_BU_BURAIBRAKE02 = 5,
	CRI_SKILLSE_BURAI_BU_CHARA01 = 40,
	CRI_SKILLSE_BURAI_BU_START01 = 80,
	CRI_SKILLSE_BURAI_BU_BURAIARTS02 = 3,
	CRI_SKILLSE_BURAI_BU_BURAIARTS01_1 = 1,
	CRI_SKILLSE_BURAI_BU_BURAIARTS01_2 = 2
}
