public enum SkillSE_XDMC
{
	NONE = 0,
	CRI_SKILLSE_XDMC_CUENUM = 11,
	CRI_SKILLSE_XDMC_XC_CHARA01 = 40,
	CRI_SKILLSE_XDMC_XC_MAJIN01 = 10,
	CRI_SKILLSE_XDMC_XC_MAJIN02 = 11,
	CRI_SKILLSE_XDMC_XC_STINGER03 = 3,
	CRI_SKILLSE_XDMC_XC_STINGER02 = 2,
	CRI_SKILLSE_XDMC_XC_STINGER01 = 1,
	CRI_SKILLSE_XDMC_XC_STINGER04 = 4,
	CRI_SKILLSE_XDMC_XC_RAIN02 = 7,
	CRI_SKILLSE_XDMC_XC_START01 = 80,
	CRI_SKILLSE_XDMC_XC_RAIN04 = 9,
	CRI_SKILLSE_XDMC_XC_MAJIN03 = 81
}
