public static class SkillSE_ZERONMi
{
	public const int iCRI_SKILLSE_ZERONM_CUENUM = 3;

	public const int iCRI_SKILLSE_ZERONM_ZN_BUSTER = 1;

	public const int iCRI_SKILLSE_ZERONM_ZN_GENMU = 3;

	public const int iCRI_SKILLSE_ZERONM_ZN_CHARA01 = 40;

	public const SkillSE_ZERONM CRI_SKILLSE_ZERONM_CUENUM = SkillSE_ZERONM.CRI_SKILLSE_ZERONM_CUENUM;

	public const SkillSE_ZERONM CRI_SKILLSE_ZERONM_ZN_BUSTER = SkillSE_ZERONM.CRI_SKILLSE_ZERONM_ZN_BUSTER;

	public const SkillSE_ZERONM CRI_SKILLSE_ZERONM_ZN_GENMU = SkillSE_ZERONM.CRI_SKILLSE_ZERONM_CUENUM;

	public const SkillSE_ZERONM CRI_SKILLSE_ZERONM_ZN_CHARA01 = SkillSE_ZERONM.CRI_SKILLSE_ZERONM_ZN_CHARA01;
}
