public enum SkillSE_ZERODMC
{
	NONE = 0,
	CRI_SKILLSE_ZERODMC_CUENUM = 9,
	CRI_SKILLSE_ZERODMC_ZC_CHARA01 = 40,
	CRI_SKILLSE_ZERODMC_ZC_EARTH01 = 1,
	CRI_SKILLSE_ZERODMC_ZC_EARTH02 = 2,
	CRI_SKILLSE_ZERODMC_ZC_MAJIN02 = 9,
	CRI_SKILLSE_ZERODMC_ZC_MAJIN01 = 8,
	CRI_SKILLSE_ZERODMC_ZC_JIGEN01 = 4,
	CRI_SKILLSE_ZERODMC_ZC_JIGEN03 = 6,
	CRI_SKILLSE_ZERODMC_ZC_JIGEN02 = 5,
	CRI_SKILLSE_ZERODMC_ZC_START01 = 80
}
