public enum SkillSE_FORTEEXE
{
	NONE = 0,
	CRI_SKILLSE_FORTEEXE_CUENUM = 8,
	CRI_SKILLSE_FORTEEXE_FE_AIRBURST01 = 1,
	CRI_SKILLSE_FORTEEXE_FE_AIRBURST02 = 2,
	CRI_SKILLSE_FORTEEXE_FE_EXPLOSION = 3,
	CRI_SKILLSE_FORTEEXE_FE_EVOLVE = 4,
	CRI_SKILLSE_FORTEEXE_FE_AURA_LP = 5,
	CRI_SKILLSE_FORTEEXE_FE_AURA_STOP = 6,
	CRI_SKILLSE_FORTEEXE_FE_CHARA01 = 40,
	CRI_SKILLSE_FORTEEXE_FE_START01 = 80
}
