public enum SkillSE_ALIA
{
	NONE = 0,
	CRI_SKILLSE_ALIA_CUENUM = 10,
	CRI_SKILLSE_ALIA_AA_MELTCREEPER = 1,
	CRI_SKILLSE_ALIA_AA_GREENSPINNER = 3,
	CRI_SKILLSE_ALIA_AA_HEART = 6,
	CRI_SKILLSE_ALIA_AA_KISS01 = 4,
	CRI_SKILLSE_ALIA_AA_KISS02 = 5,
	CRI_SKILLSE_ALIA_AA_START01 = 80,
	CRI_SKILLSE_ALIA_AA_CHARA01 = 40,
	CRI_SKILLSE_ALIA_AA_KANE_LP = 7,
	CRI_SKILLSE_ALIA_AA_KANE_STOP = 8,
	CRI_SKILLSE_ALIA_AA_BOUQUET = 9
}
