public enum STORY_VAVA
{
	NONE = 0,
	CRI_STORY_VAVA_CUENUM = 15,
	CRI_STORY_VAVA_S_VA_STORY01 = 1,
	CRI_STORY_VAVA_S_VA_STORY02 = 2,
	CRI_STORY_VAVA_S_VA_STORY03 = 3,
	CRI_STORY_VAVA_S_VA_STORY04 = 4,
	CRI_STORY_VAVA_S_VA_STORY05 = 5,
	CRI_STORY_VAVA_S_VA_STORY06 = 6,
	CRI_STORY_VAVA_S_VA_STORY07 = 7,
	CRI_STORY_VAVA_S_VA_STORY08 = 8,
	CRI_STORY_VAVA_S_VA_STORY09 = 9,
	CRI_STORY_VAVA_S_VA_STORY13 = 13,
	CRI_STORY_VAVA_S_VA_STORY11 = 11,
	CRI_STORY_VAVA_S_VA_STORY10 = 10,
	CRI_STORY_VAVA_S_VA_STORY12 = 12,
	CRI_STORY_VAVA_S_VA_STORY14 = 14,
	CRI_STORY_VAVA_S_VA_STORY15 = 15
}
