public static class STORY_VAVAi
{
	public const int iCRI_STORY_VAVA_CUENUM = 15;

	public const int iCRI_STORY_VAVA_S_VA_STORY01 = 1;

	public const int iCRI_STORY_VAVA_S_VA_STORY02 = 2;

	public const int iCRI_STORY_VAVA_S_VA_STORY03 = 3;

	public const int iCRI_STORY_VAVA_S_VA_STORY04 = 4;

	public const int iCRI_STORY_VAVA_S_VA_STORY05 = 5;

	public const int iCRI_STORY_VAVA_S_VA_STORY06 = 6;

	public const int iCRI_STORY_VAVA_S_VA_STORY07 = 7;

	public const int iCRI_STORY_VAVA_S_VA_STORY08 = 8;

	public const int iCRI_STORY_VAVA_S_VA_STORY09 = 9;

	public const int iCRI_STORY_VAVA_S_VA_STORY13 = 13;

	public const int iCRI_STORY_VAVA_S_VA_STORY11 = 11;

	public const int iCRI_STORY_VAVA_S_VA_STORY10 = 10;

	public const int iCRI_STORY_VAVA_S_VA_STORY12 = 12;

	public const int iCRI_STORY_VAVA_S_VA_STORY14 = 14;

	public const int iCRI_STORY_VAVA_S_VA_STORY15 = 15;

	public const STORY_VAVA CRI_STORY_VAVA_CUENUM = STORY_VAVA.CRI_STORY_VAVA_CUENUM;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY01 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY01;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY02 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY02;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY03 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY03;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY04 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY04;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY05 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY05;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY06 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY06;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY07 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY07;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY08 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY08;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY09 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY09;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY13 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY13;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY11 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY11;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY10 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY10;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY12 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY12;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY14 = STORY_VAVA.CRI_STORY_VAVA_S_VA_STORY14;

	public const STORY_VAVA CRI_STORY_VAVA_S_VA_STORY15 = STORY_VAVA.CRI_STORY_VAVA_CUENUM;
}
