public static class STORY_ROLLi
{
	public const int iCRI_STORY_ROLL_CUENUM = 10;

	public const int iCRI_STORY_ROLL_S_RL_STORY01 = 1;

	public const int iCRI_STORY_ROLL_S_RL_STORY02 = 2;

	public const int iCRI_STORY_ROLL_S_RL_STORY03 = 3;

	public const int iCRI_STORY_ROLL_S_RL_STORY04 = 4;

	public const int iCRI_STORY_ROLL_S_RL_STORY05 = 5;

	public const int iCRI_STORY_ROLL_S_RL_STORY06 = 6;

	public const int iCRI_STORY_ROLL_S_RL_STORY07 = 7;

	public const int iCRI_STORY_ROLL_S_RL_STORY08 = 8;

	public const int iCRI_STORY_ROLL_S_RL_STORY09 = 9;

	public const int iCRI_STORY_ROLL_S_RL_STORY10 = 10;

	public const STORY_ROLL CRI_STORY_ROLL_CUENUM = STORY_ROLL.CRI_STORY_ROLL_CUENUM;

	public const STORY_ROLL CRI_STORY_ROLL_S_RL_STORY01 = STORY_ROLL.CRI_STORY_ROLL_S_RL_STORY01;

	public const STORY_ROLL CRI_STORY_ROLL_S_RL_STORY02 = STORY_ROLL.CRI_STORY_ROLL_S_RL_STORY02;

	public const STORY_ROLL CRI_STORY_ROLL_S_RL_STORY03 = STORY_ROLL.CRI_STORY_ROLL_S_RL_STORY03;

	public const STORY_ROLL CRI_STORY_ROLL_S_RL_STORY04 = STORY_ROLL.CRI_STORY_ROLL_S_RL_STORY04;

	public const STORY_ROLL CRI_STORY_ROLL_S_RL_STORY05 = STORY_ROLL.CRI_STORY_ROLL_S_RL_STORY05;

	public const STORY_ROLL CRI_STORY_ROLL_S_RL_STORY06 = STORY_ROLL.CRI_STORY_ROLL_S_RL_STORY06;

	public const STORY_ROLL CRI_STORY_ROLL_S_RL_STORY07 = STORY_ROLL.CRI_STORY_ROLL_S_RL_STORY07;

	public const STORY_ROLL CRI_STORY_ROLL_S_RL_STORY08 = STORY_ROLL.CRI_STORY_ROLL_S_RL_STORY08;

	public const STORY_ROLL CRI_STORY_ROLL_S_RL_STORY09 = STORY_ROLL.CRI_STORY_ROLL_S_RL_STORY09;

	public const STORY_ROLL CRI_STORY_ROLL_S_RL_STORY10 = STORY_ROLL.CRI_STORY_ROLL_CUENUM;
}
