public static class STORY_KOBUNi
{
	public const int iCRI_STORY_KOBUN_CUENUM = 5;

	public const int iCRI_STORY_KOBUN_S_KB_STORY01 = 1;

	public const int iCRI_STORY_KOBUN_S_KB_STORY02 = 2;

	public const int iCRI_STORY_KOBUN_S_KB_STORY03 = 3;

	public const int iCRI_STORY_KOBUN_S_KB_STORY04 = 4;

	public const int iCRI_STORY_KOBUN_S_KB_STORY05 = 5;

	public const STORY_KOBUN CRI_STORY_KOBUN_CUENUM = STORY_KOBUN.CRI_STORY_KOBUN_CUENUM;

	public const STORY_KOBUN CRI_STORY_KOBUN_S_KB_STORY01 = STORY_KOBUN.CRI_STORY_KOBUN_S_KB_STORY01;

	public const STORY_KOBUN CRI_STORY_KOBUN_S_KB_STORY02 = STORY_KOBUN.CRI_STORY_KOBUN_S_KB_STORY02;

	public const STORY_KOBUN CRI_STORY_KOBUN_S_KB_STORY03 = STORY_KOBUN.CRI_STORY_KOBUN_S_KB_STORY03;

	public const STORY_KOBUN CRI_STORY_KOBUN_S_KB_STORY04 = STORY_KOBUN.CRI_STORY_KOBUN_S_KB_STORY04;

	public const STORY_KOBUN CRI_STORY_KOBUN_S_KB_STORY05 = STORY_KOBUN.CRI_STORY_KOBUN_CUENUM;
}
