public static class STORY_IRIS2i
{
	public const int iCRI_STORY_IRIS2_CUENUM = 11;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY02 = 2;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY03 = 3;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY04 = 4;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY01 = 1;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY05 = 5;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY06 = 6;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY07 = 7;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY08 = 8;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY09 = 9;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY10 = 10;

	public const int iCRI_STORY_IRIS2_S_IR2_STORY11 = 11;

	public const STORY_IRIS2 CRI_STORY_IRIS2_CUENUM = STORY_IRIS2.CRI_STORY_IRIS2_CUENUM;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY02 = STORY_IRIS2.CRI_STORY_IRIS2_S_IR2_STORY02;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY03 = STORY_IRIS2.CRI_STORY_IRIS2_S_IR2_STORY03;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY04 = STORY_IRIS2.CRI_STORY_IRIS2_S_IR2_STORY04;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY01 = STORY_IRIS2.CRI_STORY_IRIS2_S_IR2_STORY01;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY05 = STORY_IRIS2.CRI_STORY_IRIS2_S_IR2_STORY05;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY06 = STORY_IRIS2.CRI_STORY_IRIS2_S_IR2_STORY06;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY07 = STORY_IRIS2.CRI_STORY_IRIS2_S_IR2_STORY07;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY08 = STORY_IRIS2.CRI_STORY_IRIS2_S_IR2_STORY08;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY09 = STORY_IRIS2.CRI_STORY_IRIS2_S_IR2_STORY09;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY10 = STORY_IRIS2.CRI_STORY_IRIS2_S_IR2_STORY10;

	public const STORY_IRIS2 CRI_STORY_IRIS2_S_IR2_STORY11 = STORY_IRIS2.CRI_STORY_IRIS2_CUENUM;
}
