public enum STORY_ROLLCAS
{
	NONE = 0,
	CRI_STORY_ROLLCAS_CUENUM = 13,
	CRI_STORY_ROLLCAS_S_RC_STORY01 = 1,
	CRI_STORY_ROLLCAS_S_RC_STORY02 = 2,
	CRI_STORY_ROLLCAS_S_RC_STORY03 = 3,
	CRI_STORY_ROLLCAS_S_RC_STORY04 = 4,
	CRI_STORY_ROLLCAS_S_RC_STORY05 = 5,
	CRI_STORY_ROLLCAS_S_RC_STORY06 = 6,
	CRI_STORY_ROLLCAS_S_RC_STORY07 = 7,
	CRI_STORY_ROLLCAS_S_RC_STORY08 = 8,
	CRI_STORY_ROLLCAS_S_RC_STORY09 = 9,
	CRI_STORY_ROLLCAS_S_RC_STORY10 = 10,
	CRI_STORY_ROLLCAS_S_RC_STORY11 = 11,
	CRI_STORY_ROLLCAS_S_RC_STORY12 = 12,
	CRI_STORY_ROLLCAS_S_RC_STORY13 = 13
}
