public static class STORY_FERHAMi
{
	public const int iCRI_STORY_FERHAM_CUENUM = 15;

	public const int iCRI_STORY_FERHAM_S_FM_STORY01 = 1;

	public const int iCRI_STORY_FERHAM_S_FM_STORY02 = 2;

	public const int iCRI_STORY_FERHAM_S_FM_STORY03 = 3;

	public const int iCRI_STORY_FERHAM_S_FM_STORY04 = 4;

	public const int iCRI_STORY_FERHAM_S_FM_STORY05 = 5;

	public const int iCRI_STORY_FERHAM_S_FM_STORY06 = 6;

	public const int iCRI_STORY_FERHAM_S_FM_STORY07 = 7;

	public const int iCRI_STORY_FERHAM_S_FM_STORY08 = 8;

	public const int iCRI_STORY_FERHAM_S_FM_STORY09 = 9;

	public const int iCRI_STORY_FERHAM_S_FM_STORY10 = 10;

	public const int iCRI_STORY_FERHAM_S_FM_STORY11 = 11;

	public const int iCRI_STORY_FERHAM_S_FM_STORY12 = 12;

	public const int iCRI_STORY_FERHAM_S_FM_STORY13 = 13;

	public const int iCRI_STORY_FERHAM_S_FM_STORY14 = 14;

	public const int iCRI_STORY_FERHAM_S_FM_STORY15 = 15;

	public const STORY_FERHAM CRI_STORY_FERHAM_CUENUM = STORY_FERHAM.CRI_STORY_FERHAM_CUENUM;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY01 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY01;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY02 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY02;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY03 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY03;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY04 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY04;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY05 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY05;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY06 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY06;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY07 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY07;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY08 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY08;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY09 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY09;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY10 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY10;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY11 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY11;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY12 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY12;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY13 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY13;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY14 = STORY_FERHAM.CRI_STORY_FERHAM_S_FM_STORY14;

	public const STORY_FERHAM CRI_STORY_FERHAM_S_FM_STORY15 = STORY_FERHAM.CRI_STORY_FERHAM_CUENUM;
}
