public static class STORY_ZEROi
{
	public const int iCRI_STORY_ZERO_CUENUM = 36;

	public const int iCRI_STORY_ZERO_S_Z_STORY01 = 1;

	public const int iCRI_STORY_ZERO_S_Z_STORY02 = 2;

	public const int iCRI_STORY_ZERO_S_Z_STORY03 = 3;

	public const int iCRI_STORY_ZERO_S_Z_STORY04 = 4;

	public const int iCRI_STORY_ZERO_S_Z_STORY05 = 5;

	public const int iCRI_STORY_ZERO_S_Z_STORY06 = 6;

	public const int iCRI_STORY_ZERO_S_Z_STORY07 = 7;

	public const int iCRI_STORY_ZERO_S_Z_STORY08 = 8;

	public const int iCRI_STORY_ZERO_S_Z_STORY09 = 9;

	public const int iCRI_STORY_ZERO_S_Z_STORY10 = 10;

	public const int iCRI_STORY_ZERO_S_Z_STORY11 = 11;

	public const int iCRI_STORY_ZERO_S_Z_STORY12 = 12;

	public const int iCRI_STORY_ZERO_S_Z_STORY13 = 13;

	public const int iCRI_STORY_ZERO_S_Z_STORY14 = 14;

	public const int iCRI_STORY_ZERO_S_Z_STORY15 = 15;

	public const int iCRI_STORY_ZERO_S_Z_STORY16 = 16;

	public const int iCRI_STORY_ZERO_S_Z_STORY17 = 17;

	public const int iCRI_STORY_ZERO_S_Z_STORY18 = 18;

	public const int iCRI_STORY_ZERO_S_Z_STORY19 = 19;

	public const int iCRI_STORY_ZERO_S_Z_STORY20 = 20;

	public const int iCRI_STORY_ZERO_S_Z_STORY21 = 21;

	public const int iCRI_STORY_ZERO_S_Z_STORY22 = 22;

	public const int iCRI_STORY_ZERO_S_Z_STORY23 = 23;

	public const int iCRI_STORY_ZERO_S_Z_STORY24 = 24;

	public const int iCRI_STORY_ZERO_S_Z_STORY25 = 25;

	public const int iCRI_STORY_ZERO_S_Z_STORY26 = 26;

	public const int iCRI_STORY_ZERO_S_Z_STORY27 = 27;

	public const int iCRI_STORY_ZERO_S_Z_STORY28 = 28;

	public const int iCRI_STORY_ZERO_S_Z_STORY29 = 29;

	public const int iCRI_STORY_ZERO_S_Z_STORY30 = 30;

	public const int iCRI_STORY_ZERO_S_Z_STORY31 = 31;

	public const int iCRI_STORY_ZERO_S_Z_STORY32 = 32;

	public const int iCRI_STORY_ZERO_S_Z_STORY33 = 33;

	public const int iCRI_STORY_ZERO_S_Z_STORY34 = 34;

	public const int iCRI_STORY_ZERO_S_Z_STORY35 = 35;

	public const int iCRI_STORY_ZERO_S_Z_STORY36 = 36;

	public const STORY_ZERO CRI_STORY_ZERO_CUENUM = STORY_ZERO.CRI_STORY_ZERO_CUENUM;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY01 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY01;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY02 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY02;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY03 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY03;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY04 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY04;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY05 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY05;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY06 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY06;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY07 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY07;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY08 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY08;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY09 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY09;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY10 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY10;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY11 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY11;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY12 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY12;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY13 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY13;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY14 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY14;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY15 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY15;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY16 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY16;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY17 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY17;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY18 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY18;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY19 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY19;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY20 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY20;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY21 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY21;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY22 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY22;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY23 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY23;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY24 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY24;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY25 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY25;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY26 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY26;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY27 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY27;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY28 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY28;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY29 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY29;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY30 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY30;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY31 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY31;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY32 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY32;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY33 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY33;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY34 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY34;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY35 = STORY_ZERO.CRI_STORY_ZERO_S_Z_STORY35;

	public const STORY_ZERO CRI_STORY_ZERO_S_Z_STORY36 = STORY_ZERO.CRI_STORY_ZERO_CUENUM;
}
