public static class STORY_ERATOi
{
	public const int iCRI_STORY_ERATO_CUENUM = 46;

	public const int iCRI_STORY_ERATO_S_ER_STORY01 = 1;

	public const int iCRI_STORY_ERATO_S_ER_STORY02 = 2;

	public const int iCRI_STORY_ERATO_S_ER_STORY03 = 3;

	public const int iCRI_STORY_ERATO_S_ER_STORY04 = 4;

	public const int iCRI_STORY_ERATO_S_ER_STORY05 = 5;

	public const int iCRI_STORY_ERATO_S_ER_STORY06 = 6;

	public const int iCRI_STORY_ERATO_S_ER_STORY07 = 7;

	public const int iCRI_STORY_ERATO_S_ER_STORY08 = 8;

	public const int iCRI_STORY_ERATO_S_ER_STORY09 = 9;

	public const int iCRI_STORY_ERATO_S_ER_STORY10 = 10;

	public const int iCRI_STORY_ERATO_S_ER_STORY11 = 11;

	public const int iCRI_STORY_ERATO_S_ER_STORY12 = 12;

	public const int iCRI_STORY_ERATO_S_ER_STORY13 = 13;

	public const int iCRI_STORY_ERATO_S_ER_STORY14 = 14;

	public const int iCRI_STORY_ERATO_S_ER_STORY15 = 15;

	public const int iCRI_STORY_ERATO_S_ER_STORY16 = 16;

	public const int iCRI_STORY_ERATO_S_ER_STORY17 = 17;

	public const int iCRI_STORY_ERATO_S_ER_STORY18 = 18;

	public const int iCRI_STORY_ERATO_S_ER_STORY19 = 19;

	public const int iCRI_STORY_ERATO_S_ER_STORY20 = 20;

	public const int iCRI_STORY_ERATO_S_ER_STORY21 = 21;

	public const int iCRI_STORY_ERATO_S_ER_STORY22 = 22;

	public const int iCRI_STORY_ERATO_S_ER_STORY23 = 23;

	public const int iCRI_STORY_ERATO_S_ER_STORY24 = 24;

	public const int iCRI_STORY_ERATO_S_ER_STORY25 = 25;

	public const int iCRI_STORY_ERATO_S_ER_STORY26 = 26;

	public const int iCRI_STORY_ERATO_S_ER_STORY27 = 27;

	public const int iCRI_STORY_ERATO_S_ER_STORY28 = 28;

	public const int iCRI_STORY_ERATO_S_ER_STORY29 = 29;

	public const int iCRI_STORY_ERATO_S_ER_STORY30 = 30;

	public const int iCRI_STORY_ERATO_S_ER_STORY31 = 31;

	public const int iCRI_STORY_ERATO_S_ER_STORY32 = 32;

	public const int iCRI_STORY_ERATO_S_ER_STORY33 = 33;

	public const int iCRI_STORY_ERATO_S_ER_STORY34 = 34;

	public const int iCRI_STORY_ERATO_S_ER_STORY35 = 35;

	public const int iCRI_STORY_ERATO_S_ER_STORY36 = 36;

	public const int iCRI_STORY_ERATO_S_ER_STORY37 = 37;

	public const int iCRI_STORY_ERATO_S_ER_STORY38 = 38;

	public const int iCRI_STORY_ERATO_S_ER_STORY39 = 39;

	public const int iCRI_STORY_ERATO_S_ER_STORY40 = 40;

	public const int iCRI_STORY_ERATO_S_ER_STORY41 = 41;

	public const int iCRI_STORY_ERATO_S_ER_STORY42 = 42;

	public const int iCRI_STORY_ERATO_S_ER_STORY43 = 43;

	public const int iCRI_STORY_ERATO_S_ER_STORY44 = 44;

	public const int iCRI_STORY_ERATO_S_ER_STORY45 = 45;

	public const int iCRI_STORY_ERATO_S_ER_STORY46 = 46;

	public const STORY_ERATO CRI_STORY_ERATO_CUENUM = STORY_ERATO.CRI_STORY_ERATO_CUENUM;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY01 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY01;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY02 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY02;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY03 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY03;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY04 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY04;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY05 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY05;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY06 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY06;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY07 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY07;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY08 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY08;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY09 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY09;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY10 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY10;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY11 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY11;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY12 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY12;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY13 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY13;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY14 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY14;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY15 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY15;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY16 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY16;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY17 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY17;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY18 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY18;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY19 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY19;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY20 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY20;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY21 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY21;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY22 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY22;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY23 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY23;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY24 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY24;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY25 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY25;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY26 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY26;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY27 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY27;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY28 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY28;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY29 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY29;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY30 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY30;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY31 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY31;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY32 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY32;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY33 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY33;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY34 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY34;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY35 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY35;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY36 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY36;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY37 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY37;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY38 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY38;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY39 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY39;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY40 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY40;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY41 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY41;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY42 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY42;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY43 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY43;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY44 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY44;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY45 = STORY_ERATO.CRI_STORY_ERATO_S_ER_STORY45;

	public const STORY_ERATO CRI_STORY_ERATO_S_ER_STORY46 = STORY_ERATO.CRI_STORY_ERATO_CUENUM;
}
