public enum STORY_KB
{
	NONE = 0,
	CRI_STORY_KB_CUENUM = 5,
	CRI_STORY_KB_KB_STORY01 = 1,
	CRI_STORY_KB_KB_STORY02 = 2,
	CRI_STORY_KB_KB_STORY03 = 3,
	CRI_STORY_KB_KB_STORY04 = 4,
	CRI_STORY_KB_KB_STORY05 = 5
}
