public enum STORY_ROLL
{
	NONE = 0,
	CRI_STORY_ROLL_CUENUM = 10,
	CRI_STORY_ROLL_S_RL_STORY01 = 1,
	CRI_STORY_ROLL_S_RL_STORY02 = 2,
	CRI_STORY_ROLL_S_RL_STORY03 = 3,
	CRI_STORY_ROLL_S_RL_STORY04 = 4,
	CRI_STORY_ROLL_S_RL_STORY05 = 5,
	CRI_STORY_ROLL_S_RL_STORY06 = 6,
	CRI_STORY_ROLL_S_RL_STORY07 = 7,
	CRI_STORY_ROLL_S_RL_STORY08 = 8,
	CRI_STORY_ROLL_S_RL_STORY09 = 9,
	CRI_STORY_ROLL_S_RL_STORY10 = 10
}
