public enum STORY_NMDER
{
	NONE = 0,
	CRI_STORY_NMDER_CUENUM = 5,
	CRI_STORY_NMDER_S_NM_STORY01 = 1,
	CRI_STORY_NMDER_S_NM_STORY02 = 2,
	CRI_STORY_NMDER_S_NM_STORY03 = 3,
	CRI_STORY_NMDER_S_NM_STORY04 = 4,
	CRI_STORY_NMDER_S_NM_STORY05 = 5
}
