public static class STORY_KBi
{
	public const int iCRI_STORY_KB_CUENUM = 5;

	public const int iCRI_STORY_KB_KB_STORY01 = 1;

	public const int iCRI_STORY_KB_KB_STORY02 = 2;

	public const int iCRI_STORY_KB_KB_STORY03 = 3;

	public const int iCRI_STORY_KB_KB_STORY04 = 4;

	public const int iCRI_STORY_KB_KB_STORY05 = 5;

	public const STORY_KB CRI_STORY_KB_CUENUM = STORY_KB.CRI_STORY_KB_CUENUM;

	public const STORY_KB CRI_STORY_KB_KB_STORY01 = STORY_KB.CRI_STORY_KB_KB_STORY01;

	public const STORY_KB CRI_STORY_KB_KB_STORY02 = STORY_KB.CRI_STORY_KB_KB_STORY02;

	public const STORY_KB CRI_STORY_KB_KB_STORY03 = STORY_KB.CRI_STORY_KB_KB_STORY03;

	public const STORY_KB CRI_STORY_KB_KB_STORY04 = STORY_KB.CRI_STORY_KB_KB_STORY04;

	public const STORY_KB CRI_STORY_KB_KB_STORY05 = STORY_KB.CRI_STORY_KB_CUENUM;
}
