public static class STORY_ROCKVOLi
{
	public const int iCRI_STORY_ROCKVOL_CUENUM = 22;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY01 = 1;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY02 = 2;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY03 = 3;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY04 = 4;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY05 = 5;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY06 = 6;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY07 = 7;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY08 = 8;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY09 = 9;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY10 = 10;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY11 = 11;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY12 = 12;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY13 = 13;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY14 = 14;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY15 = 15;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY16 = 16;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY17 = 17;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY18 = 18;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY19 = 19;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY20 = 20;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY21 = 21;

	public const int iCRI_STORY_ROCKVOL_S_RV_STORY22 = 22;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_CUENUM = STORY_ROCKVOL.CRI_STORY_ROCKVOL_CUENUM;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY01 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY01;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY02 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY02;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY03 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY03;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY04 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY04;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY05 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY05;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY06 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY06;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY07 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY07;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY08 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY08;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY09 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY09;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY10 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY10;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY11 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY11;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY12 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY12;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY13 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY13;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY14 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY14;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY15 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY15;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY16 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY16;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY17 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY17;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY18 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY18;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY19 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY19;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY20 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY20;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY21 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_S_RV_STORY21;

	public const STORY_ROCKVOL CRI_STORY_ROCKVOL_S_RV_STORY22 = STORY_ROCKVOL.CRI_STORY_ROCKVOL_CUENUM;
}
