public static class STORY_FORTEi
{
	public const int iCRI_STORY_FORTE_CUENUM = 13;

	public const int iCRI_STORY_FORTE_S_FO_STORY01 = 1;

	public const int iCRI_STORY_FORTE_S_FO_STORY02 = 2;

	public const int iCRI_STORY_FORTE_S_FO_STORY03 = 3;

	public const int iCRI_STORY_FORTE_S_FO_STORY04 = 4;

	public const int iCRI_STORY_FORTE_S_FO_STORY05 = 5;

	public const int iCRI_STORY_FORTE_S_FO_STORY06 = 6;

	public const int iCRI_STORY_FORTE_S_FO_STORY07 = 7;

	public const int iCRI_STORY_FORTE_S_FO_STORY08 = 8;

	public const int iCRI_STORY_FORTE_S_FO_STORY09 = 9;

	public const int iCRI_STORY_FORTE_S_FO_STORY10 = 10;

	public const int iCRI_STORY_FORTE_S_FO_STORY11 = 11;

	public const int iCRI_STORY_FORTE_S_FO_STORY12 = 12;

	public const int iCRI_STORY_FORTE_S_FO_STORY13 = 13;

	public const STORY_FORTE CRI_STORY_FORTE_CUENUM = STORY_FORTE.CRI_STORY_FORTE_CUENUM;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY01 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY01;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY02 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY02;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY03 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY03;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY04 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY04;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY05 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY05;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY06 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY06;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY07 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY07;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY08 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY08;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY09 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY09;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY10 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY10;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY11 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY11;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY12 = STORY_FORTE.CRI_STORY_FORTE_S_FO_STORY12;

	public const STORY_FORTE CRI_STORY_FORTE_S_FO_STORY13 = STORY_FORTE.CRI_STORY_FORTE_CUENUM;
}
