public static class STORY_ANGEi
{
	public const int iCRI_STORY_ANGE_CUENUM = 38;

	public const int iCRI_STORY_ANGE_S_AN_STORY01 = 1;

	public const int iCRI_STORY_ANGE_S_AN_STORY02 = 2;

	public const int iCRI_STORY_ANGE_S_AN_STORY03 = 3;

	public const int iCRI_STORY_ANGE_S_AN_STORY04 = 4;

	public const int iCRI_STORY_ANGE_S_AN_STORY05 = 5;

	public const int iCRI_STORY_ANGE_S_AN_STORY06 = 6;

	public const int iCRI_STORY_ANGE_S_AN_STORY07 = 7;

	public const int iCRI_STORY_ANGE_S_AN_STORY08 = 8;

	public const int iCRI_STORY_ANGE_S_AN_STORY09 = 9;

	public const int iCRI_STORY_ANGE_S_AN_STORY10 = 10;

	public const int iCRI_STORY_ANGE_S_AN_STORY11 = 11;

	public const int iCRI_STORY_ANGE_S_AN_STORY12 = 12;

	public const int iCRI_STORY_ANGE_S_AN_STORY13 = 13;

	public const int iCRI_STORY_ANGE_S_AN_STORY14 = 14;

	public const int iCRI_STORY_ANGE_S_AN_STORY15 = 15;

	public const int iCRI_STORY_ANGE_S_AN_STORY16 = 16;

	public const int iCRI_STORY_ANGE_S_AN_STORY17 = 17;

	public const int iCRI_STORY_ANGE_S_AN_STORY18 = 18;

	public const int iCRI_STORY_ANGE_S_AN_STORY19 = 19;

	public const int iCRI_STORY_ANGE_S_AN_STORY20 = 20;

	public const int iCRI_STORY_ANGE_S_AN_STORY21 = 21;

	public const int iCRI_STORY_ANGE_S_AN_STORY22 = 22;

	public const int iCRI_STORY_ANGE_S_AN_STORY23 = 23;

	public const int iCRI_STORY_ANGE_S_AN_STORY24 = 24;

	public const int iCRI_STORY_ANGE_S_AN_STORY25 = 26;

	public const int iCRI_STORY_ANGE_S_AN_STORY26 = 25;

	public const int iCRI_STORY_ANGE_S_AN_STORY27 = 27;

	public const int iCRI_STORY_ANGE_S_AN_STORY28 = 28;

	public const int iCRI_STORY_ANGE_S_AN_STORY29 = 29;

	public const int iCRI_STORY_ANGE_S_AN_STORY30 = 30;

	public const int iCRI_STORY_ANGE_S_AN_STORY31 = 31;

	public const int iCRI_STORY_ANGE_S_AN_STORY32 = 32;

	public const int iCRI_STORY_ANGE_S_AN_STORY33 = 33;

	public const int iCRI_STORY_ANGE_S_AN_STORY34 = 34;

	public const int iCRI_STORY_ANGE_S_AN_STORY35 = 35;

	public const int iCRI_STORY_ANGE_S_AN_STORY36 = 36;

	public const int iCRI_STORY_ANGE_S_AN_STORY37 = 37;

	public const int iCRI_STORY_ANGE_S_AN_STORY38 = 38;

	public const STORY_ANGE CRI_STORY_ANGE_CUENUM = STORY_ANGE.CRI_STORY_ANGE_CUENUM;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY01 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY01;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY02 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY02;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY03 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY03;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY04 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY04;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY05 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY05;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY06 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY06;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY07 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY07;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY08 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY08;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY09 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY09;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY10 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY10;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY11 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY11;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY12 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY12;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY13 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY13;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY14 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY14;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY15 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY15;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY16 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY16;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY17 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY17;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY18 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY18;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY19 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY19;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY20 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY20;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY21 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY21;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY22 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY22;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY23 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY23;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY24 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY24;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY25 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY25;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY26 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY26;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY27 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY27;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY28 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY28;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY29 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY29;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY30 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY30;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY31 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY31;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY32 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY32;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY33 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY33;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY34 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY34;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY35 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY35;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY36 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY36;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY37 = STORY_ANGE.CRI_STORY_ANGE_S_AN_STORY37;

	public const STORY_ANGE CRI_STORY_ANGE_S_AN_STORY38 = STORY_ANGE.CRI_STORY_ANGE_CUENUM;
}
