public static class STORY_VIAi
{
	public const int iCRI_STORY_VIA_CUENUM = 93;

	public const int iCRI_STORY_VIA_S_VI_STORY01 = 1;

	public const int iCRI_STORY_VIA_S_VI_STORY02 = 2;

	public const int iCRI_STORY_VIA_S_VI_STORY03 = 3;

	public const int iCRI_STORY_VIA_S_VI_STORY04 = 4;

	public const int iCRI_STORY_VIA_S_VI_STORY05 = 5;

	public const int iCRI_STORY_VIA_S_VI_STORY06 = 6;

	public const int iCRI_STORY_VIA_S_VI_STORY07 = 7;

	public const int iCRI_STORY_VIA_S_VI_STORY08 = 8;

	public const int iCRI_STORY_VIA_S_VI_STORY09 = 9;

	public const int iCRI_STORY_VIA_S_VI_STORY10 = 10;

	public const int iCRI_STORY_VIA_S_VI_STORY11 = 11;

	public const int iCRI_STORY_VIA_S_VI_STORY12 = 12;

	public const int iCRI_STORY_VIA_S_VI_STORY13 = 13;

	public const int iCRI_STORY_VIA_S_VI_STORY14 = 14;

	public const int iCRI_STORY_VIA_S_VI_STORY15 = 15;

	public const int iCRI_STORY_VIA_S_VI_STORY16 = 16;

	public const int iCRI_STORY_VIA_S_VI_STORY17 = 17;

	public const int iCRI_STORY_VIA_S_VI_STORY18 = 18;

	public const int iCRI_STORY_VIA_S_VI_STORY19 = 19;

	public const int iCRI_STORY_VIA_S_VI_STORY20 = 20;

	public const int iCRI_STORY_VIA_S_VI_STORY21 = 21;

	public const int iCRI_STORY_VIA_S_VI_STORY22 = 22;

	public const int iCRI_STORY_VIA_S_VI_STORY23 = 23;

	public const int iCRI_STORY_VIA_S_VI_STORY24 = 24;

	public const int iCRI_STORY_VIA_S_VI_STORY25 = 25;

	public const int iCRI_STORY_VIA_S_VI_STORY26 = 26;

	public const int iCRI_STORY_VIA_S_VI_STORY27 = 27;

	public const int iCRI_STORY_VIA_S_VI_STORY28 = 28;

	public const int iCRI_STORY_VIA_S_VI_STORY29 = 29;

	public const int iCRI_STORY_VIA_S_VI_STORY30 = 30;

	public const int iCRI_STORY_VIA_S_VI_STORY31 = 31;

	public const int iCRI_STORY_VIA_S_VI_STORY32 = 32;

	public const int iCRI_STORY_VIA_S_VI_STORY33 = 33;

	public const int iCRI_STORY_VIA_S_VI_STORY34 = 34;

	public const int iCRI_STORY_VIA_S_VI_STORY35 = 35;

	public const int iCRI_STORY_VIA_S_VI_STORY36 = 36;

	public const int iCRI_STORY_VIA_S_VI_STORY37 = 37;

	public const int iCRI_STORY_VIA_S_VI_STORY38 = 38;

	public const int iCRI_STORY_VIA_S_VI_STORY39 = 39;

	public const int iCRI_STORY_VIA_S_VI_STORY40 = 40;

	public const int iCRI_STORY_VIA_S_VI_STORY41 = 41;

	public const int iCRI_STORY_VIA_S_VI_STORY42 = 42;

	public const int iCRI_STORY_VIA_S_VI_STORY43 = 43;

	public const int iCRI_STORY_VIA_S_VI_STORY44 = 44;

	public const int iCRI_STORY_VIA_S_VI_STORY45 = 45;

	public const int iCRI_STORY_VIA_S_VI_STORY46 = 46;

	public const int iCRI_STORY_VIA_S_VI_STORY47 = 47;

	public const int iCRI_STORY_VIA_S_VI_STORY48 = 48;

	public const int iCRI_STORY_VIA_S_VI_STORY49 = 49;

	public const int iCRI_STORY_VIA_S_VI_STORY50 = 50;

	public const int iCRI_STORY_VIA_S_VI_STORY51 = 51;

	public const int iCRI_STORY_VIA_S_VI_STORY52 = 52;

	public const int iCRI_STORY_VIA_S_VI_STORY53 = 53;

	public const int iCRI_STORY_VIA_S_VI_STORY54 = 54;

	public const int iCRI_STORY_VIA_S_VI_STORY55 = 55;

	public const int iCRI_STORY_VIA_S_VI_STORY56 = 56;

	public const int iCRI_STORY_VIA_S_VI_STORY57 = 57;

	public const int iCRI_STORY_VIA_S_VI_STORY58 = 58;

	public const int iCRI_STORY_VIA_S_VI_STORY59 = 59;

	public const int iCRI_STORY_VIA_S_VI_STORY60 = 60;

	public const int iCRI_STORY_VIA_S_VI_STORY61 = 61;

	public const int iCRI_STORY_VIA_S_VI_STORY62 = 62;

	public const int iCRI_STORY_VIA_S_VI_STORY63 = 63;

	public const int iCRI_STORY_VIA_S_VI_STORY64 = 64;

	public const int iCRI_STORY_VIA_S_VI_STORY65 = 65;

	public const int iCRI_STORY_VIA_S_VI_STORY66 = 66;

	public const int iCRI_STORY_VIA_S_VI_STORY67 = 67;

	public const int iCRI_STORY_VIA_S_VI_STORY68 = 68;

	public const int iCRI_STORY_VIA_S_VI_STORY69 = 69;

	public const int iCRI_STORY_VIA_S_VI_STORY70 = 70;

	public const int iCRI_STORY_VIA_S_VI_STORY71 = 71;

	public const int iCRI_STORY_VIA_S_VI_STORY72 = 72;

	public const int iCRI_STORY_VIA_S_VI_STORY73 = 73;

	public const int iCRI_STORY_VIA_S_VI_STORY74 = 74;

	public const int iCRI_STORY_VIA_S_VI_STORY75 = 75;

	public const int iCRI_STORY_VIA_S_VI_STORY76 = 76;

	public const int iCRI_STORY_VIA_S_VI_STORY77 = 77;

	public const int iCRI_STORY_VIA_S_VI_STORY78 = 78;

	public const int iCRI_STORY_VIA_S_VI_STORY79 = 79;

	public const int iCRI_STORY_VIA_S_VI_STORY80 = 80;

	public const int iCRI_STORY_VIA_S_VI_STORY81 = 81;

	public const int iCRI_STORY_VIA_S_VI_STORY82 = 82;

	public const int iCRI_STORY_VIA_S_VI_STORY83 = 83;

	public const int iCRI_STORY_VIA_S_VI_STORY84 = 84;

	public const int iCRI_STORY_VIA_S_VI_STORY85 = 85;

	public const int iCRI_STORY_VIA_S_VI_STORY86 = 86;

	public const int iCRI_STORY_VIA_S_VI_STORY87 = 87;

	public const int iCRI_STORY_VIA_S_VI_STORY88 = 88;

	public const int iCRI_STORY_VIA_S_VI_STORY89 = 89;

	public const int iCRI_STORY_VIA_S_VI_STORY90 = 90;

	public const int iCRI_STORY_VIA_S_VI_STORY91 = 91;

	public const int iCRI_STORY_VIA_S_VI_STORY92 = 92;

	public const int iCRI_STORY_VIA_S_VI_STORY93 = 93;

	public const STORY_VIA CRI_STORY_VIA_CUENUM = STORY_VIA.CRI_STORY_VIA_CUENUM;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY01 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY01;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY02 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY02;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY03 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY03;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY04 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY04;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY05 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY05;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY06 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY06;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY07 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY07;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY08 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY08;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY09 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY09;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY10 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY10;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY11 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY11;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY12 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY12;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY13 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY13;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY14 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY14;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY15 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY15;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY16 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY16;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY17 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY17;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY18 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY18;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY19 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY19;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY20 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY20;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY21 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY21;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY22 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY22;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY23 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY23;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY24 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY24;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY25 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY25;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY26 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY26;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY27 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY27;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY28 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY28;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY29 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY29;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY30 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY30;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY31 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY31;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY32 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY32;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY33 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY33;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY34 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY34;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY35 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY35;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY36 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY36;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY37 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY37;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY38 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY38;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY39 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY39;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY40 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY40;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY41 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY41;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY42 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY42;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY43 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY43;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY44 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY44;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY45 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY45;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY46 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY46;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY47 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY47;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY48 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY48;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY49 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY49;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY50 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY50;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY51 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY51;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY52 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY52;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY53 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY53;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY54 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY54;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY55 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY55;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY56 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY56;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY57 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY57;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY58 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY58;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY59 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY59;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY60 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY60;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY61 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY61;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY62 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY62;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY63 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY63;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY64 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY64;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY65 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY65;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY66 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY66;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY67 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY67;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY68 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY68;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY69 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY69;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY70 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY70;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY71 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY71;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY72 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY72;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY73 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY73;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY74 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY74;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY75 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY75;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY76 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY76;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY77 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY77;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY78 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY78;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY79 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY79;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY80 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY80;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY81 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY81;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY82 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY82;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY83 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY83;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY84 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY84;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY85 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY85;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY86 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY86;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY87 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY87;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY88 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY88;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY89 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY89;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY90 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY90;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY91 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY91;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY92 = STORY_VIA.CRI_STORY_VIA_S_VI_STORY92;

	public const STORY_VIA CRI_STORY_VIA_S_VI_STORY93 = STORY_VIA.CRI_STORY_VIA_CUENUM;
}
