public static class STORY_CIELi
{
	public const int iCRI_STORY_CIEL_CUENUM = 20;

	public const int iCRI_STORY_CIEL_S_CL_STORY01 = 1;

	public const int iCRI_STORY_CIEL_S_CL_STORY02 = 2;

	public const int iCRI_STORY_CIEL_S_CL_STORY03 = 3;

	public const int iCRI_STORY_CIEL_S_CL_STORY04 = 4;

	public const int iCRI_STORY_CIEL_S_CL_STORY05 = 5;

	public const int iCRI_STORY_CIEL_S_CL_STORY06 = 6;

	public const int iCRI_STORY_CIEL_S_CL_STORY07 = 7;

	public const int iCRI_STORY_CIEL_S_CL_STORY08 = 8;

	public const int iCRI_STORY_CIEL_S_CL_STORY09 = 9;

	public const int iCRI_STORY_CIEL_S_CL_STORY10 = 10;

	public const int iCRI_STORY_CIEL_S_CL_STORY11 = 11;

	public const int iCRI_STORY_CIEL_S_CL_STORY12 = 12;

	public const int iCRI_STORY_CIEL_S_CL_STORY13 = 13;

	public const int iCRI_STORY_CIEL_S_CL_STORY14 = 14;

	public const int iCRI_STORY_CIEL_S_CL_STORY15 = 15;

	public const int iCRI_STORY_CIEL_S_CL_STORY16 = 16;

	public const int iCRI_STORY_CIEL_S_CL_STORY17 = 17;

	public const int iCRI_STORY_CIEL_S_CL_STORY18 = 18;

	public const int iCRI_STORY_CIEL_S_CL_STORY19 = 19;

	public const int iCRI_STORY_CIEL_S_CL_STORY20 = 20;

	public const STORY_CIEL CRI_STORY_CIEL_CUENUM = STORY_CIEL.CRI_STORY_CIEL_CUENUM;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY01 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY01;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY02 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY02;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY03 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY03;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY04 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY04;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY05 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY05;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY06 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY06;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY07 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY07;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY08 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY08;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY09 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY09;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY10 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY10;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY11 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY11;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY12 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY12;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY13 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY13;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY14 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY14;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY15 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY15;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY16 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY16;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY17 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY17;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY18 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY18;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY19 = STORY_CIEL.CRI_STORY_CIEL_S_CL_STORY19;

	public const STORY_CIEL CRI_STORY_CIEL_S_CL_STORY20 = STORY_CIEL.CRI_STORY_CIEL_CUENUM;
}
