public static class STORY_DRAWERi
{
	public const int iCRI_STORY_DRAWER_CUENUM = 66;

	public const int iCRI_STORY_DRAWER_S_DR_STORY01 = 1;

	public const int iCRI_STORY_DRAWER_S_DR_STORY02 = 2;

	public const int iCRI_STORY_DRAWER_S_DR_STORY03 = 3;

	public const int iCRI_STORY_DRAWER_S_DR_STORY04 = 4;

	public const int iCRI_STORY_DRAWER_S_DR_STORY05 = 5;

	public const int iCRI_STORY_DRAWER_S_DR_STORY06 = 6;

	public const int iCRI_STORY_DRAWER_S_DR_STORY07 = 7;

	public const int iCRI_STORY_DRAWER_S_DR_STORY08 = 8;

	public const int iCRI_STORY_DRAWER_S_DR_STORY09 = 9;

	public const int iCRI_STORY_DRAWER_S_DR_STORY10 = 10;

	public const int iCRI_STORY_DRAWER_S_DR_STORY11 = 11;

	public const int iCRI_STORY_DRAWER_S_DR_STORY12 = 12;

	public const int iCRI_STORY_DRAWER_S_DR_STORY13 = 13;

	public const int iCRI_STORY_DRAWER_S_DR_STORY14 = 14;

	public const int iCRI_STORY_DRAWER_S_DR_STORY15 = 15;

	public const int iCRI_STORY_DRAWER_S_DR_STORY16 = 16;

	public const int iCRI_STORY_DRAWER_S_DR_STORY17 = 17;

	public const int iCRI_STORY_DRAWER_S_DR_STORY18 = 19;

	public const int iCRI_STORY_DRAWER_S_DR_STORY19 = 18;

	public const int iCRI_STORY_DRAWER_S_DR_STORY20 = 20;

	public const int iCRI_STORY_DRAWER_S_DR_STORY21 = 21;

	public const int iCRI_STORY_DRAWER_S_DR_STORY22 = 22;

	public const int iCRI_STORY_DRAWER_S_DR_STORY23 = 23;

	public const int iCRI_STORY_DRAWER_S_DR_STORY24 = 24;

	public const int iCRI_STORY_DRAWER_S_DR_STORY25 = 25;

	public const int iCRI_STORY_DRAWER_S_DR_STORY26 = 26;

	public const int iCRI_STORY_DRAWER_S_DR_STORY27 = 27;

	public const int iCRI_STORY_DRAWER_S_DR_STORY28 = 28;

	public const int iCRI_STORY_DRAWER_S_DR_STORY29 = 29;

	public const int iCRI_STORY_DRAWER_S_DR_STORY30 = 30;

	public const int iCRI_STORY_DRAWER_S_DR_STORY31 = 31;

	public const int iCRI_STORY_DRAWER_S_DR_STORY32 = 32;

	public const int iCRI_STORY_DRAWER_S_DR_STORY33 = 33;

	public const int iCRI_STORY_DRAWER_S_DR_STORY34 = 34;

	public const int iCRI_STORY_DRAWER_S_DR_STORY35 = 35;

	public const int iCRI_STORY_DRAWER_S_DR_STORY36 = 36;

	public const int iCRI_STORY_DRAWER_S_DR_STORY37 = 37;

	public const int iCRI_STORY_DRAWER_S_DR_STORY38 = 38;

	public const int iCRI_STORY_DRAWER_S_DR_STORY39 = 39;

	public const int iCRI_STORY_DRAWER_S_DR_STORY40 = 40;

	public const int iCRI_STORY_DRAWER_S_DR_STORY41 = 41;

	public const int iCRI_STORY_DRAWER_S_DR_STORY42 = 42;

	public const int iCRI_STORY_DRAWER_S_DR_STORY43 = 43;

	public const int iCRI_STORY_DRAWER_S_DR_STORY44 = 44;

	public const int iCRI_STORY_DRAWER_S_DR_STORY45 = 45;

	public const int iCRI_STORY_DRAWER_S_DR_STORY46 = 46;

	public const int iCRI_STORY_DRAWER_S_DR_STORY47 = 47;

	public const int iCRI_STORY_DRAWER_S_DR_STORY48 = 48;

	public const int iCRI_STORY_DRAWER_S_DR_STORY49 = 49;

	public const int iCRI_STORY_DRAWER_S_DR_STORY50 = 50;

	public const int iCRI_STORY_DRAWER_S_DR_STORY51 = 51;

	public const int iCRI_STORY_DRAWER_S_DR_STORY52 = 52;

	public const int iCRI_STORY_DRAWER_S_DR_STORY53 = 53;

	public const int iCRI_STORY_DRAWER_S_DR_STORY54 = 54;

	public const int iCRI_STORY_DRAWER_S_DR_STORY55 = 55;

	public const int iCRI_STORY_DRAWER_S_DR_STORY56 = 56;

	public const int iCRI_STORY_DRAWER_S_DR_STORY57 = 57;

	public const int iCRI_STORY_DRAWER_S_DR_STORY58 = 58;

	public const int iCRI_STORY_DRAWER_S_DR_STORY59 = 59;

	public const int iCRI_STORY_DRAWER_S_DR_STORY60 = 60;

	public const int iCRI_STORY_DRAWER_S_DR_STORY61 = 61;

	public const int iCRI_STORY_DRAWER_S_DR_STORY62 = 62;

	public const int iCRI_STORY_DRAWER_S_DR_STORY63 = 63;

	public const int iCRI_STORY_DRAWER_S_DR_STORY64 = 64;

	public const int iCRI_STORY_DRAWER_S_DR_STORY65 = 65;

	public const int iCRI_STORY_DRAWER_S_DR_STORY66 = 66;

	public const STORY_DRAWER CRI_STORY_DRAWER_CUENUM = STORY_DRAWER.CRI_STORY_DRAWER_CUENUM;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY01 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY01;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY02 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY02;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY03 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY03;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY04 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY04;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY05 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY05;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY06 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY06;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY07 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY07;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY08 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY08;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY09 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY09;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY10 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY10;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY11 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY11;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY12 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY12;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY13 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY13;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY14 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY14;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY15 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY15;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY16 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY16;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY17 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY17;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY18 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY18;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY19 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY19;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY20 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY20;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY21 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY21;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY22 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY22;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY23 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY23;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY24 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY24;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY25 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY25;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY26 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY26;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY27 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY27;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY28 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY28;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY29 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY29;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY30 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY30;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY31 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY31;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY32 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY32;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY33 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY33;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY34 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY34;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY35 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY35;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY36 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY36;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY37 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY37;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY38 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY38;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY39 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY39;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY40 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY40;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY41 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY41;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY42 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY42;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY43 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY43;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY44 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY44;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY45 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY45;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY46 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY46;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY47 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY47;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY48 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY48;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY49 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY49;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY50 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY50;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY51 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY51;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY52 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY52;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY53 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY53;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY54 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY54;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY55 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY55;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY56 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY56;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY57 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY57;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY58 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY58;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY59 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY59;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY60 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY60;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY61 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY61;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY62 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY62;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY63 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY63;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY64 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY64;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY65 = STORY_DRAWER.CRI_STORY_DRAWER_S_DR_STORY65;

	public const STORY_DRAWER CRI_STORY_DRAWER_S_DR_STORY66 = STORY_DRAWER.CRI_STORY_DRAWER_CUENUM;
}
