public enum STORY_FORTEEXE
{
	NONE = 0,
	CRI_STORY_FORTEEXE_CUENUM = 16,
	CRI_STORY_FORTEEXE_S_FE_STORY01 = 1,
	CRI_STORY_FORTEEXE_S_FE_STORY02 = 2,
	CRI_STORY_FORTEEXE_S_FE_STORY03 = 3,
	CRI_STORY_FORTEEXE_S_FE_STORY04 = 4,
	CRI_STORY_FORTEEXE_S_FE_STORY05 = 5,
	CRI_STORY_FORTEEXE_S_FE_STORY06 = 6,
	CRI_STORY_FORTEEXE_S_FE_STORY07 = 7,
	CRI_STORY_FORTEEXE_S_FE_STORY08 = 8,
	CRI_STORY_FORTEEXE_S_FE_STORY09 = 9,
	CRI_STORY_FORTEEXE_S_FE_STORY10 = 10,
	CRI_STORY_FORTEEXE_S_FE_STORY11 = 11,
	CRI_STORY_FORTEEXE_S_FE_STORY12 = 12,
	CRI_STORY_FORTEEXE_S_FE_STORY13 = 13,
	CRI_STORY_FORTEEXE_S_FE_STORY14 = 14,
	CRI_STORY_FORTEEXE_S_FE_STORY15 = 15,
	CRI_STORY_FORTEEXE_S_FE_STORY16 = 16
}
