public enum STORY_FERHAM
{
	NONE = 0,
	CRI_STORY_FERHAM_CUENUM = 15,
	CRI_STORY_FERHAM_S_FM_STORY01 = 1,
	CRI_STORY_FERHAM_S_FM_STORY02 = 2,
	CRI_STORY_FERHAM_S_FM_STORY03 = 3,
	CRI_STORY_FERHAM_S_FM_STORY04 = 4,
	CRI_STORY_FERHAM_S_FM_STORY05 = 5,
	CRI_STORY_FERHAM_S_FM_STORY06 = 6,
	CRI_STORY_FERHAM_S_FM_STORY07 = 7,
	CRI_STORY_FERHAM_S_FM_STORY08 = 8,
	CRI_STORY_FERHAM_S_FM_STORY09 = 9,
	CRI_STORY_FERHAM_S_FM_STORY10 = 10,
	CRI_STORY_FERHAM_S_FM_STORY11 = 11,
	CRI_STORY_FERHAM_S_FM_STORY12 = 12,
	CRI_STORY_FERHAM_S_FM_STORY13 = 13,
	CRI_STORY_FERHAM_S_FM_STORY14 = 14,
	CRI_STORY_FERHAM_S_FM_STORY15 = 15
}
