public static class STORY_ROLLCASi
{
	public const int iCRI_STORY_ROLLCAS_CUENUM = 13;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY01 = 1;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY02 = 2;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY03 = 3;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY04 = 4;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY05 = 5;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY06 = 6;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY07 = 7;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY08 = 8;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY09 = 9;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY10 = 10;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY11 = 11;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY12 = 12;

	public const int iCRI_STORY_ROLLCAS_S_RC_STORY13 = 13;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_CUENUM = STORY_ROLLCAS.CRI_STORY_ROLLCAS_CUENUM;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY01 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY01;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY02 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY02;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY03 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY03;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY04 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY04;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY05 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY05;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY06 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY06;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY07 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY07;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY08 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY08;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY09 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY09;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY10 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY10;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY11 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY11;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY12 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_S_RC_STORY12;

	public const STORY_ROLLCAS CRI_STORY_ROLLCAS_S_RC_STORY13 = STORY_ROLLCAS.CRI_STORY_ROLLCAS_CUENUM;
}
