public static class STORY_NMDERi
{
	public const int iCRI_STORY_NMDER_CUENUM = 5;

	public const int iCRI_STORY_NMDER_S_NM_STORY01 = 1;

	public const int iCRI_STORY_NMDER_S_NM_STORY02 = 2;

	public const int iCRI_STORY_NMDER_S_NM_STORY03 = 3;

	public const int iCRI_STORY_NMDER_S_NM_STORY04 = 4;

	public const int iCRI_STORY_NMDER_S_NM_STORY05 = 5;

	public const STORY_NMDER CRI_STORY_NMDER_CUENUM = STORY_NMDER.CRI_STORY_NMDER_CUENUM;

	public const STORY_NMDER CRI_STORY_NMDER_S_NM_STORY01 = STORY_NMDER.CRI_STORY_NMDER_S_NM_STORY01;

	public const STORY_NMDER CRI_STORY_NMDER_S_NM_STORY02 = STORY_NMDER.CRI_STORY_NMDER_S_NM_STORY02;

	public const STORY_NMDER CRI_STORY_NMDER_S_NM_STORY03 = STORY_NMDER.CRI_STORY_NMDER_S_NM_STORY03;

	public const STORY_NMDER CRI_STORY_NMDER_S_NM_STORY04 = STORY_NMDER.CRI_STORY_NMDER_S_NM_STORY04;

	public const STORY_NMDER CRI_STORY_NMDER_S_NM_STORY05 = STORY_NMDER.CRI_STORY_NMDER_CUENUM;
}
