public enum STORY_FORTE
{
	NONE = 0,
	CRI_STORY_FORTE_CUENUM = 13,
	CRI_STORY_FORTE_S_FO_STORY01 = 1,
	CRI_STORY_FORTE_S_FO_STORY02 = 2,
	CRI_STORY_FORTE_S_FO_STORY03 = 3,
	CRI_STORY_FORTE_S_FO_STORY04 = 4,
	CRI_STORY_FORTE_S_FO_STORY05 = 5,
	CRI_STORY_FORTE_S_FO_STORY06 = 6,
	CRI_STORY_FORTE_S_FO_STORY07 = 7,
	CRI_STORY_FORTE_S_FO_STORY08 = 8,
	CRI_STORY_FORTE_S_FO_STORY09 = 9,
	CRI_STORY_FORTE_S_FO_STORY10 = 10,
	CRI_STORY_FORTE_S_FO_STORY11 = 11,
	CRI_STORY_FORTE_S_FO_STORY12 = 12,
	CRI_STORY_FORTE_S_FO_STORY13 = 13
}
