public enum STORY_TRON
{
	NONE = 0,
	CRI_STORY_TRON_CUENUM = 16,
	CRI_STORY_TRON_S_TR_STORY01 = 1,
	CRI_STORY_TRON_S_TR_STORY02 = 2,
	CRI_STORY_TRON_S_TR_STORY03 = 3,
	CRI_STORY_TRON_S_TR_STORY04 = 4,
	CRI_STORY_TRON_S_TR_STORY05 = 5,
	CRI_STORY_TRON_S_TR_STORY06 = 6,
	CRI_STORY_TRON_S_TR_STORY07 = 7,
	CRI_STORY_TRON_S_TR_STORY08 = 8,
	CRI_STORY_TRON_S_TR_STORY09 = 9,
	CRI_STORY_TRON_S_TR_STORY10 = 10,
	CRI_STORY_TRON_S_TR_STORY11 = 11,
	CRI_STORY_TRON_S_TR_STORY12 = 12,
	CRI_STORY_TRON_S_TR_STORY13 = 13,
	CRI_STORY_TRON_S_TR_STORY14 = 14,
	CRI_STORY_TRON_S_TR_STORY15 = 15,
	CRI_STORY_TRON_S_TR_STORY16 = 16
}
