public static class SystemSEi
{
	public const int iCRI_SYSTEMSE_CUENUM = 107;

	public const int iCRI_SYSTEMSE_SYS_CAPCOMLOGO = 1;

	public const int iCRI_SYSTEMSE_SYS_OK01 = 2;

	public const int iCRI_SYSTEMSE_SYS_OK02 = 3;

	public const int iCRI_SYSTEMSE_SYS_OK03 = 4;

	public const int iCRI_SYSTEMSE_SYS_OK04 = 5;

	public const int iCRI_SYSTEMSE_SYS_OK05 = 6;

	public const int iCRI_SYSTEMSE_SYS_OK06 = 7;

	public const int iCRI_SYSTEMSE_SYS_OK07 = 8;

	public const int iCRI_SYSTEMSE_SYS_OK08 = 9;

	public const int iCRI_SYSTEMSE_SYS_OK09 = 10;

	public const int iCRI_SYSTEMSE_SYS_OK10 = 11;

	public const int iCRI_SYSTEMSE_SYS_OK11 = 12;

	public const int iCRI_SYSTEMSE_SYS_OK12 = 13;

	public const int iCRI_SYSTEMSE_SYS_OK13 = 14;

	public const int iCRI_SYSTEMSE_SYS_OK14 = 15;

	public const int iCRI_SYSTEMSE_SYS_OK15 = 16;

	public const int iCRI_SYSTEMSE_SYS_CURSOR01 = 21;

	public const int iCRI_SYSTEMSE_SYS_CURSOR02 = 22;

	public const int iCRI_SYSTEMSE_SYS_CURSOR03 = 23;

	public const int iCRI_SYSTEMSE_SYS_CURSOR04 = 25;

	public const int iCRI_SYSTEMSE_SYS_CURSOR05 = 26;

	public const int iCRI_SYSTEMSE_SYS_CURSOR06 = 27;

	public const int iCRI_SYSTEMSE_SYS_ERROR = 31;

	public const int iCRI_SYSTEMSE_SYS_BACK01 = 32;

	public const int iCRI_SYSTEMSE_SYS_WINDOW_OP = 36;

	public const int iCRI_SYSTEMSE_SYS_WINDOW_CL = 37;

	public const int iCRI_SYSTEMSE_SYS_WINDOW_OP01 = 38;

	public const int iCRI_SYSTEMSE_SYS_WINDOW_CL01 = 39;

	public const int iCRI_SYSTEMSE_SYS_WINDOW_OP02 = 40;

	public const int iCRI_SYSTEMSE_SYS_WINDOW_CL02 = 41;

	public const int iCRI_SYSTEMSE_SYS_PROGRESS01_LP = 46;

	public const int iCRI_SYSTEMSE_SYS_PROGRESS01_STOP = 47;

	public const int iCRI_SYSTEMSE_SYS_PROGRESS02_LP = 48;

	public const int iCRI_SYSTEMSE_SYS_PROGRESS02_STOP = 49;

	public const int iCRI_SYSTEMSE_SYS_PROGRESS03 = 50;

	public const int iCRI_SYSTEMSE_SYS_OPEN01 = 86;

	public const int iCRI_SYSTEMSE_SYS_OPEN02 = 87;

	public const int iCRI_SYSTEMSE_SYS_OPEN03 = 88;

	public const int iCRI_SYSTEMSE_SYS_GLOW01 = 56;

	public const int iCRI_SYSTEMSE_SYS_GLOW02 = 57;

	public const int iCRI_SYSTEMSE_SYS_GLOW03 = 58;

	public const int iCRI_SYSTEMSE_SYS_GLOW04 = 59;

	public const int iCRI_SYSTEMSE_SYS_STORE01 = 65;

	public const int iCRI_SYSTEMSE_SYS_STORE02 = 66;

	public const int iCRI_SYSTEMSE_SYS_STORE03 = 67;

	public const int iCRI_SYSTEMSE_SYS_ITEM01 = 68;

	public const int iCRI_SYSTEMSE_SYS_ITEM02 = 69;

	public const int iCRI_SYSTEMSE_SYS_TALK01_LP = 76;

	public const int iCRI_SYSTEMSE_SYS_TALK01_STOP = 77;

	public const int iCRI_SYSTEMSE_SYS_TALK02_LP = 78;

	public const int iCRI_SYSTEMSE_SYS_TALK02_STOP = 79;

	public const int iCRI_SYSTEMSE_SYS_PROGRESS04_LP = 51;

	public const int iCRI_SYSTEMSE_SYS_PROGRESS04_STOP = 52;

	public const int iCRI_SYSTEMSE_SYS_ACCESS01_LP = 33;

	public const int iCRI_SYSTEMSE_SYS_ACCESS_STOP = 34;

	public const int iCRI_SYSTEMSE_SYS_ACCESS01_STOP = 24;

	public const int iCRI_SYSTEMSE_SYS_EFFECT01 = 90;

	public const int iCRI_SYSTEMSE_SYS_OK16 = 17;

	public const int iCRI_SYSTEMSE_SYS_CURSOR07 = 28;

	public const int iCRI_SYSTEMSE_SYS_CURSOR08 = 29;

	public const int iCRI_SYSTEMSE_SYS_SCROLL01 = 30;

	public const int iCRI_SYSTEMSE_SYS_SCROLL02 = 64;

	public const int iCRI_SYSTEMSE_SYS_HOME = 45;

	public const int iCRI_SYSTEMSE_SYS_EFFECT04 = 93;

	public const int iCRI_SYSTEMSE_SYS_OK17 = 18;

	public const int iCRI_SYSTEMSE_SYS_STAMP01 = 83;

	public const int iCRI_SYSTEMSE_SYS_STAMP03 = 85;

	public const int iCRI_SYSTEMSE_SYS_STAMP02 = 84;

	public const int iCRI_SYSTEMSE_SYS_RESULT01 = 97;

	public const int iCRI_SYSTEMSE_SYS_STORY01 = 102;

	public const int iCRI_SYSTEMSE_SYS_STORY02 = 103;

	public const int iCRI_SYSTEMSE_SYS_RESULT02 = 35;

	public const int iCRI_SYSTEMSE_SYS_WINDOW_OP03 = 42;

	public const int iCRI_SYSTEMSE_SYS_TIMER01 = 70;

	public const int iCRI_SYSTEMSE_SYS_TIMER02 = 71;

	public const int iCRI_SYSTEMSE_SYS_KAITEN01 = 89;

	public const int iCRI_SYSTEMSE_SYS_OK18 = 104;

	public const int iCRI_SYSTEMSE_SYS_EFFECT02 = 91;

	public const int iCRI_SYSTEMSE_SYS_WINDOW_OP04 = 43;

	public const int iCRI_SYSTEMSE_SYS_CANCEL = 44;

	public const int iCRI_SYSTEMSE_SYS_SEND = 63;

	public const int iCRI_SYSTEMSE_SYS_GACHA01_S1 = 110;

	public const int iCRI_SYSTEMSE_SYS_GACHA01_S2 = 111;

	public const int iCRI_SYSTEMSE_SYS_GACHA01_S3 = 112;

	public const int iCRI_SYSTEMSE_SYS_GACHA01_A = 113;

	public const int iCRI_SYSTEMSE_SYS_GACHA02_1 = 114;

	public const int iCRI_SYSTEMSE_SYS_GACHA03_L = 118;

	public const int iCRI_SYSTEMSE_SYS_GACHA03_H = 116;

	public const int iCRI_SYSTEMSE_SYS_GACHA03_M = 117;

	public const int iCRI_SYSTEMSE_SYS_GACHA04 = 119;

	public const int iCRI_SYSTEMSE_SYS_GACHA05 = 120;

	public const int iCRI_SYSTEMSE_SYS_GACHA02_10 = 115;

	public const int iCRI_SYSTEMSE_SYS_GACHA02_11 = 109;

	public const int iCRI_SYSTEMSE_SYS_CHARA01 = 121;

	public const int iCRI_SYSTEMSE_SYS_RANKDOWN = 96;

	public const int iCRI_SYSTEMSE_SYS_RANKUP = 95;

	public const int iCRI_SYSTEMSE_SYS_SPIN = 80;

	public const int iCRI_SYSTEMSE_SYS_STOP = 81;

	public const int iCRI_SYSTEMSE_SYS_CHARA02 = 122;

	public const int iCRI_SYSTEMSE_SYS_CHARA03 = 123;

	public const int iCRI_SYSTEMSE_SYS_CHARA04 = 124;

	public const int iCRI_SYSTEMSE_SYS_KIDOU01 = 72;

	public const int iCRI_SYSTEMSE_SYS_KIDOU02 = 73;

	public const int iCRI_SYSTEMSE_SYS_BATTLE = 98;

	public const int iCRI_SYSTEMSE_SYS_LOSE01 = 100;

	public const int iCRI_SYSTEMSE_SYS_WIN01 = 99;

	public const int iCRI_SYSTEMSE_SYS_HALLOWEEN01 = 107;

	public const SystemSE CRI_SYSTEMSE_CUENUM = SystemSE.CRI_SYSTEMSE_CUENUM;

	public const SystemSE CRI_SYSTEMSE_SYS_CAPCOMLOGO = SystemSE.CRI_SYSTEMSE_SYS_CAPCOMLOGO;

	public const SystemSE CRI_SYSTEMSE_SYS_OK01 = SystemSE.CRI_SYSTEMSE_SYS_OK01;

	public const SystemSE CRI_SYSTEMSE_SYS_OK02 = SystemSE.CRI_SYSTEMSE_SYS_OK02;

	public const SystemSE CRI_SYSTEMSE_SYS_OK03 = SystemSE.CRI_SYSTEMSE_SYS_OK03;

	public const SystemSE CRI_SYSTEMSE_SYS_OK04 = SystemSE.CRI_SYSTEMSE_SYS_OK04;

	public const SystemSE CRI_SYSTEMSE_SYS_OK05 = SystemSE.CRI_SYSTEMSE_SYS_OK05;

	public const SystemSE CRI_SYSTEMSE_SYS_OK06 = SystemSE.CRI_SYSTEMSE_SYS_OK06;

	public const SystemSE CRI_SYSTEMSE_SYS_OK07 = SystemSE.CRI_SYSTEMSE_SYS_OK07;

	public const SystemSE CRI_SYSTEMSE_SYS_OK08 = SystemSE.CRI_SYSTEMSE_SYS_OK08;

	public const SystemSE CRI_SYSTEMSE_SYS_OK09 = SystemSE.CRI_SYSTEMSE_SYS_OK09;

	public const SystemSE CRI_SYSTEMSE_SYS_OK10 = SystemSE.CRI_SYSTEMSE_SYS_OK10;

	public const SystemSE CRI_SYSTEMSE_SYS_OK11 = SystemSE.CRI_SYSTEMSE_SYS_OK11;

	public const SystemSE CRI_SYSTEMSE_SYS_OK12 = SystemSE.CRI_SYSTEMSE_SYS_OK12;

	public const SystemSE CRI_SYSTEMSE_SYS_OK13 = SystemSE.CRI_SYSTEMSE_SYS_OK13;

	public const SystemSE CRI_SYSTEMSE_SYS_OK14 = SystemSE.CRI_SYSTEMSE_SYS_OK14;

	public const SystemSE CRI_SYSTEMSE_SYS_OK15 = SystemSE.CRI_SYSTEMSE_SYS_OK15;

	public const SystemSE CRI_SYSTEMSE_SYS_CURSOR01 = SystemSE.CRI_SYSTEMSE_SYS_CURSOR01;

	public const SystemSE CRI_SYSTEMSE_SYS_CURSOR02 = SystemSE.CRI_SYSTEMSE_SYS_CURSOR02;

	public const SystemSE CRI_SYSTEMSE_SYS_CURSOR03 = SystemSE.CRI_SYSTEMSE_SYS_CURSOR03;

	public const SystemSE CRI_SYSTEMSE_SYS_CURSOR04 = SystemSE.CRI_SYSTEMSE_SYS_CURSOR04;

	public const SystemSE CRI_SYSTEMSE_SYS_CURSOR05 = SystemSE.CRI_SYSTEMSE_SYS_CURSOR05;

	public const SystemSE CRI_SYSTEMSE_SYS_CURSOR06 = SystemSE.CRI_SYSTEMSE_SYS_CURSOR06;

	public const SystemSE CRI_SYSTEMSE_SYS_ERROR = SystemSE.CRI_SYSTEMSE_SYS_ERROR;

	public const SystemSE CRI_SYSTEMSE_SYS_BACK01 = SystemSE.CRI_SYSTEMSE_SYS_BACK01;

	public const SystemSE CRI_SYSTEMSE_SYS_WINDOW_OP = SystemSE.CRI_SYSTEMSE_SYS_WINDOW_OP;

	public const SystemSE CRI_SYSTEMSE_SYS_WINDOW_CL = SystemSE.CRI_SYSTEMSE_SYS_WINDOW_CL;

	public const SystemSE CRI_SYSTEMSE_SYS_WINDOW_OP01 = SystemSE.CRI_SYSTEMSE_SYS_WINDOW_OP01;

	public const SystemSE CRI_SYSTEMSE_SYS_WINDOW_CL01 = SystemSE.CRI_SYSTEMSE_SYS_WINDOW_CL01;

	public const SystemSE CRI_SYSTEMSE_SYS_WINDOW_OP02 = SystemSE.CRI_SYSTEMSE_SYS_WINDOW_OP02;

	public const SystemSE CRI_SYSTEMSE_SYS_WINDOW_CL02 = SystemSE.CRI_SYSTEMSE_SYS_WINDOW_CL02;

	public const SystemSE CRI_SYSTEMSE_SYS_PROGRESS01_LP = SystemSE.CRI_SYSTEMSE_SYS_PROGRESS01_LP;

	public const SystemSE CRI_SYSTEMSE_SYS_PROGRESS01_STOP = SystemSE.CRI_SYSTEMSE_SYS_PROGRESS01_STOP;

	public const SystemSE CRI_SYSTEMSE_SYS_PROGRESS02_LP = SystemSE.CRI_SYSTEMSE_SYS_PROGRESS02_LP;

	public const SystemSE CRI_SYSTEMSE_SYS_PROGRESS02_STOP = SystemSE.CRI_SYSTEMSE_SYS_PROGRESS02_STOP;

	public const SystemSE CRI_SYSTEMSE_SYS_PROGRESS03 = SystemSE.CRI_SYSTEMSE_SYS_PROGRESS03;

	public const SystemSE CRI_SYSTEMSE_SYS_OPEN01 = SystemSE.CRI_SYSTEMSE_SYS_OPEN01;

	public const SystemSE CRI_SYSTEMSE_SYS_OPEN02 = SystemSE.CRI_SYSTEMSE_SYS_OPEN02;

	public const SystemSE CRI_SYSTEMSE_SYS_OPEN03 = SystemSE.CRI_SYSTEMSE_SYS_OPEN03;

	public const SystemSE CRI_SYSTEMSE_SYS_GLOW01 = SystemSE.CRI_SYSTEMSE_SYS_GLOW01;

	public const SystemSE CRI_SYSTEMSE_SYS_GLOW02 = SystemSE.CRI_SYSTEMSE_SYS_GLOW02;

	public const SystemSE CRI_SYSTEMSE_SYS_GLOW03 = SystemSE.CRI_SYSTEMSE_SYS_GLOW03;

	public const SystemSE CRI_SYSTEMSE_SYS_GLOW04 = SystemSE.CRI_SYSTEMSE_SYS_GLOW04;

	public const SystemSE CRI_SYSTEMSE_SYS_STORE01 = SystemSE.CRI_SYSTEMSE_SYS_STORE01;

	public const SystemSE CRI_SYSTEMSE_SYS_STORE02 = SystemSE.CRI_SYSTEMSE_SYS_STORE02;

	public const SystemSE CRI_SYSTEMSE_SYS_STORE03 = SystemSE.CRI_SYSTEMSE_SYS_STORE03;

	public const SystemSE CRI_SYSTEMSE_SYS_ITEM01 = SystemSE.CRI_SYSTEMSE_SYS_ITEM01;

	public const SystemSE CRI_SYSTEMSE_SYS_ITEM02 = SystemSE.CRI_SYSTEMSE_SYS_ITEM02;

	public const SystemSE CRI_SYSTEMSE_SYS_TALK01_LP = SystemSE.CRI_SYSTEMSE_SYS_TALK01_LP;

	public const SystemSE CRI_SYSTEMSE_SYS_TALK01_STOP = SystemSE.CRI_SYSTEMSE_SYS_TALK01_STOP;

	public const SystemSE CRI_SYSTEMSE_SYS_TALK02_LP = SystemSE.CRI_SYSTEMSE_SYS_TALK02_LP;

	public const SystemSE CRI_SYSTEMSE_SYS_TALK02_STOP = SystemSE.CRI_SYSTEMSE_SYS_TALK02_STOP;

	public const SystemSE CRI_SYSTEMSE_SYS_PROGRESS04_LP = SystemSE.CRI_SYSTEMSE_SYS_PROGRESS04_LP;

	public const SystemSE CRI_SYSTEMSE_SYS_PROGRESS04_STOP = SystemSE.CRI_SYSTEMSE_SYS_PROGRESS04_STOP;

	public const SystemSE CRI_SYSTEMSE_SYS_ACCESS01_LP = SystemSE.CRI_SYSTEMSE_SYS_ACCESS01_LP;

	public const SystemSE CRI_SYSTEMSE_SYS_ACCESS_STOP = SystemSE.CRI_SYSTEMSE_SYS_ACCESS_STOP;

	public const SystemSE CRI_SYSTEMSE_SYS_ACCESS01_STOP = SystemSE.CRI_SYSTEMSE_SYS_ACCESS01_STOP;

	public const SystemSE CRI_SYSTEMSE_SYS_EFFECT01 = SystemSE.CRI_SYSTEMSE_SYS_EFFECT01;

	public const SystemSE CRI_SYSTEMSE_SYS_OK16 = SystemSE.CRI_SYSTEMSE_SYS_OK16;

	public const SystemSE CRI_SYSTEMSE_SYS_CURSOR07 = SystemSE.CRI_SYSTEMSE_SYS_CURSOR07;

	public const SystemSE CRI_SYSTEMSE_SYS_CURSOR08 = SystemSE.CRI_SYSTEMSE_SYS_CURSOR08;

	public const SystemSE CRI_SYSTEMSE_SYS_SCROLL01 = SystemSE.CRI_SYSTEMSE_SYS_SCROLL01;

	public const SystemSE CRI_SYSTEMSE_SYS_SCROLL02 = SystemSE.CRI_SYSTEMSE_SYS_SCROLL02;

	public const SystemSE CRI_SYSTEMSE_SYS_HOME = SystemSE.CRI_SYSTEMSE_SYS_HOME;

	public const SystemSE CRI_SYSTEMSE_SYS_EFFECT04 = SystemSE.CRI_SYSTEMSE_SYS_EFFECT04;

	public const SystemSE CRI_SYSTEMSE_SYS_OK17 = SystemSE.CRI_SYSTEMSE_SYS_OK17;

	public const SystemSE CRI_SYSTEMSE_SYS_STAMP01 = SystemSE.CRI_SYSTEMSE_SYS_STAMP01;

	public const SystemSE CRI_SYSTEMSE_SYS_STAMP03 = SystemSE.CRI_SYSTEMSE_SYS_STAMP03;

	public const SystemSE CRI_SYSTEMSE_SYS_STAMP02 = SystemSE.CRI_SYSTEMSE_SYS_STAMP02;

	public const SystemSE CRI_SYSTEMSE_SYS_RESULT01 = SystemSE.CRI_SYSTEMSE_SYS_RESULT01;

	public const SystemSE CRI_SYSTEMSE_SYS_STORY01 = SystemSE.CRI_SYSTEMSE_SYS_STORY01;

	public const SystemSE CRI_SYSTEMSE_SYS_STORY02 = SystemSE.CRI_SYSTEMSE_SYS_STORY02;

	public const SystemSE CRI_SYSTEMSE_SYS_RESULT02 = SystemSE.CRI_SYSTEMSE_SYS_RESULT02;

	public const SystemSE CRI_SYSTEMSE_SYS_WINDOW_OP03 = SystemSE.CRI_SYSTEMSE_SYS_WINDOW_OP03;

	public const SystemSE CRI_SYSTEMSE_SYS_TIMER01 = SystemSE.CRI_SYSTEMSE_SYS_TIMER01;

	public const SystemSE CRI_SYSTEMSE_SYS_TIMER02 = SystemSE.CRI_SYSTEMSE_SYS_TIMER02;

	public const SystemSE CRI_SYSTEMSE_SYS_KAITEN01 = SystemSE.CRI_SYSTEMSE_SYS_KAITEN01;

	public const SystemSE CRI_SYSTEMSE_SYS_OK18 = SystemSE.CRI_SYSTEMSE_SYS_OK18;

	public const SystemSE CRI_SYSTEMSE_SYS_EFFECT02 = SystemSE.CRI_SYSTEMSE_SYS_EFFECT02;

	public const SystemSE CRI_SYSTEMSE_SYS_WINDOW_OP04 = SystemSE.CRI_SYSTEMSE_SYS_WINDOW_OP04;

	public const SystemSE CRI_SYSTEMSE_SYS_CANCEL = SystemSE.CRI_SYSTEMSE_SYS_CANCEL;

	public const SystemSE CRI_SYSTEMSE_SYS_SEND = SystemSE.CRI_SYSTEMSE_SYS_SEND;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA01_S1 = SystemSE.CRI_SYSTEMSE_SYS_GACHA01_S1;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA01_S2 = SystemSE.CRI_SYSTEMSE_SYS_GACHA01_S2;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA01_S3 = SystemSE.CRI_SYSTEMSE_SYS_GACHA01_S3;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA01_A = SystemSE.CRI_SYSTEMSE_SYS_GACHA01_A;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA02_1 = SystemSE.CRI_SYSTEMSE_SYS_GACHA02_1;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA03_L = SystemSE.CRI_SYSTEMSE_SYS_GACHA03_L;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA03_H = SystemSE.CRI_SYSTEMSE_SYS_GACHA03_H;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA03_M = SystemSE.CRI_SYSTEMSE_SYS_GACHA03_M;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA04 = SystemSE.CRI_SYSTEMSE_SYS_GACHA04;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA05 = SystemSE.CRI_SYSTEMSE_SYS_GACHA05;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA02_10 = SystemSE.CRI_SYSTEMSE_SYS_GACHA02_10;

	public const SystemSE CRI_SYSTEMSE_SYS_GACHA02_11 = SystemSE.CRI_SYSTEMSE_SYS_GACHA02_11;

	public const SystemSE CRI_SYSTEMSE_SYS_CHARA01 = SystemSE.CRI_SYSTEMSE_SYS_CHARA01;

	public const SystemSE CRI_SYSTEMSE_SYS_RANKDOWN = SystemSE.CRI_SYSTEMSE_SYS_RANKDOWN;

	public const SystemSE CRI_SYSTEMSE_SYS_RANKUP = SystemSE.CRI_SYSTEMSE_SYS_RANKUP;

	public const SystemSE CRI_SYSTEMSE_SYS_SPIN = SystemSE.CRI_SYSTEMSE_SYS_SPIN;

	public const SystemSE CRI_SYSTEMSE_SYS_STOP = SystemSE.CRI_SYSTEMSE_SYS_STOP;

	public const SystemSE CRI_SYSTEMSE_SYS_CHARA02 = SystemSE.CRI_SYSTEMSE_SYS_CHARA02;

	public const SystemSE CRI_SYSTEMSE_SYS_CHARA03 = SystemSE.CRI_SYSTEMSE_SYS_CHARA03;

	public const SystemSE CRI_SYSTEMSE_SYS_CHARA04 = SystemSE.CRI_SYSTEMSE_SYS_CHARA04;

	public const SystemSE CRI_SYSTEMSE_SYS_KIDOU01 = SystemSE.CRI_SYSTEMSE_SYS_KIDOU01;

	public const SystemSE CRI_SYSTEMSE_SYS_KIDOU02 = SystemSE.CRI_SYSTEMSE_SYS_KIDOU02;

	public const SystemSE CRI_SYSTEMSE_SYS_BATTLE = SystemSE.CRI_SYSTEMSE_SYS_BATTLE;

	public const SystemSE CRI_SYSTEMSE_SYS_LOSE01 = SystemSE.CRI_SYSTEMSE_SYS_LOSE01;

	public const SystemSE CRI_SYSTEMSE_SYS_WIN01 = SystemSE.CRI_SYSTEMSE_SYS_WIN01;

	public const SystemSE CRI_SYSTEMSE_SYS_HALLOWEEN01 = SystemSE.CRI_SYSTEMSE_CUENUM;
}
