public static class VOICE_VAVAi
{
	public const int iCRI_VOICE_VAVA_CUENUM = 21;

	public const int iCRI_VOICE_VAVA_V_VA_HURT01 = 1;

	public const int iCRI_VOICE_VAVA_V_VA_ATTACK01 = 25;

	public const int iCRI_VOICE_VAVA_V_VA_PINCH01 = 20;

	public const int iCRI_VOICE_VAVA_V_VA_PINCH02 = 21;

	public const int iCRI_VOICE_VAVA_V_VA_PINCH03 = 22;

	public const int iCRI_VOICE_VAVA_V_VA_LOSE01 = 5;

	public const int iCRI_VOICE_VAVA_V_VA_UNIQUE01 = 6;

	public const int iCRI_VOICE_VAVA_V_VA_WIN01 = 3;

	public const int iCRI_VOICE_VAVA_V_VA_JUMP01 = 12;

	public const int iCRI_VOICE_VAVA_V_VA_SABER01 = 14;

	public const int iCRI_VOICE_VAVA_V_VA_SABER02 = 15;

	public const int iCRI_VOICE_VAVA_V_VA_SABER03 = 16;

	public const int iCRI_VOICE_VAVA_V_VA_SABER04 = 17;

	public const int iCRI_VOICE_VAVA_V_VA_SABER05 = 18;

	public const int iCRI_VOICE_VAVA_V_VA_SKILL02 = 9;

	public const int iCRI_VOICE_VAVA_V_VA_SKILL01 = 8;

	public const int iCRI_VOICE_VAVA_V_VA_START01 = 2;

	public const int iCRI_VOICE_VAVA_V_VA_SKILL03 = 10;

	public const int iCRI_VOICE_VAVA_V_VA_SKILL04 = 11;

	public const int iCRI_VOICE_VAVA_V_VA_CHARA01 = 26;

	public const int iCRI_VOICE_VAVA_V_VA_CHARA02 = 40;

	public const VOICE_VAVA CRI_VOICE_VAVA_CUENUM = VOICE_VAVA.CRI_VOICE_VAVA_CUENUM;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_HURT01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_HURT01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_ATTACK01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_ATTACK01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_PINCH01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_PINCH01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_PINCH02 = VOICE_VAVA.CRI_VOICE_VAVA_CUENUM;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_PINCH03 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_PINCH03;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_LOSE01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_LOSE01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_UNIQUE01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_UNIQUE01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_WIN01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_WIN01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_JUMP01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_JUMP01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_SABER01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_SABER01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_SABER02 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_SABER02;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_SABER03 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_SABER03;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_SABER04 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_SABER04;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_SABER05 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_SABER05;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_SKILL02 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_SKILL02;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_SKILL01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_SKILL01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_START01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_START01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_SKILL03 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_SKILL03;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_SKILL04 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_SKILL04;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_CHARA01 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_CHARA01;

	public const VOICE_VAVA CRI_VOICE_VAVA_V_VA_CHARA02 = VOICE_VAVA.CRI_VOICE_VAVA_V_VA_CHARA02;
}
