public static class VOICE_CIEL3i
{
	public const int iCRI_VOICE_CIEL3_CUENUM = 16;

	public const int iCRI_VOICE_CIEL3_V_CL3_HURT01 = 1;

	public const int iCRI_VOICE_CIEL3_V_CL3_ATTACK01 = 25;

	public const int iCRI_VOICE_CIEL3_V_CL3_SKILL01 = 8;

	public const int iCRI_VOICE_CIEL3_V_CL3_SKILL02 = 9;

	public const int iCRI_VOICE_CIEL3_V_CL3_PINCH01 = 20;

	public const int iCRI_VOICE_CIEL3_V_CL3_PINCH02 = 21;

	public const int iCRI_VOICE_CIEL3_V_CL3_PINCH03 = 22;

	public const int iCRI_VOICE_CIEL3_V_CL3_LOSE01 = 5;

	public const int iCRI_VOICE_CIEL3_V_CL3_UNIQUE01 = 6;

	public const int iCRI_VOICE_CIEL3_V_CL3_WIN01 = 3;

	public const int iCRI_VOICE_CIEL3_V_CL3_JUMP01 = 12;

	public const int iCRI_VOICE_CIEL3_V_CL3_SABER01 = 14;

	public const int iCRI_VOICE_CIEL3_V_CL3_SABER03 = 16;

	public const int iCRI_VOICE_CIEL3_V_CL3_SABER05 = 18;

	public const int iCRI_VOICE_CIEL3_V_CL3_START01 = 2;

	public const int iCRI_VOICE_CIEL3_V_CL3_CHARA01 = 40;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_CUENUM = VOICE_CIEL3.CRI_VOICE_CIEL3_CUENUM;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_HURT01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_HURT01;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_ATTACK01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_ATTACK01;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_SKILL01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_SKILL01;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_SKILL02 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_SKILL02;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_PINCH01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_PINCH01;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_PINCH02 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_PINCH02;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_PINCH03 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_PINCH03;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_LOSE01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_LOSE01;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_UNIQUE01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_UNIQUE01;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_WIN01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_WIN01;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_JUMP01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_JUMP01;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_SABER01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_SABER01;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_SABER03 = VOICE_CIEL3.CRI_VOICE_CIEL3_CUENUM;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_SABER05 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_SABER05;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_START01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_START01;

	public const VOICE_CIEL3 CRI_VOICE_CIEL3_V_CL3_CHARA01 = VOICE_CIEL3.CRI_VOICE_CIEL3_V_CL3_CHARA01;
}
