public enum VOICE_XFalcon
{
	NONE = 0,
	CRI_VOICE_XFALCON_CUENUM = 17,
	CRI_VOICE_XFALCON_V_XF_HURT01 = 1,
	CRI_VOICE_XFALCON_V_XF_ATTACK01 = 25,
	CRI_VOICE_XFALCON_V_XF_SKILL01 = 8,
	CRI_VOICE_XFALCON_V_XF_PINCH01 = 20,
	CRI_VOICE_XFALCON_V_XF_PINCH02 = 21,
	CRI_VOICE_XFALCON_V_XF_PINCH03 = 22,
	CRI_VOICE_XFALCON_V_XF_LOSE01 = 5,
	CRI_VOICE_XFALCON_V_XF_UNIQUE01 = 6,
	CRI_VOICE_XFALCON_V_XF_WIN01 = 3,
	CRI_VOICE_XFALCON_V_XF_JUMP01 = 12,
	CRI_VOICE_XFALCON_V_XF_SABER01 = 14,
	CRI_VOICE_XFALCON_V_XF_SABER02 = 15,
	CRI_VOICE_XFALCON_V_XF_SABER03 = 16,
	CRI_VOICE_XFALCON_V_XF_SABER04 = 17,
	CRI_VOICE_XFALCON_V_XF_SABER05 = 18,
	CRI_VOICE_XFALCON_V_XF_START01 = 2,
	CRI_VOICE_XFALCON_V_XF_SKILL02 = 9
}
