public static class VOICE_XShadowi
{
	public const int iCRI_VOICE_XSHADOW_CUENUM = 16;

	public const int iCRI_VOICE_XSHADOW_V_XS_HURT01 = 1;

	public const int iCRI_VOICE_XSHADOW_V_XS_ATTACK01 = 25;

	public const int iCRI_VOICE_XSHADOW_V_XS_SKILL01 = 8;

	public const int iCRI_VOICE_XSHADOW_V_XS_SKILL02 = 9;

	public const int iCRI_VOICE_XSHADOW_V_XS_PINCH01 = 20;

	public const int iCRI_VOICE_XSHADOW_V_XS_PINCH02 = 21;

	public const int iCRI_VOICE_XSHADOW_V_XS_PINCH03 = 22;

	public const int iCRI_VOICE_XSHADOW_V_XS_LOSE01 = 5;

	public const int iCRI_VOICE_XSHADOW_V_XS_UNIQUE01 = 6;

	public const int iCRI_VOICE_XSHADOW_V_XS_WIN01 = 3;

	public const int iCRI_VOICE_XSHADOW_V_XS_JUMP01 = 12;

	public const int iCRI_VOICE_XSHADOW_V_XS_SABER01 = 14;

	public const int iCRI_VOICE_XSHADOW_V_XS_SABER03 = 16;

	public const int iCRI_VOICE_XSHADOW_V_XS_SABER05 = 18;

	public const int iCRI_VOICE_XSHADOW_V_XS_START01 = 2;

	public const int iCRI_VOICE_XSHADOW_V_XS_CHARA01 = 40;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_CUENUM = VOICE_XShadow.CRI_VOICE_XSHADOW_CUENUM;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_HURT01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_HURT01;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_ATTACK01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_ATTACK01;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_SKILL01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_SKILL01;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_SKILL02 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_SKILL02;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_PINCH01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_PINCH01;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_PINCH02 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_PINCH02;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_PINCH03 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_PINCH03;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_LOSE01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_LOSE01;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_UNIQUE01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_UNIQUE01;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_WIN01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_WIN01;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_JUMP01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_JUMP01;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_SABER01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_SABER01;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_SABER03 = VOICE_XShadow.CRI_VOICE_XSHADOW_CUENUM;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_SABER05 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_SABER05;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_START01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_START01;

	public const VOICE_XShadow CRI_VOICE_XSHADOW_V_XS_CHARA01 = VOICE_XShadow.CRI_VOICE_XSHADOW_V_XS_CHARA01;
}
