public static class VOICE_ICOi
{
	public const int iCRI_VOICE_ICO_CUENUM = 28;

	public const int iCRI_VOICE_ICO_V_IC_HURT01 = 1;

	public const int iCRI_VOICE_ICO_V_IC_ATTACK01 = 25;

	public const int iCRI_VOICE_ICO_V_IC_SKILL01 = 8;

	public const int iCRI_VOICE_ICO_V_IC_SKILL02 = 9;

	public const int iCRI_VOICE_ICO_V_IC_SKILL04 = 11;

	public const int iCRI_VOICE_ICO_V_IC_PINCH01 = 20;

	public const int iCRI_VOICE_ICO_V_IC_PINCH02 = 21;

	public const int iCRI_VOICE_ICO_V_IC_PINCH03 = 22;

	public const int iCRI_VOICE_ICO_V_IC_LOSE01 = 5;

	public const int iCRI_VOICE_ICO_V_IC_UNIQUE01 = 6;

	public const int iCRI_VOICE_ICO_V_IC_WIN01 = 3;

	public const int iCRI_VOICE_ICO_V_IC_JUMP01 = 12;

	public const int iCRI_VOICE_ICO_V_IC_SABER01 = 14;

	public const int iCRI_VOICE_ICO_V_IC_SABER02 = 15;

	public const int iCRI_VOICE_ICO_V_IC_SABER03 = 16;

	public const int iCRI_VOICE_ICO_V_IC_SABER04 = 17;

	public const int iCRI_VOICE_ICO_V_IC_SABER05 = 18;

	public const int iCRI_VOICE_ICO_V_IC_START01 = 2;

	public const int iCRI_VOICE_ICO_V_IC_CHARA01 = 40;

	public const int iCRI_VOICE_ICO_V_IC_CHARA04 = 44;

	public const int iCRI_VOICE_ICO_V_IC_CHARA05 = 45;

	public const int iCRI_VOICE_ICO_V_IC_CHARA02 = 41;

	public const int iCRI_VOICE_ICO_V_IC_SKILL03 = 10;

	public const int iCRI_VOICE_ICO_V_IC_UNIQUE02 = 7;

	public const int iCRI_VOICE_ICO_V_IC_CHARA03_1 = 42;

	public const int iCRI_VOICE_ICO_V_IC_CHARA03_2 = 43;

	public const int iCRI_VOICE_ICO_V_IC_WIN02 = 4;

	public const int iCRI_VOICE_ICO_V_IC_UNIQUE03 = 26;

	public const VOICE_ICO CRI_VOICE_ICO_CUENUM = VOICE_ICO.CRI_VOICE_ICO_CUENUM;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_HURT01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_HURT01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_ATTACK01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_ATTACK01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_SKILL01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_SKILL01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_SKILL02 = VOICE_ICO.CRI_VOICE_ICO_V_IC_SKILL02;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_SKILL04 = VOICE_ICO.CRI_VOICE_ICO_V_IC_SKILL04;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_PINCH01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_PINCH01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_PINCH02 = VOICE_ICO.CRI_VOICE_ICO_V_IC_PINCH02;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_PINCH03 = VOICE_ICO.CRI_VOICE_ICO_V_IC_PINCH03;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_LOSE01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_LOSE01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_UNIQUE01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_UNIQUE01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_WIN01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_WIN01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_JUMP01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_JUMP01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_SABER01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_SABER01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_SABER02 = VOICE_ICO.CRI_VOICE_ICO_V_IC_SABER02;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_SABER03 = VOICE_ICO.CRI_VOICE_ICO_V_IC_SABER03;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_SABER04 = VOICE_ICO.CRI_VOICE_ICO_V_IC_SABER04;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_SABER05 = VOICE_ICO.CRI_VOICE_ICO_V_IC_SABER05;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_START01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_START01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_CHARA01 = VOICE_ICO.CRI_VOICE_ICO_V_IC_CHARA01;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_CHARA04 = VOICE_ICO.CRI_VOICE_ICO_V_IC_CHARA04;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_CHARA05 = VOICE_ICO.CRI_VOICE_ICO_V_IC_CHARA05;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_CHARA02 = VOICE_ICO.CRI_VOICE_ICO_V_IC_CHARA02;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_SKILL03 = VOICE_ICO.CRI_VOICE_ICO_V_IC_SKILL03;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_UNIQUE02 = VOICE_ICO.CRI_VOICE_ICO_V_IC_UNIQUE02;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_CHARA03_1 = VOICE_ICO.CRI_VOICE_ICO_V_IC_CHARA03_1;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_CHARA03_2 = VOICE_ICO.CRI_VOICE_ICO_V_IC_CHARA03_2;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_WIN02 = VOICE_ICO.CRI_VOICE_ICO_V_IC_WIN02;

	public const VOICE_ICO CRI_VOICE_ICO_V_IC_UNIQUE03 = VOICE_ICO.CRI_VOICE_ICO_V_IC_UNIQUE03;
}
