public static class VOICE_RMEXE2i
{
	public const int iCRI_VOICE_RMEXE2_CUENUM = 15;

	public const int iCRI_VOICE_RMEXE2_V_RE2_HURT01 = 1;

	public const int iCRI_VOICE_RMEXE2_V_RE2_ATTACK01 = 25;

	public const int iCRI_VOICE_RMEXE2_V_RE2_SKILL01 = 8;

	public const int iCRI_VOICE_RMEXE2_V_RE2_SKILL02 = 9;

	public const int iCRI_VOICE_RMEXE2_V_RE2_PINCH01 = 20;

	public const int iCRI_VOICE_RMEXE2_V_RE2_PINCH02 = 21;

	public const int iCRI_VOICE_RMEXE2_V_RE2_PINCH03 = 22;

	public const int iCRI_VOICE_RMEXE2_V_RE2_LOSE01 = 5;

	public const int iCRI_VOICE_RMEXE2_V_RE2_UNIQUE01 = 6;

	public const int iCRI_VOICE_RMEXE2_V_RE2_WIN01 = 3;

	public const int iCRI_VOICE_RMEXE2_V_RE2_JUMP01 = 12;

	public const int iCRI_VOICE_RMEXE2_V_RE2_SABER01 = 14;

	public const int iCRI_VOICE_RMEXE2_V_RE2_SABER03 = 16;

	public const int iCRI_VOICE_RMEXE2_V_RE2_SABER05 = 18;

	public const int iCRI_VOICE_RMEXE2_V_RE2_START01 = 2;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_CUENUM = VOICE_RMEXE2.CRI_VOICE_RMEXE2_CUENUM;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_HURT01 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_HURT01;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_ATTACK01 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_ATTACK01;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_SKILL01 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_SKILL01;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_SKILL02 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_SKILL02;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_PINCH01 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_PINCH01;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_PINCH02 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_PINCH02;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_PINCH03 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_PINCH03;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_LOSE01 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_LOSE01;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_UNIQUE01 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_UNIQUE01;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_WIN01 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_WIN01;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_JUMP01 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_JUMP01;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_SABER01 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_SABER01;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_SABER03 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_SABER03;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_SABER05 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_SABER05;

	public const VOICE_RMEXE2 CRI_VOICE_RMEXE2_V_RE2_START01 = VOICE_RMEXE2.CRI_VOICE_RMEXE2_V_RE2_START01;
}
