public static class VOICE_RMZeroi
{
	public const int iCRI_VOICE_RMZERO_CUENUM = 18;

	public const int iCRI_VOICE_RMZERO_V_ZZ_HURT01 = 1;

	public const int iCRI_VOICE_RMZERO_V_ZZ_ATTACK01 = 25;

	public const int iCRI_VOICE_RMZERO_V_ZZ_SKILL01 = 8;

	public const int iCRI_VOICE_RMZERO_V_ZZ_SKILL02_1 = 9;

	public const int iCRI_VOICE_RMZERO_V_ZZ_SKILL02_2 = 26;

	public const int iCRI_VOICE_RMZERO_V_ZZ_PINCH01 = 20;

	public const int iCRI_VOICE_RMZERO_V_ZZ_PINCH02 = 21;

	public const int iCRI_VOICE_RMZERO_V_ZZ_PINCH03 = 22;

	public const int iCRI_VOICE_RMZERO_V_ZZ_LOSE01 = 5;

	public const int iCRI_VOICE_RMZERO_V_ZZ_UNIQUE01 = 6;

	public const int iCRI_VOICE_RMZERO_V_ZZ_WIN01 = 3;

	public const int iCRI_VOICE_RMZERO_V_ZZ_JUMP01 = 12;

	public const int iCRI_VOICE_RMZERO_V_ZZ_SABER01 = 14;

	public const int iCRI_VOICE_RMZERO_V_ZZ_SABER02 = 15;

	public const int iCRI_VOICE_RMZERO_V_ZZ_SABER03 = 16;

	public const int iCRI_VOICE_RMZERO_V_ZZ_SABER04 = 17;

	public const int iCRI_VOICE_RMZERO_V_ZZ_SABER05 = 18;

	public const int iCRI_VOICE_RMZERO_V_ZZ_START01 = 2;

	public const VOICE_RMZero CRI_VOICE_RMZERO_CUENUM = VOICE_RMZero.CRI_VOICE_RMZERO_CUENUM;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_HURT01 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_HURT01;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_ATTACK01 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_ATTACK01;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_SKILL01 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_SKILL01;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_SKILL02_1 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_SKILL02_1;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_SKILL02_2 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_SKILL02_2;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_PINCH01 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_PINCH01;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_PINCH02 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_PINCH02;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_PINCH03 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_PINCH03;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_LOSE01 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_LOSE01;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_UNIQUE01 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_UNIQUE01;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_WIN01 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_WIN01;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_JUMP01 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_JUMP01;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_SABER01 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_SABER01;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_SABER02 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_SABER02;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_SABER03 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_SABER03;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_SABER04 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_SABER04;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_SABER05 = VOICE_RMZero.CRI_VOICE_RMZERO_CUENUM;

	public const VOICE_RMZero CRI_VOICE_RMZERO_V_ZZ_START01 = VOICE_RMZero.CRI_VOICE_RMZERO_V_ZZ_START01;
}
