public static class VOICE_RICO2i
{
	public const int iCRI_VOICE_RICO2_CUENUM = 21;

	public const int iCRI_VOICE_RICO2_V_RI2_HURT01 = 1;

	public const int iCRI_VOICE_RICO2_V_RI2_ATTACK01 = 25;

	public const int iCRI_VOICE_RICO2_V_RI2_SKILL05 = 26;

	public const int iCRI_VOICE_RICO2_V_RI2_SKILL01 = 8;

	public const int iCRI_VOICE_RICO2_V_RI2_SKILL02 = 9;

	public const int iCRI_VOICE_RICO2_V_RI2_PINCH01 = 20;

	public const int iCRI_VOICE_RICO2_V_RI2_PINCH02 = 21;

	public const int iCRI_VOICE_RICO2_V_RI2_PINCH03 = 22;

	public const int iCRI_VOICE_RICO2_V_RI2_LOSE01 = 5;

	public const int iCRI_VOICE_RICO2_V_RI2_CHARA01_1 = 40;

	public const int iCRI_VOICE_RICO2_V_RI2_CHARA02 = 42;

	public const int iCRI_VOICE_RICO2_V_RI2_CHARA01_2 = 41;

	public const int iCRI_VOICE_RICO2_V_RI2_WIN01 = 3;

	public const int iCRI_VOICE_RICO2_V_RI2_JUMP01 = 12;

	public const int iCRI_VOICE_RICO2_V_RI2_SABER01 = 14;

	public const int iCRI_VOICE_RICO2_V_RI2_SABER03 = 16;

	public const int iCRI_VOICE_RICO2_V_RI2_SABER05 = 18;

	public const int iCRI_VOICE_RICO2_V_RI2_START01 = 2;

	public const int iCRI_VOICE_RICO2_V_RI2_UNIQUE01 = 6;

	public const int iCRI_VOICE_RICO2_V_RI2_SKILL03 = 10;

	public const int iCRI_VOICE_RICO2_V_RI2_SKILL04 = 11;

	public const VOICE_RICO2 CRI_VOICE_RICO2_CUENUM = VOICE_RICO2.CRI_VOICE_RICO2_CUENUM;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_HURT01 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_HURT01;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_ATTACK01 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_ATTACK01;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_SKILL05 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_SKILL05;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_SKILL01 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_SKILL01;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_SKILL02 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_SKILL02;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_PINCH01 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_PINCH01;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_PINCH02 = VOICE_RICO2.CRI_VOICE_RICO2_CUENUM;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_PINCH03 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_PINCH03;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_LOSE01 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_LOSE01;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_CHARA01_1 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_CHARA01_1;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_CHARA02 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_CHARA02;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_CHARA01_2 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_CHARA01_2;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_WIN01 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_WIN01;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_JUMP01 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_JUMP01;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_SABER01 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_SABER01;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_SABER03 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_SABER03;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_SABER05 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_SABER05;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_START01 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_START01;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_UNIQUE01 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_UNIQUE01;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_SKILL03 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_SKILL03;

	public const VOICE_RICO2 CRI_VOICE_RICO2_V_RI2_SKILL04 = VOICE_RICO2.CRI_VOICE_RICO2_V_RI2_SKILL04;
}
