public enum VOICE_ZEROMH
{
	NONE = 0,
	CRI_VOICE_ZEROMH_CUENUM = 16,
	CRI_VOICE_ZEROMH_V_ZM_HURT01 = 1,
	CRI_VOICE_ZEROMH_V_ZM_START01 = 2,
	CRI_VOICE_ZEROMH_V_ZM_WIN01 = 3,
	CRI_VOICE_ZEROMH_V_ZM_LOSE01 = 5,
	CRI_VOICE_ZEROMH_V_ZM_UNIQUE01 = 6,
	CRI_VOICE_ZEROMH_V_ZM_SKILL01 = 8,
	CRI_VOICE_ZEROMH_V_ZM_SKILL02 = 9,
	CRI_VOICE_ZEROMH_V_ZM_JUMP01 = 12,
	CRI_VOICE_ZEROMH_V_ZM_SABER01 = 14,
	CRI_VOICE_ZEROMH_V_ZM_SABER03 = 16,
	CRI_VOICE_ZEROMH_V_ZM_SABER05 = 18,
	CRI_VOICE_ZEROMH_V_ZM_PINCH01 = 20,
	CRI_VOICE_ZEROMH_V_ZM_PINCH02 = 21,
	CRI_VOICE_ZEROMH_V_ZM_PINCH03 = 22,
	CRI_VOICE_ZEROMH_V_ZM_ATTACK01 = 25,
	CRI_VOICE_ZEROMH_V_ZM_CHARA01 = 40
}
