public static class VOICE_XFalconi
{
	public const int iCRI_VOICE_XFALCON_CUENUM = 17;

	public const int iCRI_VOICE_XFALCON_V_XF_HURT01 = 1;

	public const int iCRI_VOICE_XFALCON_V_XF_ATTACK01 = 25;

	public const int iCRI_VOICE_XFALCON_V_XF_SKILL01 = 8;

	public const int iCRI_VOICE_XFALCON_V_XF_PINCH01 = 20;

	public const int iCRI_VOICE_XFALCON_V_XF_PINCH02 = 21;

	public const int iCRI_VOICE_XFALCON_V_XF_PINCH03 = 22;

	public const int iCRI_VOICE_XFALCON_V_XF_LOSE01 = 5;

	public const int iCRI_VOICE_XFALCON_V_XF_UNIQUE01 = 6;

	public const int iCRI_VOICE_XFALCON_V_XF_WIN01 = 3;

	public const int iCRI_VOICE_XFALCON_V_XF_JUMP01 = 12;

	public const int iCRI_VOICE_XFALCON_V_XF_SABER01 = 14;

	public const int iCRI_VOICE_XFALCON_V_XF_SABER02 = 15;

	public const int iCRI_VOICE_XFALCON_V_XF_SABER03 = 16;

	public const int iCRI_VOICE_XFALCON_V_XF_SABER04 = 17;

	public const int iCRI_VOICE_XFALCON_V_XF_SABER05 = 18;

	public const int iCRI_VOICE_XFALCON_V_XF_START01 = 2;

	public const int iCRI_VOICE_XFALCON_V_XF_SKILL02 = 9;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_CUENUM = VOICE_XFalcon.CRI_VOICE_XFALCON_CUENUM;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_HURT01 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_HURT01;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_ATTACK01 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_ATTACK01;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_SKILL01 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_SKILL01;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_PINCH01 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_PINCH01;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_PINCH02 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_PINCH02;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_PINCH03 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_PINCH03;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_LOSE01 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_LOSE01;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_UNIQUE01 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_UNIQUE01;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_WIN01 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_WIN01;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_JUMP01 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_JUMP01;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_SABER01 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_SABER01;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_SABER02 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_SABER02;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_SABER03 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_SABER03;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_SABER04 = VOICE_XFalcon.CRI_VOICE_XFALCON_CUENUM;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_SABER05 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_SABER05;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_START01 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_START01;

	public const VOICE_XFalcon CRI_VOICE_XFALCON_V_XF_SKILL02 = VOICE_XFalcon.CRI_VOICE_XFALCON_V_XF_SKILL02;
}
