public enum VOICE_IRISSUMMER
{
	NONE = 0,
	CRI_VOICE_IRISSUMMER_CUENUM = 16,
	CRI_VOICE_IRISSUMMER_V_IRS_HURT01 = 1,
	CRI_VOICE_IRISSUMMER_V_IRS_ATTACK01 = 25,
	CRI_VOICE_IRISSUMMER_V_IRS_SKILL01 = 8,
	CRI_VOICE_IRISSUMMER_V_IRS_SKILL02 = 9,
	CRI_VOICE_IRISSUMMER_V_IRS_PINCH01 = 20,
	CRI_VOICE_IRISSUMMER_V_IRS_PINCH02 = 21,
	CRI_VOICE_IRISSUMMER_V_IRS_PINCH03 = 22,
	CRI_VOICE_IRISSUMMER_V_IRS_LOSE01 = 5,
	CRI_VOICE_IRISSUMMER_V_IRS_UNIQUE01 = 6,
	CRI_VOICE_IRISSUMMER_V_IRS_WIN01 = 3,
	CRI_VOICE_IRISSUMMER_V_IRS_JUMP01 = 12,
	CRI_VOICE_IRISSUMMER_V_IRS_SABER01 = 14,
	CRI_VOICE_IRISSUMMER_V_IRS_SABER03 = 16,
	CRI_VOICE_IRISSUMMER_V_IRS_SABER05 = 18,
	CRI_VOICE_IRISSUMMER_V_IRS_START01 = 2,
	CRI_VOICE_IRISSUMMER_V_IRS_CHARA01 = 26
}
