public enum VOICE_ERATO
{
	NONE = 0,
	CRI_VOICE_ERATO_CUENUM = 16,
	CRI_VOICE_ERATO_V_ER_HURT01 = 1,
	CRI_VOICE_ERATO_V_ER_ATTACK01 = 25,
	CRI_VOICE_ERATO_V_ER_SKILL01 = 8,
	CRI_VOICE_ERATO_V_ER_SKILL02 = 9,
	CRI_VOICE_ERATO_V_ER_PINCH01 = 20,
	CRI_VOICE_ERATO_V_ER_PINCH02 = 21,
	CRI_VOICE_ERATO_V_ER_PINCH03 = 22,
	CRI_VOICE_ERATO_V_ER_LOSE01 = 5,
	CRI_VOICE_ERATO_V_ER_JUMP01 = 12,
	CRI_VOICE_ERATO_V_ER_UNIQUE01 = 6,
	CRI_VOICE_ERATO_V_ER_WIN01 = 3,
	CRI_VOICE_ERATO_V_ER_SABER01 = 14,
	CRI_VOICE_ERATO_V_ER_SABER03 = 16,
	CRI_VOICE_ERATO_V_ER_SABER05 = 18,
	CRI_VOICE_ERATO_V_ER_START01 = 2,
	CRI_VOICE_ERATO_V_ER_CHARA01 = 40
}
