public enum VOICE_DRAWER
{
	NONE = 0,
	CRI_VOICE_DRAWER_CUENUM = 17,
	CRI_VOICE_DRAWER_V_DR_HURT01 = 1,
	CRI_VOICE_DRAWER_V_DR_ATTACK01 = 25,
	CRI_VOICE_DRAWER_V_DR_SKILL01_1 = 8,
	CRI_VOICE_DRAWER_V_DR_SKILL02 = 10,
	CRI_VOICE_DRAWER_V_DR_SKILL01_2 = 9,
	CRI_VOICE_DRAWER_V_DR_PINCH01 = 20,
	CRI_VOICE_DRAWER_V_DR_PINCH02 = 21,
	CRI_VOICE_DRAWER_V_DR_PINCH03 = 22,
	CRI_VOICE_DRAWER_V_DR_LOSE01 = 5,
	CRI_VOICE_DRAWER_V_DR_UNIQUE01 = 6,
	CRI_VOICE_DRAWER_V_DR_WIN01 = 3,
	CRI_VOICE_DRAWER_V_DR_JUMP01 = 12,
	CRI_VOICE_DRAWER_V_DR_SABER01 = 14,
	CRI_VOICE_DRAWER_V_DR_SABER03 = 16,
	CRI_VOICE_DRAWER_V_DR_SABER05 = 18,
	CRI_VOICE_DRAWER_V_DR_START01 = 2,
	CRI_VOICE_DRAWER_V_DR_CHARA01 = 40
}
