public static class VOICE_FORTEi
{
	public const int iCRI_VOICE_FORTE_CUENUM = 19;

	public const int iCRI_VOICE_FORTE_V_FO_HURT01 = 1;

	public const int iCRI_VOICE_FORTE_V_FO_ATTACK01 = 25;

	public const int iCRI_VOICE_FORTE_V_FO_SKILL01 = 8;

	public const int iCRI_VOICE_FORTE_V_FO_SKILL03 = 10;

	public const int iCRI_VOICE_FORTE_V_FO_SKILL02 = 9;

	public const int iCRI_VOICE_FORTE_V_FO_PINCH01 = 20;

	public const int iCRI_VOICE_FORTE_V_FO_PINCH02 = 21;

	public const int iCRI_VOICE_FORTE_V_FO_PINCH03 = 22;

	public const int iCRI_VOICE_FORTE_V_FO_LOSE01 = 5;

	public const int iCRI_VOICE_FORTE_V_FO_UNIQUE01 = 6;

	public const int iCRI_VOICE_FORTE_V_FO_UNIQUE02 = 7;

	public const int iCRI_VOICE_FORTE_V_FO_WIN01 = 3;

	public const int iCRI_VOICE_FORTE_V_FO_JUMP01 = 12;

	public const int iCRI_VOICE_FORTE_V_FO_SABER01 = 14;

	public const int iCRI_VOICE_FORTE_V_FO_SABER03 = 16;

	public const int iCRI_VOICE_FORTE_V_FO_SABER05 = 18;

	public const int iCRI_VOICE_FORTE_V_FO_START01 = 2;

	public const int iCRI_VOICE_FORTE_V_FO_CHARA01 = 40;

	public const int iCRI_VOICE_FORTE_V_FO_CHARA02 = 41;

	public const VOICE_FORTE CRI_VOICE_FORTE_CUENUM = VOICE_FORTE.CRI_VOICE_FORTE_CUENUM;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_HURT01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_HURT01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_ATTACK01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_ATTACK01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_SKILL01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_SKILL01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_SKILL03 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_SKILL03;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_SKILL02 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_SKILL02;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_PINCH01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_PINCH01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_PINCH02 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_PINCH02;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_PINCH03 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_PINCH03;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_LOSE01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_LOSE01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_UNIQUE01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_UNIQUE01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_UNIQUE02 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_UNIQUE02;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_WIN01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_WIN01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_JUMP01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_JUMP01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_SABER01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_SABER01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_SABER03 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_SABER03;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_SABER05 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_SABER05;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_START01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_START01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_CHARA01 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_CHARA01;

	public const VOICE_FORTE CRI_VOICE_FORTE_V_FO_CHARA02 = VOICE_FORTE.CRI_VOICE_FORTE_V_FO_CHARA02;
}
