public enum VOICE_ZERONM
{
	NONE = 0,
	CRI_VOICE_ZERONM_CUENUM = 15,
	CRI_VOICE_ZERONM_V_ZN_HURT01 = 1,
	CRI_VOICE_ZERONM_V_ZN_ATTACK01 = 25,
	CRI_VOICE_ZERONM_V_ZN_PINCH01 = 20,
	CRI_VOICE_ZERONM_V_ZN_PINCH02 = 21,
	CRI_VOICE_ZERONM_V_ZN_PINCH03 = 22,
	CRI_VOICE_ZERONM_V_ZN_LOSE01 = 5,
	CRI_VOICE_ZERONM_V_ZN_UNIQUE01 = 6,
	CRI_VOICE_ZERONM_V_ZN_WIN01 = 3,
	CRI_VOICE_ZERONM_V_ZN_JUMP01 = 12,
	CRI_VOICE_ZERONM_V_ZN_SABER01 = 14,
	CRI_VOICE_ZERONM_V_ZN_SABER03 = 16,
	CRI_VOICE_ZERONM_V_ZN_SABER05 = 18,
	CRI_VOICE_ZERONM_V_ZN_START01 = 2,
	CRI_VOICE_ZERONM_V_ZN_SKILL01 = 8,
	CRI_VOICE_ZERONM_V_ZN_SKILL02 = 9
}
