public enum VOICE_IRIS
{
	NONE = 0,
	CRI_VOICE_IRIS_CUENUM = 18,
	CRI_VOICE_IRIS_V_IR_HURT01 = 1,
	CRI_VOICE_IRIS_V_IR_ATTACK01 = 25,
	CRI_VOICE_IRIS_V_IR_SKILL01 = 8,
	CRI_VOICE_IRIS_V_IR_SKILL02 = 9,
	CRI_VOICE_IRIS_V_IR_PINCH01 = 20,
	CRI_VOICE_IRIS_V_IR_PINCH02 = 21,
	CRI_VOICE_IRIS_V_IR_PINCH03 = 22,
	CRI_VOICE_IRIS_V_IR_LOSE01 = 5,
	CRI_VOICE_IRIS_V_IR_UNIQUE01 = 6,
	CRI_VOICE_IRIS_V_IR_WIN01 = 3,
	CRI_VOICE_IRIS_V_IR_JUMP01 = 12,
	CRI_VOICE_IRIS_V_IR_SABER01 = 14,
	CRI_VOICE_IRIS_V_IR_SABER03 = 16,
	CRI_VOICE_IRIS_V_IR_SABER05 = 18,
	CRI_VOICE_IRIS_V_IR_START01 = 2,
	CRI_VOICE_IRIS_V_IR_CHARA01 = 40,
	CRI_VOICE_IRIS_V_IR_CHARA02 = 41,
	CRI_VOICE_IRIS_V_IR_CHARA03 = 42
}
