public enum VOICE_MASSIMO
{
	NONE = 0,
	CRI_VOICE_MASSIMO_CUENUM = 15,
	CRI_VOICE_MASSIMO_V_MS_HURT01 = 1,
	CRI_VOICE_MASSIMO_V_MS_ATTACK01 = 25,
	CRI_VOICE_MASSIMO_V_MS_SKILL01 = 8,
	CRI_VOICE_MASSIMO_V_MS_SKILL02 = 9,
	CRI_VOICE_MASSIMO_V_MS_PINCH01 = 20,
	CRI_VOICE_MASSIMO_V_MS_PINCH02 = 21,
	CRI_VOICE_MASSIMO_V_MS_PINCH03 = 22,
	CRI_VOICE_MASSIMO_V_MS_LOSE01 = 5,
	CRI_VOICE_MASSIMO_V_MS_UNIQUE01 = 6,
	CRI_VOICE_MASSIMO_V_MS_WIN01 = 3,
	CRI_VOICE_MASSIMO_V_MS_SABER01 = 14,
	CRI_VOICE_MASSIMO_V_MS_SABER03 = 16,
	CRI_VOICE_MASSIMO_V_MS_SABER05 = 18,
	CRI_VOICE_MASSIMO_V_MS_START01 = 2,
	CRI_VOICE_MASSIMO_V_MS_JUMP01 = 12
}
