public enum VOICE_CINNAMON
{
	NONE = 0,
	CRI_VOICE_CINNAMON_CUENUM = 18,
	CRI_VOICE_CINNAMON_V_CM_HURT01 = 1,
	CRI_VOICE_CINNAMON_V_CM_ATTACK01 = 25,
	CRI_VOICE_CINNAMON_V_CM_SKILL01 = 8,
	CRI_VOICE_CINNAMON_V_CM_SKILL02 = 9,
	CRI_VOICE_CINNAMON_V_CM_PINCH01 = 20,
	CRI_VOICE_CINNAMON_V_CM_PINCH02 = 21,
	CRI_VOICE_CINNAMON_V_CM_PINCH03 = 22,
	CRI_VOICE_CINNAMON_V_CM_LOSE01 = 5,
	CRI_VOICE_CINNAMON_V_CM_UNIQUE01 = 6,
	CRI_VOICE_CINNAMON_V_CM_WIN01 = 3,
	CRI_VOICE_CINNAMON_V_CM_SABER01 = 14,
	CRI_VOICE_CINNAMON_V_CM_SABER02 = 15,
	CRI_VOICE_CINNAMON_V_CM_SABER03 = 16,
	CRI_VOICE_CINNAMON_V_CM_SABER04 = 17,
	CRI_VOICE_CINNAMON_V_CM_SABER05 = 18,
	CRI_VOICE_CINNAMON_V_CM_START01 = 2,
	CRI_VOICE_CINNAMON_V_CM_JUMP01 = 12,
	CRI_VOICE_CINNAMON_V_CM_SKILL03 = 10
}
