public static class VOICE_NANAi
{
	public const int iCRI_VOICE_NANA_CUENUM = 16;

	public const int iCRI_VOICE_NANA_V_NA_HURT01 = 1;

	public const int iCRI_VOICE_NANA_V_NA_ATTACK01 = 25;

	public const int iCRI_VOICE_NANA_V_NA_SKILL01 = 8;

	public const int iCRI_VOICE_NANA_V_NA_SKILL02 = 9;

	public const int iCRI_VOICE_NANA_V_NA_PINCH01 = 20;

	public const int iCRI_VOICE_NANA_V_NA_PINCH02 = 21;

	public const int iCRI_VOICE_NANA_V_NA_PINCH03 = 22;

	public const int iCRI_VOICE_NANA_V_NA_LOSE01 = 5;

	public const int iCRI_VOICE_NANA_V_NA_CHARA01 = 40;

	public const int iCRI_VOICE_NANA_V_NA_WIN01 = 3;

	public const int iCRI_VOICE_NANA_V_NA_JUMP01 = 12;

	public const int iCRI_VOICE_NANA_V_NA_SABER01 = 14;

	public const int iCRI_VOICE_NANA_V_NA_SABER03 = 16;

	public const int iCRI_VOICE_NANA_V_NA_SABER05 = 18;

	public const int iCRI_VOICE_NANA_V_NA_START01 = 2;

	public const int iCRI_VOICE_NANA_V_NA_UNIQUE01 = 6;

	public const VOICE_NANA CRI_VOICE_NANA_CUENUM = VOICE_NANA.CRI_VOICE_NANA_CUENUM;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_HURT01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_HURT01;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_ATTACK01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_ATTACK01;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_SKILL01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_SKILL01;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_SKILL02 = VOICE_NANA.CRI_VOICE_NANA_V_NA_SKILL02;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_PINCH01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_PINCH01;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_PINCH02 = VOICE_NANA.CRI_VOICE_NANA_V_NA_PINCH02;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_PINCH03 = VOICE_NANA.CRI_VOICE_NANA_V_NA_PINCH03;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_LOSE01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_LOSE01;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_CHARA01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_CHARA01;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_WIN01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_WIN01;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_JUMP01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_JUMP01;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_SABER01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_SABER01;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_SABER03 = VOICE_NANA.CRI_VOICE_NANA_CUENUM;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_SABER05 = VOICE_NANA.CRI_VOICE_NANA_V_NA_SABER05;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_START01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_START01;

	public const VOICE_NANA CRI_VOICE_NANA_V_NA_UNIQUE01 = VOICE_NANA.CRI_VOICE_NANA_V_NA_UNIQUE01;
}
