public enum VOICE_XShadow
{
	NONE = 0,
	CRI_VOICE_XSHADOW_CUENUM = 16,
	CRI_VOICE_XSHADOW_V_XS_HURT01 = 1,
	CRI_VOICE_XSHADOW_V_XS_ATTACK01 = 25,
	CRI_VOICE_XSHADOW_V_XS_SKILL01 = 8,
	CRI_VOICE_XSHADOW_V_XS_SKILL02 = 9,
	CRI_VOICE_XSHADOW_V_XS_PINCH01 = 20,
	CRI_VOICE_XSHADOW_V_XS_PINCH02 = 21,
	CRI_VOICE_XSHADOW_V_XS_PINCH03 = 22,
	CRI_VOICE_XSHADOW_V_XS_LOSE01 = 5,
	CRI_VOICE_XSHADOW_V_XS_UNIQUE01 = 6,
	CRI_VOICE_XSHADOW_V_XS_WIN01 = 3,
	CRI_VOICE_XSHADOW_V_XS_JUMP01 = 12,
	CRI_VOICE_XSHADOW_V_XS_SABER01 = 14,
	CRI_VOICE_XSHADOW_V_XS_SABER03 = 16,
	CRI_VOICE_XSHADOW_V_XS_SABER05 = 18,
	CRI_VOICE_XSHADOW_V_XS_START01 = 2,
	CRI_VOICE_XSHADOW_V_XS_CHARA01 = 40
}
