public enum VOICE_RMSS
{
	NONE = 0,
	CRI_VOICE_RMSS_CUENUM = 16,
	CRI_VOICE_RMSS_V_RS_HURT01 = 1,
	CRI_VOICE_RMSS_V_RS_ATTACK01 = 25,
	CRI_VOICE_RMSS_V_RS_SKILL01 = 8,
	CRI_VOICE_RMSS_V_RS_SKILL02 = 9,
	CRI_VOICE_RMSS_V_RS_PINCH01 = 20,
	CRI_VOICE_RMSS_V_RS_PINCH02 = 21,
	CRI_VOICE_RMSS_V_RS_PINCH03 = 22,
	CRI_VOICE_RMSS_V_RS_LOSE01 = 5,
	CRI_VOICE_RMSS_V_RS_UNIQUE01 = 6,
	CRI_VOICE_RMSS_V_RS_WIN01 = 3,
	CRI_VOICE_RMSS_V_RS_JUMP01 = 12,
	CRI_VOICE_RMSS_V_RS_SABER01 = 14,
	CRI_VOICE_RMSS_V_RS_SABER03 = 16,
	CRI_VOICE_RMSS_V_RS_SABER05 = 18,
	CRI_VOICE_RMSS_V_RS_START01 = 2,
	CRI_VOICE_RMSS_V_RS_CHARA01 = 40
}
