public enum VOICE_ANGE
{
	NONE = 0,
	CRI_VOICE_ANGE_CUENUM = 16,
	CRI_VOICE_ANGE_V_AN_HURT01 = 1,
	CRI_VOICE_ANGE_V_AN_START01 = 2,
	CRI_VOICE_ANGE_V_AN_WIN01 = 3,
	CRI_VOICE_ANGE_V_AN_LOSE01 = 5,
	CRI_VOICE_ANGE_V_AN_UNIQUE01 = 6,
	CRI_VOICE_ANGE_V_AN_SKILL01 = 8,
	CRI_VOICE_ANGE_V_AN_SKILL02 = 9,
	CRI_VOICE_ANGE_V_AN_JUMP01 = 12,
	CRI_VOICE_ANGE_V_AN_SABER01 = 14,
	CRI_VOICE_ANGE_V_AN_SABER03 = 16,
	CRI_VOICE_ANGE_V_AN_SABER05 = 18,
	CRI_VOICE_ANGE_V_AN_PINCH01 = 20,
	CRI_VOICE_ANGE_V_AN_PINCH02 = 21,
	CRI_VOICE_ANGE_V_AN_PINCH03 = 22,
	CRI_VOICE_ANGE_V_AN_ATTACK01 = 25,
	CRI_VOICE_ANGE_V_AN_CHARA01 = 40
}
