public enum VOICE_KARNEL
{
	NONE = 0,
	CRI_VOICE_KARNEL_CUENUM = 14,
	CRI_VOICE_KARNEL_V_KN_HURT01 = 1,
	CRI_VOICE_KARNEL_V_KN_ATTACK01 = 25,
	CRI_VOICE_KARNEL_V_KN_PINCH01 = 20,
	CRI_VOICE_KARNEL_V_KN_PINCH02 = 21,
	CRI_VOICE_KARNEL_V_KN_PINCH03 = 22,
	CRI_VOICE_KARNEL_V_KN_LOSE01 = 5,
	CRI_VOICE_KARNEL_V_KN_UNIQUE01 = 6,
	CRI_VOICE_KARNEL_V_KN_WIN01 = 3,
	CRI_VOICE_KARNEL_V_KN_JUMP01 = 12,
	CRI_VOICE_KARNEL_V_KN_SABER01 = 14,
	CRI_VOICE_KARNEL_V_KN_SABER03 = 16,
	CRI_VOICE_KARNEL_V_KN_SABER05 = 18,
	CRI_VOICE_KARNEL_V_KN_START01 = 2,
	CRI_VOICE_KARNEL_V_KN_SKILL01 = 8
}
