public enum VOICE_GATE
{
	NONE = 0,
	CRI_VOICE_GATE_CUENUM = 16,
	CRI_VOICE_GATE_V_GT_HURT01 = 1,
	CRI_VOICE_GATE_V_GT_START01 = 2,
	CRI_VOICE_GATE_V_GT_WIN01 = 3,
	CRI_VOICE_GATE_V_GT_LOSE01 = 5,
	CRI_VOICE_GATE_V_GT_UNIQUE01 = 6,
	CRI_VOICE_GATE_V_GT_SKILL01 = 8,
	CRI_VOICE_GATE_V_GT_SKILL02 = 9,
	CRI_VOICE_GATE_V_GT_JUMP01 = 12,
	CRI_VOICE_GATE_V_GT_SABER01 = 14,
	CRI_VOICE_GATE_V_GT_SABER03 = 16,
	CRI_VOICE_GATE_V_GT_SABER05 = 18,
	CRI_VOICE_GATE_V_GT_PINCH01 = 20,
	CRI_VOICE_GATE_V_GT_PINCH02 = 21,
	CRI_VOICE_GATE_V_GT_PINCH03 = 22,
	CRI_VOICE_GATE_V_GT_ATTACK01 = 25,
	CRI_VOICE_GATE_V_GT_CHARA01 = 40
}
