public static class VOICE_PANDORAi
{
	public const int iCRI_VOICE_PANDORA_CUENUM = 17;

	public const int iCRI_VOICE_PANDORA_V_PD_HURT01 = 1;

	public const int iCRI_VOICE_PANDORA_V_PD_ATTACK01 = 25;

	public const int iCRI_VOICE_PANDORA_V_PD_SKILL01 = 8;

	public const int iCRI_VOICE_PANDORA_V_PD_SKILL02_1 = 9;

	public const int iCRI_VOICE_PANDORA_V_PD_SKILL02_2 = 41;

	public const int iCRI_VOICE_PANDORA_V_PD_PINCH01 = 20;

	public const int iCRI_VOICE_PANDORA_V_PD_PINCH02 = 21;

	public const int iCRI_VOICE_PANDORA_V_PD_PINCH03 = 22;

	public const int iCRI_VOICE_PANDORA_V_PD_LOSE01 = 5;

	public const int iCRI_VOICE_PANDORA_V_PD_UNIQUE01 = 6;

	public const int iCRI_VOICE_PANDORA_V_PD_WIN01 = 3;

	public const int iCRI_VOICE_PANDORA_V_PD_JUMP01 = 12;

	public const int iCRI_VOICE_PANDORA_V_PD_SABER01 = 14;

	public const int iCRI_VOICE_PANDORA_V_PD_SABER03 = 16;

	public const int iCRI_VOICE_PANDORA_V_PD_SABER05 = 18;

	public const int iCRI_VOICE_PANDORA_V_PD_START01 = 2;

	public const int iCRI_VOICE_PANDORA_V_PD_CHARA01 = 40;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_CUENUM = VOICE_PANDORA.CRI_VOICE_PANDORA_CUENUM;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_HURT01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_HURT01;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_ATTACK01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_ATTACK01;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_SKILL01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_SKILL01;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_SKILL02_1 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_SKILL02_1;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_SKILL02_2 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_SKILL02_2;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_PINCH01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_PINCH01;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_PINCH02 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_PINCH02;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_PINCH03 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_PINCH03;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_LOSE01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_LOSE01;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_UNIQUE01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_UNIQUE01;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_WIN01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_WIN01;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_JUMP01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_JUMP01;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_SABER01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_SABER01;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_SABER03 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_SABER03;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_SABER05 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_SABER05;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_START01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_START01;

	public const VOICE_PANDORA CRI_VOICE_PANDORA_V_PD_CHARA01 = VOICE_PANDORA.CRI_VOICE_PANDORA_V_PD_CHARA01;
}
