public static class VOICE_Leviathani
{
	public const int iCRI_VOICE_LEVIATHAN_CUENUM = 16;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_HURT01 = 1;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_ATTACK01 = 25;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_SKILL01_1 = 8;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_SKILL01_2 = 26;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_SKILL02 = 10;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_PINCH01 = 20;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_PINCH02 = 21;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_PINCH03 = 22;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_LOSE01 = 5;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_UNIQUE01 = 6;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_WIN01 = 3;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_JUMP01 = 12;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_SABER01 = 14;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_SABER03 = 16;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_SABER05 = 18;

	public const int iCRI_VOICE_LEVIATHAN_V_LV_START01 = 2;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_CUENUM = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_CUENUM;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_HURT01 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_HURT01;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_ATTACK01 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_ATTACK01;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_SKILL01_1 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_SKILL01_1;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_SKILL01_2 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_SKILL01_2;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_SKILL02 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_SKILL02;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_PINCH01 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_PINCH01;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_PINCH02 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_PINCH02;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_PINCH03 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_PINCH03;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_LOSE01 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_LOSE01;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_UNIQUE01 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_UNIQUE01;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_WIN01 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_WIN01;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_JUMP01 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_JUMP01;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_SABER01 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_SABER01;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_SABER03 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_CUENUM;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_SABER05 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_SABER05;

	public const VOICE_Leviathan CRI_VOICE_LEVIATHAN_V_LV_START01 = VOICE_Leviathan.CRI_VOICE_LEVIATHAN_V_LV_START01;
}
