public enum VOICE_Leviathan
{
	NONE = 0,
	CRI_VOICE_LEVIATHAN_CUENUM = 16,
	CRI_VOICE_LEVIATHAN_V_LV_HURT01 = 1,
	CRI_VOICE_LEVIATHAN_V_LV_ATTACK01 = 25,
	CRI_VOICE_LEVIATHAN_V_LV_SKILL01_1 = 8,
	CRI_VOICE_LEVIATHAN_V_LV_SKILL01_2 = 26,
	CRI_VOICE_LEVIATHAN_V_LV_SKILL02 = 10,
	CRI_VOICE_LEVIATHAN_V_LV_PINCH01 = 20,
	CRI_VOICE_LEVIATHAN_V_LV_PINCH02 = 21,
	CRI_VOICE_LEVIATHAN_V_LV_PINCH03 = 22,
	CRI_VOICE_LEVIATHAN_V_LV_LOSE01 = 5,
	CRI_VOICE_LEVIATHAN_V_LV_UNIQUE01 = 6,
	CRI_VOICE_LEVIATHAN_V_LV_WIN01 = 3,
	CRI_VOICE_LEVIATHAN_V_LV_JUMP01 = 12,
	CRI_VOICE_LEVIATHAN_V_LV_SABER01 = 14,
	CRI_VOICE_LEVIATHAN_V_LV_SABER03 = 16,
	CRI_VOICE_LEVIATHAN_V_LV_SABER05 = 18,
	CRI_VOICE_LEVIATHAN_V_LV_START01 = 2
}
