public enum VOICE_BlackZERO
{
	NONE = 0,
	CRI_VOICE_BLACKZERO_CUENUM = 17,
	CRI_VOICE_BLACKZERO_V_ZU_HURT01 = 1,
	CRI_VOICE_BLACKZERO_V_ZU_ATTACK01 = 25,
	CRI_VOICE_BLACKZERO_V_ZU_SKILL01 = 8,
	CRI_VOICE_BLACKZERO_V_ZU_SKILL02 = 9,
	CRI_VOICE_BLACKZERO_V_ZU_PINCH01 = 20,
	CRI_VOICE_BLACKZERO_V_ZU_PINCH02 = 21,
	CRI_VOICE_BLACKZERO_V_ZU_PINCH03 = 22,
	CRI_VOICE_BLACKZERO_V_ZU_LOSE01 = 5,
	CRI_VOICE_BLACKZERO_V_ZU_UNIQUE01 = 6,
	CRI_VOICE_BLACKZERO_V_ZU_WIN01 = 3,
	CRI_VOICE_BLACKZERO_V_ZU_JUMP01 = 12,
	CRI_VOICE_BLACKZERO_V_ZU_SABER01 = 14,
	CRI_VOICE_BLACKZERO_V_ZU_SABER02 = 15,
	CRI_VOICE_BLACKZERO_V_ZU_SABER03 = 16,
	CRI_VOICE_BLACKZERO_V_ZU_SABER04 = 17,
	CRI_VOICE_BLACKZERO_V_ZU_SABER05 = 18,
	CRI_VOICE_BLACKZERO_V_ZU_START01 = 2
}
