public enum VOICE_RMZero
{
	NONE = 0,
	CRI_VOICE_RMZERO_CUENUM = 18,
	CRI_VOICE_RMZERO_V_ZZ_HURT01 = 1,
	CRI_VOICE_RMZERO_V_ZZ_ATTACK01 = 25,
	CRI_VOICE_RMZERO_V_ZZ_SKILL01 = 8,
	CRI_VOICE_RMZERO_V_ZZ_SKILL02_1 = 9,
	CRI_VOICE_RMZERO_V_ZZ_SKILL02_2 = 26,
	CRI_VOICE_RMZERO_V_ZZ_PINCH01 = 20,
	CRI_VOICE_RMZERO_V_ZZ_PINCH02 = 21,
	CRI_VOICE_RMZERO_V_ZZ_PINCH03 = 22,
	CRI_VOICE_RMZERO_V_ZZ_LOSE01 = 5,
	CRI_VOICE_RMZERO_V_ZZ_UNIQUE01 = 6,
	CRI_VOICE_RMZERO_V_ZZ_WIN01 = 3,
	CRI_VOICE_RMZERO_V_ZZ_JUMP01 = 12,
	CRI_VOICE_RMZERO_V_ZZ_SABER01 = 14,
	CRI_VOICE_RMZERO_V_ZZ_SABER02 = 15,
	CRI_VOICE_RMZERO_V_ZZ_SABER03 = 16,
	CRI_VOICE_RMZERO_V_ZZ_SABER04 = 17,
	CRI_VOICE_RMZERO_V_ZZ_SABER05 = 18,
	CRI_VOICE_RMZERO_V_ZZ_START01 = 2
}
