public static class VOICE_XGaiai
{
	public const int iCRI_VOICE_XGAIA_CUENUM = 18;

	public const int iCRI_VOICE_XGAIA_V_XG_HURT01 = 1;

	public const int iCRI_VOICE_XGAIA_V_XG_ATTACK01 = 25;

	public const int iCRI_VOICE_XGAIA_V_XG_SKILL01 = 8;

	public const int iCRI_VOICE_XGAIA_V_XG_PINCH01 = 20;

	public const int iCRI_VOICE_XGAIA_V_XG_PINCH02 = 21;

	public const int iCRI_VOICE_XGAIA_V_XG_PINCH03 = 22;

	public const int iCRI_VOICE_XGAIA_V_XG_LOSE01 = 5;

	public const int iCRI_VOICE_XGAIA_V_XG_UNIQUE01 = 6;

	public const int iCRI_VOICE_XGAIA_V_XG_WIN01 = 3;

	public const int iCRI_VOICE_XGAIA_V_XG_JUMP01 = 12;

	public const int iCRI_VOICE_XGAIA_V_XG_SABER01 = 14;

	public const int iCRI_VOICE_XGAIA_V_XG_SABER02 = 15;

	public const int iCRI_VOICE_XGAIA_V_XG_SABER03 = 16;

	public const int iCRI_VOICE_XGAIA_V_XG_SABER04 = 17;

	public const int iCRI_VOICE_XGAIA_V_XG_SABER05 = 18;

	public const int iCRI_VOICE_XGAIA_V_XG_START01 = 2;

	public const int iCRI_VOICE_XGAIA_V_XG_SKILL02 = 9;

	public const int iCRI_VOICE_XGAIA_V_XG_CHARA01 = 40;

	public const VOICE_XGaia CRI_VOICE_XGAIA_CUENUM = VOICE_XGaia.CRI_VOICE_XGAIA_CUENUM;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_HURT01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_HURT01;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_ATTACK01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_ATTACK01;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_SKILL01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_SKILL01;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_PINCH01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_PINCH01;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_PINCH02 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_PINCH02;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_PINCH03 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_PINCH03;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_LOSE01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_LOSE01;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_UNIQUE01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_UNIQUE01;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_WIN01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_WIN01;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_JUMP01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_JUMP01;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_SABER01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_SABER01;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_SABER02 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_SABER02;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_SABER03 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_SABER03;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_SABER04 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_SABER04;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_SABER05 = VOICE_XGaia.CRI_VOICE_XGAIA_CUENUM;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_START01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_START01;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_SKILL02 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_SKILL02;

	public const VOICE_XGaia CRI_VOICE_XGAIA_V_XG_CHARA01 = VOICE_XGaia.CRI_VOICE_XGAIA_V_XG_CHARA01;
}
