public static class VOICE_KOBUNi
{
	public const int iCRI_VOICE_KOBUN_CUENUM = 18;

	public const int iCRI_VOICE_KOBUN_V_KB_HURT01 = 1;

	public const int iCRI_VOICE_KOBUN_V_KB_ATTACK01 = 25;

	public const int iCRI_VOICE_KOBUN_V_KB_SKILL01 = 8;

	public const int iCRI_VOICE_KOBUN_V_KB_PINCH01 = 20;

	public const int iCRI_VOICE_KOBUN_V_KB_PINCH02 = 21;

	public const int iCRI_VOICE_KOBUN_V_KB_PINCH03 = 22;

	public const int iCRI_VOICE_KOBUN_V_KB_LOSE01 = 5;

	public const int iCRI_VOICE_KOBUN_V_KB_UNIQUE01 = 6;

	public const int iCRI_VOICE_KOBUN_V_KB_WIN01 = 3;

	public const int iCRI_VOICE_KOBUN_V_KB_JUMP01 = 12;

	public const int iCRI_VOICE_KOBUN_V_KB_SABER01 = 14;

	public const int iCRI_VOICE_KOBUN_V_KB_SABER03 = 16;

	public const int iCRI_VOICE_KOBUN_V_KB_SABER05 = 18;

	public const int iCRI_VOICE_KOBUN_V_KB_START01 = 2;

	public const int iCRI_VOICE_KOBUN_V_KB_SKILL04 = 11;

	public const int iCRI_VOICE_KOBUN_V_KB_SKILL02 = 9;

	public const int iCRI_VOICE_KOBUN_V_KB_SKILL03 = 10;

	public const int iCRI_VOICE_KOBUN_V_KB_CHARA01 = 40;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_CUENUM = VOICE_KOBUN.CRI_VOICE_KOBUN_CUENUM;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_HURT01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_HURT01;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_ATTACK01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_ATTACK01;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_SKILL01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_SKILL01;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_PINCH01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_PINCH01;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_PINCH02 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_PINCH02;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_PINCH03 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_PINCH03;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_LOSE01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_LOSE01;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_UNIQUE01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_UNIQUE01;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_WIN01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_WIN01;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_JUMP01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_JUMP01;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_SABER01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_SABER01;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_SABER03 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_SABER03;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_SABER05 = VOICE_KOBUN.CRI_VOICE_KOBUN_CUENUM;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_START01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_START01;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_SKILL04 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_SKILL04;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_SKILL02 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_SKILL02;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_SKILL03 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_SKILL03;

	public const VOICE_KOBUN CRI_VOICE_KOBUN_V_KB_CHARA01 = VOICE_KOBUN.CRI_VOICE_KOBUN_V_KB_CHARA01;
}
