public static class VOICE_RMEXEi
{
	public const int iCRI_VOICE_RMEXE_CUENUM = 28;

	public const int iCRI_VOICE_RMEXE_V_RE_HURT01 = 1;

	public const int iCRI_VOICE_RMEXE_V_RE_ATTACK01 = 25;

	public const int iCRI_VOICE_RMEXE_V_RE_SKILL01 = 8;

	public const int iCRI_VOICE_RMEXE_V_RE_SKILL02 = 9;

	public const int iCRI_VOICE_RMEXE_V_RE_PINCH01 = 20;

	public const int iCRI_VOICE_RMEXE_V_RE_PINCH02 = 21;

	public const int iCRI_VOICE_RMEXE_V_RE_PINCH03 = 22;

	public const int iCRI_VOICE_RMEXE_V_RE_LOSE01 = 5;

	public const int iCRI_VOICE_RMEXE_V_RE_UNIQUE01 = 6;

	public const int iCRI_VOICE_RMEXE_V_RE_WIN01 = 3;

	public const int iCRI_VOICE_RMEXE_V_RE_JUMP01 = 12;

	public const int iCRI_VOICE_RMEXE_V_RE_SABER01 = 14;

	public const int iCRI_VOICE_RMEXE_V_RE_SABER02 = 15;

	public const int iCRI_VOICE_RMEXE_V_RE_SABER03 = 16;

	public const int iCRI_VOICE_RMEXE_V_RE_SABER04 = 17;

	public const int iCRI_VOICE_RMEXE_V_RE_SABER05 = 18;

	public const int iCRI_VOICE_RMEXE_V_RE_START01 = 2;

	public const int iCRI_VOICE_RMEXE_V_RE_SKILL02_1 = 26;

	public const int iCRI_VOICE_RMEXE_V_RE_SKILL02_4 = 29;

	public const int iCRI_VOICE_RMEXE_V_RE_SKILL02_3 = 28;

	public const int iCRI_VOICE_RMEXE_V_RE_SKILL02_2 = 27;

	public const int iCRI_VOICE_RMEXE_V_RE_SKILL03_1 = 30;

	public const int iCRI_VOICE_RMEXE_V_RE_SKILL03_2 = 31;

	public const int iCRI_VOICE_RMEXE_V_RE_SKILL04 = 32;

	public const int iCRI_VOICE_RMEXE_V_RE_CHARA01 = 40;

	public const int iCRI_VOICE_RMEXE_V_RE_CHARA02 = 41;

	public const int iCRI_VOICE_RMEXE_V_RE_CHARA03 = 42;

	public const int iCRI_VOICE_RMEXE_V_RE_UNIQUE02 = 7;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_CUENUM = VOICE_RMEXE.CRI_VOICE_RMEXE_CUENUM;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_HURT01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_HURT01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_ATTACK01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_ATTACK01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SKILL01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SKILL01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SKILL02 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SKILL02;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_PINCH01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_PINCH01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_PINCH02 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_PINCH02;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_PINCH03 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_PINCH03;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_LOSE01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_LOSE01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_UNIQUE01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_UNIQUE01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_WIN01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_WIN01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_JUMP01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_JUMP01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SABER01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SABER01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SABER02 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SABER02;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SABER03 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SABER03;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SABER04 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SABER04;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SABER05 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SABER05;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_START01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_START01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SKILL02_1 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SKILL02_1;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SKILL02_4 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SKILL02_4;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SKILL02_3 = VOICE_RMEXE.CRI_VOICE_RMEXE_CUENUM;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SKILL02_2 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SKILL02_2;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SKILL03_1 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SKILL03_1;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SKILL03_2 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SKILL03_2;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_SKILL04 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_SKILL04;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_CHARA01 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_CHARA01;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_CHARA02 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_CHARA02;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_CHARA03 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_CHARA03;

	public const VOICE_RMEXE CRI_VOICE_RMEXE_V_RE_UNIQUE02 = VOICE_RMEXE.CRI_VOICE_RMEXE_V_RE_UNIQUE02;
}
