public static class VOICE_VIA2i
{
	public const int iCRI_VOICE_VIA2_CUENUM = 16;

	public const int iCRI_VOICE_VIA2_V_VI2_HURT01 = 1;

	public const int iCRI_VOICE_VIA2_V_VI2_START01 = 2;

	public const int iCRI_VOICE_VIA2_V_VI2_WIN01 = 3;

	public const int iCRI_VOICE_VIA2_V_VI2_LOSE01 = 5;

	public const int iCRI_VOICE_VIA2_V_VI2_UNIQUE01 = 6;

	public const int iCRI_VOICE_VIA2_V_VI2_SKILL01 = 8;

	public const int iCRI_VOICE_VIA2_V_VI2_SKILL02 = 9;

	public const int iCRI_VOICE_VIA2_V_VI2_JUMP01 = 12;

	public const int iCRI_VOICE_VIA2_V_VI2_SABER01 = 14;

	public const int iCRI_VOICE_VIA2_V_VI2_SABER03 = 16;

	public const int iCRI_VOICE_VIA2_V_VI2_SABER05 = 18;

	public const int iCRI_VOICE_VIA2_V_VI2_PINCH01 = 20;

	public const int iCRI_VOICE_VIA2_V_VI2_PINCH02 = 21;

	public const int iCRI_VOICE_VIA2_V_VI2_PINCH03 = 22;

	public const int iCRI_VOICE_VIA2_V_VI2_ATTACK01 = 25;

	public const int iCRI_VOICE_VIA2_V_VI2_CHARA01 = 40;

	public const VOICE_VIA2 CRI_VOICE_VIA2_CUENUM = VOICE_VIA2.CRI_VOICE_VIA2_CUENUM;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_HURT01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_HURT01;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_START01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_START01;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_WIN01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_WIN01;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_LOSE01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_LOSE01;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_UNIQUE01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_UNIQUE01;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_SKILL01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_SKILL01;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_SKILL02 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_SKILL02;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_JUMP01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_JUMP01;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_SABER01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_SABER01;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_SABER03 = VOICE_VIA2.CRI_VOICE_VIA2_CUENUM;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_SABER05 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_SABER05;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_PINCH01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_PINCH01;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_PINCH02 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_PINCH02;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_PINCH03 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_PINCH03;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_ATTACK01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_ATTACK01;

	public const VOICE_VIA2 CRI_VOICE_VIA2_V_VI2_CHARA01 = VOICE_VIA2.CRI_VOICE_VIA2_V_VI2_CHARA01;
}
