public enum VOICE_ROCKVOL
{
	NONE = 0,
	CRI_VOICE_ROCKVOL_CUENUM = 19,
	CRI_VOICE_ROCKVOL_V_RV_HURT01 = 1,
	CRI_VOICE_ROCKVOL_V_RV_ATTACK01 = 25,
	CRI_VOICE_ROCKVOL_V_RV_SKILL01 = 8,
	CRI_VOICE_ROCKVOL_V_RV_SKILL02 = 9,
	CRI_VOICE_ROCKVOL_V_RV_PINCH01 = 20,
	CRI_VOICE_ROCKVOL_V_RV_PINCH02 = 21,
	CRI_VOICE_ROCKVOL_V_RV_PINCH03 = 22,
	CRI_VOICE_ROCKVOL_V_RV_LOSE01 = 5,
	CRI_VOICE_ROCKVOL_V_RV_UNIQUE01 = 6,
	CRI_VOICE_ROCKVOL_V_RV_WIN01 = 3,
	CRI_VOICE_ROCKVOL_V_RV_JUMP01 = 12,
	CRI_VOICE_ROCKVOL_V_RV_SABER01 = 14,
	CRI_VOICE_ROCKVOL_V_RV_SABER03 = 16,
	CRI_VOICE_ROCKVOL_V_RV_SABER05 = 18,
	CRI_VOICE_ROCKVOL_V_RV_START01 = 2,
	CRI_VOICE_ROCKVOL_V_RV_CHARA01 = 40,
	CRI_VOICE_ROCKVOL_V_RV_SKILL03 = 10,
	CRI_VOICE_ROCKVOL_V_RV_SKILL04 = 11,
	CRI_VOICE_ROCKVOL_V_RV_CHARA02 = 41
}
