public static class VOICE_XArki
{
	public const int iCRI_VOICE_XARK_CUENUM = 16;

	public const int iCRI_VOICE_XARK_V_XA_HURT01 = 1;

	public const int iCRI_VOICE_XARK_V_XA_ATTACK01 = 25;

	public const int iCRI_VOICE_XARK_V_XA_SKILL01 = 8;

	public const int iCRI_VOICE_XARK_V_XA_PINCH01 = 20;

	public const int iCRI_VOICE_XARK_V_XA_PINCH02 = 21;

	public const int iCRI_VOICE_XARK_V_XA_PINCH03 = 22;

	public const int iCRI_VOICE_XARK_V_XA_LOSE01 = 5;

	public const int iCRI_VOICE_XARK_V_XA_UNIQUE01 = 6;

	public const int iCRI_VOICE_XARK_V_XA_WIN01 = 3;

	public const int iCRI_VOICE_XARK_V_XA_JUMP01 = 12;

	public const int iCRI_VOICE_XARK_V_XA_SABER01 = 14;

	public const int iCRI_VOICE_XARK_V_XA_SABER03 = 16;

	public const int iCRI_VOICE_XARK_V_XA_SABER05 = 18;

	public const int iCRI_VOICE_XARK_V_XA_START01 = 2;

	public const int iCRI_VOICE_XARK_V_XA_SKILL02 = 9;

	public const int iCRI_VOICE_XARK_V_XA_CHARA01 = 40;

	public const VOICE_XArk CRI_VOICE_XARK_CUENUM = VOICE_XArk.CRI_VOICE_XARK_CUENUM;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_HURT01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_HURT01;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_ATTACK01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_ATTACK01;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_SKILL01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_SKILL01;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_PINCH01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_PINCH01;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_PINCH02 = VOICE_XArk.CRI_VOICE_XARK_V_XA_PINCH02;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_PINCH03 = VOICE_XArk.CRI_VOICE_XARK_V_XA_PINCH03;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_LOSE01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_LOSE01;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_UNIQUE01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_UNIQUE01;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_WIN01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_WIN01;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_JUMP01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_JUMP01;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_SABER01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_SABER01;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_SABER03 = VOICE_XArk.CRI_VOICE_XARK_CUENUM;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_SABER05 = VOICE_XArk.CRI_VOICE_XARK_V_XA_SABER05;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_START01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_START01;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_SKILL02 = VOICE_XArk.CRI_VOICE_XARK_V_XA_SKILL02;

	public const VOICE_XArk CRI_VOICE_XARK_V_XA_CHARA01 = VOICE_XArk.CRI_VOICE_XARK_V_XA_CHARA01;
}
