public static class VOICE_BLUESi
{
	public const int iCRI_VOICE_BLUES_CUENUM = 19;

	public const int iCRI_VOICE_BLUES_V_BL_HURT01 = 1;

	public const int iCRI_VOICE_BLUES_V_BL_ATTACK01 = 25;

	public const int iCRI_VOICE_BLUES_V_BL_SKILL01_1 = 7;

	public const int iCRI_VOICE_BLUES_V_BL_SKILL02_2 = 10;

	public const int iCRI_VOICE_BLUES_V_BL_PINCH01 = 20;

	public const int iCRI_VOICE_BLUES_V_BL_PINCH02 = 21;

	public const int iCRI_VOICE_BLUES_V_BL_PINCH03 = 22;

	public const int iCRI_VOICE_BLUES_V_BL_LOSE01 = 5;

	public const int iCRI_VOICE_BLUES_V_BL_UNIQUE01 = 6;

	public const int iCRI_VOICE_BLUES_V_BL_WIN01 = 3;

	public const int iCRI_VOICE_BLUES_V_BL_JUMP01 = 12;

	public const int iCRI_VOICE_BLUES_V_BL_SABER01 = 14;

	public const int iCRI_VOICE_BLUES_V_BL_SABER02 = 15;

	public const int iCRI_VOICE_BLUES_V_BL_SABER03 = 16;

	public const int iCRI_VOICE_BLUES_V_BL_SABER04 = 17;

	public const int iCRI_VOICE_BLUES_V_BL_SABER05 = 18;

	public const int iCRI_VOICE_BLUES_V_BL_START01 = 2;

	public const int iCRI_VOICE_BLUES_V_BL_SKILL01_2 = 8;

	public const int iCRI_VOICE_BLUES_V_BL_SKILL02_1 = 9;

	public const VOICE_BLUES CRI_VOICE_BLUES_CUENUM = VOICE_BLUES.CRI_VOICE_BLUES_CUENUM;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_HURT01 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_HURT01;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_ATTACK01 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_ATTACK01;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_SKILL01_1 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_SKILL01_1;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_SKILL02_2 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_SKILL02_2;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_PINCH01 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_PINCH01;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_PINCH02 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_PINCH02;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_PINCH03 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_PINCH03;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_LOSE01 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_LOSE01;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_UNIQUE01 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_UNIQUE01;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_WIN01 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_WIN01;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_JUMP01 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_JUMP01;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_SABER01 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_SABER01;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_SABER02 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_SABER02;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_SABER03 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_SABER03;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_SABER04 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_SABER04;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_SABER05 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_SABER05;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_START01 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_START01;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_SKILL01_2 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_SKILL01_2;

	public const VOICE_BLUES CRI_VOICE_BLUES_V_BL_SKILL02_1 = VOICE_BLUES.CRI_VOICE_BLUES_V_BL_SKILL02_1;
}
