public enum VOICE_CHUNLI
{
	NONE = 0,
	CRI_VOICE_CHUNLI_CUENUM = 18,
	CRI_VOICE_CHUNLI_V_CH_HURT01 = 1,
	CRI_VOICE_CHUNLI_V_CH_ATTACK01 = 25,
	CRI_VOICE_CHUNLI_V_CH_SKILL01 = 8,
	CRI_VOICE_CHUNLI_V_CH_PINCH01 = 20,
	CRI_VOICE_CHUNLI_V_CH_PINCH02 = 21,
	CRI_VOICE_CHUNLI_V_CH_PINCH03 = 22,
	CRI_VOICE_CHUNLI_V_CH_LOSE01 = 5,
	CRI_VOICE_CHUNLI_V_CH_UNIQUE01 = 6,
	CRI_VOICE_CHUNLI_V_CH_WIN01 = 3,
	CRI_VOICE_CHUNLI_V_CH_JUMP01 = 12,
	CRI_VOICE_CHUNLI_V_CH_SABER01 = 14,
	CRI_VOICE_CHUNLI_V_CH_SABER02 = 15,
	CRI_VOICE_CHUNLI_V_CH_SABER03 = 16,
	CRI_VOICE_CHUNLI_V_CH_SABER04 = 17,
	CRI_VOICE_CHUNLI_V_CH_SABER05 = 18,
	CRI_VOICE_CHUNLI_V_CH_START01 = 2,
	CRI_VOICE_CHUNLI_V_CH_SKILL02 = 9,
	CRI_VOICE_CHUNLI_V_CH_CHARA01 = 40
}
