public enum VOICE_FORTE
{
	NONE = 0,
	CRI_VOICE_FORTE_CUENUM = 19,
	CRI_VOICE_FORTE_V_FO_HURT01 = 1,
	CRI_VOICE_FORTE_V_FO_ATTACK01 = 25,
	CRI_VOICE_FORTE_V_FO_SKILL01 = 8,
	CRI_VOICE_FORTE_V_FO_SKILL03 = 10,
	CRI_VOICE_FORTE_V_FO_SKILL02 = 9,
	CRI_VOICE_FORTE_V_FO_PINCH01 = 20,
	CRI_VOICE_FORTE_V_FO_PINCH02 = 21,
	CRI_VOICE_FORTE_V_FO_PINCH03 = 22,
	CRI_VOICE_FORTE_V_FO_LOSE01 = 5,
	CRI_VOICE_FORTE_V_FO_UNIQUE01 = 6,
	CRI_VOICE_FORTE_V_FO_UNIQUE02 = 7,
	CRI_VOICE_FORTE_V_FO_WIN01 = 3,
	CRI_VOICE_FORTE_V_FO_JUMP01 = 12,
	CRI_VOICE_FORTE_V_FO_SABER01 = 14,
	CRI_VOICE_FORTE_V_FO_SABER03 = 16,
	CRI_VOICE_FORTE_V_FO_SABER05 = 18,
	CRI_VOICE_FORTE_V_FO_START01 = 2,
	CRI_VOICE_FORTE_V_FO_CHARA01 = 40,
	CRI_VOICE_FORTE_V_FO_CHARA02 = 41
}
