public enum VOICE_AbsoZERO
{
	NONE = 0,
	CRI_VOICE_ABSOZERO_CUENUM = 17,
	CRI_VOICE_ABSOZERO_V_ZB_HURT01 = 1,
	CRI_VOICE_ABSOZERO_V_ZB_ATTACK01 = 25,
	CRI_VOICE_ABSOZERO_V_ZB_SKILL01 = 8,
	CRI_VOICE_ABSOZERO_V_ZB_SKILL02 = 9,
	CRI_VOICE_ABSOZERO_V_ZB_PINCH01 = 20,
	CRI_VOICE_ABSOZERO_V_ZB_PINCH02 = 21,
	CRI_VOICE_ABSOZERO_V_ZB_PINCH03 = 22,
	CRI_VOICE_ABSOZERO_V_ZB_LOSE01 = 5,
	CRI_VOICE_ABSOZERO_V_ZB_UNIQUE01 = 6,
	CRI_VOICE_ABSOZERO_V_ZB_WIN01 = 3,
	CRI_VOICE_ABSOZERO_V_ZB_JUMP01 = 12,
	CRI_VOICE_ABSOZERO_V_ZB_SABER01 = 14,
	CRI_VOICE_ABSOZERO_V_ZB_SABER02 = 15,
	CRI_VOICE_ABSOZERO_V_ZB_SABER03 = 16,
	CRI_VOICE_ABSOZERO_V_ZB_SABER04 = 17,
	CRI_VOICE_ABSOZERO_V_ZB_SABER05 = 18,
	CRI_VOICE_ABSOZERO_V_ZB_START01 = 2
}
