public enum VOICE_XDMC
{
	NONE = 0,
	CRI_VOICE_XDMC_CUENUM = 16,
	CRI_VOICE_XDMC_V_XC_HURT01 = 1,
	CRI_VOICE_XDMC_V_XC_ATTACK01 = 25,
	CRI_VOICE_XDMC_V_XC_SKILL01 = 8,
	CRI_VOICE_XDMC_V_XC_SKILL02 = 9,
	CRI_VOICE_XDMC_V_XC_PINCH01 = 20,
	CRI_VOICE_XDMC_V_XC_PINCH02 = 21,
	CRI_VOICE_XDMC_V_XC_PINCH03 = 22,
	CRI_VOICE_XDMC_V_XC_LOSE01 = 5,
	CRI_VOICE_XDMC_V_XC_UNIQUE01 = 6,
	CRI_VOICE_XDMC_V_XC_WIN01 = 3,
	CRI_VOICE_XDMC_V_XC_JUMP01 = 12,
	CRI_VOICE_XDMC_V_XC_SABER01 = 14,
	CRI_VOICE_XDMC_V_XC_SABER03 = 16,
	CRI_VOICE_XDMC_V_XC_SABER05 = 18,
	CRI_VOICE_XDMC_V_XC_START01 = 2,
	CRI_VOICE_XDMC_V_XC_CHARA01 = 40
}
