public static class VOICE_ROLLi
{
	public const int iCRI_VOICE_ROLL_CUENUM = 28;

	public const int iCRI_VOICE_ROLL_V_RL_HURT01 = 1;

	public const int iCRI_VOICE_ROLL_V_RL_ATTACK01 = 25;

	public const int iCRI_VOICE_ROLL_V_RL_SKILL01_1 = 7;

	public const int iCRI_VOICE_ROLL_V_RL_SKILL01_2 = 8;

	public const int iCRI_VOICE_ROLL_V_RL_SKILL02 = 9;

	public const int iCRI_VOICE_ROLL_V_RL_PINCH01 = 20;

	public const int iCRI_VOICE_ROLL_V_RL_PINCH02 = 21;

	public const int iCRI_VOICE_ROLL_V_RL_PINCH03 = 22;

	public const int iCRI_VOICE_ROLL_V_RL_LOSE01 = 5;

	public const int iCRI_VOICE_ROLL_V_RL_UNIQUE01 = 6;

	public const int iCRI_VOICE_ROLL_V_RL_WIN01 = 3;

	public const int iCRI_VOICE_ROLL_V_RL_JUMP01 = 12;

	public const int iCRI_VOICE_ROLL_V_RL_SABER01 = 14;

	public const int iCRI_VOICE_ROLL_V_RL_SABER02 = 15;

	public const int iCRI_VOICE_ROLL_V_RL_SABER03 = 16;

	public const int iCRI_VOICE_ROLL_V_RL_SABER04 = 17;

	public const int iCRI_VOICE_ROLL_V_RL_SABER05 = 18;

	public const int iCRI_VOICE_ROLL_V_RL_START01 = 2;

	public const int iCRI_VOICE_ROLL_V_RL_SKILL03 = 10;

	public const int iCRI_VOICE_ROLL_V_RL_SKILL04 = 11;

	public const int iCRI_VOICE_ROLL_V_RL_CHARA01 = 26;

	public const int iCRI_VOICE_ROLL_V_RL_CHARA02 = 27;

	public const int iCRI_VOICE_ROLL_V_RL_CHARA03 = 28;

	public const int iCRI_VOICE_ROLL_V_RL_CHARA04 = 29;

	public const int iCRI_VOICE_ROLL_V_RL_CHARA05 = 40;

	public const int iCRI_VOICE_ROLL_V_RL_CHARA06 = 41;

	public const int iCRI_VOICE_ROLL_V_RL_UNIQUE02 = 39;

	public const int iCRI_VOICE_ROLL_V_RL_SKILL05 = 38;

	public const VOICE_ROLL CRI_VOICE_ROLL_CUENUM = VOICE_ROLL.CRI_VOICE_ROLL_CUENUM;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_HURT01 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_HURT01;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_ATTACK01 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_ATTACK01;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SKILL01_1 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SKILL01_1;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SKILL01_2 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SKILL01_2;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SKILL02 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SKILL02;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_PINCH01 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_PINCH01;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_PINCH02 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_PINCH02;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_PINCH03 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_PINCH03;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_LOSE01 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_LOSE01;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_UNIQUE01 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_UNIQUE01;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_WIN01 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_WIN01;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_JUMP01 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_JUMP01;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SABER01 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SABER01;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SABER02 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SABER02;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SABER03 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SABER03;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SABER04 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SABER04;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SABER05 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SABER05;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_START01 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_START01;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SKILL03 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SKILL03;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SKILL04 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SKILL04;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_CHARA01 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_CHARA01;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_CHARA02 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_CHARA02;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_CHARA03 = VOICE_ROLL.CRI_VOICE_ROLL_CUENUM;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_CHARA04 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_CHARA04;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_CHARA05 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_CHARA05;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_CHARA06 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_CHARA06;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_UNIQUE02 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_UNIQUE02;

	public const VOICE_ROLL CRI_VOICE_ROLL_V_RL_SKILL05 = VOICE_ROLL.CRI_VOICE_ROLL_V_RL_SKILL05;
}
