public enum VOICE_UltimateX
{
	NONE = 0,
	CRI_VOICE_ULTIMATEX_CUENUM = 17,
	CRI_VOICE_ULTIMATEX_V_XU_HURT01 = 1,
	CRI_VOICE_ULTIMATEX_V_XU_ATTACK01 = 25,
	CRI_VOICE_ULTIMATEX_V_XU_SKILL02 = 9,
	CRI_VOICE_ULTIMATEX_V_XU_PINCH01 = 20,
	CRI_VOICE_ULTIMATEX_V_XU_PINCH02 = 21,
	CRI_VOICE_ULTIMATEX_V_XU_PINCH03 = 22,
	CRI_VOICE_ULTIMATEX_V_XU_LOSE01 = 5,
	CRI_VOICE_ULTIMATEX_V_XU_UNIQUE01 = 6,
	CRI_VOICE_ULTIMATEX_V_XU_WIN01 = 3,
	CRI_VOICE_ULTIMATEX_V_XU_JUMP01 = 12,
	CRI_VOICE_ULTIMATEX_V_XU_SABER01 = 14,
	CRI_VOICE_ULTIMATEX_V_XU_SABER02 = 15,
	CRI_VOICE_ULTIMATEX_V_XU_SABER03 = 16,
	CRI_VOICE_ULTIMATEX_V_XU_SABER04 = 17,
	CRI_VOICE_ULTIMATEX_V_XU_SABER05 = 18,
	CRI_VOICE_ULTIMATEX_V_XU_START01 = 2,
	CRI_VOICE_ULTIMATEX_V_XU_SKILL01 = 8
}
