public static class VOICE_BlackZEROi
{
	public const int iCRI_VOICE_BLACKZERO_CUENUM = 17;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_HURT01 = 1;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_ATTACK01 = 25;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_SKILL01 = 8;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_SKILL02 = 9;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_PINCH01 = 20;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_PINCH02 = 21;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_PINCH03 = 22;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_LOSE01 = 5;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_UNIQUE01 = 6;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_WIN01 = 3;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_JUMP01 = 12;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_SABER01 = 14;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_SABER02 = 15;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_SABER03 = 16;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_SABER04 = 17;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_SABER05 = 18;

	public const int iCRI_VOICE_BLACKZERO_V_ZU_START01 = 2;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_CUENUM = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_CUENUM;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_HURT01 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_HURT01;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_ATTACK01 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_ATTACK01;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_SKILL01 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_SKILL01;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_SKILL02 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_SKILL02;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_PINCH01 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_PINCH01;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_PINCH02 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_PINCH02;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_PINCH03 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_PINCH03;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_LOSE01 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_LOSE01;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_UNIQUE01 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_UNIQUE01;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_WIN01 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_WIN01;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_JUMP01 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_JUMP01;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_SABER01 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_SABER01;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_SABER02 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_SABER02;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_SABER03 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_SABER03;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_SABER04 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_CUENUM;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_SABER05 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_SABER05;

	public const VOICE_BlackZERO CRI_VOICE_BLACKZERO_V_ZU_START01 = VOICE_BlackZERO.CRI_VOICE_BLACKZERO_V_ZU_START01;
}
