public static class VOICE_ZEROi
{
	public const int iCRI_VOICE_ZERO_CUENUM = 24;

	public const int iCRI_VOICE_ZERO_V_Z_HURT01 = 1;

	public const int iCRI_VOICE_ZERO_V_Z_ATTACK01 = 25;

	public const int iCRI_VOICE_ZERO_V_Z_SKILL01 = 8;

	public const int iCRI_VOICE_ZERO_V_Z_SKILL02 = 9;

	public const int iCRI_VOICE_ZERO_V_Z_SKILL03 = 10;

	public const int iCRI_VOICE_ZERO_V_Z_PINCH01 = 20;

	public const int iCRI_VOICE_ZERO_V_Z_PINCH02 = 21;

	public const int iCRI_VOICE_ZERO_V_Z_PINCH03 = 22;

	public const int iCRI_VOICE_ZERO_V_Z_LOSE01 = 5;

	public const int iCRI_VOICE_ZERO_V_Z_UNIQUE01 = 6;

	public const int iCRI_VOICE_ZERO_V_Z_UNIQUE02 = 7;

	public const int iCRI_VOICE_ZERO_V_Z_UNIQUE03 = 26;

	public const int iCRI_VOICE_ZERO_V_Z_WIN01 = 3;

	public const int iCRI_VOICE_ZERO_V_Z_WIN02 = 4;

	public const int iCRI_VOICE_ZERO_V_Z_JUMP01 = 12;

	public const int iCRI_VOICE_ZERO_V_Z_SABER01 = 14;

	public const int iCRI_VOICE_ZERO_V_Z_SABER02 = 15;

	public const int iCRI_VOICE_ZERO_V_Z_SABER03 = 16;

	public const int iCRI_VOICE_ZERO_V_Z_SABER04 = 17;

	public const int iCRI_VOICE_ZERO_V_Z_SABER05 = 18;

	public const int iCRI_VOICE_ZERO_V_Z_START01 = 2;

	public const int iCRI_VOICE_ZERO_V_Z_CHARA02 = 41;

	public const int iCRI_VOICE_ZERO_V_Z_CHARA03 = 42;

	public const int iCRI_VOICE_ZERO_V_Z_CHARA01 = 40;

	public const VOICE_ZERO CRI_VOICE_ZERO_CUENUM = VOICE_ZERO.CRI_VOICE_ZERO_CUENUM;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_HURT01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_HURT01;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_ATTACK01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_ATTACK01;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_SKILL01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_SKILL01;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_SKILL02 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_SKILL02;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_SKILL03 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_SKILL03;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_PINCH01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_PINCH01;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_PINCH02 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_PINCH02;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_PINCH03 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_PINCH03;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_LOSE01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_LOSE01;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_UNIQUE01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_UNIQUE01;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_UNIQUE02 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_UNIQUE02;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_UNIQUE03 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_UNIQUE03;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_WIN01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_WIN01;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_WIN02 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_WIN02;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_JUMP01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_JUMP01;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_SABER01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_SABER01;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_SABER02 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_SABER02;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_SABER03 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_SABER03;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_SABER04 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_SABER04;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_SABER05 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_SABER05;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_START01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_START01;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_CHARA02 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_CHARA02;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_CHARA03 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_CHARA03;

	public const VOICE_ZERO CRI_VOICE_ZERO_V_Z_CHARA01 = VOICE_ZERO.CRI_VOICE_ZERO_V_Z_CHARA01;
}
