public static class VOICE_X1stArmori
{
	public const int iCRI_VOICE_X1STARMOR_CUENUM = 18;

	public const int iCRI_VOICE_X1STARMOR_V_X1_HURT01 = 1;

	public const int iCRI_VOICE_X1STARMOR_V_X1_ATTACK01 = 25;

	public const int iCRI_VOICE_X1STARMOR_V_X1_SKILL01 = 8;

	public const int iCRI_VOICE_X1STARMOR_V_X1_SKILL02 = 9;

	public const int iCRI_VOICE_X1STARMOR_V_X1_PINCH01 = 20;

	public const int iCRI_VOICE_X1STARMOR_V_X1_PINCH02 = 21;

	public const int iCRI_VOICE_X1STARMOR_V_X1_PINCH03 = 22;

	public const int iCRI_VOICE_X1STARMOR_V_X1_LOSE01 = 5;

	public const int iCRI_VOICE_X1STARMOR_V_X1_UNIQUE01 = 6;

	public const int iCRI_VOICE_X1STARMOR_V_X1_WIN01 = 3;

	public const int iCRI_VOICE_X1STARMOR_V_X1_JUMP01 = 12;

	public const int iCRI_VOICE_X1STARMOR_V_X1_SABER01 = 14;

	public const int iCRI_VOICE_X1STARMOR_V_X1_SABER02 = 15;

	public const int iCRI_VOICE_X1STARMOR_V_X1_SABER03 = 16;

	public const int iCRI_VOICE_X1STARMOR_V_X1_SABER04 = 17;

	public const int iCRI_VOICE_X1STARMOR_V_X1_SABER05 = 18;

	public const int iCRI_VOICE_X1STARMOR_V_X1_START01 = 2;

	public const int iCRI_VOICE_X1STARMOR_V_X1_UNIQUE02 = 7;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_CUENUM = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_CUENUM;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_HURT01 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_HURT01;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_ATTACK01 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_ATTACK01;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_SKILL01 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_SKILL01;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_SKILL02 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_SKILL02;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_PINCH01 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_PINCH01;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_PINCH02 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_PINCH02;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_PINCH03 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_PINCH03;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_LOSE01 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_LOSE01;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_UNIQUE01 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_UNIQUE01;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_WIN01 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_WIN01;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_JUMP01 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_JUMP01;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_SABER01 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_SABER01;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_SABER02 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_SABER02;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_SABER03 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_SABER03;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_SABER04 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_SABER04;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_SABER05 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_CUENUM;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_START01 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_START01;

	public const VOICE_X1stArmor CRI_VOICE_X1STARMOR_V_X1_UNIQUE02 = VOICE_X1stArmor.CRI_VOICE_X1STARMOR_V_X1_UNIQUE02;
}
