public enum VOICE_ZERODMC
{
	NONE = 0,
	CRI_VOICE_ZERODMC_CUENUM = 16,
	CRI_VOICE_ZERODMC_V_ZC_HURT01 = 1,
	CRI_VOICE_ZERODMC_V_ZC_ATTACK01 = 25,
	CRI_VOICE_ZERODMC_V_ZC_SKILL01 = 8,
	CRI_VOICE_ZERODMC_V_ZC_SKILL02 = 9,
	CRI_VOICE_ZERODMC_V_ZC_PINCH01 = 20,
	CRI_VOICE_ZERODMC_V_ZC_PINCH02 = 21,
	CRI_VOICE_ZERODMC_V_ZC_PINCH03 = 22,
	CRI_VOICE_ZERODMC_V_ZC_LOSE01 = 5,
	CRI_VOICE_ZERODMC_V_ZC_UNIQUE01 = 6,
	CRI_VOICE_ZERODMC_V_ZC_WIN01 = 3,
	CRI_VOICE_ZERODMC_V_ZC_JUMP01 = 12,
	CRI_VOICE_ZERODMC_V_ZC_SABER01 = 14,
	CRI_VOICE_ZERODMC_V_ZC_SABER03 = 16,
	CRI_VOICE_ZERODMC_V_ZC_SABER05 = 18,
	CRI_VOICE_ZERODMC_V_ZC_START01 = 2,
	CRI_VOICE_ZERODMC_V_ZC_CHARA01 = 40
}
