public enum VOICE_HARPYIA
{
	NONE = 0,
	CRI_VOICE_HARPYIA_CUENUM = 14,
	CRI_VOICE_HARPYIA_V_HA_HURT01 = 1,
	CRI_VOICE_HARPYIA_V_HA_ATTACK01 = 25,
	CRI_VOICE_HARPYIA_V_HA_PINCH01 = 20,
	CRI_VOICE_HARPYIA_V_HA_PINCH02 = 21,
	CRI_VOICE_HARPYIA_V_HA_PINCH03 = 22,
	CRI_VOICE_HARPYIA_V_HA_LOSE01 = 5,
	CRI_VOICE_HARPYIA_V_HA_UNIQUE01 = 6,
	CRI_VOICE_HARPYIA_V_HA_WIN01 = 3,
	CRI_VOICE_HARPYIA_V_HA_JUMP01 = 12,
	CRI_VOICE_HARPYIA_V_HA_SABER01 = 14,
	CRI_VOICE_HARPYIA_V_HA_SABER03 = 16,
	CRI_VOICE_HARPYIA_V_HA_SABER05 = 18,
	CRI_VOICE_HARPYIA_V_HA_START01 = 2,
	CRI_VOICE_HARPYIA_V_HA_SKILL01 = 8
}
