public static class VOICE_UltimateXi
{
	public const int iCRI_VOICE_ULTIMATEX_CUENUM = 17;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_HURT01 = 1;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_ATTACK01 = 25;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_SKILL02 = 9;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_PINCH01 = 20;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_PINCH02 = 21;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_PINCH03 = 22;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_LOSE01 = 5;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_UNIQUE01 = 6;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_WIN01 = 3;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_JUMP01 = 12;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_SABER01 = 14;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_SABER02 = 15;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_SABER03 = 16;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_SABER04 = 17;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_SABER05 = 18;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_START01 = 2;

	public const int iCRI_VOICE_ULTIMATEX_V_XU_SKILL01 = 8;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_CUENUM = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_CUENUM;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_HURT01 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_HURT01;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_ATTACK01 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_ATTACK01;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_SKILL02 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_SKILL02;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_PINCH01 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_PINCH01;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_PINCH02 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_PINCH02;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_PINCH03 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_PINCH03;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_LOSE01 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_LOSE01;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_UNIQUE01 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_UNIQUE01;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_WIN01 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_WIN01;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_JUMP01 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_JUMP01;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_SABER01 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_SABER01;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_SABER02 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_SABER02;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_SABER03 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_SABER03;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_SABER04 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_CUENUM;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_SABER05 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_SABER05;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_START01 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_START01;

	public const VOICE_UltimateX CRI_VOICE_ULTIMATEX_V_XU_SKILL01 = VOICE_UltimateX.CRI_VOICE_ULTIMATEX_V_XU_SKILL01;
}
