public enum VOICE_NANA
{
	NONE = 0,
	CRI_VOICE_NANA_CUENUM = 16,
	CRI_VOICE_NANA_V_NA_HURT01 = 1,
	CRI_VOICE_NANA_V_NA_ATTACK01 = 25,
	CRI_VOICE_NANA_V_NA_SKILL01 = 8,
	CRI_VOICE_NANA_V_NA_SKILL02 = 9,
	CRI_VOICE_NANA_V_NA_PINCH01 = 20,
	CRI_VOICE_NANA_V_NA_PINCH02 = 21,
	CRI_VOICE_NANA_V_NA_PINCH03 = 22,
	CRI_VOICE_NANA_V_NA_LOSE01 = 5,
	CRI_VOICE_NANA_V_NA_CHARA01 = 40,
	CRI_VOICE_NANA_V_NA_WIN01 = 3,
	CRI_VOICE_NANA_V_NA_JUMP01 = 12,
	CRI_VOICE_NANA_V_NA_SABER01 = 14,
	CRI_VOICE_NANA_V_NA_SABER03 = 16,
	CRI_VOICE_NANA_V_NA_SABER05 = 18,
	CRI_VOICE_NANA_V_NA_START01 = 2,
	CRI_VOICE_NANA_V_NA_UNIQUE01 = 6
}
