public static class VOICE_KARNELi
{
	public const int iCRI_VOICE_KARNEL_CUENUM = 14;

	public const int iCRI_VOICE_KARNEL_V_KN_HURT01 = 1;

	public const int iCRI_VOICE_KARNEL_V_KN_ATTACK01 = 25;

	public const int iCRI_VOICE_KARNEL_V_KN_PINCH01 = 20;

	public const int iCRI_VOICE_KARNEL_V_KN_PINCH02 = 21;

	public const int iCRI_VOICE_KARNEL_V_KN_PINCH03 = 22;

	public const int iCRI_VOICE_KARNEL_V_KN_LOSE01 = 5;

	public const int iCRI_VOICE_KARNEL_V_KN_UNIQUE01 = 6;

	public const int iCRI_VOICE_KARNEL_V_KN_WIN01 = 3;

	public const int iCRI_VOICE_KARNEL_V_KN_JUMP01 = 12;

	public const int iCRI_VOICE_KARNEL_V_KN_SABER01 = 14;

	public const int iCRI_VOICE_KARNEL_V_KN_SABER03 = 16;

	public const int iCRI_VOICE_KARNEL_V_KN_SABER05 = 18;

	public const int iCRI_VOICE_KARNEL_V_KN_START01 = 2;

	public const int iCRI_VOICE_KARNEL_V_KN_SKILL01 = 8;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_CUENUM = VOICE_KARNEL.CRI_VOICE_KARNEL_CUENUM;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_HURT01 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_HURT01;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_ATTACK01 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_ATTACK01;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_PINCH01 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_PINCH01;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_PINCH02 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_PINCH02;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_PINCH03 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_PINCH03;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_LOSE01 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_LOSE01;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_UNIQUE01 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_UNIQUE01;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_WIN01 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_WIN01;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_JUMP01 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_JUMP01;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_SABER01 = VOICE_KARNEL.CRI_VOICE_KARNEL_CUENUM;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_SABER03 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_SABER03;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_SABER05 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_SABER05;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_START01 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_START01;

	public const VOICE_KARNEL CRI_VOICE_KARNEL_V_KN_SKILL01 = VOICE_KARNEL.CRI_VOICE_KARNEL_V_KN_SKILL01;
}
