public enum VOICE_PALETTE
{
	NONE = 0,
	CRI_VOICE_PALETTE_CUENUM = 19,
	CRI_VOICE_PALETTE_V_PL_HURT01 = 1,
	CRI_VOICE_PALETTE_V_PL_ATTACK01 = 25,
	CRI_VOICE_PALETTE_V_PL_SKILL01 = 8,
	CRI_VOICE_PALETTE_V_PL_SKILL02 = 9,
	CRI_VOICE_PALETTE_V_PL_PINCH01 = 20,
	CRI_VOICE_PALETTE_V_PL_PINCH02 = 21,
	CRI_VOICE_PALETTE_V_PL_PINCH03 = 22,
	CRI_VOICE_PALETTE_V_PL_LOSE01 = 5,
	CRI_VOICE_PALETTE_V_PL_UNIQUE01 = 6,
	CRI_VOICE_PALETTE_V_PL_WIN01 = 3,
	CRI_VOICE_PALETTE_V_PL_SABER01 = 14,
	CRI_VOICE_PALETTE_V_PL_SABER02 = 15,
	CRI_VOICE_PALETTE_V_PL_JUMP01 = 12,
	CRI_VOICE_PALETTE_V_PL_SABER03 = 16,
	CRI_VOICE_PALETTE_V_PL_SABER04 = 17,
	CRI_VOICE_PALETTE_V_PL_SABER05 = 18,
	CRI_VOICE_PALETTE_V_PL_START01 = 2,
	CRI_VOICE_PALETTE_V_PL_SKILL03 = 10,
	CRI_VOICE_PALETTE_V_PL_CHARA01 = 40
}
