public enum VOICE_XArk
{
	NONE = 0,
	CRI_VOICE_XARK_CUENUM = 16,
	CRI_VOICE_XARK_V_XA_HURT01 = 1,
	CRI_VOICE_XARK_V_XA_ATTACK01 = 25,
	CRI_VOICE_XARK_V_XA_SKILL01 = 8,
	CRI_VOICE_XARK_V_XA_PINCH01 = 20,
	CRI_VOICE_XARK_V_XA_PINCH02 = 21,
	CRI_VOICE_XARK_V_XA_PINCH03 = 22,
	CRI_VOICE_XARK_V_XA_LOSE01 = 5,
	CRI_VOICE_XARK_V_XA_UNIQUE01 = 6,
	CRI_VOICE_XARK_V_XA_WIN01 = 3,
	CRI_VOICE_XARK_V_XA_JUMP01 = 12,
	CRI_VOICE_XARK_V_XA_SABER01 = 14,
	CRI_VOICE_XARK_V_XA_SABER03 = 16,
	CRI_VOICE_XARK_V_XA_SABER05 = 18,
	CRI_VOICE_XARK_V_XA_START01 = 2,
	CRI_VOICE_XARK_V_XA_SKILL02 = 9,
	CRI_VOICE_XARK_V_XA_CHARA01 = 40
}
