public static class VOICE_MARINOi
{
	public const int iCRI_VOICE_MARINO_CUENUM = 21;

	public const int iCRI_VOICE_MARINO_V_MR_HURT01 = 1;

	public const int iCRI_VOICE_MARINO_V_MR_ATTACK01 = 25;

	public const int iCRI_VOICE_MARINO_V_MR_SKILL01 = 8;

	public const int iCRI_VOICE_MARINO_V_MR_SKILL02 = 9;

	public const int iCRI_VOICE_MARINO_V_MR_PINCH01 = 20;

	public const int iCRI_VOICE_MARINO_V_MR_PINCH02 = 21;

	public const int iCRI_VOICE_MARINO_V_MR_PINCH03 = 22;

	public const int iCRI_VOICE_MARINO_V_MR_LOSE01 = 5;

	public const int iCRI_VOICE_MARINO_V_MR_UNIQUE01 = 6;

	public const int iCRI_VOICE_MARINO_V_MR_WIN01 = 3;

	public const int iCRI_VOICE_MARINO_V_MR_SABER01 = 14;

	public const int iCRI_VOICE_MARINO_V_MR_SABER02 = 15;

	public const int iCRI_VOICE_MARINO_V_MR_SABER03 = 16;

	public const int iCRI_VOICE_MARINO_V_MR_SABER04 = 17;

	public const int iCRI_VOICE_MARINO_V_MR_SABER05 = 18;

	public const int iCRI_VOICE_MARINO_V_MR_START01 = 2;

	public const int iCRI_VOICE_MARINO_V_MR_JUMP01 = 12;

	public const int iCRI_VOICE_MARINO_V_MR_SKILL03 = 26;

	public const int iCRI_VOICE_MARINO_V_MR_SKILL04_1 = 27;

	public const int iCRI_VOICE_MARINO_V_MR_SKILL04_2 = 28;

	public const int iCRI_VOICE_MARINO_V_MR_CHARA01 = 29;

	public const VOICE_MARINO CRI_VOICE_MARINO_CUENUM = VOICE_MARINO.CRI_VOICE_MARINO_CUENUM;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_HURT01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_HURT01;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_ATTACK01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_ATTACK01;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_SKILL01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_SKILL01;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_SKILL02 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_SKILL02;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_PINCH01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_PINCH01;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_PINCH02 = VOICE_MARINO.CRI_VOICE_MARINO_CUENUM;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_PINCH03 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_PINCH03;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_LOSE01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_LOSE01;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_UNIQUE01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_UNIQUE01;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_WIN01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_WIN01;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_SABER01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_SABER01;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_SABER02 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_SABER02;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_SABER03 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_SABER03;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_SABER04 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_SABER04;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_SABER05 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_SABER05;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_START01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_START01;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_JUMP01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_JUMP01;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_SKILL03 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_SKILL03;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_SKILL04_1 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_SKILL04_1;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_SKILL04_2 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_SKILL04_2;

	public const VOICE_MARINO CRI_VOICE_MARINO_V_MR_CHARA01 = VOICE_MARINO.CRI_VOICE_MARINO_V_MR_CHARA01;
}
