public enum VOICE_XGaia
{
	NONE = 0,
	CRI_VOICE_XGAIA_CUENUM = 18,
	CRI_VOICE_XGAIA_V_XG_HURT01 = 1,
	CRI_VOICE_XGAIA_V_XG_ATTACK01 = 25,
	CRI_VOICE_XGAIA_V_XG_SKILL01 = 8,
	CRI_VOICE_XGAIA_V_XG_PINCH01 = 20,
	CRI_VOICE_XGAIA_V_XG_PINCH02 = 21,
	CRI_VOICE_XGAIA_V_XG_PINCH03 = 22,
	CRI_VOICE_XGAIA_V_XG_LOSE01 = 5,
	CRI_VOICE_XGAIA_V_XG_UNIQUE01 = 6,
	CRI_VOICE_XGAIA_V_XG_WIN01 = 3,
	CRI_VOICE_XGAIA_V_XG_JUMP01 = 12,
	CRI_VOICE_XGAIA_V_XG_SABER01 = 14,
	CRI_VOICE_XGAIA_V_XG_SABER02 = 15,
	CRI_VOICE_XGAIA_V_XG_SABER03 = 16,
	CRI_VOICE_XGAIA_V_XG_SABER04 = 17,
	CRI_VOICE_XGAIA_V_XG_SABER05 = 18,
	CRI_VOICE_XGAIA_V_XG_START01 = 2,
	CRI_VOICE_XGAIA_V_XG_SKILL02 = 9,
	CRI_VOICE_XGAIA_V_XG_CHARA01 = 40
}
