public enum VOICE_GOUKI
{
	NONE = 0,
	CRI_VOICE_GOUKI_CUENUM = 18,
	CRI_VOICE_GOUKI_V_GO_HURT01 = 1,
	CRI_VOICE_GOUKI_V_GO_ATTACK01 = 25,
	CRI_VOICE_GOUKI_V_GO_SKILL01 = 8,
	CRI_VOICE_GOUKI_V_GO_SKILL02 = 9,
	CRI_VOICE_GOUKI_V_GO_PINCH01 = 20,
	CRI_VOICE_GOUKI_V_GO_PINCH02 = 21,
	CRI_VOICE_GOUKI_V_GO_PINCH03 = 22,
	CRI_VOICE_GOUKI_V_GO_LOSE01 = 5,
	CRI_VOICE_GOUKI_V_GO_UNIQUE01 = 6,
	CRI_VOICE_GOUKI_V_GO_WIN01 = 3,
	CRI_VOICE_GOUKI_V_GO_JUMP01 = 12,
	CRI_VOICE_GOUKI_V_GO_SABER01 = 14,
	CRI_VOICE_GOUKI_V_GO_SABER02 = 15,
	CRI_VOICE_GOUKI_V_GO_SABER03 = 16,
	CRI_VOICE_GOUKI_V_GO_SABER04 = 17,
	CRI_VOICE_GOUKI_V_GO_SABER05 = 18,
	CRI_VOICE_GOUKI_V_GO_START01 = 2,
	CRI_VOICE_GOUKI_V_GO_CHARA01 = 40
}
