public enum VOICE_KOBUN
{
	NONE = 0,
	CRI_VOICE_KOBUN_CUENUM = 18,
	CRI_VOICE_KOBUN_V_KB_HURT01 = 1,
	CRI_VOICE_KOBUN_V_KB_ATTACK01 = 25,
	CRI_VOICE_KOBUN_V_KB_SKILL01 = 8,
	CRI_VOICE_KOBUN_V_KB_PINCH01 = 20,
	CRI_VOICE_KOBUN_V_KB_PINCH02 = 21,
	CRI_VOICE_KOBUN_V_KB_PINCH03 = 22,
	CRI_VOICE_KOBUN_V_KB_LOSE01 = 5,
	CRI_VOICE_KOBUN_V_KB_UNIQUE01 = 6,
	CRI_VOICE_KOBUN_V_KB_WIN01 = 3,
	CRI_VOICE_KOBUN_V_KB_JUMP01 = 12,
	CRI_VOICE_KOBUN_V_KB_SABER01 = 14,
	CRI_VOICE_KOBUN_V_KB_SABER03 = 16,
	CRI_VOICE_KOBUN_V_KB_SABER05 = 18,
	CRI_VOICE_KOBUN_V_KB_START01 = 2,
	CRI_VOICE_KOBUN_V_KB_SKILL04 = 11,
	CRI_VOICE_KOBUN_V_KB_SKILL02 = 9,
	CRI_VOICE_KOBUN_V_KB_SKILL03 = 10,
	CRI_VOICE_KOBUN_V_KB_CHARA01 = 40
}
