public enum VOICE_PANDORA
{
	NONE = 0,
	CRI_VOICE_PANDORA_CUENUM = 17,
	CRI_VOICE_PANDORA_V_PD_HURT01 = 1,
	CRI_VOICE_PANDORA_V_PD_ATTACK01 = 25,
	CRI_VOICE_PANDORA_V_PD_SKILL01 = 8,
	CRI_VOICE_PANDORA_V_PD_SKILL02_1 = 9,
	CRI_VOICE_PANDORA_V_PD_SKILL02_2 = 41,
	CRI_VOICE_PANDORA_V_PD_PINCH01 = 20,
	CRI_VOICE_PANDORA_V_PD_PINCH02 = 21,
	CRI_VOICE_PANDORA_V_PD_PINCH03 = 22,
	CRI_VOICE_PANDORA_V_PD_LOSE01 = 5,
	CRI_VOICE_PANDORA_V_PD_UNIQUE01 = 6,
	CRI_VOICE_PANDORA_V_PD_WIN01 = 3,
	CRI_VOICE_PANDORA_V_PD_JUMP01 = 12,
	CRI_VOICE_PANDORA_V_PD_SABER01 = 14,
	CRI_VOICE_PANDORA_V_PD_SABER03 = 16,
	CRI_VOICE_PANDORA_V_PD_SABER05 = 18,
	CRI_VOICE_PANDORA_V_PD_START01 = 2,
	CRI_VOICE_PANDORA_V_PD_CHARA01 = 40
}
