public enum VOICE_FORTEEXE
{
	NONE = 0,
	CRI_VOICE_FORTEEXE_CUENUM = 16,
	CRI_VOICE_FORTEEXE_V_FE_HURT01 = 1,
	CRI_VOICE_FORTEEXE_V_FE_ATTACK01 = 25,
	CRI_VOICE_FORTEEXE_V_FE_SKILL01 = 8,
	CRI_VOICE_FORTEEXE_V_FE_SKILL02 = 9,
	CRI_VOICE_FORTEEXE_V_FE_PINCH01 = 20,
	CRI_VOICE_FORTEEXE_V_FE_PINCH02 = 21,
	CRI_VOICE_FORTEEXE_V_FE_PINCH03 = 22,
	CRI_VOICE_FORTEEXE_V_FE_LOSE01 = 5,
	CRI_VOICE_FORTEEXE_V_FE_UNIQUE01 = 6,
	CRI_VOICE_FORTEEXE_V_FE_WIN01 = 3,
	CRI_VOICE_FORTEEXE_V_FE_JUMP01 = 12,
	CRI_VOICE_FORTEEXE_V_FE_SABER01 = 14,
	CRI_VOICE_FORTEEXE_V_FE_SABER03 = 16,
	CRI_VOICE_FORTEEXE_V_FE_SABER05 = 18,
	CRI_VOICE_FORTEEXE_V_FE_START01 = 2,
	CRI_VOICE_FORTEEXE_V_FE_CHARA01 = 40
}
