public static class VOICE_SIGMAi
{
	public const int iCRI_VOICE_SIGMA_CUENUM = 20;

	public const int iCRI_VOICE_SIGMA_V_SG_HURT01 = 1;

	public const int iCRI_VOICE_SIGMA_V_SG_ATTACK01 = 25;

	public const int iCRI_VOICE_SIGMA_V_SG_SKILL02 = 9;

	public const int iCRI_VOICE_SIGMA_V_SG_SKILL01 = 8;

	public const int iCRI_VOICE_SIGMA_V_SG_PINCH01 = 20;

	public const int iCRI_VOICE_SIGMA_V_SG_PINCH02 = 21;

	public const int iCRI_VOICE_SIGMA_V_SG_PINCH03 = 22;

	public const int iCRI_VOICE_SIGMA_V_SG_LOSE01 = 5;

	public const int iCRI_VOICE_SIGMA_V_SG_UNIQUE01 = 6;

	public const int iCRI_VOICE_SIGMA_V_SG_WIN01 = 3;

	public const int iCRI_VOICE_SIGMA_V_SG_JUMP01 = 12;

	public const int iCRI_VOICE_SIGMA_V_SG_SABER01 = 14;

	public const int iCRI_VOICE_SIGMA_V_SG_SABER03 = 16;

	public const int iCRI_VOICE_SIGMA_V_SG_SABER05 = 18;

	public const int iCRI_VOICE_SIGMA_V_SG_START01 = 2;

	public const int iCRI_VOICE_SIGMA_V_SG_UNIQUE02 = 7;

	public const int iCRI_VOICE_SIGMA_V_SG_CHARA01 = 40;

	public const int iCRI_VOICE_SIGMA_V_SG_CHARA03 = 41;

	public const int iCRI_VOICE_SIGMA_V_SG_UNIQUE03 = 26;

	public const int iCRI_VOICE_SIGMA_V_SG_SKILL03 = 10;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_CUENUM = VOICE_SIGMA.CRI_VOICE_SIGMA_CUENUM;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_HURT01 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_HURT01;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_ATTACK01 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_ATTACK01;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_SKILL02 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_SKILL02;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_SKILL01 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_SKILL01;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_PINCH01 = VOICE_SIGMA.CRI_VOICE_SIGMA_CUENUM;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_PINCH02 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_PINCH02;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_PINCH03 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_PINCH03;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_LOSE01 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_LOSE01;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_UNIQUE01 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_UNIQUE01;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_WIN01 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_WIN01;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_JUMP01 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_JUMP01;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_SABER01 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_SABER01;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_SABER03 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_SABER03;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_SABER05 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_SABER05;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_START01 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_START01;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_UNIQUE02 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_UNIQUE02;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_CHARA01 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_CHARA01;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_CHARA03 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_CHARA03;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_UNIQUE03 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_UNIQUE03;

	public const VOICE_SIGMA CRI_VOICE_SIGMA_V_SG_SKILL03 = VOICE_SIGMA.CRI_VOICE_SIGMA_V_SG_SKILL03;
}
