public static class VOICE_RYUi
{
	public const int iCRI_VOICE_RYU_CUENUM = 19;

	public const int iCRI_VOICE_RYU_V_RY_HURT01 = 1;

	public const int iCRI_VOICE_RYU_V_RY_ATTACK01 = 25;

	public const int iCRI_VOICE_RYU_V_RY_SKILL01_1 = 8;

	public const int iCRI_VOICE_RYU_V_RY_PINCH01 = 20;

	public const int iCRI_VOICE_RYU_V_RY_PINCH02 = 21;

	public const int iCRI_VOICE_RYU_V_RY_PINCH03 = 22;

	public const int iCRI_VOICE_RYU_V_RY_LOSE01 = 5;

	public const int iCRI_VOICE_RYU_V_RY_UNIQUE01 = 6;

	public const int iCRI_VOICE_RYU_V_RY_WIN01 = 3;

	public const int iCRI_VOICE_RYU_V_RY_JUMP01 = 12;

	public const int iCRI_VOICE_RYU_V_RY_SABER01 = 14;

	public const int iCRI_VOICE_RYU_V_RY_SABER02 = 15;

	public const int iCRI_VOICE_RYU_V_RY_SABER03 = 16;

	public const int iCRI_VOICE_RYU_V_RY_SABER04 = 17;

	public const int iCRI_VOICE_RYU_V_RY_SABER05 = 18;

	public const int iCRI_VOICE_RYU_V_RY_START01 = 2;

	public const int iCRI_VOICE_RYU_V_RY_SKILL01_2 = 9;

	public const int iCRI_VOICE_RYU_V_RY_SKILL02 = 10;

	public const int iCRI_VOICE_RYU_V_RY_CHARA01 = 40;

	public const VOICE_RYU CRI_VOICE_RYU_CUENUM = VOICE_RYU.CRI_VOICE_RYU_CUENUM;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_HURT01 = VOICE_RYU.CRI_VOICE_RYU_V_RY_HURT01;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_ATTACK01 = VOICE_RYU.CRI_VOICE_RYU_V_RY_ATTACK01;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_SKILL01_1 = VOICE_RYU.CRI_VOICE_RYU_V_RY_SKILL01_1;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_PINCH01 = VOICE_RYU.CRI_VOICE_RYU_V_RY_PINCH01;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_PINCH02 = VOICE_RYU.CRI_VOICE_RYU_V_RY_PINCH02;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_PINCH03 = VOICE_RYU.CRI_VOICE_RYU_V_RY_PINCH03;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_LOSE01 = VOICE_RYU.CRI_VOICE_RYU_V_RY_LOSE01;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_UNIQUE01 = VOICE_RYU.CRI_VOICE_RYU_V_RY_UNIQUE01;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_WIN01 = VOICE_RYU.CRI_VOICE_RYU_V_RY_WIN01;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_JUMP01 = VOICE_RYU.CRI_VOICE_RYU_V_RY_JUMP01;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_SABER01 = VOICE_RYU.CRI_VOICE_RYU_V_RY_SABER01;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_SABER02 = VOICE_RYU.CRI_VOICE_RYU_V_RY_SABER02;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_SABER03 = VOICE_RYU.CRI_VOICE_RYU_V_RY_SABER03;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_SABER04 = VOICE_RYU.CRI_VOICE_RYU_V_RY_SABER04;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_SABER05 = VOICE_RYU.CRI_VOICE_RYU_V_RY_SABER05;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_START01 = VOICE_RYU.CRI_VOICE_RYU_V_RY_START01;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_SKILL01_2 = VOICE_RYU.CRI_VOICE_RYU_V_RY_SKILL01_2;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_SKILL02 = VOICE_RYU.CRI_VOICE_RYU_V_RY_SKILL02;

	public const VOICE_RYU CRI_VOICE_RYU_V_RY_CHARA01 = VOICE_RYU.CRI_VOICE_RYU_V_RY_CHARA01;
}
