public static class VOICE_ANGEi
{
	public const int iCRI_VOICE_ANGE_CUENUM = 16;

	public const int iCRI_VOICE_ANGE_V_AN_HURT01 = 1;

	public const int iCRI_VOICE_ANGE_V_AN_START01 = 2;

	public const int iCRI_VOICE_ANGE_V_AN_WIN01 = 3;

	public const int iCRI_VOICE_ANGE_V_AN_LOSE01 = 5;

	public const int iCRI_VOICE_ANGE_V_AN_UNIQUE01 = 6;

	public const int iCRI_VOICE_ANGE_V_AN_SKILL01 = 8;

	public const int iCRI_VOICE_ANGE_V_AN_SKILL02 = 9;

	public const int iCRI_VOICE_ANGE_V_AN_JUMP01 = 12;

	public const int iCRI_VOICE_ANGE_V_AN_SABER01 = 14;

	public const int iCRI_VOICE_ANGE_V_AN_SABER03 = 16;

	public const int iCRI_VOICE_ANGE_V_AN_SABER05 = 18;

	public const int iCRI_VOICE_ANGE_V_AN_PINCH01 = 20;

	public const int iCRI_VOICE_ANGE_V_AN_PINCH02 = 21;

	public const int iCRI_VOICE_ANGE_V_AN_PINCH03 = 22;

	public const int iCRI_VOICE_ANGE_V_AN_ATTACK01 = 25;

	public const int iCRI_VOICE_ANGE_V_AN_CHARA01 = 40;

	public const VOICE_ANGE CRI_VOICE_ANGE_CUENUM = VOICE_ANGE.CRI_VOICE_ANGE_CUENUM;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_HURT01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_HURT01;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_START01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_START01;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_WIN01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_WIN01;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_LOSE01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_LOSE01;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_UNIQUE01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_UNIQUE01;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_SKILL01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_SKILL01;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_SKILL02 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_SKILL02;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_JUMP01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_JUMP01;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_SABER01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_SABER01;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_SABER03 = VOICE_ANGE.CRI_VOICE_ANGE_CUENUM;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_SABER05 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_SABER05;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_PINCH01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_PINCH01;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_PINCH02 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_PINCH02;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_PINCH03 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_PINCH03;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_ATTACK01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_ATTACK01;

	public const VOICE_ANGE CRI_VOICE_ANGE_V_AN_CHARA01 = VOICE_ANGE.CRI_VOICE_ANGE_V_AN_CHARA01;
}
