public enum VOICE_ZERODive
{
	NONE = 0,
	CRI_VOICE_ZERODIVE_CUENUM = 16,
	CRI_VOICE_ZERODIVE_V_ZD_HURT01 = 1,
	CRI_VOICE_ZERODIVE_V_ZD_ATTACK01 = 25,
	CRI_VOICE_ZERODIVE_V_ZD_SKILL01 = 8,
	CRI_VOICE_ZERODIVE_V_ZD_SKILL02 = 9,
	CRI_VOICE_ZERODIVE_V_ZD_PINCH01 = 20,
	CRI_VOICE_ZERODIVE_V_ZD_PINCH02 = 21,
	CRI_VOICE_ZERODIVE_V_ZD_PINCH03 = 22,
	CRI_VOICE_ZERODIVE_V_ZD_LOSE01 = 5,
	CRI_VOICE_ZERODIVE_V_ZD_UNIQUE01 = 6,
	CRI_VOICE_ZERODIVE_V_ZD_WIN01 = 3,
	CRI_VOICE_ZERODIVE_V_ZD_JUMP01 = 12,
	CRI_VOICE_ZERODIVE_V_ZD_SABER01 = 14,
	CRI_VOICE_ZERODIVE_V_ZD_SABER03 = 16,
	CRI_VOICE_ZERODIVE_V_ZD_SABER05 = 18,
	CRI_VOICE_ZERODIVE_V_ZD_START01 = 2,
	CRI_VOICE_ZERODIVE_V_ZD_CHARA01 = 40
}
