public enum VOICE_DRAGOON
{
	NONE = 0,
	CRI_VOICE_DRAGOON_CUENUM = 13,
	CRI_VOICE_DRAGOON_V_DG_HURT01 = 1,
	CRI_VOICE_DRAGOON_V_DG_ATTACK01 = 25,
	CRI_VOICE_DRAGOON_V_DG_PINCH01 = 20,
	CRI_VOICE_DRAGOON_V_DG_PINCH02 = 21,
	CRI_VOICE_DRAGOON_V_DG_PINCH03 = 22,
	CRI_VOICE_DRAGOON_V_DG_LOSE01 = 5,
	CRI_VOICE_DRAGOON_V_DG_UNIQUE01 = 6,
	CRI_VOICE_DRAGOON_V_DG_WIN01 = 3,
	CRI_VOICE_DRAGOON_V_DG_JUMP01 = 12,
	CRI_VOICE_DRAGOON_V_DG_SABER01 = 14,
	CRI_VOICE_DRAGOON_V_DG_SABER03 = 16,
	CRI_VOICE_DRAGOON_V_DG_SABER05 = 18,
	CRI_VOICE_DRAGOON_V_DG_START01 = 2
}
