public static class VOICE_DRAGOONi
{
	public const int iCRI_VOICE_DRAGOON_CUENUM = 13;

	public const int iCRI_VOICE_DRAGOON_V_DG_HURT01 = 1;

	public const int iCRI_VOICE_DRAGOON_V_DG_ATTACK01 = 25;

	public const int iCRI_VOICE_DRAGOON_V_DG_PINCH01 = 20;

	public const int iCRI_VOICE_DRAGOON_V_DG_PINCH02 = 21;

	public const int iCRI_VOICE_DRAGOON_V_DG_PINCH03 = 22;

	public const int iCRI_VOICE_DRAGOON_V_DG_LOSE01 = 5;

	public const int iCRI_VOICE_DRAGOON_V_DG_UNIQUE01 = 6;

	public const int iCRI_VOICE_DRAGOON_V_DG_WIN01 = 3;

	public const int iCRI_VOICE_DRAGOON_V_DG_JUMP01 = 12;

	public const int iCRI_VOICE_DRAGOON_V_DG_SABER01 = 14;

	public const int iCRI_VOICE_DRAGOON_V_DG_SABER03 = 16;

	public const int iCRI_VOICE_DRAGOON_V_DG_SABER05 = 18;

	public const int iCRI_VOICE_DRAGOON_V_DG_START01 = 2;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_CUENUM = VOICE_DRAGOON.CRI_VOICE_DRAGOON_CUENUM;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_HURT01 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_HURT01;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_ATTACK01 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_ATTACK01;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_PINCH01 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_PINCH01;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_PINCH02 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_PINCH02;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_PINCH03 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_PINCH03;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_LOSE01 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_LOSE01;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_UNIQUE01 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_UNIQUE01;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_WIN01 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_WIN01;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_JUMP01 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_JUMP01;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_SABER01 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_SABER01;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_SABER03 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_SABER03;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_SABER05 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_SABER05;

	public const VOICE_DRAGOON CRI_VOICE_DRAGOON_V_DG_START01 = VOICE_DRAGOON.CRI_VOICE_DRAGOON_V_DG_START01;
}
