public static class VOICE_CINNAMONi
{
	public const int iCRI_VOICE_CINNAMON_CUENUM = 18;

	public const int iCRI_VOICE_CINNAMON_V_CM_HURT01 = 1;

	public const int iCRI_VOICE_CINNAMON_V_CM_ATTACK01 = 25;

	public const int iCRI_VOICE_CINNAMON_V_CM_SKILL01 = 8;

	public const int iCRI_VOICE_CINNAMON_V_CM_SKILL02 = 9;

	public const int iCRI_VOICE_CINNAMON_V_CM_PINCH01 = 20;

	public const int iCRI_VOICE_CINNAMON_V_CM_PINCH02 = 21;

	public const int iCRI_VOICE_CINNAMON_V_CM_PINCH03 = 22;

	public const int iCRI_VOICE_CINNAMON_V_CM_LOSE01 = 5;

	public const int iCRI_VOICE_CINNAMON_V_CM_UNIQUE01 = 6;

	public const int iCRI_VOICE_CINNAMON_V_CM_WIN01 = 3;

	public const int iCRI_VOICE_CINNAMON_V_CM_SABER01 = 14;

	public const int iCRI_VOICE_CINNAMON_V_CM_SABER02 = 15;

	public const int iCRI_VOICE_CINNAMON_V_CM_SABER03 = 16;

	public const int iCRI_VOICE_CINNAMON_V_CM_SABER04 = 17;

	public const int iCRI_VOICE_CINNAMON_V_CM_SABER05 = 18;

	public const int iCRI_VOICE_CINNAMON_V_CM_START01 = 2;

	public const int iCRI_VOICE_CINNAMON_V_CM_JUMP01 = 12;

	public const int iCRI_VOICE_CINNAMON_V_CM_SKILL03 = 10;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_CUENUM = VOICE_CINNAMON.CRI_VOICE_CINNAMON_CUENUM;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_HURT01 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_HURT01;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_ATTACK01 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_ATTACK01;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_SKILL01 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_SKILL01;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_SKILL02 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_SKILL02;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_PINCH01 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_PINCH01;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_PINCH02 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_PINCH02;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_PINCH03 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_PINCH03;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_LOSE01 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_LOSE01;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_UNIQUE01 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_UNIQUE01;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_WIN01 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_WIN01;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_SABER01 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_SABER01;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_SABER02 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_SABER02;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_SABER03 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_SABER03;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_SABER04 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_SABER04;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_SABER05 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_CUENUM;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_START01 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_START01;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_JUMP01 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_JUMP01;

	public const VOICE_CINNAMON CRI_VOICE_CINNAMON_V_CM_SKILL03 = VOICE_CINNAMON.CRI_VOICE_CINNAMON_V_CM_SKILL03;
}
