public static class VOICE_ZERONMi
{
	public const int iCRI_VOICE_ZERONM_CUENUM = 15;

	public const int iCRI_VOICE_ZERONM_V_ZN_HURT01 = 1;

	public const int iCRI_VOICE_ZERONM_V_ZN_ATTACK01 = 25;

	public const int iCRI_VOICE_ZERONM_V_ZN_PINCH01 = 20;

	public const int iCRI_VOICE_ZERONM_V_ZN_PINCH02 = 21;

	public const int iCRI_VOICE_ZERONM_V_ZN_PINCH03 = 22;

	public const int iCRI_VOICE_ZERONM_V_ZN_LOSE01 = 5;

	public const int iCRI_VOICE_ZERONM_V_ZN_UNIQUE01 = 6;

	public const int iCRI_VOICE_ZERONM_V_ZN_WIN01 = 3;

	public const int iCRI_VOICE_ZERONM_V_ZN_JUMP01 = 12;

	public const int iCRI_VOICE_ZERONM_V_ZN_SABER01 = 14;

	public const int iCRI_VOICE_ZERONM_V_ZN_SABER03 = 16;

	public const int iCRI_VOICE_ZERONM_V_ZN_SABER05 = 18;

	public const int iCRI_VOICE_ZERONM_V_ZN_START01 = 2;

	public const int iCRI_VOICE_ZERONM_V_ZN_SKILL01 = 8;

	public const int iCRI_VOICE_ZERONM_V_ZN_SKILL02 = 9;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_CUENUM = VOICE_ZERONM.CRI_VOICE_ZERONM_CUENUM;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_HURT01 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_HURT01;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_ATTACK01 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_ATTACK01;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_PINCH01 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_PINCH01;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_PINCH02 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_PINCH02;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_PINCH03 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_PINCH03;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_LOSE01 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_LOSE01;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_UNIQUE01 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_UNIQUE01;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_WIN01 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_WIN01;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_JUMP01 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_JUMP01;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_SABER01 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_SABER01;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_SABER03 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_SABER03;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_SABER05 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_SABER05;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_START01 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_START01;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_SKILL01 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_SKILL01;

	public const VOICE_ZERONM CRI_VOICE_ZERONM_V_ZN_SKILL02 = VOICE_ZERONM.CRI_VOICE_ZERONM_V_ZN_SKILL02;
}
