public enum VOICE_ROLLCAS
{
	NONE = 0,
	CRI_VOICE_ROLLCAS_CUENUM = 16,
	CRI_VOICE_ROLLCAS_V_RC_HURT01 = 1,
	CRI_VOICE_ROLLCAS_V_RC_ATTACK01 = 25,
	CRI_VOICE_ROLLCAS_V_RC_SKILL01 = 8,
	CRI_VOICE_ROLLCAS_V_RC_PINCH01 = 20,
	CRI_VOICE_ROLLCAS_V_RC_PINCH02 = 21,
	CRI_VOICE_ROLLCAS_V_RC_PINCH03 = 22,
	CRI_VOICE_ROLLCAS_V_RC_LOSE01 = 5,
	CRI_VOICE_ROLLCAS_V_RC_UNIQUE01 = 6,
	CRI_VOICE_ROLLCAS_V_RC_WIN01 = 3,
	CRI_VOICE_ROLLCAS_V_RC_JUMP01 = 12,
	CRI_VOICE_ROLLCAS_V_RC_SABER01 = 14,
	CRI_VOICE_ROLLCAS_V_RC_SABER03 = 16,
	CRI_VOICE_ROLLCAS_V_RC_SABER05 = 18,
	CRI_VOICE_ROLLCAS_V_RC_START01 = 2,
	CRI_VOICE_ROLLCAS_V_RC_SKILL02 = 9,
	CRI_VOICE_ROLLCAS_V_RC_CHARA01 = 40
}
