public static class VOICE_HARPYIAi
{
	public const int iCRI_VOICE_HARPYIA_CUENUM = 14;

	public const int iCRI_VOICE_HARPYIA_V_HA_HURT01 = 1;

	public const int iCRI_VOICE_HARPYIA_V_HA_ATTACK01 = 25;

	public const int iCRI_VOICE_HARPYIA_V_HA_PINCH01 = 20;

	public const int iCRI_VOICE_HARPYIA_V_HA_PINCH02 = 21;

	public const int iCRI_VOICE_HARPYIA_V_HA_PINCH03 = 22;

	public const int iCRI_VOICE_HARPYIA_V_HA_LOSE01 = 5;

	public const int iCRI_VOICE_HARPYIA_V_HA_UNIQUE01 = 6;

	public const int iCRI_VOICE_HARPYIA_V_HA_WIN01 = 3;

	public const int iCRI_VOICE_HARPYIA_V_HA_JUMP01 = 12;

	public const int iCRI_VOICE_HARPYIA_V_HA_SABER01 = 14;

	public const int iCRI_VOICE_HARPYIA_V_HA_SABER03 = 16;

	public const int iCRI_VOICE_HARPYIA_V_HA_SABER05 = 18;

	public const int iCRI_VOICE_HARPYIA_V_HA_START01 = 2;

	public const int iCRI_VOICE_HARPYIA_V_HA_SKILL01 = 8;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_CUENUM = VOICE_HARPYIA.CRI_VOICE_HARPYIA_CUENUM;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_HURT01 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_HURT01;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_ATTACK01 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_ATTACK01;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_PINCH01 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_PINCH01;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_PINCH02 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_PINCH02;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_PINCH03 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_PINCH03;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_LOSE01 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_LOSE01;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_UNIQUE01 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_UNIQUE01;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_WIN01 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_WIN01;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_JUMP01 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_JUMP01;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_SABER01 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_CUENUM;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_SABER03 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_SABER03;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_SABER05 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_SABER05;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_START01 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_START01;

	public const VOICE_HARPYIA CRI_VOICE_HARPYIA_V_HA_SKILL01 = VOICE_HARPYIA.CRI_VOICE_HARPYIA_V_HA_SKILL01;
}
