public static class VOICE_IRIS4i
{
	public const int iCRI_VOICE_IRIS4_CUENUM = 16;

	public const int iCRI_VOICE_IRIS4_V_IR4_HURT01 = 1;

	public const int iCRI_VOICE_IRIS4_V_IR4_START01 = 2;

	public const int iCRI_VOICE_IRIS4_V_IR4_WIN01 = 3;

	public const int iCRI_VOICE_IRIS4_V_IR4_SKILL01 = 8;

	public const int iCRI_VOICE_IRIS4_V_IR4_SKILL02 = 9;

	public const int iCRI_VOICE_IRIS4_V_IR4_PINCH01 = 20;

	public const int iCRI_VOICE_IRIS4_V_IR4_PINCH02 = 21;

	public const int iCRI_VOICE_IRIS4_V_IR4_PINCH03 = 22;

	public const int iCRI_VOICE_IRIS4_V_IR4_LOSE01 = 5;

	public const int iCRI_VOICE_IRIS4_V_IR4_UNIQUE01 = 6;

	public const int iCRI_VOICE_IRIS4_V_IR4_JUMP01 = 12;

	public const int iCRI_VOICE_IRIS4_V_IR4_SABER01 = 14;

	public const int iCRI_VOICE_IRIS4_V_IR4_SABER03 = 16;

	public const int iCRI_VOICE_IRIS4_V_IR4_SABER05 = 18;

	public const int iCRI_VOICE_IRIS4_V_IR4_ATTACK01 = 25;

	public const int iCRI_VOICE_IRIS4_V_IR4_CHARA01 = 40;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_CUENUM = VOICE_IRIS4.CRI_VOICE_IRIS4_CUENUM;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_HURT01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_HURT01;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_START01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_START01;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_WIN01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_WIN01;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_SKILL01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_SKILL01;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_SKILL02 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_SKILL02;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_PINCH01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_PINCH01;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_PINCH02 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_PINCH02;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_PINCH03 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_PINCH03;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_LOSE01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_LOSE01;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_UNIQUE01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_UNIQUE01;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_JUMP01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_JUMP01;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_SABER01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_SABER01;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_SABER03 = VOICE_IRIS4.CRI_VOICE_IRIS4_CUENUM;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_SABER05 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_SABER05;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_ATTACK01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_ATTACK01;

	public const VOICE_IRIS4 CRI_VOICE_IRIS4_V_IR4_CHARA01 = VOICE_IRIS4.CRI_VOICE_IRIS4_V_IR4_CHARA01;
}
