public static class VOICE_DRAWERi
{
	public const int iCRI_VOICE_DRAWER_CUENUM = 17;

	public const int iCRI_VOICE_DRAWER_V_DR_HURT01 = 1;

	public const int iCRI_VOICE_DRAWER_V_DR_ATTACK01 = 25;

	public const int iCRI_VOICE_DRAWER_V_DR_SKILL01_1 = 8;

	public const int iCRI_VOICE_DRAWER_V_DR_SKILL02 = 10;

	public const int iCRI_VOICE_DRAWER_V_DR_SKILL01_2 = 9;

	public const int iCRI_VOICE_DRAWER_V_DR_PINCH01 = 20;

	public const int iCRI_VOICE_DRAWER_V_DR_PINCH02 = 21;

	public const int iCRI_VOICE_DRAWER_V_DR_PINCH03 = 22;

	public const int iCRI_VOICE_DRAWER_V_DR_LOSE01 = 5;

	public const int iCRI_VOICE_DRAWER_V_DR_UNIQUE01 = 6;

	public const int iCRI_VOICE_DRAWER_V_DR_WIN01 = 3;

	public const int iCRI_VOICE_DRAWER_V_DR_JUMP01 = 12;

	public const int iCRI_VOICE_DRAWER_V_DR_SABER01 = 14;

	public const int iCRI_VOICE_DRAWER_V_DR_SABER03 = 16;

	public const int iCRI_VOICE_DRAWER_V_DR_SABER05 = 18;

	public const int iCRI_VOICE_DRAWER_V_DR_START01 = 2;

	public const int iCRI_VOICE_DRAWER_V_DR_CHARA01 = 40;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_CUENUM = VOICE_DRAWER.CRI_VOICE_DRAWER_CUENUM;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_HURT01 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_HURT01;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_ATTACK01 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_ATTACK01;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_SKILL01_1 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_SKILL01_1;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_SKILL02 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_SKILL02;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_SKILL01_2 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_SKILL01_2;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_PINCH01 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_PINCH01;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_PINCH02 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_PINCH02;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_PINCH03 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_PINCH03;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_LOSE01 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_LOSE01;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_UNIQUE01 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_UNIQUE01;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_WIN01 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_WIN01;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_JUMP01 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_JUMP01;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_SABER01 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_SABER01;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_SABER03 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_SABER03;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_SABER05 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_SABER05;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_START01 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_START01;

	public const VOICE_DRAWER CRI_VOICE_DRAWER_V_DR_CHARA01 = VOICE_DRAWER.CRI_VOICE_DRAWER_V_DR_CHARA01;
}
