public static class VOICE_ZEROMHi
{
	public const int iCRI_VOICE_ZEROMH_CUENUM = 16;

	public const int iCRI_VOICE_ZEROMH_V_ZM_HURT01 = 1;

	public const int iCRI_VOICE_ZEROMH_V_ZM_START01 = 2;

	public const int iCRI_VOICE_ZEROMH_V_ZM_WIN01 = 3;

	public const int iCRI_VOICE_ZEROMH_V_ZM_LOSE01 = 5;

	public const int iCRI_VOICE_ZEROMH_V_ZM_UNIQUE01 = 6;

	public const int iCRI_VOICE_ZEROMH_V_ZM_SKILL01 = 8;

	public const int iCRI_VOICE_ZEROMH_V_ZM_SKILL02 = 9;

	public const int iCRI_VOICE_ZEROMH_V_ZM_JUMP01 = 12;

	public const int iCRI_VOICE_ZEROMH_V_ZM_SABER01 = 14;

	public const int iCRI_VOICE_ZEROMH_V_ZM_SABER03 = 16;

	public const int iCRI_VOICE_ZEROMH_V_ZM_SABER05 = 18;

	public const int iCRI_VOICE_ZEROMH_V_ZM_PINCH01 = 20;

	public const int iCRI_VOICE_ZEROMH_V_ZM_PINCH02 = 21;

	public const int iCRI_VOICE_ZEROMH_V_ZM_PINCH03 = 22;

	public const int iCRI_VOICE_ZEROMH_V_ZM_ATTACK01 = 25;

	public const int iCRI_VOICE_ZEROMH_V_ZM_CHARA01 = 40;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_CUENUM = VOICE_ZEROMH.CRI_VOICE_ZEROMH_CUENUM;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_HURT01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_HURT01;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_START01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_START01;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_WIN01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_WIN01;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_LOSE01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_LOSE01;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_UNIQUE01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_UNIQUE01;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_SKILL01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_SKILL01;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_SKILL02 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_SKILL02;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_JUMP01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_JUMP01;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_SABER01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_SABER01;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_SABER03 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_CUENUM;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_SABER05 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_SABER05;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_PINCH01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_PINCH01;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_PINCH02 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_PINCH02;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_PINCH03 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_PINCH03;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_ATTACK01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_ATTACK01;

	public const VOICE_ZEROMH CRI_VOICE_ZEROMH_V_ZM_CHARA01 = VOICE_ZEROMH.CRI_VOICE_ZEROMH_V_ZM_CHARA01;
}
