public static class VOICE_IRISi
{
	public const int iCRI_VOICE_IRIS_CUENUM = 18;

	public const int iCRI_VOICE_IRIS_V_IR_HURT01 = 1;

	public const int iCRI_VOICE_IRIS_V_IR_ATTACK01 = 25;

	public const int iCRI_VOICE_IRIS_V_IR_SKILL01 = 8;

	public const int iCRI_VOICE_IRIS_V_IR_SKILL02 = 9;

	public const int iCRI_VOICE_IRIS_V_IR_PINCH01 = 20;

	public const int iCRI_VOICE_IRIS_V_IR_PINCH02 = 21;

	public const int iCRI_VOICE_IRIS_V_IR_PINCH03 = 22;

	public const int iCRI_VOICE_IRIS_V_IR_LOSE01 = 5;

	public const int iCRI_VOICE_IRIS_V_IR_UNIQUE01 = 6;

	public const int iCRI_VOICE_IRIS_V_IR_WIN01 = 3;

	public const int iCRI_VOICE_IRIS_V_IR_JUMP01 = 12;

	public const int iCRI_VOICE_IRIS_V_IR_SABER01 = 14;

	public const int iCRI_VOICE_IRIS_V_IR_SABER03 = 16;

	public const int iCRI_VOICE_IRIS_V_IR_SABER05 = 18;

	public const int iCRI_VOICE_IRIS_V_IR_START01 = 2;

	public const int iCRI_VOICE_IRIS_V_IR_CHARA01 = 40;

	public const int iCRI_VOICE_IRIS_V_IR_CHARA02 = 41;

	public const int iCRI_VOICE_IRIS_V_IR_CHARA03 = 42;

	public const VOICE_IRIS CRI_VOICE_IRIS_CUENUM = VOICE_IRIS.CRI_VOICE_IRIS_CUENUM;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_HURT01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_HURT01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_ATTACK01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_ATTACK01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_SKILL01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_SKILL01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_SKILL02 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_SKILL02;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_PINCH01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_PINCH01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_PINCH02 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_PINCH02;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_PINCH03 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_PINCH03;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_LOSE01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_LOSE01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_UNIQUE01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_UNIQUE01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_WIN01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_WIN01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_JUMP01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_JUMP01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_SABER01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_SABER01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_SABER03 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_SABER03;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_SABER05 = VOICE_IRIS.CRI_VOICE_IRIS_CUENUM;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_START01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_START01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_CHARA01 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_CHARA01;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_CHARA02 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_CHARA02;

	public const VOICE_IRIS CRI_VOICE_IRIS_V_IR_CHARA03 = VOICE_IRIS.CRI_VOICE_IRIS_V_IR_CHARA03;
}
