public enum VOICE_DYNAMO
{
	NONE = 0,
	CRI_VOICE_DYNAMO_CUENUM = 18,
	CRI_VOICE_DYNAMO_V_DY_HURT01 = 1,
	CRI_VOICE_DYNAMO_V_DY_ATTACK01 = 25,
	CRI_VOICE_DYNAMO_V_DY_SKILL01 = 8,
	CRI_VOICE_DYNAMO_V_DY_PINCH01 = 20,
	CRI_VOICE_DYNAMO_V_DY_PINCH02 = 21,
	CRI_VOICE_DYNAMO_V_DY_PINCH03 = 22,
	CRI_VOICE_DYNAMO_V_DY_LOSE01 = 5,
	CRI_VOICE_DYNAMO_V_DY_UNIQUE01 = 6,
	CRI_VOICE_DYNAMO_V_DY_WIN01 = 3,
	CRI_VOICE_DYNAMO_V_DY_JUMP01 = 12,
	CRI_VOICE_DYNAMO_V_DY_SABER01 = 14,
	CRI_VOICE_DYNAMO_V_DY_SABER02 = 15,
	CRI_VOICE_DYNAMO_V_DY_SABER03 = 16,
	CRI_VOICE_DYNAMO_V_DY_SABER04 = 17,
	CRI_VOICE_DYNAMO_V_DY_SABER05 = 18,
	CRI_VOICE_DYNAMO_V_DY_START01 = 2,
	CRI_VOICE_DYNAMO_V_DY_SKILL02 = 10,
	CRI_VOICE_DYNAMO_V_DY_CHARA01 = 40
}
