public static class VOICE_MASSIMOi
{
	public const int iCRI_VOICE_MASSIMO_CUENUM = 15;

	public const int iCRI_VOICE_MASSIMO_V_MS_HURT01 = 1;

	public const int iCRI_VOICE_MASSIMO_V_MS_ATTACK01 = 25;

	public const int iCRI_VOICE_MASSIMO_V_MS_SKILL01 = 8;

	public const int iCRI_VOICE_MASSIMO_V_MS_SKILL02 = 9;

	public const int iCRI_VOICE_MASSIMO_V_MS_PINCH01 = 20;

	public const int iCRI_VOICE_MASSIMO_V_MS_PINCH02 = 21;

	public const int iCRI_VOICE_MASSIMO_V_MS_PINCH03 = 22;

	public const int iCRI_VOICE_MASSIMO_V_MS_LOSE01 = 5;

	public const int iCRI_VOICE_MASSIMO_V_MS_UNIQUE01 = 6;

	public const int iCRI_VOICE_MASSIMO_V_MS_WIN01 = 3;

	public const int iCRI_VOICE_MASSIMO_V_MS_SABER01 = 14;

	public const int iCRI_VOICE_MASSIMO_V_MS_SABER03 = 16;

	public const int iCRI_VOICE_MASSIMO_V_MS_SABER05 = 18;

	public const int iCRI_VOICE_MASSIMO_V_MS_START01 = 2;

	public const int iCRI_VOICE_MASSIMO_V_MS_JUMP01 = 12;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_CUENUM = VOICE_MASSIMO.CRI_VOICE_MASSIMO_CUENUM;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_HURT01 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_HURT01;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_ATTACK01 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_ATTACK01;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_SKILL01 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_SKILL01;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_SKILL02 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_SKILL02;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_PINCH01 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_PINCH01;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_PINCH02 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_PINCH02;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_PINCH03 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_PINCH03;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_LOSE01 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_LOSE01;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_UNIQUE01 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_UNIQUE01;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_WIN01 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_WIN01;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_SABER01 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_SABER01;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_SABER03 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_SABER03;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_SABER05 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_SABER05;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_START01 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_START01;

	public const VOICE_MASSIMO CRI_VOICE_MASSIMO_V_MS_JUMP01 = VOICE_MASSIMO.CRI_VOICE_MASSIMO_V_MS_JUMP01;
}
