public static class VOICE_ALIAi
{
	public const int iCRI_VOICE_ALIA_CUENUM = 22;

	public const int iCRI_VOICE_ALIA_V_AA_HURT01 = 1;

	public const int iCRI_VOICE_ALIA_V_AA_ATTACK01 = 25;

	public const int iCRI_VOICE_ALIA_V_AA_JUMP01 = 12;

	public const int iCRI_VOICE_ALIA_V_AA_SKILL01 = 8;

	public const int iCRI_VOICE_ALIA_V_AA_SKILL02 = 9;

	public const int iCRI_VOICE_ALIA_V_AA_PINCH01 = 20;

	public const int iCRI_VOICE_ALIA_V_AA_PINCH02 = 21;

	public const int iCRI_VOICE_ALIA_V_AA_PINCH03 = 22;

	public const int iCRI_VOICE_ALIA_V_AA_LOSE01 = 5;

	public const int iCRI_VOICE_ALIA_V_AA_UNIQUE01 = 6;

	public const int iCRI_VOICE_ALIA_V_AA_WIN01 = 3;

	public const int iCRI_VOICE_ALIA_V_AA_SABER01 = 14;

	public const int iCRI_VOICE_ALIA_V_AA_SABER02 = 15;

	public const int iCRI_VOICE_ALIA_V_AA_SABER03 = 16;

	public const int iCRI_VOICE_ALIA_V_AA_SABER04 = 17;

	public const int iCRI_VOICE_ALIA_V_AA_SABER05 = 18;

	public const int iCRI_VOICE_ALIA_V_AA_START01 = 2;

	public const int iCRI_VOICE_ALIA_V_AA_UNIQUE02 = 7;

	public const int iCRI_VOICE_ALIA_V_AA_SKILL03 = 10;

	public const int iCRI_VOICE_ALIA_V_AA_CHARA01 = 40;

	public const int iCRI_VOICE_ALIA_V_AA_SKILL04 = 11;

	public const int iCRI_VOICE_ALIA_V_AA_SKILL05 = 26;

	public const VOICE_ALIA CRI_VOICE_ALIA_CUENUM = VOICE_ALIA.CRI_VOICE_ALIA_CUENUM;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_HURT01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_HURT01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_ATTACK01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_ATTACK01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_JUMP01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_JUMP01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_SKILL01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_SKILL01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_SKILL02 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_SKILL02;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_PINCH01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_PINCH01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_PINCH02 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_PINCH02;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_PINCH03 = VOICE_ALIA.CRI_VOICE_ALIA_CUENUM;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_LOSE01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_LOSE01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_UNIQUE01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_UNIQUE01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_WIN01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_WIN01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_SABER01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_SABER01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_SABER02 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_SABER02;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_SABER03 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_SABER03;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_SABER04 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_SABER04;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_SABER05 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_SABER05;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_START01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_START01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_UNIQUE02 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_UNIQUE02;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_SKILL03 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_SKILL03;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_CHARA01 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_CHARA01;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_SKILL04 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_SKILL04;

	public const VOICE_ALIA CRI_VOICE_ALIA_V_AA_SKILL05 = VOICE_ALIA.CRI_VOICE_ALIA_V_AA_SKILL05;
}
