public static class VOICE_ROCKVOLi
{
	public const int iCRI_VOICE_ROCKVOL_CUENUM = 19;

	public const int iCRI_VOICE_ROCKVOL_V_RV_HURT01 = 1;

	public const int iCRI_VOICE_ROCKVOL_V_RV_ATTACK01 = 25;

	public const int iCRI_VOICE_ROCKVOL_V_RV_SKILL01 = 8;

	public const int iCRI_VOICE_ROCKVOL_V_RV_SKILL02 = 9;

	public const int iCRI_VOICE_ROCKVOL_V_RV_PINCH01 = 20;

	public const int iCRI_VOICE_ROCKVOL_V_RV_PINCH02 = 21;

	public const int iCRI_VOICE_ROCKVOL_V_RV_PINCH03 = 22;

	public const int iCRI_VOICE_ROCKVOL_V_RV_LOSE01 = 5;

	public const int iCRI_VOICE_ROCKVOL_V_RV_UNIQUE01 = 6;

	public const int iCRI_VOICE_ROCKVOL_V_RV_WIN01 = 3;

	public const int iCRI_VOICE_ROCKVOL_V_RV_JUMP01 = 12;

	public const int iCRI_VOICE_ROCKVOL_V_RV_SABER01 = 14;

	public const int iCRI_VOICE_ROCKVOL_V_RV_SABER03 = 16;

	public const int iCRI_VOICE_ROCKVOL_V_RV_SABER05 = 18;

	public const int iCRI_VOICE_ROCKVOL_V_RV_START01 = 2;

	public const int iCRI_VOICE_ROCKVOL_V_RV_CHARA01 = 40;

	public const int iCRI_VOICE_ROCKVOL_V_RV_SKILL03 = 10;

	public const int iCRI_VOICE_ROCKVOL_V_RV_SKILL04 = 11;

	public const int iCRI_VOICE_ROCKVOL_V_RV_CHARA02 = 41;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_CUENUM = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_CUENUM;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_HURT01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_HURT01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_ATTACK01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_ATTACK01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_SKILL01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_SKILL01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_SKILL02 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_SKILL02;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_PINCH01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_PINCH01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_PINCH02 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_PINCH02;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_PINCH03 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_PINCH03;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_LOSE01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_LOSE01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_UNIQUE01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_UNIQUE01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_WIN01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_WIN01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_JUMP01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_JUMP01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_SABER01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_SABER01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_SABER03 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_SABER03;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_SABER05 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_SABER05;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_START01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_START01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_CHARA01 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_CHARA01;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_SKILL03 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_SKILL03;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_SKILL04 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_SKILL04;

	public const VOICE_ROCKVOL CRI_VOICE_ROCKVOL_V_RV_CHARA02 = VOICE_ROCKVOL.CRI_VOICE_ROCKVOL_V_RV_CHARA02;
}
