public enum VOICE_LAYER
{
	NONE = 0,
	CRI_VOICE_LAYER_CUENUM = 18,
	CRI_VOICE_LAYER_V_LY_HURT01 = 1,
	CRI_VOICE_LAYER_V_LY_ATTACK01 = 25,
	CRI_VOICE_LAYER_V_LY_SKILL01 = 26,
	CRI_VOICE_LAYER_V_LY_SKILL02 = 8,
	CRI_VOICE_LAYER_V_LY_PINCH01 = 20,
	CRI_VOICE_LAYER_V_LY_PINCH02 = 21,
	CRI_VOICE_LAYER_V_LY_PINCH03 = 22,
	CRI_VOICE_LAYER_V_LY_LOSE01 = 5,
	CRI_VOICE_LAYER_V_LY_UNIQUE01 = 6,
	CRI_VOICE_LAYER_V_LY_WIN01 = 3,
	CRI_VOICE_LAYER_V_LY_JUMP01 = 12,
	CRI_VOICE_LAYER_V_LY_SABER01 = 14,
	CRI_VOICE_LAYER_V_LY_SABER03 = 16,
	CRI_VOICE_LAYER_V_LY_SABER05 = 18,
	CRI_VOICE_LAYER_V_LY_START01 = 2,
	CRI_VOICE_LAYER_V_LY_SKILL03 = 10,
	CRI_VOICE_LAYER_V_LY_SKILL04 = 11,
	CRI_VOICE_LAYER_V_LY_CHARA01 = 27
}
