public static class WeaponSEi
{
	public const int iCRI_WEAPONSE_CUENUM = 114;

	public const int iCRI_WEAPONSE_WEP_SHOT_RIFLE01 = 1;

	public const int iCRI_WEAPONSE_WEP_SHOT_RIFLE02 = 2;

	public const int iCRI_WEAPONSE_WEP_SHOT_RIFLE03 = 3;

	public const int iCRI_WEAPONSE_WEP_SHOT_RIFLE04 = 4;

	public const int iCRI_WEAPONSE_WEP_SHOT_RIFLE05 = 5;

	public const int iCRI_WEAPONSE_WEP_SHOT_RIFLE06 = 6;

	public const int iCRI_WEAPONSE_WEP_SHOT_RIFLE07 = 7;

	public const int iCRI_WEAPONSE_WEP_SHOT_LAZER01 = 8;

	public const int iCRI_WEAPONSE_WEP_SHOT_LAZER02 = 9;

	public const int iCRI_WEAPONSE_WEP_SHOT_LAZER03 = 10;

	public const int iCRI_WEAPONSE_WEP_SHOT_GATLING01 = 18;

	public const int iCRI_WEAPONSE_WEP_SHOT_GATLING02 = 19;

	public const int iCRI_WEAPONSE_WEP_SHOT_GATLING03 = 20;

	public const int iCRI_WEAPONSE_WEP_SHOT_GATLING04 = 21;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER01 = 23;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER02 = 24;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER03_LP = 25;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER03_STOP = 26;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER04 = 27;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER05 = 28;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER06 = 29;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER07 = 30;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER08 = 31;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER09 = 32;

	public const int iCRI_WEAPONSE_WEP_SHOT_BUSTER10 = 33;

	public const int iCRI_WEAPONSE_WEP_SHOT_BAZOOKA01 = 36;

	public const int iCRI_WEAPONSE_WEP_SHOT_BAZOOKA02 = 37;

	public const int iCRI_WEAPONSE_WEP_SHOT_BAZOOKA03 = 38;

	public const int iCRI_WEAPONSE_WEP_SHOT_BAZOOKA04 = 39;

	public const int iCRI_WEAPONSE_WEP_SHOT_BAZOOKA05 = 35;

	public const int iCRI_WEAPONSE_WEP_SHOT_BAZOOKA06 = 34;

	public const int iCRI_WEAPONSE_WEP_SHOT_BAZOOKA07 = 52;

	public const int iCRI_WEAPONSE_WEP_JET_FIRE01 = 41;

	public const int iCRI_WEAPONSE_WEP_JET_COLD01 = 43;

	public const int iCRI_WEAPONSE_WEP_JET_COLD02 = 44;

	public const int iCRI_WEAPONSE_WEP_JET_POISON01 = 45;

	public const int iCRI_WEAPONSE_WEP_JET_POISON02 = 46;

	public const int iCRI_WEAPONSE_WEP_JET_ELECTRIC01 = 47;

	public const int iCRI_WEAPONSE_WEP_JET_ENERGY01 = 48;

	public const int iCRI_WEAPONSE_WEP_JET_ENERGY02 = 50;

	public const int iCRI_WEAPONSE_WEP_JET_ENERGY03 = 40;

	public const int iCRI_WEAPONSE_WEP_JET_FIRE02 = 42;

	public const int iCRI_WEAPONSE_WEP_JET_SAND01 = 49;

	public const int iCRI_WEAPONSE_WEP_JET_ELECTRIC02 = 51;

	public const int iCRI_WEAPONSE_WEP_JET_WIND01 = 53;

	public const int iCRI_WEAPONSE_WEP_CUT_SABER01_2 = 60;

	public const int iCRI_WEAPONSE_WEP_CUT_SABER01 = 61;

	public const int iCRI_WEAPONSE_WEP_CUT_SABER03 = 62;

	public const int iCRI_WEAPONSE_WEP_CUT_SURV01 = 57;

	public const int iCRI_WEAPONSE_WEP_CUT_SURV02 = 58;

	public const int iCRI_WEAPONSE_WEP_CUT_SURV03 = 59;

	public const int iCRI_WEAPONSE_WEP_CUT_HEAVY01 = 67;

	public const int iCRI_WEAPONSE_WEP_CUT_HEAVY02 = 68;

	public const int iCRI_WEAPONSE_WEP_CUT_HEAVY03 = 69;

	public const int iCRI_WEAPONSE_WEP_CUT_SPIN02 = 85;

	public const int iCRI_WEAPONSE_WEP_CUT_WAVE01 = 65;

	public const int iCRI_WEAPONSE_WEP_CUT_OOKEN01 = 71;

	public const int iCRI_WEAPONSE_WEP_CUT_OOKEN02 = 72;

	public const int iCRI_WEAPONSE_WEP_CUT_OOKEN03 = 73;

	public const int iCRI_WEAPONSE_WEP_CUT_IKA = 74;

	public const int iCRI_WEAPONSE_WEP_CUT_HUMMER = 76;

	public const int iCRI_WEAPONSE_WEP_CUT_SWORD01 = 77;

	public const int iCRI_WEAPONSE_WEP_CUT_TACHI01 = 63;

	public const int iCRI_WEAPONSE_WEP_CUT_TACHI03 = 66;

	public const int iCRI_WEAPONSE_WEP_CUT_TACHI02 = 64;

	public const int iCRI_WEAPONSE_WEP_CUT_ELECTRIC01 = 70;

	public const int iCRI_WEAPONSE_WEP_TRW_SPIN01 = 81;

	public const int iCRI_WEAPONSE_WEP_TRW_THROW01 = 82;

	public const int iCRI_WEAPONSE_WEP_TRW_THROW02 = 83;

	public const int iCRI_WEAPONSE_WEP_TRW_BOM01 = 84;

	public const int iCRI_WEAPONSE_WEP_FLY_ENERGY01_LP = 91;

	public const int iCRI_WEAPONSE_WEP_FLY_ENERGY01_STOP = 92;

	public const int iCRI_WEAPONSE_WEP_FLY_ENERGY02_LP = 93;

	public const int iCRI_WEAPONSE_WEP_FLY_ENERGY02_STOP = 94;

	public const int iCRI_WEAPONSE_WEP_FLY_ENERGY03_LP = 95;

	public const int iCRI_WEAPONSE_WEP_FLY_ENERGY03_STOP = 96;

	public const int iCRI_WEAPONSE_WEP_FLY_MISSILE01_LP = 101;

	public const int iCRI_WEAPONSE_WEP_FLY_MISSILE01_STOP = 102;

	public const int iCRI_WEAPONSE_WEP_FLY_MISSILE02_LP = 103;

	public const int iCRI_WEAPONSE_WEP_FLY_MISSILE02_STOP = 104;

	public const int iCRI_WEAPONSE_WEP_FLY_MISSILE03_LP = 105;

	public const int iCRI_WEAPONSE_WEP_FLY_MISSILE03_STOP = 106;

	public const int iCRI_WEAPONSE_WEP_FLY_MISILE04 = 107;

	public const int iCRI_WEAPONSE_WEP_CHIP_MAOH = 121;

	public const int iCRI_WEAPONSE_WEP_CHIP_SCORP_LP = 122;

	public const int iCRI_WEAPONSE_WEP_CHIP_SCORP_STOP = 123;

	public const int iCRI_WEAPONSE_WEP_CHIP_EAGLE_LP = 127;

	public const int iCRI_WEAPONSE_WEP_CHIP_EAGLE_STOP = 128;

	public const int iCRI_WEAPONSE_WEP_CHIP_PENG = 125;

	public const int iCRI_WEAPONSE_WEP_CHIP_SONIC = 126;

	public const int iCRI_WEAPONSE_WEP_CHIP_CF0 = 124;

	public const int iCRI_WEAPONSE_WEP_CHIP_DRILL = 129;

	public const int iCRI_WEAPONSE_WEP_CHIP_BOOMEL_LP = 130;

	public const int iCRI_WEAPONSE_WEP_CHIP_BOOMEL_STOP = 131;

	public const int iCRI_WEAPONSE_WEP_CHIP_VAJUR_LP = 132;

	public const int iCRI_WEAPONSE_WEP_CHIP_VAJUR_STOP = 133;

	public const int iCRI_WEAPONSE_WEP_CHIP_MAGMA = 134;

	public const int iCRI_WEAPONSE_WEP_CHIP_YELLOW = 135;

	public const int iCRI_WEAPONSE_WEP_CHIP_MUSHROOM = 136;

	public const int iCRI_WEAPONSE_WEP_ETC_BALL01 = 112;

	public const int iCRI_WEAPONSE_WEP_ETC_NUCKLE = 113;

	public const int iCRI_WEAPONSE_WEP_ETC_CHARGE01 = 111;

	public const int iCRI_WEAPONSE_WEP_ETC_DMFLD01_STOP = 115;

	public const int iCRI_WEAPONSE_WEP_ETC_DMFLD01_LP = 114;

	public const int iCRI_WEAPONSE_WEP_ETC_DMFLD02_LP = 116;

	public const int iCRI_WEAPONSE_WEP_ETC_DMFLD02_STOP = 117;

	public const int iCRI_WEAPONSE_WEP_ETC_BALL02 = 118;

	public const int iCRI_WEAPONSE_WEP_ETC_BALL03 = 108;

	public const int iCRI_WEAPONSE_WEP_ETC_DMFLD03_LP = 119;

	public const int iCRI_WEAPONSE_WEP_ETC_DMFLD03_STOP = 120;

	public const int iCRI_WEAPONSE_WEP_ETC_DMFLD04_LP = 109;

	public const int iCRI_WEAPONSE_WEP_ETC_DMFLD04_STOP = 110;

	public const int iCRI_WEAPONSE_WEP_ETC_DMFLD05 = 89;

	public const int iCRI_WEAPONSE_WEP_ETC_VANISH01 = 90;

	public const WeaponSE CRI_WEAPONSE_CUENUM = WeaponSE.CRI_WEAPONSE_CUENUM;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_RIFLE01 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_RIFLE01;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_RIFLE02 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_RIFLE02;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_RIFLE03 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_RIFLE03;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_RIFLE04 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_RIFLE04;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_RIFLE05 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_RIFLE05;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_RIFLE06 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_RIFLE06;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_RIFLE07 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_RIFLE07;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_LAZER01 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_LAZER01;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_LAZER02 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_LAZER02;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_LAZER03 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_LAZER03;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_GATLING01 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_GATLING01;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_GATLING02 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_GATLING02;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_GATLING03 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_GATLING03;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_GATLING04 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_GATLING04;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER01 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER01;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER02 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER02;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER03_LP = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER03_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER03_STOP = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER03_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER04 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER04;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER05 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER05;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER06 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER06;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER07 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER07;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER08 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER08;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER09 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER09;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BUSTER10 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BUSTER10;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BAZOOKA01 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BAZOOKA01;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BAZOOKA02 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BAZOOKA02;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BAZOOKA03 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BAZOOKA03;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BAZOOKA04 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BAZOOKA04;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BAZOOKA05 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BAZOOKA05;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BAZOOKA06 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BAZOOKA06;

	public const WeaponSE CRI_WEAPONSE_WEP_SHOT_BAZOOKA07 = WeaponSE.CRI_WEAPONSE_WEP_SHOT_BAZOOKA07;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_FIRE01 = WeaponSE.CRI_WEAPONSE_WEP_JET_FIRE01;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_COLD01 = WeaponSE.CRI_WEAPONSE_WEP_JET_COLD01;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_COLD02 = WeaponSE.CRI_WEAPONSE_WEP_JET_COLD02;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_POISON01 = WeaponSE.CRI_WEAPONSE_WEP_JET_POISON01;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_POISON02 = WeaponSE.CRI_WEAPONSE_WEP_JET_POISON02;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_ELECTRIC01 = WeaponSE.CRI_WEAPONSE_WEP_JET_ELECTRIC01;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_ENERGY01 = WeaponSE.CRI_WEAPONSE_WEP_JET_ENERGY01;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_ENERGY02 = WeaponSE.CRI_WEAPONSE_WEP_JET_ENERGY02;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_ENERGY03 = WeaponSE.CRI_WEAPONSE_WEP_JET_ENERGY03;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_FIRE02 = WeaponSE.CRI_WEAPONSE_WEP_JET_FIRE02;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_SAND01 = WeaponSE.CRI_WEAPONSE_WEP_JET_SAND01;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_ELECTRIC02 = WeaponSE.CRI_WEAPONSE_WEP_JET_ELECTRIC02;

	public const WeaponSE CRI_WEAPONSE_WEP_JET_WIND01 = WeaponSE.CRI_WEAPONSE_WEP_JET_WIND01;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_SABER01_2 = WeaponSE.CRI_WEAPONSE_WEP_CUT_SABER01_2;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_SABER01 = WeaponSE.CRI_WEAPONSE_WEP_CUT_SABER01;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_SABER03 = WeaponSE.CRI_WEAPONSE_WEP_CUT_SABER03;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_SURV01 = WeaponSE.CRI_WEAPONSE_WEP_CUT_SURV01;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_SURV02 = WeaponSE.CRI_WEAPONSE_WEP_CUT_SURV02;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_SURV03 = WeaponSE.CRI_WEAPONSE_WEP_CUT_SURV03;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_HEAVY01 = WeaponSE.CRI_WEAPONSE_WEP_CUT_HEAVY01;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_HEAVY02 = WeaponSE.CRI_WEAPONSE_WEP_CUT_HEAVY02;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_HEAVY03 = WeaponSE.CRI_WEAPONSE_WEP_CUT_HEAVY03;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_SPIN02 = WeaponSE.CRI_WEAPONSE_WEP_CUT_SPIN02;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_WAVE01 = WeaponSE.CRI_WEAPONSE_WEP_CUT_WAVE01;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_OOKEN01 = WeaponSE.CRI_WEAPONSE_WEP_CUT_OOKEN01;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_OOKEN02 = WeaponSE.CRI_WEAPONSE_WEP_CUT_OOKEN02;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_OOKEN03 = WeaponSE.CRI_WEAPONSE_WEP_CUT_OOKEN03;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_IKA = WeaponSE.CRI_WEAPONSE_WEP_CUT_IKA;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_HUMMER = WeaponSE.CRI_WEAPONSE_WEP_CUT_HUMMER;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_SWORD01 = WeaponSE.CRI_WEAPONSE_WEP_CUT_SWORD01;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_TACHI01 = WeaponSE.CRI_WEAPONSE_WEP_CUT_TACHI01;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_TACHI03 = WeaponSE.CRI_WEAPONSE_WEP_CUT_TACHI03;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_TACHI02 = WeaponSE.CRI_WEAPONSE_WEP_CUT_TACHI02;

	public const WeaponSE CRI_WEAPONSE_WEP_CUT_ELECTRIC01 = WeaponSE.CRI_WEAPONSE_WEP_CUT_ELECTRIC01;

	public const WeaponSE CRI_WEAPONSE_WEP_TRW_SPIN01 = WeaponSE.CRI_WEAPONSE_WEP_TRW_SPIN01;

	public const WeaponSE CRI_WEAPONSE_WEP_TRW_THROW01 = WeaponSE.CRI_WEAPONSE_WEP_TRW_THROW01;

	public const WeaponSE CRI_WEAPONSE_WEP_TRW_THROW02 = WeaponSE.CRI_WEAPONSE_WEP_TRW_THROW02;

	public const WeaponSE CRI_WEAPONSE_WEP_TRW_BOM01 = WeaponSE.CRI_WEAPONSE_WEP_TRW_BOM01;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_ENERGY01_LP = WeaponSE.CRI_WEAPONSE_WEP_FLY_ENERGY01_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_ENERGY01_STOP = WeaponSE.CRI_WEAPONSE_WEP_FLY_ENERGY01_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_ENERGY02_LP = WeaponSE.CRI_WEAPONSE_WEP_FLY_ENERGY02_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_ENERGY02_STOP = WeaponSE.CRI_WEAPONSE_WEP_FLY_ENERGY02_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_ENERGY03_LP = WeaponSE.CRI_WEAPONSE_WEP_FLY_ENERGY03_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_ENERGY03_STOP = WeaponSE.CRI_WEAPONSE_WEP_FLY_ENERGY03_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_MISSILE01_LP = WeaponSE.CRI_WEAPONSE_WEP_FLY_MISSILE01_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_MISSILE01_STOP = WeaponSE.CRI_WEAPONSE_WEP_FLY_MISSILE01_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_MISSILE02_LP = WeaponSE.CRI_WEAPONSE_WEP_FLY_MISSILE02_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_MISSILE02_STOP = WeaponSE.CRI_WEAPONSE_WEP_FLY_MISSILE02_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_MISSILE03_LP = WeaponSE.CRI_WEAPONSE_WEP_FLY_MISSILE03_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_MISSILE03_STOP = WeaponSE.CRI_WEAPONSE_WEP_FLY_MISSILE03_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_FLY_MISILE04 = WeaponSE.CRI_WEAPONSE_WEP_FLY_MISILE04;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_MAOH = WeaponSE.CRI_WEAPONSE_WEP_CHIP_MAOH;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_SCORP_LP = WeaponSE.CRI_WEAPONSE_WEP_CHIP_SCORP_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_SCORP_STOP = WeaponSE.CRI_WEAPONSE_WEP_CHIP_SCORP_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_EAGLE_LP = WeaponSE.CRI_WEAPONSE_WEP_CHIP_EAGLE_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_EAGLE_STOP = WeaponSE.CRI_WEAPONSE_WEP_CHIP_EAGLE_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_PENG = WeaponSE.CRI_WEAPONSE_WEP_CHIP_PENG;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_SONIC = WeaponSE.CRI_WEAPONSE_WEP_CHIP_SONIC;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_CF0 = WeaponSE.CRI_WEAPONSE_WEP_CHIP_CF0;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_DRILL = WeaponSE.CRI_WEAPONSE_WEP_CHIP_DRILL;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_BOOMEL_LP = WeaponSE.CRI_WEAPONSE_WEP_CHIP_BOOMEL_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_BOOMEL_STOP = WeaponSE.CRI_WEAPONSE_WEP_CHIP_BOOMEL_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_VAJUR_LP = WeaponSE.CRI_WEAPONSE_WEP_CHIP_VAJUR_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_VAJUR_STOP = WeaponSE.CRI_WEAPONSE_WEP_CHIP_VAJUR_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_MAGMA = WeaponSE.CRI_WEAPONSE_WEP_CHIP_MAGMA;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_YELLOW = WeaponSE.CRI_WEAPONSE_WEP_CHIP_YELLOW;

	public const WeaponSE CRI_WEAPONSE_WEP_CHIP_MUSHROOM = WeaponSE.CRI_WEAPONSE_WEP_CHIP_MUSHROOM;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_BALL01 = WeaponSE.CRI_WEAPONSE_WEP_ETC_BALL01;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_NUCKLE = WeaponSE.CRI_WEAPONSE_WEP_ETC_NUCKLE;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_CHARGE01 = WeaponSE.CRI_WEAPONSE_WEP_ETC_CHARGE01;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_DMFLD01_STOP = WeaponSE.CRI_WEAPONSE_WEP_ETC_DMFLD01_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_DMFLD01_LP = WeaponSE.CRI_WEAPONSE_CUENUM;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_DMFLD02_LP = WeaponSE.CRI_WEAPONSE_WEP_ETC_DMFLD02_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_DMFLD02_STOP = WeaponSE.CRI_WEAPONSE_WEP_ETC_DMFLD02_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_BALL02 = WeaponSE.CRI_WEAPONSE_WEP_ETC_BALL02;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_BALL03 = WeaponSE.CRI_WEAPONSE_WEP_ETC_BALL03;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_DMFLD03_LP = WeaponSE.CRI_WEAPONSE_WEP_ETC_DMFLD03_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_DMFLD03_STOP = WeaponSE.CRI_WEAPONSE_WEP_ETC_DMFLD03_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_DMFLD04_LP = WeaponSE.CRI_WEAPONSE_WEP_ETC_DMFLD04_LP;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_DMFLD04_STOP = WeaponSE.CRI_WEAPONSE_WEP_ETC_DMFLD04_STOP;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_DMFLD05 = WeaponSE.CRI_WEAPONSE_WEP_ETC_DMFLD05;

	public const WeaponSE CRI_WEAPONSE_WEP_ETC_VANISH01 = WeaponSE.CRI_WEAPONSE_WEP_ETC_VANISH01;
}
