public static class WeaponSE02i
{
	public const int iCRI_WEAPONSE02_CUENUM = 5;

	public const int iCRI_WEAPONSE02_WEP_CHIP_BOOMEL_LP = 121;

	public const int iCRI_WEAPONSE02_WEP_CHIP_BOOMEL_STOP = 122;

	public const int iCRI_WEAPONSE02_WEP_CHIP_VAJUR_LP = 123;

	public const int iCRI_WEAPONSE02_WEP_CHIP_VAJUR_STOP = 124;

	public const int iCRI_WEAPONSE02_WEP_CHIP_MAGMA = 128;

	public const WeaponSE02 CRI_WEAPONSE02_CUENUM = WeaponSE02.CRI_WEAPONSE02_CUENUM;

	public const WeaponSE02 CRI_WEAPONSE02_WEP_CHIP_BOOMEL_LP = WeaponSE02.CRI_WEAPONSE02_WEP_CHIP_BOOMEL_LP;

	public const WeaponSE02 CRI_WEAPONSE02_WEP_CHIP_BOOMEL_STOP = WeaponSE02.CRI_WEAPONSE02_WEP_CHIP_BOOMEL_STOP;

	public const WeaponSE02 CRI_WEAPONSE02_WEP_CHIP_VAJUR_LP = WeaponSE02.CRI_WEAPONSE02_WEP_CHIP_VAJUR_LP;

	public const WeaponSE02 CRI_WEAPONSE02_WEP_CHIP_VAJUR_STOP = WeaponSE02.CRI_WEAPONSE02_WEP_CHIP_VAJUR_STOP;

	public const WeaponSE02 CRI_WEAPONSE02_WEP_CHIP_MAGMA = WeaponSE02.CRI_WEAPONSE02_WEP_CHIP_MAGMA;
}
